Repository opendatahub-io/odh-dashboard, pull requests merged in 2022-11, with the labels that each got.

#710 Block the user without authorization from the whole application
  frontend/src/app/App.tsx
  frontend/src/app/AppRoutes.tsx
  frontend/src/app/Header.tsx
  frontend/src/pages/Documentation.tsx
  frontend/src/pages/Error.tsx
  frontend/src/pages/Loading.tsx
  frontend/src/pages/Placeholder.tsx
  frontend/src/pages/UnauthorizedError.tsx
Labels: lgtm, approved

#721 Bump PF, React, Redux versions
  backend/src/routes/api/segment-key/segmentKeyUtils.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/SDKInitialize.tsx
  frontend/src/app/App.tsx
  frontend/src/app/AppLauncher.tsx
  frontend/src/app/AppNotificationDrawer.tsx
  frontend/src/app/Header.tsx
  frontend/src/app/HeaderTools.tsx
  frontend/src/app/QuickStarts.tsx
  frontend/src/components/BrandImage.tsx
  frontend/src/components/FilterSidePanelCategoryItem.tsx
  frontend/src/components/OdhAppCard.tsx
  frontend/src/components/ToastNotification.tsx
  frontend/src/components/ToastNotifications.tsx
  frontend/src/components/localStorage/LocalStorageContext.tsx
  frontend/src/index.tsx
  frontend/src/pages/ApplicationsPage.tsx
  frontend/src/pages/BYONImages/BYONImagesTable.tsx
  frontend/src/pages/BYONImages/ImportImageModal.tsx
  frontend/src/pages/BYONImages/UpdateImageModal.tsx
  frontend/src/pages/clusterSettings/ClusterSettings.tsx
  frontend/src/pages/notebookController/NotebookControllerContext.tsx
  frontend/src/pages/notebookController/SetupCurrentNotebook.tsx
  frontend/src/pages/notebookController/ValidateNotebookNamespace.tsx
  frontend/src/pages/notebookController/screens/admin/NotebookAdminContext.tsx
  frontend/src/pages/notebookController/screens/server/ImageVersions.tsx
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/pages/projects/components/DeleteModal.tsx
  frontend/src/pages/projects/components/GenericSidebar.tsx
  frontend/src/pages/projects/components/IndentSection.tsx
  frontend/src/pages/projects/components/ResourceNameTooltip.tsx
  frontend/src/pages/projects/notebook/NotebookStatusPopover.tsx
  frontend/src/pages/projects/screens/detail/DetailsSection.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageVersionTooltip.tsx
  frontend/src/redux/hooks.ts
  frontend/src/redux/reducers/rootReducers.ts
  frontend/src/redux/selectors/project.ts
  frontend/src/redux/selectors/user.ts
  frontend/src/redux/store/store.ts
  frontend/src/redux/types.ts
  frontend/src/utilities/useEnableApplication.tsx
  frontend/src/utilities/useNotification.ts
  frontend/src/utilities/useSegmentTracking.ts
  frontend/src/utilities/useWatchBYONImages.tsx
  frontend/src/utilities/useWatchBuildStatus.tsx
  frontend/src/utilities/useWatchComponents.tsx
Labels: lgtm, approved

#726 Rename variables and files
  frontend/src/api/models/odh.ts
  frontend/src/api/network/deployedModel.ts
  frontend/src/api/network/inferenceServices.ts
  frontend/src/api/network/roleBindings.ts
  frontend/src/api/network/serviceAccounts.ts
  frontend/src/api/network/servingRuntimes.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelServing/screens/const.ts
  frontend/src/pages/modelServing/screens/global/data.ts
  frontend/src/pages/modelServing/screens/global/utils.ts
  frontend/src/pages/modelServing/screens/projects/ManageServingRuntimeModal.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeList.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeReplicaSection.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeSizeExpandedField.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeSizeSection.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTokenInput.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTokenSection.tsx
  frontend/src/pages/modelServing/screens/projects/useServingRuntimes.ts
  frontend/src/pages/modelServing/screens/projects/utils.ts
  frontend/src/pages/modelServing/screens/types.ts
  frontend/src/pages/projects/ProjectDetailsContext.tsx
  frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
  frontend/src/pages/projects/utils.ts
  frontend/src/types.ts
Labels: lgtm, approved

#725 Fixes error Cluster admin does not get RHODS Admin access if it's the…
  backend/src/types.ts
  backend/src/utils/groupsUtils.ts
Labels: lgtm

#729 Add support to deployed server
  frontend/src/api/network/projects.ts
  frontend/src/api/network/roleBindings.ts
  frontend/src/api/network/secrets.ts
  frontend/src/api/network/serviceAccounts.ts
  frontend/src/api/network/servingRuntimes.ts
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeList.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeReplicaSection.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeExpandedField.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenInput.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenSection.tsx
  frontend/src/pages/modelServing/screens/projects/useServingRuntimes.ts
  frontend/src/pages/modelServing/screens/projects/utils.ts
  frontend/src/pages/modelServing/utils.ts
Labels: feature/model-serving

#731 Fix authentication to access dsg notebooks
  frontend/src/api/network/notebooks.ts
Labels: lgtm, approved

#736 Adjust DSG Image Puller Permissions
  backend/src/utils/prometheusUtils.ts
  frontend/src/pages/projects/screens/projects/ManageProjectModal.tsx
  manifests/overlays/authentication/fetch-builds-and-images.yaml
  manifests/overlays/authentication/image-clusterrolebinding.yaml
  manifests/overlays/authentication/kustomization.yaml
Labels: lgtm, approved

#742 Add delete InferenceService modal
  frontend/src/api/network/inferenceServices.ts
  frontend/src/pages/modelServing/screens/global/DeleteInferenceServiceModal.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceEndpoint.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceListView.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeDetails.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableExpandedSection.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableRow.tsx
  frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
Labels: lgtm, approved

#750 Workbenches don't conflict when sharing a name
  frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx
Labels: lgtm, approved

#720 Support handling pass-through K8sStatus errors in our network flow
  frontend/src/SDKInitialize.tsx
  frontend/src/api/errorUtils.ts
  frontend/src/api/index.ts
  frontend/src/api/network/projects.ts
  frontend/src/pages/projects/screens/projects/ManageProjectModal.tsx
Labels: lgtm, approved

#724 [DSG]: fix ux issues
  frontend/src/pages/projects/notebook/NotebookRouteLink.tsx
  frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx
  frontend/src/pages/projects/notebook/StopNotebookConfirmModal.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTableRow.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageStreamSelector.tsx
Labels: lgtm, approved

#763 Use Labels when creating/fetching DSG Projects
  backend/src/routes/api/namespaces/const.ts
  backend/src/routes/api/namespaces/index.ts
  backend/src/routes/api/namespaces/namespaceUtils.ts
  frontend/src/api/network/projects.ts
  frontend/src/pages/projects/projectNameUtils.ts
  frontend/src/pages/projects/utils.ts
Labels: lgtm, approved

#755 Update env text
  frontend/src/pages/projects/screens/spawner/environmentVariables/GenericKeyValuePairField.tsx
Labels: lgtm, approved

#757 Delete configmaps & secrets with the notebook
  frontend/src/api/network/configMaps.ts
  frontend/src/api/network/secrets.ts
  frontend/src/pages/projects/notebook/DeleteNotebookModal.tsx
  frontend/src/pages/projects/screens/spawner/environmentVariables/EnvConfigMap.tsx
  frontend/src/pages/projects/screens/spawner/environmentVariables/EnvDataTypeField.tsx
  frontend/src/pages/projects/screens/spawner/environmentVariables/EnvSecret.tsx
  frontend/src/pages/projects/screens/spawner/environmentVariables/EnvironmentVariables.tsx
  frontend/src/pages/projects/types.ts
Labels: lgtm, approved

#765 Support editing data connections
  frontend/src/api/network/secrets.ts
  frontend/src/pages/projects/dataConnections/const.ts
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsList.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTable.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTableRow.tsx
  frontend/src/pages/projects/screens/detail/data-connections/ManageDataConnectionModal.tsx
  frontend/src/pages/projects/screens/detail/data-connections/utils.ts
  frontend/src/pages/projects/types.ts
Labels: lgtm, approved

#764 Cleanup display names on projects
  backend/src/plugins/kube.ts
  backend/src/utils/resourceUtils.ts
Labels: lgtm, approved

#711 Misc Improvements for DSG
  frontend/src/pages/clusterSettings/ClusterSettings.tsx
  frontend/src/pages/projects/components/PVSizeField.tsx
  frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx
  frontend/src/pages/projects/notebook/utils.ts
  frontend/src/pages/projects/pvc/MountPathField.tsx
  frontend/src/pages/projects/screens/detail/notebooks/NotebookStorageBars.tsx
  frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/spawnerUtils.ts
  frontend/src/pages/projects/screens/spawner/storage/CreateNewStorageSection.tsx
  frontend/src/pages/projects/screens/spawner/storage/StorageField.tsx
  frontend/src/pages/projects/types.ts
Labels: lgtm, approved

#693 Use username during nb spawning
  backend/src/routes/api/status/index.ts
  backend/src/utils/adminUtils.ts
  frontend/src/pages/notebookController/NotebookController.tsx
  frontend/src/pages/notebookController/screens/server/NotebookServer.tsx
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/pages/notebookController/screens/server/StopServerModal.tsx
  frontend/src/redux/actions/actions.ts
  frontend/src/services/notebookService.ts
Labels: lgtm, approved

#758 Add support to deployed server
  frontend/src/api/network/inferenceServices.ts
  frontend/src/api/network/projects.ts
  frontend/src/api/network/secrets.ts
  frontend/src/api/network/servingRuntimes.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelServing/screens/const.ts
  frontend/src/pages/modelServing/screens/global/EmptyModelServing.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx
  frontend/src/pages/modelServing/screens/global/ServeModelButton.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionSection.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ExistingProjectField.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceFrameworkSection.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ProjectSection.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/useModelFramework.ts
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/useModelServigProjects.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/useModelServingProjects.ts
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeList.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableRow.tsx
  frontend/src/pages/modelServing/screens/projects/utils.ts
  frontend/src/pages/modelServing/screens/types.ts
  frontend/src/pages/projects/components/ExistingPVCField.tsx
  frontend/src/pages/projects/components/NameDescriptionField.tsx
  frontend/src/pages/projects/components/SearchField.tsx
  frontend/src/pages/projects/dataConnections/const.ts
  frontend/src/pages/projects/notebook/NotebookStatusPopover.tsx
  frontend/src/pages/projects/notebook/SelectNotebookField.tsx
  frontend/src/pages/projects/screens/detail/data-connections/useDataConnections.ts
Labels: lgtm, approved

#769 Refetch notebook route if error
  frontend/src/pages/projects/notebook/NotebookRouteLink.tsx
  frontend/src/pages/projects/notebook/useRouteForNotebook.ts
Labels: lgtm, approved

#772 Add support for serving runtime edit
  frontend/src/api/network/secrets.ts
  frontend/src/api/network/servingRuntimes.ts
  frontend/src/pages/modelServing/screens/global/InferenceServiceEndpoint.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionSection.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceFrameworkSection.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeList.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenInput.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTable.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableRow.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTokens.tsx
  frontend/src/pages/modelServing/screens/projects/utils.ts
  frontend/src/pages/modelServing/screens/types.ts
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsList.tsx
  frontend/src/pages/projects/screens/detail/data-connections/useDataConnections.ts
Labels: lgtm, approved

#777 Add editing environment variables and storage features for notebook
  frontend/src/api/network/notebooks.ts
  frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx
  frontend/src/pages/projects/screens/spawner/EditSpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/environmentVariables/useNotebookEnvVariables.tsx
  frontend/src/pages/projects/screens/spawner/service.ts
  frontend/src/pages/projects/screens/spawner/spawnerUtils.ts
  frontend/src/pages/projects/screens/spawner/storage/AddExistingStorageField.tsx
  frontend/src/pages/projects/screens/spawner/storage/StorageField.tsx
  frontend/src/pages/projects/screens/spawner/storage/useAvailablePvcs.ts
  frontend/src/pages/projects/screens/spawner/storage/useNotebookRootStorage.ts
  frontend/src/pages/projects/screens/spawner/storage/utils.ts
  frontend/src/pages/projects/types.ts
Labels: lgtm, approved

#778 Fix dependency array
  frontend/src/pages/modelServing/screens/projects/utils.ts
Labels: lgtm, approved

#776 Override and disable applications when we have errors fetching
  backend/src/utils/resourceUtils.ts
Labels: lgtm, approved

#781 Handle Model Serving addition cleaner
  backend/src/routes/api/k8s/pass-through.ts
  frontend/src/SDKInitialize.tsx
  frontend/src/pages/modelServing/useServingRuntimes.ts
  frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
  frontend/src/utilities/NavData.ts
  frontend/src/utilities/utils.ts
Labels: lgtm, approved

#784 Enable token deletion
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
  frontend/src/pages/modelServing/screens/projects/utils.ts
Labels: lgtm, approved

#785 Sync crds with downstream
  manifests/crd/odh-dashboard-crd.yaml
  manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Labels: lgtm, approved

#780 Improve Connected Functionality
  frontend/src/pages/projects/notebook/ConnectedNotebookField.tsx
  frontend/src/pages/projects/notebook/ConnectedNotebookNames.tsx
  frontend/src/pages/projects/notebook/StorageNotebookConnections.tsx
  frontend/src/pages/projects/notebook/useNonConnectedNotebooks.ts
  frontend/src/pages/projects/notebook/useRelatedNotebooks.ts
  frontend/src/pages/projects/notebook/utils.ts
  frontend/src/pages/projects/pvc/AddNotebookStorage.tsx
  frontend/src/pages/projects/pvc/DeletePVCModal.tsx
  frontend/src/pages/projects/pvc/MountPathField.tsx
  frontend/src/pages/projects/screens/detail/data-connections/ChangeDataConnectionWorkbenchModal.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTable.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTableRow.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DeleteDataConnectionModal.tsx
  frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx
  frontend/src/pages/projects/screens/detail/storage/StorageTableRow.tsx
  frontend/src/pages/projects/screens/detail/storage/useIsRootVolume.ts
  frontend/src/pages/projects/screens/spawner/storage/utils.ts
Labels: lgtm, approved

#786 Fix kube sa token
  backend/src/plugins/kube.ts
  backend/src/routes/api/gpu/gpuUtils.ts
  backend/src/types.ts
Labels: lgtm, approved

#789 UI enhancements for model serving
  frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx
  frontend/src/pages/modelServing/screens/global/utils.ts
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionExistingField.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionSection.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableRow.tsx
  frontend/src/pages/modelServing/screens/types.ts
  manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Labels: lgtm, approved

#798 Use SessionStorage to refresh every hour on OAuth issues
  frontend/src/app/App.tsx
  frontend/src/app/useApplicationSettings.tsx
  frontend/src/app/useTimeBasedRefresh.ts
  frontend/src/components/browserStorage/BrowserStorageContext.tsx
  frontend/src/components/browserStorage/index.ts
  frontend/src/components/localStorage/LocalStorageContext.tsx
  frontend/src/components/localStorage/index.ts
  frontend/src/index.tsx
  frontend/src/pages/learningCenter/LearningCenter.tsx
  frontend/src/pages/notebookController/screens/server/useBrowserTabPreference.ts
  frontend/src/pages/projects/notebook/useStopNotebookModalAvailability.ts
Labels: lgtm, approved

#803 Add missing annotation for data connection secret
  frontend/src/api/network/secrets.ts
Labels: lgtm, approved

#815 UI Enhancements
  .env
  CONTRIBUTING.md
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelServing/screens/global/InferenceServiceEndpoint.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceListView.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceStatus.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx
  frontend/src/pages/modelServing/screens/global/InternalServicePopoverContent.tsx
  frontend/src/pages/modelServing/screens/global/ModelServingGlobal.tsx
  frontend/src/pages/modelServing/screens/global/data.ts
  frontend/src/pages/modelServing/screens/global/useRouteForInferenceService.ts
  frontend/src/pages/modelServing/screens/global/utils.ts
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeReplicaSection.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeExpandedField.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenInput.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableExpandedSection.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableRow.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTokenDisplay.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTokenTableRow.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTokens.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTokensTable.tsx
  frontend/src/pages/modelServing/screens/projects/utils.ts
Labels: lgtm, approved

#812 Fix bug limiting access to global view to regular users:
  frontend/src/api/network/inferenceServices.ts
  frontend/src/api/network/projects.ts
  frontend/src/api/network/servingRuntimes.ts
  frontend/src/pages/modelServing/useInferenceServices.ts
  frontend/src/pages/modelServing/useServingRuntimes.ts
Labels: lgtm, approved, feature/model-serving

#816 Bump PF version and remove some Custom CSS styles
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/App.scss
  frontend/src/app/App.tsx
  frontend/src/app/AppContext.ts
  frontend/src/app/AppNotificationDrawer.tsx
  frontend/src/app/Header.tsx
  frontend/src/app/HeaderTools.tsx
  frontend/src/app/NavSidebar.tsx
  frontend/src/components/BrandImage.tsx
  frontend/src/components/DocCardBadges.tsx
  frontend/src/components/FavoriteButton.scss
  frontend/src/components/FavoriteButton.tsx
  frontend/src/components/OdhAppCard.tsx
  frontend/src/components/OdhCard.scss
  frontend/src/components/OdhDocCard.tsx
  frontend/src/components/OdhDocListItem.tsx
  frontend/src/components/OdhExploreCard.tsx
  frontend/src/components/OdhListItem.scss
  frontend/src/components/SupportedAppTitle.tsx
  frontend/src/components/ToastNotifications.tsx
  frontend/src/images/odh-logo.svg
  frontend/src/pages/ApplicationsPage.scss
  frontend/src/pages/ApplicationsPage.tsx
  frontend/src/pages/enabledApplications/EnabledApplications.tsx
  frontend/src/pages/exploreApplication/EnableModal.tsx
  frontend/src/pages/exploreApplication/ExploreApplications.tsx
  frontend/src/pages/learningCenter/LearningCenter.tsx
  frontend/src/pages/learningCenter/LearningCenterDataView.tsx
  frontend/src/pages/notebookController/NotebookController.scss
  frontend/src/pages/notebookController/screens/admin/ImpersonateAlert.tsx
  frontend/src/pages/notebookController/screens/admin/NotebookAdminControl.tsx
  frontend/src/pages/notebookController/screens/server/NotebookServer.tsx
  frontend/src/pages/notebookController/screens/server/SizeSelectField.tsx
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/utilities/useDesktopWidth.tsx
  frontend/src/utilities/useWatchBuildStatus.tsx
  frontend/src/utilities/utils.ts
Labels: lgtm, approved

#819 Add workbench created and updated telemetry events
  frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
  frontend/src/types.ts
  frontend/src/utilities/segmentIOUtils.tsx
Labels: lgtm, approved

#822 Add toleration settings to DS project workbench
  frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
Labels: lgtm, approved
