Repository opendatahub-io/odh-dashboard, pull requests merged in 2022-08, with the labels that each got.

#350 Allow creating notebook in different namespace
  backend/src/routes/api/configmaps/index.ts
  backend/src/routes/api/pvc/index.ts
  backend/src/routes/api/rolebindings/index.ts
  backend/src/routes/api/secrets/index.ts
  backend/src/types.ts
  docs/dashboard_config.md
  frontend/src/pages/notebookController/NotebookController.tsx
  frontend/src/pages/notebookController/SpawnerPage.tsx
  frontend/src/redux/actions/actions.ts
  frontend/src/redux/reducers/appReducer.ts
  frontend/src/redux/types.ts
  frontend/src/services/configMapService.ts
  frontend/src/services/pvcService.ts
  frontend/src/services/roleBindingService.ts
  frontend/src/services/secretsService.ts
  frontend/src/types.ts
  frontend/src/utilities/notebookControllerUtils.ts
  frontend/src/utilities/useWatchNotebook.tsx
  manifests/base/cluster-role.yaml
  manifests/base/odh-dashboard-crd.yaml
  manifests/base/role.yaml
Labels: notebook-controller

#379 RBAC: Allow dashboard SA to get IS layers
  manifests/base/cluster-role.yaml
Labels: notebook-controller

#384 Add detailed logs for starting server modal
  backend/src/routes/api/nb-events/eventUtils.ts
  backend/src/routes/api/nb-events/index.ts
  backend/src/types.ts
  frontend/src/pages/notebookController/NotebookController.scss
  frontend/src/pages/notebookController/NotebookControllerContext.tsx
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/pages/notebookController/screens/server/StartServerModal.tsx
  frontend/src/services/notebookEventsService.ts
  frontend/src/types.ts
  frontend/src/utilities/notebookControllerUtils.ts
  frontend/src/utilities/useNotification.ts
  frontend/src/utilities/useWatchNotebookEvents.tsx
  manifests/base/cluster-role.yaml
Labels: notebook-controller

#373 Update dockerignore
  .dockerignore
Labels: lgtm, approved

#406 added nodeAffinity during notebook creation with 0 gpus
  frontend/src/services/notebookService.ts
Labels: lgtm, approved

#277 Update Bug report to clarify question about OCP infra
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: lgtm, approved

#412 Update delegate urls argument for dashboard oauth
  manifests/overlays/authentication/deployment.yaml
Labels: lgtm, approved

#417 Extract size form out of Spawner Page
  frontend/src/pages/notebookController/screens/server/SizeSelectField.tsx
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/pages/notebookController/screens/server/usePreferredNotebookSize.ts
Labels: lgtm, approved

#423 Allow system:authenicated to work for users
  backend/src/routes/api/status/statusUtils.ts
  backend/src/utils/resourceUtils.ts
Labels: lgtm, approved

#426 Cleanup BYON references in the UI
  frontend/src/pages/BYONImages/BYONImages.tsx
  frontend/src/pages/BYONImages/BYONImagesTable.tsx
  frontend/src/pages/BYONImages/DeleteBYONImageModal.tsx
  frontend/src/pages/BYONImages/ImportImageModal.tsx
  frontend/src/pages/BYONImages/UpdateImageModal.tsx
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
Labels: lgtm, approved

#429 Add required fields, remove unused fields from CRD
  backend/src/types.ts
  frontend/src/types.ts
  manifests/base/odh-dashboard-crd.yaml
Labels: lgtm, approved

#424 modified username translation to utilize encodeURIComponent
  frontend/src/__tests__/notebookControllerUtils.spec.ts
  frontend/src/utilities/notebookControllerUtils.ts
Labels: lgtm, approved

#404 Fix User Data Collection checkbox
  backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts
  backend/src/types.ts
  frontend/src/pages/clusterSettings/ClusterSettings.tsx
  frontend/src/pages/clusterSettings/const.ts
  frontend/src/types.ts
Labels: lgtm, approved

#435 Change probe endpoint
  manifests/base/deployment.yaml
Labels: lgtm, approved

#440 Stop mutating objects by sort functions
  frontend/src/app/AppNotificationDrawer.tsx
  frontend/src/pages/BYONImages/BYONImagesTable.tsx
  frontend/src/pages/notebookController/screens/server/ImageVersions.tsx
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/utilities/imageUtils.ts
  frontend/src/utilities/useWatchImages.tsx
Labels: lgtm, approved

#437 Set unique ID for every env var field and input
  frontend/src/pages/notebookController/screens/server/EnvironmentVariablesField.tsx
  frontend/src/pages/notebookController/screens/server/EnvironmentVariablesRow.tsx
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
Labels: lgtm, approved

#432 Add telemetry event for starting server
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/types.ts
Labels: lgtm, approved

#434 Update doc on Explore page and Resources page
  backend/src/routes/api/components/list.ts
  backend/src/routes/api/quickstarts/quickStartUtils.ts
  backend/src/types.ts
  backend/src/utils/resourceUtils.ts
  data/applications/jupyter.yaml
  data/getting-started/jupyter.md
  frontend/src/components/OdhExploreCard.tsx
  frontend/src/pages/enabledApplications/EnabledApplications.tsx
  frontend/src/types.ts
Labels: lgtm, approved

#270 Groups admin panel
  backend/src/routes/api/config/configUtils.ts
  backend/src/routes/api/groups-config/groupsConfigUtil.ts
  backend/src/routes/api/groups-config/index.ts
  backend/src/routes/api/notebooks/notebookUtils.ts
  backend/src/routes/api/status/statusUtils.ts
  backend/src/types.ts
  backend/src/utils/adminUtils.ts
  backend/src/utils/groupsUtils.ts
  backend/src/utils/resourceUtils.ts
  backend/src/utils/userUtils.ts
  docs/admin_dashboard.md
  docs/dashboard_config.md
  docs/meta/admin-panel.png
  frontend/src/app/Routes.tsx
  frontend/src/components/MultiSelection.tsx
  frontend/src/pages/groupSettings/GroupSettings.scss
  frontend/src/pages/groupSettings/GroupSettings.tsx
  frontend/src/pages/groupSettings/GroupTypes.ts
  frontend/src/services/groupSettingsService.ts
  frontend/src/utilities/NavData.ts
  frontend/src/utilities/useWatchGroups.tsx
  manifests/base/cluster-role.yaml
  manifests/overlays/odhdashboardconfig/groups-config.configmap.yaml
  manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Labels: kind/enhancement, lgtm, approved, feature/adminui

#415 Use patches to stop notebooks
  backend/package-lock.json
  backend/src/routes/api/nb-events/eventUtils.ts
  backend/src/routes/api/nb-events/index.ts
  backend/src/routes/api/notebooks/index.ts
  backend/src/routes/api/notebooks/notebookUtils.ts
  backend/src/routes/api/status/adminAllowedUsers.ts
  backend/src/routes/api/status/index.ts
  backend/src/routes/api/status/statusUtils.ts
  backend/src/typeHelpers.ts
  backend/src/types.ts
  backend/src/utils/adminUtils.ts
  backend/src/utils/resourceUtils.ts
  frontend/package-lock.json
  frontend/src/pages/notebookController/NotebookController.scss
  frontend/src/pages/notebookController/NotebookController.tsx
  frontend/src/pages/notebookController/NotebookControllerContext.tsx
  frontend/src/pages/notebookController/SetupCurrentNotebook.tsx
  frontend/src/pages/notebookController/SetupCurrentUserState.tsx
  frontend/src/pages/notebookController/const.ts
  frontend/src/pages/notebookController/notebookControllerContextTypes.ts
  frontend/src/pages/notebookController/screens/admin/ImpersonateAlert.tsx
  frontend/src/pages/notebookController/screens/admin/NotebookAdmin.tsx
  frontend/src/pages/notebookController/screens/admin/NotebookAdminContext.tsx
  frontend/src/pages/notebookController/screens/admin/NotebookAdminControl.tsx
  frontend/src/pages/notebookController/screens/admin/NotebookControllerTabs.tsx
  frontend/src/pages/notebookController/screens/admin/ServerStatus.tsx
  frontend/src/pages/notebookController/screens/admin/StopAllServersButton.tsx
  frontend/src/pages/notebookController/screens/admin/UserTableCellTransform.tsx
  frontend/src/pages/notebookController/screens/admin/const.ts
  frontend/src/pages/notebookController/screens/admin/types.ts
  frontend/src/pages/notebookController/screens/admin/useAdminUsers.ts
  frontend/src/pages/notebookController/screens/admin/useCheckForAllowedUsers.ts
  frontend/src/pages/notebookController/screens/admin/useCheckUserPrivilege.ts
  frontend/src/pages/notebookController/screens/server/NotebookControlPanelRedirect.tsx
  frontend/src/pages/notebookController/screens/server/NotebookServer.tsx
  frontend/src/pages/notebookController/screens/server/NotebookServerDetails.tsx
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/pages/notebookController/screens/server/StartServerModal.tsx
  frontend/src/pages/notebookController/screens/server/StopServerModal.tsx
  frontend/src/pages/notebookController/screens/server/usePreferredNotebookSize.ts
  frontend/src/pages/notebookController/screens/server/useSpawnerNotebookModalState.ts
  frontend/src/pages/notebookController/screens/server/useWatchNotebookForSpawnerPage.ts
  frontend/src/pages/notebookController/useAdminTabState.ts
  frontend/src/pages/notebookController/useCurrentUser.ts
  frontend/src/pages/notebookController/useImpersonationForContext.ts
  frontend/src/redux/actions/actions.ts
  frontend/src/services/dashboardConfigService.ts
  frontend/src/services/notebookService.ts
  frontend/src/typeHelpers.ts
  frontend/src/types.ts
  frontend/src/utilities/notebookControllerUtils.ts
  frontend/src/utilities/useWatchNotebook.tsx
  frontend/src/utilities/useWatchNotebookEvents.tsx
  frontend/src/utilities/useWatchNotebooksForUsers.tsx
Labels: lgtm, approved

#446 Allow the Cluster settings page to save with no tolerations settings
  backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts
Labels: lgtm, approved

#447 Improve initial Application loading, wait on user info
  frontend/src/app/App.tsx
Labels: lgtm, approved

#448 Removing the now unused OdhDashboardConfig status property
  docs/dashboard_config.md
  frontend/src/types.ts
  manifests/base/odh-dashboard-crd.yaml
Labels: lgtm, approved

#454 Type check when notebookController is not defined
  backend/src/routes/api/components/list.ts
  backend/src/routes/api/quickstarts/quickStartUtils.ts
  backend/src/utils/componentUtils.ts
  backend/src/utils/resourceUtils.ts
Labels: lgtm, approved

#457 Update OWNERS file
  OWNERS
Labels: lgtm, approved

#456 Refine notebook controller routes
  frontend/src/pages/notebookController/screens/server/NotebookServerRoutes.tsx
Labels: lgtm, approved

#462 Move CONTRIBUTING to root
  CONTRIBUTING.md
  README.md
  docs/README.md
Labels: lgtm, approved
