Repository opendatahub-io/odh-dashboard, pull requests merged in 2022-10, with the labels that each got.

#582 Create add storage modal
  frontend/src/pages/projects/modals/addStorageModal/AddExistingStorageForm.tsx
  frontend/src/pages/projects/modals/addStorageModal/AddStorageModal.tsx
  frontend/src/pages/projects/modals/addStorageModal/ConnectWorkbenchOptions.tsx
  frontend/src/pages/projects/modals/addStorageModal/CreateNewStorageForm.tsx
  frontend/src/pages/projects/modals/addStorageModal/addStorageModal.scss
  frontend/src/pages/projects/modals/addStorageModal/const.ts
  frontend/src/pages/projects/modals/addStorageModal/types.ts
  frontend/src/pages/projects/notebook/ListNotebookState.tsx
  frontend/src/pages/projects/screens/detail/StorageList.tsx
Labels: lgtm, approved

#610 Add part of spawner page
  frontend/src/api/index.ts
  frontend/src/api/models/openShift.ts
  frontend/src/api/network/builds.ts
  frontend/src/api/network/imageStreams.ts
  frontend/src/api/network/notebooks.ts
  frontend/src/app/App.tsx
  frontend/src/k8sTypes.ts
  frontend/src/pages/projects/ProjectViewRoutes.tsx
  frontend/src/pages/projects/components/GenericSidebar.tsx
  frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
  frontend/src/pages/projects/screens/detail/WorkspacesList.tsx
  frontend/src/pages/projects/screens/projects/ManageProjectModal.tsx
  frontend/src/pages/projects/screens/spawner/FormFooter.tsx
  frontend/src/pages/projects/screens/spawner/NameDescriptionField.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/const.ts
  frontend/src/pages/projects/screens/spawner/deploymentSize/ContainerSizeSelector.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageSelectorField.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageStreamPopover.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageStreamSelector.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageVersionSelector.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageVersionTooltip.tsx
  frontend/src/pages/projects/screens/spawner/spawnerUtils.ts
  frontend/src/pages/projects/screens/spawner/types.ts
  frontend/src/pages/projects/screens/spawner/useBuildStatuses.ts
  frontend/src/pages/projects/screens/spawner/useImageStreams.ts
  frontend/src/pages/projects/screens/spawner/useNotebookSize.ts
  frontend/src/pages/projects/utils.ts
  frontend/src/types.ts
  frontend/src/utilities/utils.ts
Labels: lgtm, approved

#615 Bug fixes for ISV CR issues.
  backend/src/utils/resourceUtils.ts
  data/features.json
Labels: lgtm, approved

#618 Remove logging of 404 error responses for pvc, configmaps and secrets
  backend/src/routes/api/configmaps/index.ts
  backend/src/routes/api/pvc/index.ts
  backend/src/routes/api/secrets/index.ts
Labels: lgtm, approved

#628 Improve performance in nb-events
  backend/src/routes/api/nb-events/eventUtils.ts
  frontend/src/pages/notebookController/screens/server/StartServerModal.tsx
  frontend/src/utilities/useWatchNotebookEvents.tsx
Labels: lgtm, approved

#638 Disable start server when env is in error
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
Labels: lgtm, approved

#643 Limit notebook endpoint continued
  backend/src/routes/api/configmaps/index.ts
  backend/src/routes/api/envs/index.ts
  backend/src/routes/api/images/imageUtils.ts
  backend/src/routes/api/notebooks/index.ts
  backend/src/routes/api/notebooks/notebookUtils.ts
  backend/src/routes/api/notebooks/utils.ts
  backend/src/routes/api/pvc/index.ts
  backend/src/routes/api/route/index.ts
  backend/src/routes/api/secrets/index.ts
  backend/src/routes/api/status/adminAllowedUsers.ts
  backend/src/typeHelpers.ts
  backend/src/types.ts
  backend/src/utils/constants.ts
  backend/src/utils/envUtils.ts
  backend/src/utils/notebookUtils.ts
  backend/src/utils/route-security.ts
  backend/src/utils/userUtils.ts
  frontend/src/pages/notebookController/const.ts
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/pages/notebookController/screens/server/StopServerModal.tsx
  frontend/src/pages/notebookController/screens/server/useSpawnerNotebookModalState.ts
  frontend/src/services/configMapService.ts
  frontend/src/services/envService.ts
  frontend/src/services/notebookService.ts
  frontend/src/services/pvcService.ts
  frontend/src/services/secretsService.ts
  frontend/src/types.ts
  frontend/src/utilities/notebookControllerUtils.ts
  manifests/base/cluster-role.yaml
Labels: lgtm, approved

#645 Improvements to #587
  backend/src/routes/api/notebooks/utils.ts
  backend/src/typeHelpers.ts
  backend/src/types.ts
  backend/src/utils/notebookUtils.ts
  backend/src/utils/route-security.ts
  backend/src/utils/userUtils.ts
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/services/notebookService.ts
  frontend/src/types.ts
Labels: do-not-merge/hold, lgtm

#640 Hold the last activity time of the Notebook until spawn modal closes
  frontend/src/pages/notebookController/screens/server/StartServerModal.tsx
  frontend/src/utilities/notebookControllerUtils.ts
Labels: lgtm, approved

#637 Add storage section for spawner page
  frontend/src/api/network/imageStreams.ts
  frontend/src/api/network/notebooks.ts
  frontend/src/api/network/pvcs.ts
  frontend/src/api/network/roleBindings.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/projects/components/ExistingStoragePVField.tsx
  frontend/src/pages/projects/components/ExistingStorageProjectField.tsx
  frontend/src/pages/projects/components/NewStorageNameDescFields.tsx
  frontend/src/pages/projects/components/PVSizeField.tsx
  frontend/src/pages/projects/const.ts
  frontend/src/pages/projects/modals/addStorageModal/AddExistingStorageForm.tsx
  frontend/src/pages/projects/modals/addStorageModal/AddExistingStorageSection.tsx
  frontend/src/pages/projects/modals/addStorageModal/AddStorageModal.tsx
  frontend/src/pages/projects/modals/addStorageModal/ConnectWorkbenchOptions.tsx
  frontend/src/pages/projects/modals/addStorageModal/ConnectWorkspaceOptionsField.tsx
  frontend/src/pages/projects/modals/addStorageModal/CreateNewStorageForm.tsx
  frontend/src/pages/projects/modals/addStorageModal/CreateNewStorageSection.tsx
  frontend/src/pages/projects/modals/addStorageModal/addStorageModal.scss
  frontend/src/pages/projects/modals/addStorageModal/const.ts
  frontend/src/pages/projects/modals/addStorageModal/types.ts
  frontend/src/pages/projects/screens/projects/ManageProjectModal.tsx
  frontend/src/pages/projects/screens/spawner/FormFooter.tsx
  frontend/src/pages/projects/screens/spawner/NameDescriptionField.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/service.ts
  frontend/src/pages/projects/screens/spawner/spawnerUtils.ts
  frontend/src/pages/projects/screens/spawner/storage/AddExistingStorageSection.tsx
  frontend/src/pages/projects/screens/spawner/storage/ConnectWorkspaceOptionsField.tsx
  frontend/src/pages/projects/screens/spawner/storage/CreateNewStorageSection.tsx
  frontend/src/pages/projects/screens/spawner/storage/StorageField.tsx
  frontend/src/pages/projects/screens/spawner/types.ts
  frontend/src/pages/projects/types.ts
  frontend/src/pages/projects/useGenericObjectState.ts
  frontend/src/pages/projects/useGenericSet.ts
  frontend/src/pages/projects/utils.ts
  frontend/src/types.ts
  frontend/src/utilities/utils.ts
Labels: lgtm, approved

#665 Code cleanup
  frontend/src/pages/projects/notebook/NotebookImagePackageDetails.tsx
  frontend/src/pages/projects/screens/detail/storage/CreateNewStorageSection.tsx
  frontend/src/pages/projects/screens/detail/workspaces/WorkspacePackageDetails.tsx
  frontend/src/pages/projects/screens/detail/workspaces/WorkspaceTableRow.tsx
  frontend/src/pages/projects/screens/detail/workspaces/useWorkspaceImage.ts
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageSelectorField.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageStreamSelector.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageVersionTooltip.tsx
  frontend/src/pages/projects/screens/spawner/spawnerUtils.ts
  frontend/src/pages/projects/screens/spawner/storage/CreateNewStorageSection.tsx
  frontend/src/pages/projects/screens/spawner/storage/StorageField.tsx
  frontend/src/pages/projects/screens/spawner/storage/utils.ts
  frontend/src/pages/projects/typeHelpers.ts
  frontend/src/pages/projects/types.ts
  frontend/src/pages/projects/useGenericObjectState.ts
  frontend/src/typeHelpers.ts
Labels: lgtm

#666 Add storage list layout
  frontend/src/pages/projects/components/StorageSizeBars.tsx
  frontend/src/pages/projects/screens/detail/storage/AddStorageModal.tsx
  frontend/src/pages/projects/screens/detail/storage/ConnectWorkspaceOptionsField.tsx
  frontend/src/pages/projects/screens/detail/storage/CreateNewStorageSection.tsx
  frontend/src/pages/projects/screens/detail/storage/StorageList.tsx
  frontend/src/pages/projects/screens/detail/storage/StorageTable.tsx
  frontend/src/pages/projects/screens/detail/storage/StorageTableRow.tsx
  frontend/src/pages/projects/screens/detail/storage/data.ts
  frontend/src/pages/projects/screens/detail/storage/useProjectPvcs.ts
  frontend/src/pages/projects/screens/detail/storage/utils.ts
  frontend/src/pages/projects/screens/detail/workspaces/WorkspaceStorageBars.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/storage/ConnectWorkspaceOptionsField.tsx
  frontend/src/pages/projects/screens/spawner/storage/CreateNewStorageSection.tsx
  frontend/src/pages/projects/screens/spawner/storage/utils.ts
  frontend/src/pages/projects/types.ts
  frontend/src/pages/projects/utils.ts
Labels: lgtm, approved

#671 Data Connections List
  frontend/src/api/network/secrets.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/projects/notebook/ConnectedWorkspaces.tsx
  frontend/src/pages/projects/notebook/useConnectedNotebooks.ts
  frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsList.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTable.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTableRow.tsx
  frontend/src/pages/projects/screens/detail/data-connections/connectionRenderers.tsx
  frontend/src/pages/projects/screens/detail/data-connections/data.ts
  frontend/src/pages/projects/screens/detail/data-connections/useDataConnections.ts
  frontend/src/pages/projects/screens/detail/data-connections/utils.ts
  frontend/src/pages/projects/types.ts
  frontend/src/pages/projects/utils.ts
Labels: lgtm, approved

#672 Stop Notebook Confirmation Modal
  frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx
  frontend/src/pages/projects/notebook/StopNotebookConfirmModal.tsx
  frontend/src/pages/projects/notebook/useStopNotebookModalAvailability.ts
  frontend/src/pages/projects/screens/detail/workspaces/WorkspaceTableRow.tsx
Labels: lgtm, approved

#673 Delete Notebook Modal
  frontend/src/api/network/notebooks.ts
  frontend/src/pages/projects/notebook/DeleteNotebookModal.tsx
  frontend/src/pages/projects/notebook/useProjectNotebooks.ts
  frontend/src/pages/projects/screens/detail/workspaces/WorkspaceTable.tsx
  frontend/src/pages/projects/screens/detail/workspaces/WorkspaceTableRow.tsx
  frontend/src/pages/projects/screens/detail/workspaces/WorkspacesList.tsx
Labels: lgtm, approved

#573 Add autoscale check for GPU
  backend/src/plugins/kube.ts
  backend/src/routes/api/gpu/gpuUtils.ts
  backend/src/routes/api/status/statusUtils.ts
  backend/src/types.ts
  frontend/src/pages/notebookController/screens/server/GPUSelectField.tsx
  frontend/src/services/gpuService.ts
  frontend/src/types.ts
  manifests/base/cluster-role.yaml
Labels: lgtm, approved

#670 Spawner Environment Section
  frontend/src/api/network/configMaps.ts
  frontend/src/api/network/notebooks.ts
  frontend/src/api/network/secrets.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/environmentVariables/AWSField.tsx
  frontend/src/pages/projects/screens/spawner/environmentVariables/EnvironmentVariables.tsx
  frontend/src/pages/projects/screens/spawner/environmentVariables/EnvironmentVariablesRow.tsx
  frontend/src/pages/projects/screens/spawner/environmentVariables/KeyValueField.tsx
  frontend/src/pages/projects/screens/spawner/environmentVariables/const.ts
  frontend/src/pages/projects/screens/spawner/service.ts
  frontend/src/pages/projects/types.ts
Labels: lgtm, approved

#669 Add empty view and empty dsg section
  backend/src/types.ts
  backend/src/utils/constants.ts
  frontend/src/app/AppRoutes.tsx
  frontend/src/pages/modelServing/screens/global/EmptyModelServing.tsx
  frontend/src/pages/modelServing/screens/global/ModelServingGlobal.tsx
  frontend/src/pages/projects/screens/detail/EmptyDetailsList.tsx
  frontend/src/pages/projects/screens/detail/ModelServerList.tsx
  frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
  frontend/src/pages/projects/screens/detail/const.ts
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsList.tsx
  frontend/src/pages/projects/screens/detail/storage/StorageList.tsx
  frontend/src/pages/projects/screens/detail/types.ts
  frontend/src/pages/projects/screens/detail/workspaces/WorkspacesList.tsx
  frontend/src/types.ts
  frontend/src/utilities/NavData.ts
  manifests/crd/odh-dashboard-crd.yaml
  manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Labels: feature/model-serving

#682 Add breadcrumb to project detail and spawner page.
  frontend/src/pages/ApplicationsPage.scss
  frontend/src/pages/ApplicationsPage.tsx
  frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
  frontend/src/pages/projects/screens/projects/useUserProjects.ts
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
Labels: lgtm, approved

#686 Use the kube config to get the current logged in token
  backend/src/plugins/kube.ts
  backend/src/routes/api/gpu/gpuUtils.ts
  backend/src/routes/api/status/statusUtils.ts
  backend/src/types.ts
Labels: lgtm, approved

#684 Adjust Storage based on UX input
  frontend/src/api/network/notebooks.ts
  frontend/src/api/network/pvcs.ts
  frontend/src/api/prometheus/pvcs.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/projects/components/ExistingPVCField.tsx
  frontend/src/pages/projects/components/GenericSidebar.tsx
  frontend/src/pages/projects/components/NameDescriptionField.tsx
  frontend/src/pages/projects/components/PVSizeField.tsx
  frontend/src/pages/projects/components/StorageSizeBars.tsx
  frontend/src/pages/projects/notebook/useConnectedNotebooks.ts
  frontend/src/pages/projects/notebook/useProjectNotebookStates.ts
  frontend/src/pages/projects/notebook/useProjectNotebooks.ts
  frontend/src/pages/projects/notebook/utils.ts
  frontend/src/pages/projects/pvc/AddNotebookStorage.tsx
  frontend/src/pages/projects/pvc/DeletePVCModal.tsx
  frontend/src/pages/projects/pvc/MountPathField.tsx
  frontend/src/pages/projects/pvc/const.ts
  frontend/src/pages/projects/pvc/useNotebookPVCItems.ts
  frontend/src/pages/projects/screens/detail/EmptyDetailsList.tsx
  frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
  frontend/src/pages/projects/screens/detail/const.ts
  frontend/src/pages/projects/screens/detail/data-connections/utils.ts
  frontend/src/pages/projects/screens/detail/storage/AddExistingStorageSection.tsx
  frontend/src/pages/projects/screens/detail/storage/AddStorageModal.tsx
  frontend/src/pages/projects/screens/detail/storage/ConnectExistingWorkspace.tsx
  frontend/src/pages/projects/screens/detail/storage/ConnectWorkspaceOptionsField.tsx
  frontend/src/pages/projects/screens/detail/storage/CreateNewStorageSection.tsx
  frontend/src/pages/projects/screens/detail/storage/ExistingConnectedNotebooks.tsx
  frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.scss
  frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx
  frontend/src/pages/projects/screens/detail/storage/StorageList.tsx
  frontend/src/pages/projects/screens/detail/storage/StorageTable.tsx
  frontend/src/pages/projects/screens/detail/storage/StorageTableRow.tsx
  frontend/src/pages/projects/screens/detail/storage/utils.ts
  frontend/src/pages/projects/screens/detail/types.ts
  frontend/src/pages/projects/screens/detail/workspaces/WorkspaceStorageBars.tsx
  frontend/src/pages/projects/screens/detail/workspaces/WorkspaceTable.tsx
  frontend/src/pages/projects/screens/detail/workspaces/WorkspaceTableRow.tsx
  frontend/src/pages/projects/screens/detail/workspaces/WorkspacesList.tsx
  frontend/src/pages/projects/screens/projects/ManageProjectModal.tsx
  frontend/src/pages/projects/screens/projects/ProjectTableRow.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/environmentVariables/EnvironmentVariables.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageSelectorField.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageStreamPopover.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageStreamSelector.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageVersionSelector.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageVersionTooltip.tsx
  frontend/src/pages/projects/screens/spawner/service.ts
  frontend/src/pages/projects/screens/spawner/spawnerUtils.ts
  frontend/src/pages/projects/screens/spawner/storage/AddExistingStorageField.tsx
  frontend/src/pages/projects/screens/spawner/storage/AddExistingStorageSection.tsx
  frontend/src/pages/projects/screens/spawner/storage/CreateNewStorageSection.tsx
  frontend/src/pages/projects/screens/spawner/storage/StorageField.tsx
  frontend/src/pages/projects/screens/spawner/storage/useAvailablePvcs.ts
  frontend/src/pages/projects/screens/spawner/storage/utils.ts
  frontend/src/pages/projects/types.ts
  frontend/src/pages/projects/utils.ts
Labels: lgtm, approved

#683 Add status tooltip and start notebook modal
  frontend/src/api/index.ts
  frontend/src/api/models/k8s.ts
  frontend/src/api/network/events.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/projects/notebook/NotebookRouteLink.tsx
  frontend/src/pages/projects/notebook/NotebookStatusPopover.tsx
  frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx
  frontend/src/pages/projects/notebook/StartNotebookModal.tsx
  frontend/src/pages/projects/notebook/service.ts
  frontend/src/pages/projects/notebook/types.ts
  frontend/src/pages/projects/notebook/useRefreshNotebookUntilStart.ts
  frontend/src/pages/projects/notebook/useWatchNotebookEvents.ts
  frontend/src/pages/projects/notebook/utils.ts
Labels: lgtm, approved

#658 Create dedicated OAuthclient
  manifests/overlays/authentication/deployment.yaml
  manifests/overlays/authentication/secret.yaml
Labels: lgtm, approved

#667 Fix Oauth Issues when retrieving username
  backend/src/utils/route-security.ts
  backend/src/utils/userUtils.ts
  frontend/src/app/useApplicationSettings.tsx
Labels: lgtm

#590 Generate a random OAuth cookie secret
  Makefile
  install/deploy.sh
  install/undeploy.sh
  manifests/overlays/authentication/deployment.yaml
  manifests/overlays/authentication/secret.yaml
Labels: lgtm, approved

#696 DSG Fixes
  frontend/src/pages/projects/ProjectDetailsContext.tsx
  frontend/src/pages/projects/notebook/ConnectedWorkspaces.tsx
  frontend/src/pages/projects/notebook/useConnectedNotebooks.ts
  frontend/src/pages/projects/notebook/useRelatedNotebooks.ts
  frontend/src/pages/projects/pvc/utils.ts
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsList.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTableRow.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DeleteDataConnectionModal.tsx
  frontend/src/pages/projects/screens/detail/data-connections/useDataConnections.ts
  frontend/src/pages/projects/screens/detail/data-connections/utils.ts
  frontend/src/pages/projects/screens/detail/storage/StorageList.tsx
  frontend/src/pages/projects/screens/detail/storage/StorageTableRow.tsx
  frontend/src/pages/projects/screens/detail/workspaces/WorkspacesList.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
  frontend/src/pages/projects/screens/spawner/service.ts
  frontend/src/pages/projects/screens/spawner/storage/utils.ts
  frontend/src/pages/projects/types.ts
  frontend/src/pages/projects/utils.ts
  frontend/src/types.ts
Labels: lgtm, approved

#692 Change wrong "Memory requests" text occurences to "Requests" in notebook controller
  frontend/src/pages/notebookController/screens/server/NotebookServerDetails.tsx
  frontend/src/pages/notebookController/screens/server/SizeSelectField.tsx
Labels: lgtm, approved

#697 Refresh notebook status and fetch all status periodically
  frontend/src/pages/projects/ProjectDetailsContext.tsx
  frontend/src/pages/projects/dataConnections/AWSField.tsx
  frontend/src/pages/projects/notebook/ListNotebookState.tsx
  frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx
  frontend/src/pages/projects/notebook/useRefreshNotebookUntilStart.ts
  frontend/src/pages/projects/notebook/useRelatedNotebooks.ts
  frontend/src/pages/projects/notebook/utils.ts
  frontend/src/pages/projects/pvc/MountPathField.tsx
  frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
  frontend/src/pages/projects/screens/detail/const.ts
  frontend/src/pages/projects/screens/detail/notebooks/NotebookList.tsx
  frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx
  frontend/src/pages/projects/screens/detail/storage/ExistingConnectedNotebooks.tsx
  frontend/src/pages/projects/screens/detail/storage/StorageList.tsx
  frontend/src/pages/projects/screens/detail/types.ts
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/const.ts
  frontend/src/pages/projects/screens/spawner/deploymentSize/ContainerSizeSelector.tsx
  frontend/src/pages/projects/screens/spawner/storage/StorageField.tsx
  frontend/src/pages/projects/screens/spawner/types.ts
Labels: lgtm, approved

#698 Improve storage section features and bug fix
  frontend/src/api/network/notebooks.ts
  frontend/src/api/network/pvcs.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/projects/ProjectDetailsContext.tsx
  frontend/src/pages/projects/components/PVSizeField.tsx
  frontend/src/pages/projects/const.ts
  frontend/src/pages/projects/notebook/ListNotebookState.tsx
  frontend/src/pages/projects/notebook/service.ts
  frontend/src/pages/projects/notebook/utils.ts
  frontend/src/pages/projects/pvc/AddNotebookStorage.tsx
  frontend/src/pages/projects/screens/detail/notebooks/NotebookList.tsx
  frontend/src/pages/projects/screens/detail/notebooks/NotebookTable.tsx
  frontend/src/pages/projects/screens/detail/storage/ConnectExistingNotebook.tsx
  frontend/src/pages/projects/screens/detail/storage/ExistingConnectedNotebooks.tsx
  frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx
  frontend/src/pages/projects/screens/detail/storage/StorageList.tsx
  frontend/src/pages/projects/screens/detail/storage/StorageTable.tsx
  frontend/src/pages/projects/screens/projects/ManageProjectModal.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/environmentVariables/EnvironmentVariables.tsx
  frontend/src/pages/projects/screens/spawner/storage/AddExistingStorageField.tsx
  frontend/src/pages/projects/screens/spawner/storage/CreateNewStorageSection.tsx
  frontend/src/pages/projects/screens/spawner/storage/StorageField.tsx
  frontend/src/pages/projects/screens/spawner/storage/useAvailablePvcSize.ts
  frontend/src/pages/projects/screens/spawner/storage/useAvailablePvcs.ts
  frontend/src/pages/projects/screens/spawner/storage/utils.ts
  frontend/src/pages/projects/types.ts
  frontend/src/utilities/utils.ts
Labels: lgtm, approved

#699 Add ability to delete attached PVC
  frontend/src/k8sTypes.ts
  frontend/src/pages/projects/const.ts
  frontend/src/pages/projects/notebook/utils.ts
  frontend/src/pages/projects/pvc/DeletePVCModal.tsx
  frontend/src/pages/projects/screens/spawner/storage/useAvailablePvcSize.ts
  frontend/src/pages/projects/screens/spawner/storage/useAvailablePvcs.ts
Labels: lgtm, approved

#700 Improve Project Creation & Data Connection Modal
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/network/notebooks.ts
  frontend/src/api/network/projects.ts
  frontend/src/pages/notebookController/useNamespaces.ts
  frontend/src/pages/projects/notebook/ConnectedNotebooks.tsx
  frontend/src/pages/projects/notebook/SelectNotebookField.tsx
  frontend/src/pages/projects/notebook/useNonConnectedNotebooks.ts
  frontend/src/pages/projects/notebook/useProjectNotebooks.ts
  frontend/src/pages/projects/notebook/useRelatedNotebooks.ts
  frontend/src/pages/projects/pvc/DeletePVCModal.tsx
  frontend/src/pages/projects/pvc/utils.ts
  frontend/src/pages/projects/screens/detail/data-connections/ChangeDataConnectionWorkbenchModal.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsList.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTable.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTableRow.tsx
  frontend/src/pages/projects/screens/detail/storage/ConnectExistingNotebook.tsx
  frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx
  frontend/src/pages/projects/screens/projects/ManageProjectModal.tsx
  frontend/src/pages/projects/screens/spawner/storage/utils.ts
  frontend/src/pages/projects/types.ts
Labels: lgtm, approved

#701 Fixes for DSG
  backend/src/routes/api/gpu/index.ts
  frontend/src/api/network/pvcs.ts
  frontend/src/pages/projects/components/DeleteModal.tsx
  frontend/src/pages/projects/notebook/DeleteNotebookModal.tsx
  frontend/src/pages/projects/pvc/DeletePVCModal.tsx
  frontend/src/pages/projects/pvc/useNotebookPVCItems.ts
  frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTableRow.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DeleteDataConnectionModal.tsx
  frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx
  frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx
  frontend/src/pages/projects/screens/detail/storage/StorageTableRow.tsx
  frontend/src/pages/projects/screens/projects/DeleteProjectModal.tsx
  frontend/src/pages/projects/screens/projects/ProjectTableRow.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/deploymentSize/ContainerSizeSelector.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageSelectorField.tsx
Labels: lgtm, approved

#702 Translate display names into k8s names
  frontend/src/api/network/notebooks.ts
  frontend/src/api/network/projects.ts
  frontend/src/api/network/pvcs.ts
  frontend/src/api/network/secrets.ts
  frontend/src/pages/projects/components/DeleteModal.tsx
  frontend/src/pages/projects/components/NameDescriptionField.tsx
  frontend/src/pages/projects/notebook/DeleteNotebookModal.tsx
  frontend/src/pages/projects/pvc/DeletePVCModal.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DeleteDataConnectionModal.tsx
  frontend/src/pages/projects/screens/projects/DeleteProjectModal.tsx
  frontend/src/pages/projects/screens/projects/ManageProjectModal.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/service.ts
  frontend/src/pages/projects/screens/spawner/storage/CreateNewStorageSection.tsx
  frontend/src/pages/projects/screens/spawner/storage/utils.ts
  frontend/src/pages/projects/types.ts
  frontend/src/pages/projects/utils.ts
Labels: lgtm, approved

#704 Fixes and features for DSG
  backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts
  backend/src/routes/api/images/imageUtils.ts
  backend/src/routes/api/validate-isv/validateISV.ts
  backend/src/utils/constants.ts
  backend/src/utils/deployment.ts
  backend/src/utils/envUtils.ts
  backend/src/utils/notebookUtils.ts
  frontend/src/api/network/notebooks.ts
  frontend/src/pages/projects/components/DeleteModalConnectedAlert.tsx
  frontend/src/pages/projects/notebook/NotebookImagePackageDetails.tsx
  frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx
  frontend/src/pages/projects/notebook/service.ts
  frontend/src/pages/projects/pvc/DeletePVCModal.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsList.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTableRow.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DeleteDataConnectionModal.tsx
  frontend/src/pages/projects/screens/detail/data-connections/data.ts
  frontend/src/pages/projects/screens/detail/notebooks/NotebookTable.tsx
  frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx
  frontend/src/pages/projects/screens/detail/notebooks/data.ts
  frontend/src/pages/projects/screens/detail/storage/StorageTable.tsx
  frontend/src/pages/projects/screens/detail/storage/StorageTableRow.tsx
  frontend/src/pages/projects/screens/spawner/deploymentSize/ContainerSizeSelector.tsx
  frontend/src/pages/projects/screens/spawner/environmentVariables/EnvTypeSelectField.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageStreamSelector.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageVersionSelector.tsx
  frontend/src/pages/projects/utils.ts
Labels: lgtm, approved

#687 Bump PF version and remove findDomNode warning
  backend/package-lock.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/AppLauncher.tsx
  frontend/src/app/HeaderTools.tsx
  frontend/src/app/NavSidebar.tsx
  frontend/src/components/DocCardBadges.tsx
  frontend/src/components/MultiSelection.tsx
  frontend/src/components/OdhAppCard.tsx
  frontend/src/components/OdhCard.scss
  frontend/src/components/OdhDocCard.tsx
  frontend/src/components/OdhDocListItem.tsx
  frontend/src/components/OdhListItem.scss
  frontend/src/components/SupportedAppTitle.tsx
  frontend/src/pages/BYONImages/BYONImagesTable.tsx
  frontend/src/pages/exploreApplication/GetStartedPanel.tsx
  frontend/src/pages/learningCenter/LearningCenterToolbar.tsx
  frontend/src/pages/notebookController/screens/server/EnvironmentVariablesRow.tsx
  frontend/src/pages/notebookController/screens/server/GPUSelectField.tsx
  frontend/src/pages/notebookController/screens/server/ImageSelector.tsx
  frontend/src/pages/notebookController/screens/server/ImageTagPopover.tsx
  frontend/src/pages/notebookController/screens/server/SizeSelectField.tsx
Labels: lgtm, approved

#714 Update Root Owners File
  OWNERS
Labels: lgtm, approved

#715 Simplify bug report view
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: lgtm, approved
