Repository opendatahub-io/odh-dashboard, pull requests merged in 2022-09, with the labels that each got.

#472 Invert Access/Stop notebook server buttons on notebook server control panel
  backend/src/types.ts
  frontend/src/pages/notebookController/screens/server/NotebookServer.tsx
Labels: lgtm, approved

#471 Add empty DSG page & nav
  backend/src/types.ts
  backend/src/utils/constants.ts
  frontend/package-lock.json
  frontend/src/app/NavSidebar.tsx
  frontend/src/app/Routes.tsx
  frontend/src/pages/projects/EmptyProjects.tsx
  frontend/src/pages/projects/ProjectView.tsx
  frontend/src/types.ts
  frontend/src/utilities/NavData.ts
  frontend/src/utilities/useWatchDashboardConfig.tsx
  manifests/base/odh-dashboard-crd.yaml
  manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Labels: lgtm, approved

#477 Enable viewing users notebook details from the admin panel
  frontend/src/pages/notebookController/screens/admin/NotebookActions.tsx
  frontend/src/pages/notebookController/screens/admin/NotebookAdminControl.tsx
  frontend/src/pages/notebookController/screens/admin/ServerStatus.tsx
  frontend/src/pages/notebookController/screens/admin/UserTableCellTransform.tsx
  frontend/src/pages/notebookController/screens/admin/const.ts
  frontend/src/pages/notebookController/screens/admin/types.ts
  frontend/src/pages/notebookController/screens/admin/useAdminUsers.ts
Labels: lgtm, approved

#468 README: Add automated image build info
  CONTRIBUTING.md
  README.md
Labels: lgtm, approved

#279 Kubernetes Pass Through API & SDK Initialization
  .github/workflows/pull_request.yml
  backend/src/routes/api/configmaps/index.ts
  backend/src/routes/api/k8s/index.ts
  backend/src/routes/api/k8s/pass-through.ts
  backend/src/routes/api/notebooks/index.ts
  backend/src/routes/api/notebooks/notebookUtils.ts
  backend/src/routes/api/pvc/index.ts
  backend/src/routes/api/secrets/index.ts
  backend/src/types.ts
  backend/src/utils/constants.ts
  backend/src/utils/userUtils.ts
  docs/README.md
  docs/SDK.md
  frontend/.eslintrc
  frontend/config/setupTests.js
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/SDKInitialize.tsx
  frontend/src/index.tsx
  frontend/src/models/index.ts
  frontend/src/models/k8s.ts
  frontend/src/models/odh.ts
  frontend/src/pages/learningCenter/LearningCenter.tsx
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/pages/notebookController/screens/server/StopServerModal.tsx
  frontend/src/services/configMapService.ts
  frontend/src/services/notebookService.ts
  frontend/src/services/pvcService.ts
  frontend/src/services/secretsService.ts
  frontend/src/types.ts
  frontend/src/utilities/notebookControllerUtils.ts
Labels: lgtm, approved

#475 Support not having an issue if the Notebook was deleted
  backend/src/routes/api/notebooks/notebookUtils.ts
  frontend/package-lock.json
Labels: lgtm, approved

#489 Add Samu as a backup approver
  OWNERS
Labels: lgtm

#488 Add Route Security to some routes
  backend/src/routes/api/configmaps/index.ts
  backend/src/routes/api/groups-config/groupsConfigUtil.ts
  backend/src/routes/api/notebooks/notebookUtils.ts
  backend/src/routes/api/pvc/index.ts
  backend/src/routes/api/secrets/index.ts
  backend/src/routes/api/status/adminAllowedUsers.ts
  backend/src/routes/api/status/statusUtils.ts
  backend/src/types.ts
  backend/src/utils/route-security.ts
  backend/src/utils/userUtils.ts
Labels: lgtm, approved

#501 Fix issue with requesting kube resources
  backend/src/routes/api/notebooks/index.ts
  backend/src/routes/api/notebooks/notebookUtils.ts
  backend/src/utils/route-security.ts
Labels: lgtm, approved

#502 Secure all routes
  backend/src/routes/api/builds/index.ts
  backend/src/routes/api/cluster-settings/index.ts
  backend/src/routes/api/components/index.ts
  backend/src/routes/api/config/index.ts
  backend/src/routes/api/console-links/index.ts
  backend/src/routes/api/docs/index.ts
  backend/src/routes/api/getting-started/index.ts
  backend/src/routes/api/gpu/index.ts
  backend/src/routes/api/groups-config/index.ts
  backend/src/routes/api/images/index.ts
  backend/src/routes/api/nb-events/index.ts
  backend/src/routes/api/notebooks/index.ts
  backend/src/routes/api/notebooks/notebookUtils.ts
  backend/src/routes/api/quickstarts/index.ts
  backend/src/routes/api/rolebindings/index.ts
  backend/src/routes/api/segment-key/index.ts
  backend/src/routes/api/status/index.ts
  backend/src/routes/api/validate-isv/index.ts
  backend/src/types.ts
  backend/src/utils/route-security.ts
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
Labels: lgtm, approved

#505 Fix type issues
  backend/src/types.ts
Labels: lgtm

#511 Fix type issues
  backend/src/types.ts
Labels: lgtm, approved

#499 Ignore 409 case for RBs
  backend/src/routes/api/rolebindings/index.ts
Labels: lgtm, approved

#481 Misc cleanup of DSG
  backend/src/routes/api/rolebindings/index.ts
  frontend/src/SDKInitialize.tsx
  frontend/src/app/NavSidebar.tsx
  frontend/src/models/k8s.ts
  frontend/src/services/roleBindingService.ts
Labels: lgtm, approved

#522 Add additional route security
  backend/src/routes/api/notebooks/index.ts
  backend/src/routes/api/rolebindings/index.ts
  backend/src/routes/api/secrets/index.ts
  backend/src/utils/adminUtils.ts
  backend/src/utils/route-security.ts
Labels: lgtm, approved

#516 Update the logic of getting and patching the route for notebook
  backend/src/routes/api/notebooks/index.ts
  backend/src/routes/api/notebooks/notebookUtils.ts
  frontend/src/pages/notebookController/screens/server/NotebookServer.tsx
Labels: lgtm, approved

#498 Remove logic - kube:admin as default username
  backend/src/routes/api/groups-config/index.ts
  backend/src/routes/api/status/index.ts
  backend/src/utils/route-security.ts
  backend/src/utils/userUtils.ts
Labels: lgtm, approved

#520 Check notebook status by container statuses instead of pod phase
  backend/src/routes/api/notebooks/notebookUtils.ts
Labels: lgtm, approved

#521 Improve the Start Modal Opening
  frontend/src/pages/notebookController/SetupCurrentNotebook.tsx
  frontend/src/pages/notebookController/notebookControllerContextTypes.ts
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/pages/notebookController/screens/server/useSpawnerNotebookModalState.ts
  frontend/src/utilities/useWatchNotebooksForUsers.tsx
Labels: lgtm, approved

#529 Improve Admin Access & Disallow Outside Namespaces
  backend/src/utils/route-security.ts
Labels: lgtm, approved

#543 Update liveness/readiness probe with an endpoint without auth.
  backend/src/routes/api/health/healthUtils.ts
  backend/src/routes/api/health/index.ts
  manifests/base/deployment.yaml
Labels: lgtm, approved

#541 Improve Spawner Speed by Batching Requests
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/pages/notebookController/screens/server/StartServerModal.tsx
  frontend/src/utilities/notebookControllerUtils.ts
Labels: lgtm, approved

#531 Make Jupyter tile have a proper link
  frontend/src/components/OdhAppCard.tsx
Labels: lgtm, approved

#547 Improved spawner errors
  backend/src/routes/api/health/index.ts
  backend/src/utils/requestUtils.ts
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
Labels: lgtm, approved

#538 Add TriggeredScaleUp event and info alert
  frontend/src/pages/notebookController/screens/server/StartServerModal.tsx
  frontend/src/types.ts
  frontend/src/utilities/notebookControllerUtils.ts
Labels: lgtm, approved

#535 Show FailedScheduling issues in the Start Modal
  frontend/src/pages/notebookController/screens/server/StartServerModal.tsx
  frontend/src/types.ts
  frontend/src/utilities/notebookControllerUtils.ts
Labels: lgtm, approved

#518 Update imagetag names documentation to reflect `nightly` image builds
  README.md
  manifests/base/kustomization.yaml
Labels: lgtm, approved

#540 Increase Deployment replicas to 5
  manifests/base/deployment.yaml
Labels: lgtm, approved

#550 Catch up main
  backend/src/routes/api/notebooks/notebookUtils.ts
  backend/src/routes/api/route/index.ts
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/pages/notebookController/screens/server/StartServerModal.tsx
  frontend/src/services/routeService.ts
  frontend/src/utilities/notebookControllerUtils.ts
Labels: lgtm, approved

#243 Changes for ISV to get this information using K8s calls.
  backend/src/routes/api/components/list.ts
  backend/src/routes/api/docs/list.ts
  backend/src/routes/api/getting-started/gettingStartedUtils.ts
  backend/src/routes/api/getting-started/index.ts
  backend/src/routes/api/getting-started/list.ts
  backend/src/routes/api/quickstarts/index.ts
  backend/src/routes/api/quickstarts/list.ts
  backend/src/routes/api/quickstarts/quickStartUtils.ts
  backend/src/routes/api/validate-isv/validateISV.ts
  backend/src/types.ts
  backend/src/utils/resourceUtils.ts
  data/applications/jupyter.yaml
  data/applications/jupyterhub.yaml
  data/docs/jupyterhub-install-python-packages-how-to.yaml
  data/docs/jupyterhub-update-server-settings-how-to.yaml
  data/docs/jupyterhub-use-s3-bucket-data-how-to.yaml
  data/docs/jupyterhub-view-installed-packages-how-to.yaml
  data/features.json
  data/getting-started/jupyter.md
  data/getting-started/jupyterhub.md
  docs/apis.md
  frontend/__mocks__/mockEnabledApplications.ts
  frontend/__mocks__/mockExploreApplications.ts
  frontend/package-lock.json
  frontend/src/__tests__/ExploreApplications.spec.tsx
  frontend/src/components/BrandImage.tsx
  frontend/src/components/DocCardBadges.tsx
  frontend/src/components/OdhDocCard.tsx
  frontend/src/components/OdhDocListItem.tsx
  frontend/src/pages/exploreApplication/GetStartedPanel.tsx
  frontend/src/pages/learningCenter/DocTypeFilters.tsx
  frontend/src/pages/learningCenter/LearningCenter.tsx
  frontend/src/pages/learningCenter/useDocFilterer.ts
  frontend/src/services/gettingStartedService.ts
  frontend/src/types.ts
  frontend/src/utilities/useGettingStarted.tsx
  frontend/src/utilities/useWatchDocs.tsx
  frontend/src/utilities/useWatchQuickStarts.tsx
  manifests/apps/jupyter/create-jupyter-notebook-quickstart.yaml
  manifests/apps/jupyter/deploy-python-model-quickstart.yaml
  manifests/apps/jupyter/jupyter-app.yaml
  manifests/apps/jupyter/jupyter-docs.yaml
  manifests/apps/jupyter/jupyterhub-app.yaml
  manifests/apps/jupyter/kustomization.yaml
  manifests/apps/kustomization.yaml
  manifests/base/kustomization.yaml
  manifests/crd/kustomization.yaml
  manifests/crd/odh-application-crd.yaml
  manifests/crd/odh-dashboard-crd.yaml
  manifests/crd/odh-document-crd.yaml
  manifests/crd/odh-quick-start-crd.yaml
Labels: lgtm, approved

#532 2.1 hotfix bugs
  backend/src/routes/api/groups-config/index.ts
  backend/src/routes/api/health/healthUtils.ts
  backend/src/routes/api/health/index.ts
  backend/src/routes/api/notebooks/index.ts
  backend/src/routes/api/notebooks/notebookUtils.ts
  backend/src/routes/api/rolebindings/index.ts
  backend/src/routes/api/route/index.ts
  backend/src/routes/api/status/index.ts
  backend/src/utils/requestUtils.ts
  backend/src/utils/route-security.ts
  backend/src/utils/userUtils.ts
  frontend/src/app/App.tsx
  frontend/src/app/HeaderTools.tsx
  frontend/src/app/appUtils.ts
  frontend/src/pages/notebookController/SetupCurrentNotebook.tsx
  frontend/src/pages/notebookController/notebookControllerContextTypes.ts
  frontend/src/pages/notebookController/screens/server/NotebookServer.tsx
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/pages/notebookController/screens/server/StartServerModal.tsx
  frontend/src/pages/notebookController/screens/server/useSpawnerNotebookModalState.ts
  frontend/src/services/routeService.ts
  frontend/src/utilities/notebookControllerUtils.ts
  frontend/src/utilities/useWatchDashboardConfig.tsx
  frontend/src/utilities/useWatchNotebooksForUsers.tsx
  manifests/base/deployment.yaml
Labels: do-not-merge/hold, approved

#552 When we get an OAuth Failure, we logout
  backend/src/utils/userUtils.ts
  frontend/src/app/App.tsx
  frontend/src/app/HeaderTools.tsx
  frontend/src/app/appUtils.ts
  frontend/src/app/useApplicationSettings.tsx
Labels: lgtm, approved

#536 Add name check logic to Toleration in ClusterSettings
  frontend/src/pages/clusterSettings/ClusterSettings.scss
  frontend/src/pages/clusterSettings/ClusterSettings.tsx
  frontend/src/types.ts
Labels: lgtm, approved

#554 Secure Routes for Empty Name Property
  backend/src/utils/route-security.ts
Labels: lgtm, approved

#565 Disable the KFNBC Admin Tabs
  frontend/src/pages/notebookController/NotebookController.tsx
Labels: lgtm, approved

#562 Support proper errors for configmap requests
  backend/src/routes/api/configmaps/index.ts
Labels: lgtm, approved

#530 Open new tab for new spawned notebook server
  frontend/src/__tests__/LearningCenter.spec.tsx
  frontend/src/app/App.tsx
  frontend/src/components/localStorage/LocalStorageContext.tsx
  frontend/src/components/localStorage/index.ts
  frontend/src/pages/learningCenter/LearningCenter.tsx
  frontend/src/pages/notebookController/const.ts
  frontend/src/pages/notebookController/screens/server/BrowserTabPreferenceCheckbox.tsx
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/pages/notebookController/screens/server/StartServerModal.tsx
  frontend/src/pages/notebookController/screens/server/useBrowserTabPreference.ts
  frontend/src/utilities/useLocalStorage.ts
Labels: lgtm, approved

#563 Improve event filtering to avoid scary messages
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/pages/notebookController/screens/server/StartServerModal.tsx
  frontend/src/pages/notebookController/screens/server/useSpawnerNotebookModalState.ts
  frontend/src/types.ts
  frontend/src/utilities/notebookControllerUtils.ts
  frontend/src/utilities/useWatchNotebookEvents.tsx
Labels: lgtm, approved

#569 Change tolerations text to avoid mislead
  frontend/src/pages/clusterSettings/ClusterSettings.tsx
Labels: lgtm, approved

#574 Issue 561 - Fix for feature.json.
  data/feature.json
Labels: lgtm, approved

#571 Add permissions for CRD
  manifests/base/role.yaml
Labels: lgtm, approved

#576 Fix sanitization
  backend/src/routes/api/notebooks/index.ts
  backend/src/utils/route-security.ts
Labels: lgtm, approved

#476 Refactor user group settings
  backend/src/types.ts
  backend/src/utils/groupsUtils.ts
  frontend/src/components/FormGroupSettings.tsx
  frontend/src/components/MultiSelection.tsx
  frontend/src/pages/groupSettings/GroupSettings.scss
  frontend/src/pages/groupSettings/GroupSettings.tsx
  frontend/src/pages/groupSettings/groupTypes.ts
  frontend/src/services/groupSettingsService.ts
  frontend/src/utilities/useWatchGroups.tsx
  frontend/src/utilities/utils.ts
  manifests/overlays/odhdashboardconfig/kustomization.yaml
Labels: lgtm, approved

#578 Add project view details page
  frontend/src/app/Routes.tsx
  frontend/src/pages/projects/ProjectViewRoutes.tsx
  frontend/src/pages/projects/screens/detail/DataConnectionsList.tsx
  frontend/src/pages/projects/screens/detail/DetailsSection.tsx
  frontend/src/pages/projects/screens/detail/EmptyDetailsList.tsx
  frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
  frontend/src/pages/projects/screens/detail/ProjectDetailsSidebar.tsx
  frontend/src/pages/projects/screens/detail/StorageList.tsx
  frontend/src/pages/projects/screens/detail/WorkspacesList.tsx
  frontend/src/pages/projects/screens/detail/const.ts
  frontend/src/pages/projects/screens/detail/types.ts
Labels: lgtm, approved

#572 Adjust dependabot's target branch
  .github/dependabot.yml
Labels: lgtm, approved

#414 Add data-ids where possible
  frontend/config/setupTests.js
  frontend/src/app/NavSidebar.tsx
  frontend/src/components/OdhAppCard.tsx
  frontend/src/components/OdhDocCard.tsx
  frontend/src/components/OdhExploreCard.tsx
  frontend/src/pages/ApplicationsPage.tsx
  frontend/src/pages/BYONImages/BYONImages.tsx
  frontend/src/pages/BYONImages/BYONImagesTable.tsx
  frontend/src/pages/BYONImages/EditStepTableRow.tsx
  frontend/src/pages/BYONImages/ImportImageModal.tsx
  frontend/src/pages/BYONImages/UpdateImageModal.tsx
  frontend/src/pages/clusterSettings/ClusterSettings.tsx
  frontend/src/pages/enabledApplications/EnabledApplications.tsx
  frontend/src/pages/exploreApplication/EnableModal.tsx
  frontend/src/pages/exploreApplication/EnableVariable.tsx
  frontend/src/pages/exploreApplication/ExploreApplications.tsx
  frontend/src/pages/exploreApplication/GetStartedPanel.tsx
  frontend/src/pages/groupSettings/GroupSettings.tsx
  frontend/src/pages/learningCenter/ApplicationFilters.tsx
  frontend/src/pages/learningCenter/DocTypeFilters.tsx
  frontend/src/pages/learningCenter/EnabledFilters.tsx
  frontend/src/pages/learningCenter/LearningCenter.tsx
  frontend/src/pages/learningCenter/ProviderTypeFilters.tsx
  frontend/src/pages/notebookController/screens/admin/ImpersonateAlert.tsx
  frontend/src/pages/notebookController/screens/admin/NotebookControllerTabs.tsx
  frontend/src/pages/notebookController/screens/admin/ServerStatus.tsx
  frontend/src/pages/notebookController/screens/admin/StopAllServersButton.tsx
  frontend/src/pages/notebookController/screens/server/EnvironmentVariablesField.tsx
  frontend/src/pages/notebookController/screens/server/EnvironmentVariablesRow.tsx
  frontend/src/pages/notebookController/screens/server/GPUSelectField.tsx
  frontend/src/pages/notebookController/screens/server/ImageSelector.tsx
  frontend/src/pages/notebookController/screens/server/ImageVersions.tsx
  frontend/src/pages/notebookController/screens/server/NotebookServer.tsx
  frontend/src/pages/notebookController/screens/server/NotebookServerDetails.tsx
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/pages/notebookController/screens/server/StartServerModal.tsx
  frontend/src/pages/notebookController/screens/server/StopServerModal.tsx
Labels: lgtm, approved

#583 Delete any envFrom sections from notebook containers.
  backend/src/types.ts
  backend/src/utils/route-security.ts
Labels: lgtm, approved

#585 Add description to "cluster settings saved" toast
  frontend/src/pages/clusterSettings/ClusterSettings.tsx
Labels: lgtm, approved

#589 Upgrade PF dependecies and fix some styles
  backend/package-lock.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/OdhDocListItem.tsx
  frontend/src/components/OdhListItem.scss
  frontend/src/pages/BYONImages/EditStepTableRow.tsx
  frontend/src/pages/BYONImages/ImportImageModal.tsx
  frontend/src/pages/BYONImages/UpdateImageModal.tsx
  frontend/src/pages/clusterSettings/ClusterSettings.tsx
  frontend/src/pages/exploreApplication/EnableVariable.tsx
  frontend/src/pages/notebookController/NotebookController.scss
  frontend/src/pages/notebookController/screens/server/ImageTagPopover.tsx
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
Labels: lgtm, approved

#593 Update react deps
  backend/package-lock.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/App.tsx
  frontend/src/app/AppRoutes.tsx
  frontend/src/components/OdhAppCard.tsx
  frontend/src/pages/exploreApplication/ExploreApplications.tsx
  frontend/src/pages/learningCenter/ApplicationFilters.tsx
  frontend/src/pages/learningCenter/CategoryFilters.tsx
  frontend/src/pages/learningCenter/DocTypeFilters.tsx
  frontend/src/pages/learningCenter/EnabledFilters.tsx
  frontend/src/pages/learningCenter/LearningCenterDataView.tsx
  frontend/src/pages/learningCenter/LearningCenterListHeader.tsx
  frontend/src/pages/learningCenter/LearningCenterToolbar.tsx
  frontend/src/pages/learningCenter/ProviderTypeFilters.tsx
  frontend/src/pages/notebookController/NotebookLogoutRedirect.tsx
  frontend/src/pages/notebookController/screens/server/NotebookControlPanelRedirect.tsx
  frontend/src/pages/notebookController/screens/server/NotebookServer.tsx
  frontend/src/pages/notebookController/screens/server/NotebookServerRoutes.tsx
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/pages/notebookController/screens/server/StartServerModal.tsx
  frontend/src/pages/notebookController/screens/server/useSpawnerNotebookModalState.ts
  frontend/src/utilities/router.ts
  frontend/src/utilities/useTrackHistory.ts
Labels: lgtm, approved

#594 Upgrade misc deps to remove install warnings
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved

#597 Create projects
  backend/package.json
  backend/src/routes/api/k8s/index.ts
  backend/src/routes/api/k8s/pass-through.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/index.ts
  frontend/src/api/models/index.ts
  frontend/src/api/models/openShift.ts
  frontend/src/api/network/projects.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/ApplicationsPage.tsx
  frontend/src/pages/projects/EmptyProjects.tsx
  frontend/src/pages/projects/ProjectDetailsContext.tsx
  frontend/src/pages/projects/ProjectView.tsx
  frontend/src/pages/projects/ProjectViewRoutes.tsx
  frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
  frontend/src/pages/projects/screens/projectList/NewProjectButton.tsx
  frontend/src/pages/projects/screens/projectList/ProjectLink.tsx
  frontend/src/pages/projects/screens/projectList/ProjectView.tsx
  frontend/src/pages/projects/screens/projectList/useUserProjects.ts
  frontend/src/pages/projects/useProject.ts
  frontend/src/pages/projects/utils.ts
  frontend/src/utilities/string.ts
  frontend/src/utilities/useTableColumnSort.ts
Labels: lgtm, approved

#606 Update cfchase in OWNERS
  OWNERS
Labels: lgtm, approved

#605 List Projects & Delete Project
  backend/package.json
  backend/src/routes/api/k8s/pass-through.ts
  frontend/src/api/index.ts
  frontend/src/api/models/k8s.ts
  frontend/src/api/models/openShift.ts
  frontend/src/api/network/notebooks.ts
  frontend/src/api/network/pods.ts
  frontend/src/api/network/projects.ts
  frontend/src/api/network/routes.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/notebookController/screens/admin/UserTableCellTransform.tsx
  frontend/src/pages/projects/ProjectDetailsContext.tsx
  frontend/src/pages/projects/ProjectViewRoutes.tsx
  frontend/src/pages/projects/notebook/ListNotebookState.tsx
  frontend/src/pages/projects/notebook/NotebookRouteLink.tsx
  frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx
  frontend/src/pages/projects/notebook/service.ts
  frontend/src/pages/projects/notebook/types.ts
  frontend/src/pages/projects/notebook/useProjectNotebooks.ts
  frontend/src/pages/projects/notebook/useRefreshNotebookUntilStart.ts
  frontend/src/pages/projects/notebook/useRouteForNotebook.ts
  frontend/src/pages/projects/notebook/utils.ts
  frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
  frontend/src/pages/projects/screens/projectList/NewProjectButton.tsx
  frontend/src/pages/projects/screens/projectList/ProjectView.tsx
  frontend/src/pages/projects/screens/projects/DeleteProjectModal.tsx
  frontend/src/pages/projects/screens/projects/EmptyProjects.tsx
  frontend/src/pages/projects/screens/projects/FilterToolbar.tsx
  frontend/src/pages/projects/screens/projects/ManageProjectModal.tsx
  frontend/src/pages/projects/screens/projects/NewProjectButton.tsx
  frontend/src/pages/projects/screens/projects/ProjectLink.tsx
  frontend/src/pages/projects/screens/projects/ProjectListView.tsx
  frontend/src/pages/projects/screens/projects/ProjectTable.tsx
  frontend/src/pages/projects/screens/projects/ProjectTableRow.tsx
  frontend/src/pages/projects/screens/projects/ProjectView.tsx
  frontend/src/pages/projects/screens/projects/tableData.tsx
  frontend/src/pages/projects/screens/projects/useUserProjects.ts
  frontend/src/pages/projects/useProject.ts
  frontend/src/pages/projects/utils.ts
  frontend/src/utilities/useTableColumnSort.ts
Labels: lgtm, approved

#602 Add regex validation for enviroment variable name
  frontend/src/pages/notebookController/const.ts
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
Labels: lgtm, approved
