Repository opendatahub-io/odh-dashboard, pull requests merged in 2023-06, with the labels that each got.

#1318 TrustyAI Client
  backend/src/utils/httpUtils.ts
  frontend/src/api/index.ts
  frontend/src/api/pipelines/custom.ts
  frontend/src/api/proxyUtils.ts
  frontend/src/api/trustyai/custom.ts
  frontend/src/api/trustyai/k8s.ts
  frontend/src/api/trustyai/rawTypes.ts
  frontend/src/concepts/explainability/ExplainabilityContext.tsx
  frontend/src/concepts/explainability/const.ts
  frontend/src/concepts/explainability/types.ts
  frontend/src/concepts/explainability/useExplainabilityModelData.ts
  frontend/src/concepts/explainability/useTrustyAPIRoute.ts
  frontend/src/concepts/explainability/useTrustyAPIState.ts
  frontend/src/concepts/explainability/useTrustyAiNamespaceCR.ts
  frontend/src/concepts/explainability/utils.ts
  frontend/src/concepts/pipelines/context/PipelinesContext.tsx
  frontend/src/concepts/pipelines/context/useAPIState.ts
  frontend/src/concepts/pipelines/context/usePipelineAPIState.ts
  frontend/src/concepts/proxy/types.ts
  frontend/src/concepts/proxy/useAPIState.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelServing/ModelServingRoutes.tsx
  frontend/src/pages/modelServing/screens/metrics/GlobalInferenceMetricsWrapper.tsx
  frontend/src/pages/modelServing/screens/metrics/MetricsPage.tsx
  frontend/src/pages/modelServing/screens/metrics/TrustyChart.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectInferenceMetricsWrapper.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectRuntimeMetricsWrapper.tsx
  frontend/src/pages/projects/ProjectViewRoutes.tsx
Labels: lgtm, approved

#1309 Fix Project Create/Update/Delete Modals
  frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTable.tsx
  frontend/src/concepts/projects/ProjectsContext.tsx
  frontend/src/pages/projects/components/DeleteModal.tsx
  frontend/src/pages/projects/screens/projects/DeleteProjectModal.tsx
  frontend/src/pages/projects/screens/projects/ManageProjectModal.tsx
  frontend/src/pages/projects/screens/projects/NewProjectButton.tsx
  frontend/src/pages/projects/screens/projects/ProjectListView.tsx
  frontend/src/utilities/useFetchState.ts
Labels: lgtm, approved

#1249 Parse BYON repository URL correctly
  backend/src/routes/api/images/imageUtils.ts
  backend/src/types.ts
  backend/src/utils/constants.ts
  frontend/src/__tests__/dockerRepositoryURL.spec.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/BYONImages/BYONImagesTable.tsx
  frontend/src/pages/BYONImages/ImageErrorStatus.tsx
  frontend/src/pages/BYONImages/ImportImageModal.tsx
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageSelectorField.tsx
  frontend/src/pages/projects/screens/spawner/spawnerUtils.ts
  frontend/src/types.ts
  frontend/src/utilities/NavData.tsx
  frontend/src/utilities/const.ts
Labels: lgtm, approved

#1046 add dynamic namespace to delegate-url oauth arg
  manifests/base/deployment.yaml
  manifests/overlays/authentication/deployment.yaml
Labels: lgtm, approved, ok-to-test

#1291 Fix serving runtime edit creation
  frontend/src/api/k8s/serviceAccounts.ts
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenInput.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenSection.tsx
  frontend/src/pages/modelServing/utils.ts
Labels: lgtm, approved

#1322 pipelines modal use up top date data connections
  frontend/src/concepts/pipelines/content/configurePipelinesServer/ConfigurePipelinesServerModal.tsx
  frontend/src/concepts/pipelines/content/configurePipelinesServer/ObjectStorageSection.tsx
Labels: lgtm, approved

#1321 navigate on new run form
  frontend/src/concepts/pipelines/content/createRun/RunForm.tsx
  frontend/src/concepts/pipelines/content/createRun/const.ts
Labels: lgtm, approved

#1290 Add model bias configuration table
  frontend/src/concepts/dashboard/DashboardSearchField.tsx
  frontend/src/pages/modelServing/ModelServingRoutes.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceListView.tsx
  frontend/src/pages/modelServing/screens/metrics/BiasConfigurationBreadcrumbPage.tsx
  frontend/src/pages/modelServing/screens/metrics/BiasConfigurationEmptyState.tsx
  frontend/src/pages/modelServing/screens/metrics/BiasConfigurationPage.tsx
  frontend/src/pages/modelServing/screens/metrics/BiasConfigurationTable.tsx
  frontend/src/pages/modelServing/screens/metrics/BiasConfigurationTableRow.tsx
  frontend/src/pages/modelServing/screens/metrics/GlobalInferenceMetricsPage.tsx
  frontend/src/pages/modelServing/screens/metrics/GlobalInferenceMetricsWrapper.tsx
  frontend/src/pages/modelServing/screens/metrics/InferenceMetricsPathWrapper.tsx
  frontend/src/pages/modelServing/screens/metrics/MetricsPage.tsx
  frontend/src/pages/modelServing/screens/metrics/tableData.tsx
  frontend/src/pages/modelServing/screens/metrics/utils.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectInferenceMetricsConfigurationPage.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectInferenceMetricsPage.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectInferenceMetricsPathWrapper.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectInferenceMetricsWrapper.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectRuntimeMetricsWrapper.tsx
  frontend/src/pages/projects/ProjectViewRoutes.tsx
  frontend/src/pages/projects/screens/projects/ProjectListView.tsx
Labels: lgtm, approved

#1175 feat: add GH action to scan files in repo on PR basis
  .github/trivy.yaml
  .github/workflows/vuln_scan.yml
Labels: lgtm, approved, needs-ok-to-test

#1337 Update Trusty AI client to handle API changes (#1336)
  frontend/src/api/trustyai/rawTypes.ts
Labels: lgtm, approved, feature/model-serving

#1343 Add bias metrics configuration modal
  frontend/src/api/prometheus/serving.ts
  frontend/src/concepts/dashboard/DashboardModalFooter.tsx
  frontend/src/pages/modelServing/ModelServingRoutes.tsx
  frontend/src/pages/modelServing/screens/metrics/BiasConfigurationAlertPopover.tsx
  frontend/src/pages/modelServing/screens/metrics/BiasConfigurationBreadcrumbPage.tsx
  frontend/src/pages/modelServing/screens/metrics/BiasConfigurationButton.tsx
  frontend/src/pages/modelServing/screens/metrics/BiasConfigurationPage.tsx
  frontend/src/pages/modelServing/screens/metrics/BiasConfigurationTable.tsx
  frontend/src/pages/modelServing/screens/metrics/BiasConfigurationTableRow.tsx
  frontend/src/pages/modelServing/screens/metrics/BiasTab.tsx
  frontend/src/pages/modelServing/screens/metrics/EmptyBiasConfigurationCard.tsx
  frontend/src/pages/modelServing/screens/metrics/MetricsPage.tsx
  frontend/src/pages/modelServing/screens/metrics/MetricsPageTabs.tsx
  frontend/src/pages/modelServing/screens/metrics/biasConfigurationModal/DeleteBiasConfigurationModal.tsx
  frontend/src/pages/modelServing/screens/metrics/biasConfigurationModal/ManageBiasConfigurationModal.tsx
  frontend/src/pages/modelServing/screens/metrics/biasConfigurationModal/MetricTypeField.tsx
  frontend/src/pages/modelServing/screens/metrics/biasConfigurationModal/useBiasConfigurationObject.ts
  frontend/src/pages/modelServing/screens/metrics/const.ts
  frontend/src/pages/modelServing/screens/metrics/tableData.tsx
  frontend/src/pages/modelServing/screens/metrics/utils.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectInferenceMetricsConfigurationPage.tsx
  frontend/src/pages/projects/ProjectViewRoutes.tsx
Labels: lgtm, approved

#1314 add playwright testing and e2e testing
  .github/workflows/pull_request.yml
  .github/workflows/storybook-tests.yml
  CONTRIBUTING.md
  frontend/.babelrc.json
  frontend/.env.test
  frontend/.eslintrc
  frontend/.gitignore
  frontend/.storybook/main.js
  frontend/.storybook/test-runner.js
  frontend/config/setupTests.js
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/playwright.config.ts
  frontend/src/__tests__/EnabledApplications.spec.tsx
  frontend/src/__tests__/ExploreApplications.spec.tsx
  frontend/src/__tests__/LearningCenter.spec.tsx
  frontend/src/__tests__/e2e/CreateEditDeleteProject.spec.ts
  frontend/src/__tests__/e2e/const.ts
  frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.spec.ts
  frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.stories.tsx
  frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts
  frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.stories.tsx
  frontend/src/__tests__/integration/pages/projects/ProjectDetails.spec.ts
  frontend/src/__tests__/integration/pages/projects/ProjectDetails.stories.tsx
  frontend/src/__tests__/integration/pages/projects/ProjectView.spec.ts
  frontend/src/__tests__/integration/pages/projects/ProjectView.stories.tsx
  frontend/src/__tests__/unit/notebookControllerUtils.spec.ts
  frontend/src/pages/modelServing/screens/global/ModelServingGlobal.stories.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ExistingProjectField.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceFrameworkSection.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceServingRuntimeSection.tsx
  frontend/src/pages/projects/screens/projects/ProjectView.stories.tsx
  frontend/tsconfig.json
  package.json
  tests/__snapshots__/dist.test.js.snap
  tests/dist.test.js
Labels: lgtm, approved

#1293 Add tensorflow as supported runtime of onnx ootb
  manifests/modelserving/ovms-gpu-ootb.yaml
  manifests/modelserving/ovms-ootb.yaml
Labels: lgtm, approved

#1294 Refactor Custom Serving Runtime admin
  backend/src/routes/api/dashboardConfig/index.ts
  backend/src/routes/api/servingRuntimes/index.ts
  backend/src/routes/api/templates/index.ts
  backend/src/types.ts
  frontend/src/api/k8s/dashboardConfig.ts
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAddTemplate.tsx
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeContext.tsx
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeEnabledToggle.tsx
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeListView.tsx
  frontend/src/pages/modelServing/customServingRuntimes/DeleteCustomServingRuntimeModal.tsx
  frontend/src/pages/modelServing/customServingRuntimes/useTemplateOrder.ts
  frontend/src/pages/modelServing/customServingRuntimes/useTemplates.ts
  frontend/src/services/dashboardService.ts
  frontend/src/services/templateService.ts
Labels: lgtm, approved

#1378 Fix metrics submission issue and handle errors
  frontend/src/api/trustyai/custom.ts
  frontend/src/api/trustyai/errorUtils.ts
  frontend/src/api/trustyai/rawTypes.ts
  frontend/src/concepts/dashboard/DashboardModalFooter.tsx
  frontend/src/concepts/explainability/useExplainabilityModelData.ts
  frontend/src/concepts/explainability/useTrustyAPIState.ts
  frontend/src/pages/modelServing/screens/metrics/BiasMetricConfigSelector.tsx
  frontend/src/pages/modelServing/screens/metrics/BiasTab.tsx
  frontend/src/pages/modelServing/screens/metrics/biasConfigurationModal/ManageBiasConfigurationModal.tsx
  frontend/src/pages/modelServing/screens/metrics/biasConfigurationModal/useBiasConfigurationObject.ts
  frontend/src/pages/modelServing/screens/metrics/utils.tsx
Labels: lgtm, approved

#1382 Fixes to update project error message
  frontend/src/pages/projects/screens/projects/ManageProjectModal.tsx
Labels: lgtm, approved

#1074 Refactor ClusterSettings page and add storybook tests
  frontend/package.json
  frontend/src/__mocks__/mockClusterSettings.ts
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/__tests__/integration/pages/clusterSettings/ClusterSettings.spec.ts
  frontend/src/__tests__/integration/pages/clusterSettings/ClusterSettings.stories.tsx
  frontend/src/__tests__/integration/pages/projects/ProjectDetails.spec.ts
  frontend/src/pages/clusterSettings/ClusterSettings.tsx
  frontend/src/pages/clusterSettings/CullerSettings.tsx
  frontend/src/pages/clusterSettings/PVCSizeSettings.tsx
  frontend/src/pages/clusterSettings/TelemetrySettings.tsx
  frontend/src/pages/clusterSettings/TolerationSettings.tsx
  frontend/src/pages/clusterSettings/const.ts
  frontend/src/pages/projects/screens/detail/ProjectDetailsComponents.tsx
  frontend/src/services/clusterSettingsService.ts
  frontend/src/types.ts
Labels: lgtm, approved

#1391 Rename 'Upload a new pipeline' to 'Import pipeline' to keep consistency
  frontend/src/concepts/pipelines/content/createRun/contentSections/PipelineSection.tsx
Labels: lgtm, approved

#1393 Fix nav logo in safari
  frontend/src/app/App.scss
Labels: lgtm, approved

#1398 Rename configure to add
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeList.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeListButtonAction.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
Labels: lgtm, approved

#1390 Default and restrict threshold, add tooltips, default duplicate name and set feature flag
  backend/src/types.ts
  backend/src/utils/constants.ts
  docs/dashboard_config.md
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/api/prometheus/serving.ts
  frontend/src/api/prometheus/usePrometheusQueryRange.ts
  frontend/src/concepts/dashboard/DashboardEmptyTableView.tsx
  frontend/src/concepts/dashboard/DashboardHelpTooltip.tsx
  frontend/src/concepts/explainability/ExplainabilityContext.tsx
  frontend/src/concepts/explainability/useBiasMetricsEnabled.ts
  frontend/src/concepts/explainability/useTrustyAPIRoute.ts
  frontend/src/concepts/explainability/useTrustyAiNamespaceCR.ts
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTable.tsx
  frontend/src/pages/modelServing/ModelServingRoutes.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx
  frontend/src/pages/modelServing/screens/metrics/BiasConfigurationEmptyState.tsx
  frontend/src/pages/modelServing/screens/metrics/BiasConfigurationPage.tsx
  frontend/src/pages/modelServing/screens/metrics/BiasConfigurationTable.tsx
  frontend/src/pages/modelServing/screens/metrics/EmptyBiasConfigurationCard.tsx
  frontend/src/pages/modelServing/screens/metrics/MetricsPageTabs.tsx
  frontend/src/pages/modelServing/screens/metrics/biasConfigurationModal/ManageBiasConfigurationModal.tsx
  frontend/src/pages/modelServing/screens/metrics/biasConfigurationModal/MetricTypeField.tsx
  frontend/src/pages/modelServing/screens/metrics/biasConfigurationModal/useBiasConfigurationObject.ts
  frontend/src/pages/modelServing/screens/metrics/const.ts
  frontend/src/pages/modelServing/screens/metrics/useMetricsPageEnabledTabs.ts
  frontend/src/pages/modelServing/screens/metrics/utils.tsx
  frontend/src/pages/pipelines/global/pipelines/PipelinesView.tsx
  frontend/src/pages/projects/ProjectViewRoutes.tsx
  frontend/src/pages/projects/screens/projects/ProjectListView.tsx
  frontend/src/types.ts
  manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
  manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Labels: lgtm, approved

#1399 Minor enhancements to bias chart (#1386)
  frontend/src/pages/modelServing/screens/const.ts
  frontend/src/pages/modelServing/screens/metrics/BiasTab.tsx
  frontend/src/pages/modelServing/screens/metrics/EmptyBiasChartSelectionCard.tsx
  frontend/src/pages/modelServing/screens/metrics/biasConfigurationModal/DeleteBiasConfigurationModal.tsx
  frontend/src/pages/modelServing/screens/metrics/useBiasChartsBrowserStorage.ts
  frontend/src/pages/modelServing/screens/types.ts
Labels: lgtm, approved

#1404 Fixes issue with bias charts auto-refreshing with stale data (#1403)
  frontend/src/api/prometheus/serving.ts
  frontend/src/api/prometheus/useQueryRangeResourceData.ts
  frontend/src/utilities/useRefreshInterval.ts
  frontend/src/utilities/useRestructureContextResourceData.tsx
Labels: lgtm, approved

#1396 Rename kebab actions from 'Clone' to 'Duplicate'
  frontend/src/concepts/pipelines/content/createRun/CloneRunPage.tsx
  frontend/src/concepts/pipelines/content/createRun/useRunFormData.ts
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetailsActions.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTableRow.tsx
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeTableRow.tsx
Labels: lgtm, approved

#1354 Fix serving runtime validation
  backend/src/types.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelServing/customServingRuntimes/utils.ts
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
Labels: lgtm, approved

#1402 Migration of listent function for fastify v4
  backend/src/server.ts
  backend/src/utils/constants.ts
Labels: lgtm, approved

#1416 Switch to Kubernetes secret instead of users credentials
  frontend/src/concepts/pipelines/context/useManageElyraSecret.ts
  frontend/src/concepts/pipelines/elyra/utils.ts
Labels: lgtm, approved

#1412 no pipelines error fix
  backend/src/utils/resourceUtils.ts
  frontend/src/pages/dependencies/PipelinesDependencyMissing.tsx
Labels: lgtm, approved

#1410 Make pipeline input parameters more evident
  frontend/src/concepts/pipelines/content/createRun/const.ts
Labels: lgtm, approved

#1397 Fix legacy model server display name
  frontend/src/__mocks__/mockRouteK8sResource.ts
  frontend/src/__mocks__/mockServingRuntimeK8sResource.ts
  frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.spec.ts
  frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts
  frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.stories.tsx
  frontend/src/__tests__/integration/pages/projects/ProjectDetails.stories.tsx
  frontend/src/pages/modelServing/customServingRuntimes/utils.ts
Labels: lgtm, approved

#1413 Add performance metrics feature flag and refactor runtime server route
  backend/src/types.ts
  backend/src/utils/constants.ts
  docs/dashboard_config.md
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/api/prometheus/serving.ts
  frontend/src/pages/modelServing/screens/metrics/GlobalInferenceMetricsPage.tsx
  frontend/src/pages/modelServing/screens/metrics/MetricsPage.tsx
  frontend/src/pages/modelServing/screens/metrics/MetricsPageTabs.scss
  frontend/src/pages/modelServing/screens/metrics/MetricsPageTabs.tsx
  frontend/src/pages/modelServing/screens/metrics/PerformanceTab.tsx
  frontend/src/pages/modelServing/screens/metrics/useMetricsPageEnabledTabs.ts
  frontend/src/pages/modelServing/screens/metrics/usePerformanceMetricsEnabled.ts
  frontend/src/pages/modelServing/screens/projects/ProjectInferenceMetricsPage.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectRuntimeMetricsPathWrapper.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectRuntimeMetricsWrapper.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableRow.tsx
  frontend/src/pages/modelServing/screens/projects/utils.ts
  frontend/src/pages/modelServing/useModelMetricsEnabled.ts
  frontend/src/pages/projects/ProjectViewRoutes.tsx
  frontend/src/types.ts
  manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
  manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Labels: lgtm, approved

#1419 Update Existing Elyra Secret if incorrect
  frontend/src/concepts/pipelines/context/useManageElyraSecret.ts
  frontend/src/concepts/pipelines/elyra/const.ts
  frontend/src/concepts/pipelines/elyra/utils.ts
Labels: lgtm, approved

#1414 Enhance modal to delete project by pressing enter key
  frontend/src/pages/projects/components/DeleteModal.tsx
Labels: lgtm, approved, ok-to-test

#1421 Model serving metrics renaming
  frontend/src/api/prometheus/serving.ts
  frontend/src/api/trustyai/rawTypes.ts
  frontend/src/concepts/explainability/types.ts
  frontend/src/pages/modelServing/ModelServingRoutes.tsx
  frontend/src/pages/modelServing/screens/metrics/BiasConfigurationBreadcrumbPage.tsx
  frontend/src/pages/modelServing/screens/metrics/BiasMetricConfigSelector.tsx
  frontend/src/pages/modelServing/screens/metrics/GlobalInferenceMetricsWrapper.tsx
  frontend/src/pages/modelServing/screens/metrics/GlobalModelMetricsPage.tsx
  frontend/src/pages/modelServing/screens/metrics/GlobalModelMetricsWrapper.tsx
  frontend/src/pages/modelServing/screens/metrics/MetricsPage.tsx
  frontend/src/pages/modelServing/screens/metrics/ModelGraphs.tsx
  frontend/src/pages/modelServing/screens/metrics/ModelMetricsPathWrapper.tsx
  frontend/src/pages/modelServing/screens/metrics/ModelServingMetricsContext.tsx
  frontend/src/pages/modelServing/screens/metrics/PerformanceTab.tsx
  frontend/src/pages/modelServing/screens/metrics/ServerGraphs.tsx
  frontend/src/pages/modelServing/screens/metrics/TrustyChart.tsx
  frontend/src/pages/modelServing/screens/metrics/biasConfigurationModal/DeleteBiasConfigurationModal.tsx
  frontend/src/pages/modelServing/screens/metrics/biasConfigurationModal/ManageBiasConfigurationModal.tsx
  frontend/src/pages/modelServing/screens/metrics/biasConfigurationModal/MetricTypeField.tsx
  frontend/src/pages/modelServing/screens/metrics/biasConfigurationModal/useBiasConfigurationObject.ts
  frontend/src/pages/modelServing/screens/metrics/const.ts
  frontend/src/pages/modelServing/screens/metrics/types.ts
  frontend/src/pages/modelServing/screens/metrics/utils.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectInferenceMetricsWrapper.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectModelMetricsConfigurationPage.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectModelMetricsPage.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectModelMetricsPathWrapper.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectModelMetricsWrapper.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectServerMetricsPathWrapper.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectServerMetricsWrapper.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableRow.tsx
  frontend/src/pages/modelServing/screens/types.ts
  frontend/src/pages/projects/ProjectViewRoutes.tsx
Labels: lgtm, approved

#1406 Pipeline experiments
  frontend/src/api/pipelines/callTypes.ts
  frontend/src/api/pipelines/custom.ts
  frontend/src/components/table/CheckboxCell.tsx
  frontend/src/components/table/CheckboxTd.tsx
  frontend/src/components/table/Table.tsx
  frontend/src/concepts/pipelines/apiHooks/useExperiements.ts
  frontend/src/concepts/pipelines/content/DeletePipelineCoreResourceModal.tsx
  frontend/src/concepts/pipelines/content/createRun/RunForm.tsx
  frontend/src/concepts/pipelines/content/createRun/RunPage.tsx
  frontend/src/concepts/pipelines/content/createRun/const.ts
  frontend/src/concepts/pipelines/content/createRun/contentSections/ExperimentSection.tsx
  frontend/src/concepts/pipelines/content/createRun/submitUtils.ts
  frontend/src/concepts/pipelines/content/createRun/types.ts
  frontend/src/concepts/pipelines/content/createRun/useRunFormData.ts
  frontend/src/concepts/pipelines/content/experiment/ManageExperimentModal.tsx
  frontend/src/concepts/pipelines/content/tables/ExperimentToggleGroup.tsx
  frontend/src/concepts/pipelines/content/tables/RunTableToolbarActions.tsx
  frontend/src/concepts/pipelines/content/tables/columns.ts
  frontend/src/concepts/pipelines/content/tables/experiments/ExperimentActions.tsx
  frontend/src/concepts/pipelines/content/tables/experiments/ExperimentsTable.tsx
  frontend/src/concepts/pipelines/content/tables/experiments/ExperimentsTableRow.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableToolbar.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTable.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTableRow.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTableToolbar.tsx
  frontend/src/concepts/pipelines/context/useAPIState.ts
  frontend/src/concepts/pipelines/types.ts
  frontend/src/pages/pipelines/global/runs/GlobalPipelineRunsTabs.tsx
  frontend/src/pages/pipelines/global/runs/ScheduledRuns.tsx
  frontend/src/pages/pipelines/global/runs/TriggeredRuns.tsx
Labels: lgtm, approved

#1436 Keep the enabled/disabled status after editing the custom notebook image
  backend/src/routes/api/images/imageUtils.ts
Labels: lgtm, approved, ok-to-test

#1443 Adds support for TrustyAI Operator
  frontend/src/api/models/trustyai.ts
  frontend/src/api/trustyai/k8s.ts
  frontend/src/concepts/explainability/ExplainabilityContext.tsx
  frontend/src/concepts/explainability/const.ts
  frontend/src/concepts/explainability/content/InstallTrustyAICheckbox.tsx
  frontend/src/concepts/explainability/content/TrustyAIDeleteModal.tsx
  frontend/src/concepts/explainability/types.ts
  frontend/src/concepts/explainability/useBiasMetricsInstalled.ts
  frontend/src/concepts/explainability/useExplainabilityModelData.ts
  frontend/src/concepts/explainability/useManageTrustyAICR.ts
  frontend/src/concepts/explainability/useTrustyAIAPIRoute.ts
  frontend/src/concepts/explainability/useTrustyAIAPIState.ts
  frontend/src/concepts/explainability/useTrustyAINamespaceCR.ts
  frontend/src/concepts/explainability/useTrustyAiNamespaceCR.ts
  frontend/src/concepts/proxy/useAPIState.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelServing/ModelServingRoutes.tsx
  frontend/src/pages/modelServing/screens/metrics/MetricsPage.tsx
  frontend/src/pages/modelServing/screens/metrics/MetricsPageTabs.tsx
  frontend/src/pages/modelServing/screens/metrics/ModelServingExplainabilityWrapper.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectInferenceExplainabilityWrapper.tsx
  frontend/src/pages/projects/ProjectDetailsContext.tsx
  frontend/src/pages/projects/ProjectViewRoutes.tsx
  frontend/src/pages/projects/projectSettings/ModelBiasSettingsCard.tsx
  frontend/src/pages/projects/projectSettings/ProjectSettingsPage.tsx
  frontend/src/pages/projects/projectSettings/const.ts
  frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
Labels: lgtm, approved

#1446 Fix typo in triaging.md
  docs/triaging.md
Labels: lgtm, approved

#1361 chore: resolved the gap issue when Error shows
  frontend/src/concepts/dashboard/DashboardModalFooter.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
Labels: lgtm, approved

#1407 Refactor Custom Serving Runtime enablement
  backend/src/routes/api/dashboardConfig/index.ts
  backend/src/routes/api/rolebindings/index.ts
  backend/src/routes/api/templates/index.ts
  backend/src/types.ts
  backend/src/utils/constants.ts
  backend/src/utils/resourceUtils.ts
  docs/dashboard_config.md
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/api/k8s/dashboardConfig.ts
  frontend/src/api/k8s/templates.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeContext.tsx
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeEnabledToggle.tsx
  frontend/src/pages/modelServing/customServingRuntimes/DeleteCustomServingRuntimeModal.tsx
  frontend/src/pages/modelServing/customServingRuntimes/useTemplateDisablement.ts
  frontend/src/pages/modelServing/customServingRuntimes/utils.ts
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeList.tsx
  frontend/src/pages/projects/ProjectDetailsContext.tsx
  frontend/src/services/dashboardService.ts
  frontend/src/services/templateService.ts
  frontend/src/types.ts
  manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
  manifests/modelserving/ovms-gpu-ootb.yaml
  manifests/modelserving/ovms-ootb.yaml
  manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Labels: lgtm, approved
