Repository opendatahub-io/odh-dashboard, pull requests merged in 2023-09, with the labels that each got.

#1724 Pipeline run pod logs
  frontend/src/components/SimpleDropdownSelect.tsx
  frontend/src/concepts/dashboard/codeEditor/useCodeEditorAsLogs.tsx
  frontend/src/concepts/k8s/pods/useFetchLogs.ts
  frontend/src/concepts/k8s/pods/usePod.ts
  frontend/src/concepts/k8s/pods/utils.ts
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightContent.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightTabs.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTabStatus.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/const.ts
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/usePodContainerLogState.ts
  frontend/src/k8sTypes.ts
  frontend/src/utilities/string.ts
Labels: lgtm, approved

#1749 Refresh data connections when deploying model on project details page
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeList.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTable.tsx
Labels: lgtm, approved

#1677 Fix bug in migration for GPUS
  backend/src/routes/api/accelerators/acceleratorUtils.ts
  backend/src/types.ts
  backend/src/utils/resourceUtils.ts
  frontend/src/api/k8s/accelerators.ts
  frontend/src/api/k8s/notebooks.ts
  frontend/src/api/k8s/servingRuntimes.ts
  frontend/src/api/k8s/utils.ts
  frontend/src/components/SimpleDropdownSelect.tsx
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeDetails.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTemplateSection.tsx
  frontend/src/pages/modelServing/screens/projects/useServingAccelerator.ts
  frontend/src/pages/modelServing/screens/projects/useServingRuntimeAccelerator.ts
  frontend/src/pages/modelServing/screens/projects/utils.ts
  frontend/src/pages/modelServing/screens/types.ts
  frontend/src/pages/notebookController/screens/server/AcceleratorSelectField.tsx
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/pages/notebookController/screens/server/useAccelerators.ts
  frontend/src/pages/projects/screens/detail/notebooks/useNotebookAccelerator.ts
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/types.ts
  frontend/src/types.ts
  frontend/src/utilities/tolerations.ts
  frontend/src/utilities/useAcceleratorState.ts
  manifests/base/cluster-role.yaml
Labels: lgtm, approved

#1718 Truncate long display name in serving runtimes
  frontend/src/components/table/Table.tsx
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeTableRow.tsx
Labels: lgtm, approved

#1753 revert add rbac accelerator role
  manifests/base/fetch-accelerators.rbac.yaml
  manifests/base/kustomization.yaml
Labels: lgtm, approved

#1748 Limit storage min size onBlur instead of onChange
  frontend/src/pages/projects/components/PVSizeField.tsx
Labels: lgtm, approved

#1703 display StatefulSet errors when notebook pod fails to create
  backend/src/routes/api/nb-events/eventUtils.ts
  backend/src/routes/api/nb-events/index.ts
  frontend/src/api/k8s/events.ts
  frontend/src/api/models/k8s.ts
  frontend/src/pages/notebookController/screens/server/StartServerModal.tsx
  frontend/src/pages/projects/notebook/StartNotebookModal.tsx
  frontend/src/pages/projects/notebook/useWatchNotebookEvents.ts
  frontend/src/pages/projects/notebook/utils.ts
  frontend/src/services/notebookEventsService.ts
  frontend/src/utilities/notebookControllerUtils.ts
  frontend/src/utilities/useWatchNotebookEvents.tsx
Labels: lgtm, approved

#1754 add rbac accelerator role
  manifests/base/fetch-accelerators.rbac.yaml
  manifests/base/kustomization.yaml
Labels: lgtm, approved

#1725 Update Jupyter Quickstart
  manifests/apps/jupyter/create-jupyter-notebook-quickstart.yaml
  manifests/apps/jupyter/deploy-python-model-quickstart.yaml
  manifests/apps/jupyter/jupyter-app.yaml
  manifests/apps/jupyter/jupyter-docs.yaml
  manifests/apps/jupyter/kustomization.yaml
Labels: lgtm, approved

#1630 add utility to make it easier and more robust to test hooks
  frontend/package-lock.json
  frontend/package.json
  frontend/src/__tests__/unit/testUtils/hooks.spec.ts
  frontend/src/__tests__/unit/testUtils/hooks.ts
  frontend/src/__tests__/unit/useFetchState.spec.ts
  frontend/src/__tests__/unit/useGroups.spec.ts
  frontend/src/pages/TestPage.tsx.bak
  frontend/src/utilities/useFetchState.ts
Labels: lgtm, approved, pr/no-tests-allowed

#1755 tooltip on pipeline screen impede clicking of the slider right above
  frontend/src/concepts/pipelines/content/tables/renderUtils.tsx
Labels: lgtm, approved, pr/no-tests-allowed

#1752 Add access check before deleting model server
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTable.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableRow.tsx
Labels: lgtm, approved, pr/no-tests-allowed

#1722 Added pipeline run param tab
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerBottomTabs.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabParameters.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/utils.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/TaskDetailsPrintKeyValues.tsx
Labels: lgtm, approved, pr/no-tests-allowed

#1764 Minor accelerator fixes
  backend/src/plugins/kube.ts
  backend/src/routes/api/accelerators/acceleratorUtils.ts
  backend/src/utils/resourceUtils.ts
  frontend/src/components/SimpleDropdownSelect.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeDetails.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx
  frontend/src/pages/notebookController/screens/server/AcceleratorSelectField.tsx
  frontend/src/pages/notebookController/screens/server/NotebookServerDetails.tsx
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
  frontend/src/utilities/useAcceleratorState.ts
Labels: lgtm, approved, pr/no-tests-allowed

#1777 Fix model server expand issue on the project details page
  frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTable.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableRow.tsx
Labels: lgtm, approved

#1773 co-locate unit tests with their target source
  docs/architecture.md
  frontend/jest.config.js
  frontend/src/__tests__/dockerRepositoryURL.spec.ts
  frontend/src/pages/TestPage.tsx.bak
  frontend/src/pages/projects/projectSharing/__tests__/useGroups.spec.ts
  frontend/src/utilities/__tests__/const.spec.ts
  frontend/src/utilities/__tests__/notebookControllerUtils.spec.ts
  frontend/src/utilities/__tests__/useFetchState.spec.ts
Labels: lgtm, approved

#1739 Fixed isCpuLimitEqual and isMemoryLimitEqual wrongly comparing null/undefined values.
  frontend/src/utilities/__tests__/valueUnits.spec.ts
  frontend/src/utilities/valueUnits.ts
Labels: lgtm, approved, ok-to-test, pr/no-tests-allowed

#1714 Support storage size unit and show error message correctly
  frontend/src/api/k8s/notebooks.ts
  frontend/src/api/k8s/pvcs.ts
  frontend/src/app/App.scss
  frontend/src/components/ValueUnitField.tsx
  frontend/src/pages/clusterSettings/ClusterSettings.tsx
  frontend/src/pages/clusterSettings/PVCSizeSettings.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionSection.tsx
  frontend/src/pages/notebookController/const.ts
  frontend/src/pages/projects/components/PVSizeField.tsx
  frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.scss
  frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx
  frontend/src/pages/projects/screens/spawner/service.ts
  frontend/src/pages/projects/screens/spawner/storage/StorageField.tsx
  frontend/src/pages/projects/screens/spawner/storage/useAvailablePvcSize.ts
  frontend/src/pages/projects/screens/spawner/storage/useDefaultPvcSize.ts
  frontend/src/pages/projects/screens/spawner/storage/utils.ts
  frontend/src/pages/projects/types.ts
  frontend/src/types.ts
Labels: lgtm, approved, pr/no-tests-allowed

#1761 Add shm to ServingRuntime volumes and volumeMounts
  backend/src/types.ts
  frontend/src/api/k8s/notebooks.ts
  frontend/src/api/k8s/servingRuntimes.ts
  frontend/src/api/k8s/utils.ts
  frontend/src/k8sTypes.ts
Labels: lgtm, approved, pr/no-tests-allowed

#1782 Minor UX fixes for custom notebook images
  frontend/src/pages/BYONImages/BYONImageModal/ImageLocationField.tsx
  frontend/src/pages/BYONImages/BYONImageModal/ManageBYONImageModal.tsx
  frontend/src/pages/BYONImages/BYONImagesTableRow.tsx
  frontend/src/pages/BYONImages/utils.ts
Labels: lgtm, approved

#1778 Fix error creating pipeline server when data connection endpoint omits scheme
  frontend/jest.config.js
  frontend/src/concepts/pipelines/content/configurePipelinesServer/__tests__/utils.spec.ts
  frontend/src/concepts/pipelines/content/configurePipelinesServer/utils.ts
Labels: lgtm, approved

#1789 Added Edge to SME areas
  docs/smes.md
Labels: lgtm, approved

#1517 Fix Pipeline Job titles are partially handled
  frontend/src/components/table/TableRowTitleDescription.tsx
  frontend/src/concepts/pipelines/content/DeletePipelineCoreResourceModal.tsx
  frontend/src/concepts/pipelines/content/PipelineJobReferenceName.tsx
  frontend/src/concepts/pipelines/content/PipelineRunTypeLabel.tsx
  frontend/src/concepts/pipelines/content/createRun/useRunFormData.ts
  frontend/src/concepts/pipelines/content/pipelinesDetails/PipelineDetailsTitle.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabDetails.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRowTitle.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/usePipelineRunFilter.ts
  frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTable.tsx
  frontend/src/concepts/pipelines/content/tables/utils.ts
  frontend/src/concepts/pipelines/context/PipelinesContext.tsx
  frontend/src/concepts/pipelines/context/useJobRelatedInformation.ts
  frontend/src/pages/ApplicationsPage.tsx
  frontend/src/pages/projects/components/DeleteModal.tsx
Labels: lgtm, approved, pr/no-tests-allowed

#1794 Add UX and Tracker internal templates
  .github/ISSUE_TEMPLATE/internal_tracker.yml
  .github/ISSUE_TEMPLATE/internal_ux.yml
Labels: lgtm, approved

#1803 update scroll container selector for JumpLinks
  frontend/src/app/App.tsx
  frontend/src/components/GenericSidebar.tsx
  frontend/src/utilities/const.ts
  frontend/src/utilities/utils.ts
Labels: lgtm, approved

#1828 Improve logging with objects
  backend/.eslintrc
  backend/src/plugins/kube.ts
  backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts
  backend/src/routes/api/dev-impersonate/index.ts
  backend/src/routes/api/groups-config/groupsConfigUtil.ts
  backend/src/routes/api/images/imageUtils.ts
  backend/src/routes/api/segment-key/segmentKeyUtils.ts
  backend/src/server.ts
  backend/src/utils/adminUtils.ts
  backend/src/utils/prometheusUtils.ts
Labels: lgtm, approved

#1834 Revert "Revamp empty state in Model Serving Global"
  docs/architecture.md
  frontend/src/__tests__/integration/hooks/useFetchState.spec.ts
  frontend/src/__tests__/integration/pages/clusterSettings/ClusterSettings.spec.ts
  frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.spec.ts
  frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.stories.tsx
  frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts
  frontend/src/__tests__/integration/pages/projects/ProjectDetails.spec.ts
  frontend/src/__tests__/integration/pages/projects/ProjectView.spec.ts
  frontend/src/__tests__/integration/utils.ts
  frontend/src/pages/modelServing/screens/global/EmptyModelServing.tsx
  frontend/tsconfig.json
Labels: lgtm, approved

#1819 Add duplicate option for non-OOTB custom serving runtimes
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeTableRow.tsx
Labels: lgtm, approved

#1211 Remove JupyterHub dependencies
  backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts
  backend/src/routes/api/components/list.ts
  backend/src/routes/api/docs/list.ts
  backend/src/routes/api/quickstarts/list.ts
  backend/src/utils/deployment.ts
  backend/src/utils/resourceUtils.ts
  docs/dashboard_config.md
  docs/user_interaction.md
  frontend/src/__mocks__/mockDocs.ts
  frontend/src/__mocks__/mockEnabledApplications.ts
  frontend/src/__mocks__/mockExploreApplications.ts
  frontend/src/__mocks__/mockGettingStartedDoc.ts
  frontend/src/app/AppRoutes.tsx
  frontend/src/images/jupyterhub.svg
  frontend/src/pages/clusterSettings/ClusterSettings.tsx
  frontend/src/pages/notebookController/screens/server/NotebookControlPanelRedirect.tsx
  frontend/src/pages/projects/screens/projects/EmptyProjects.tsx
  frontend/src/pages/projects/screens/projects/LaunchJupyterButton.tsx
  frontend/src/pages/projects/screens/projects/ProjectListView.tsx
  manifests/apps/jupyter/jupyter-docs.yaml
  manifests/apps/jupyter/jupyterhub-app.yaml
  manifests/kfdef/odh-dashboard-kfnbc-test.yaml
  manifests/overlays/odhdashboardconfig/odh-enabled-applications-config.configmap.yaml
Labels: lgtm, approved, pr/no-tests-allowed

#1830 Tech Debt Template
  .github/ISSUE_TEMPLATE/internal_techdebt.yml
Labels: lgtm, approved

#1846 Convert nightly over to the right image
  manifests/base/kustomization.yaml
Labels: lgtm, approved

#1750 support k8s websockets
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/routes/api/k8s/pass-through.ts
  backend/src/routes/api/namespaces/namespaceUtils.ts
  backend/src/routes/wss/k8s/index.ts
  backend/src/utils/directCallUtils.ts
  frontend/.storybook/preview.js
  frontend/config/webpack.dev.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/SDKInitialize.tsx
  frontend/src/__mocks__/mock404Error.ts
  frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.stories.tsx
  frontend/src/__tests__/integration/pages/projects/ProjectDetails.stories.tsx
  frontend/src/index.tsx
  frontend/src/redux/context.ts
  frontend/src/redux/hooks.ts
  frontend/src/redux/store/store.ts
Labels: lgtm, approved, pr/no-tests-allowed

#1715 Missing Duplicate Run from Triggered Action Menu
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetailsActions.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx
Labels: lgtm, approved, pr/no-tests-allowed

#1865 fix accelerator detection logic
  backend/src/routes/api/accelerators/acceleratorUtils.ts
Labels: lgtm, approved

#1790 Fix issue with resource types for cpus
  backend/src/types.ts
  frontend/src/components/CPUField.tsx
  frontend/src/pages/modelServing/__tests__/utils.spec.ts
  frontend/src/pages/modelServing/utils.ts
  frontend/src/types.ts
  frontend/src/utilities/__tests__/valueUnits.spec.ts
  frontend/src/utilities/valueUnits.ts
Labels: lgtm, approved

#1877 update cluster role to allow accelerator profile creation
  manifests/base/cluster-role.yaml
Labels: lgtm, approved

#1784 Limit the use of `useTableColumnSort` hook
  frontend/.eslintrc
  frontend/src/components/table/Table.tsx
  frontend/src/components/table/const.ts
  frontend/src/components/table/index.ts
  frontend/src/components/table/types.ts
  frontend/src/components/table/useCheckboxTable.ts
  frontend/src/components/table/useTableColumnSort.ts
  frontend/src/concepts/pipelines/content/tables/columns.ts
  frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTable.tsx
  frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTableRow.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTable.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTableRow.tsx
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeListView.tsx
  frontend/src/pages/modelServing/customServingRuntimes/templatedData.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx
  frontend/src/pages/modelServing/screens/global/data.ts
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTable.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeTokensTable.tsx
  frontend/src/pages/modelServing/screens/projects/data.ts
  frontend/src/pages/notebookController/screens/admin/NotebookAdminControl.tsx
  frontend/src/pages/notebookController/screens/admin/data.ts
  frontend/src/pages/projects/projectSharing/ProjectSharingTable.tsx
  frontend/src/pages/projects/projectSharing/data.ts
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTable.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTableRow.tsx
  frontend/src/pages/projects/screens/detail/data-connections/data.ts
  frontend/src/pages/projects/screens/detail/notebooks/NotebookTable.tsx
  frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx
  frontend/src/pages/projects/screens/detail/notebooks/data.ts
  frontend/src/pages/projects/screens/detail/storage/StorageTable.tsx
  frontend/src/pages/projects/screens/detail/storage/StorageTableRow.tsx
  frontend/src/pages/projects/screens/detail/storage/data.ts
  frontend/src/pages/projects/screens/projects/ProjectListView.tsx
  frontend/src/pages/projects/screens/projects/tableData.tsx
Labels: lgtm, approved

#1851 Add/update documentation on the dashboard flows
  .github/ISSUE_TEMPLATE/internal_ux.yml
  CONTRIBUTING.md
  README.md
  docs/README.md
  docs/SDK.md
  docs/admin-dashboard.md
  docs/apis.md
  docs/architecture.md
  docs/byon.md
  docs/dashboard-config.md
  docs/dev-setup.md
  docs/process-definition/README.md
  docs/process-definition/advisors.md
  docs/process-definition/branches.md
  docs/process-definition/flow-feature.md
  docs/process-definition/flow-standard.md
  docs/process-definition/flow-ux.md
  docs/process-definition/incubation.md
  docs/process-definition/meta/ImagesSource.drawio
  docs/process-definition/meta/branchesBasic.png
  docs/process-definition/meta/branchesComplex.png
  docs/process-definition/meta/featureFlow.png
  docs/process-definition/meta/featureStoryFlow.png
  docs/process-definition/meta/featureTrackerFlow.png
  docs/process-definition/meta/fullFlow.png
  docs/process-definition/meta/standardFlow.png
  docs/process-definition/meta/uxInternalFlow.png
  docs/process-definition/releases.md
  docs/process-definition/tech-debt.md
  docs/process-definition/triage.md
  docs/release-steps.md
  docs/releases.md
  docs/smes.md
  docs/triaging.md
  docs/user-interaction.md
Labels: lgtm, approved
