Repository opendatahub-io/odh-dashboard, pull requests merged in 2023-10, with the labels that each got.

#1732 use generic object state on data connections and prevent resetting on edit
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/dataConnection/DataConnectionField.tsx
  frontend/src/pages/projects/screens/spawner/dataConnection/useNotebookDataConnection.ts
Labels: lgtm, approved, pr/no-tests-allowed

#1770 Add owner references to Elyra role binding when creating notebooks
  frontend/src/api/k8s/notebooks.ts
  frontend/src/api/k8s/roleBindings.ts
  frontend/src/concepts/pipelines/elyra/utils.ts
  frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx
Labels: lgtm, approved

#1887 refactor hook test utils to extend jest matchers
  frontend/jest.config.js
  frontend/src/__tests__/unit/jest.d.ts
  frontend/src/__tests__/unit/jest.setup.ts
  frontend/src/__tests__/unit/testUtils/hooks.spec.ts
  frontend/src/__tests__/unit/testUtils/hooks.ts
  frontend/src/pages/projects/projectSharing/__tests__/useGroups.spec.ts
  frontend/src/utilities/__tests__/useFetchState.spec.ts
  frontend/src/utilities/useFetchState.ts
Labels: lgtm, approved

#1885 Revamp add server button and add tooltip
  frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeList.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeListButtonAction.tsx
Labels: lgtm, approved

#1899 adding workflow to auto-add issues to project boards
  .github/workflows/auto-add-issues-to-project.yaml
Labels: lgtm, approved

#1743 Delete pipeline server from the Pipelines Section in Projects page
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineServerActions.tsx
  frontend/src/pages/pipelines/global/pipelines/GlobalPipelines.tsx
  frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx
  frontend/src/pages/projects/screens/detail/pipelines/PipelinesSection.tsx
Labels: lgtm, approved, pr/no-tests-allowed

#1903 refresh accelerators after reset
  frontend/src/utilities/useAcceleratorState.ts
Labels: lgtm, approved, pr/no-tests-allowed

#1088 feat(ossm): adds OSSM annotations to the relevant cluster resources
  backend/src/routes/api/namespaces/namespaceUtils.ts
  backend/src/routes/api/notebooks/utils.ts
  backend/src/types.ts
  backend/src/utils/constants.ts
  backend/src/utils/notebookUtils.ts
  backend/src/utils/resourceUtils.ts
  docs/dashboard_config.md
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/api/k8s/notebooks.ts
  frontend/src/api/k8s/routes.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx
  frontend/src/pages/projects/notebook/useRouteForNotebook.ts
  frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
  frontend/src/types.ts
  manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
  manifests/overlays/minimal/README.md
  manifests/overlays/minimal/deployment-resources-patch.yaml
  manifests/overlays/minimal/kustomization.yaml
  manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
  manifests/overlays/service-mesh/OWNERS
  manifests/overlays/service-mesh/kustomization.yaml
  manifests/overlays/service-mesh/patches/deployment-patch.yaml
  manifests/overlays/service-mesh/patches/oauth-client-patch.yaml
  manifests/overlays/service-mesh/patches/oauth-config-patch.yaml
  manifests/overlays/service-mesh/patches/route-patch.yaml
  manifests/overlays/service-mesh/patches/service-account-patch.yaml
  manifests/overlays/service-mesh/patches/service-patch.yaml
Labels: do-not-merge/hold, lgtm, approved, ok-to-test, pr/no-tests-allowed

#1862 Show alert when external route is set while token is not set for model server
  frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenSection.tsx
Labels: lgtm, approved

#1792 Remove 'opendatahub.io/link' dependency for notebook controller
  backend/src/routes/api/notebooks/utils.ts
  backend/src/types.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/notebookController/NotebookControllerContext.tsx
  frontend/src/pages/notebookController/NotebookLogoutRedirect.tsx
  frontend/src/pages/notebookController/SetupCurrentNotebook.tsx
  frontend/src/pages/notebookController/notebookControllerContextTypes.ts
  frontend/src/pages/notebookController/screens/server/NotebookServer.tsx
  frontend/src/pages/notebookController/useImpersonationForContext.ts
  frontend/src/services/notebookService.ts
  frontend/src/types.ts
  frontend/src/utilities/__tests__/notebookControllerUtils.spec.ts
  frontend/src/utilities/__tests__/notebookControllerUtils.spec.tsx
  frontend/src/utilities/notebookControllerUtils.ts
Labels: lgtm, approved

#1740 first try at storageclasses get and promises
  frontend/src/api/index.ts
  frontend/src/api/k8s/pvcs.ts
  frontend/src/api/k8s/storageClasses.ts
  frontend/src/api/models/k8s.ts
  frontend/src/app/App.tsx
  frontend/src/app/AppContext.ts
  frontend/src/concepts/k8s/useStorageClasses.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
  frontend/src/pages/projects/screens/spawner/service.ts
  frontend/src/pages/projects/screens/spawner/storage/usePreferredStorageClass.ts
  frontend/src/types.ts
Labels: lgtm, approved, ok-to-test, pr/no-tests-allowed

#1772 Update Custom Serving Runtime tooltip with Openshift resource information
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeTableRow.tsx
  frontend/src/services/templateService.ts
  frontend/src/types.ts
  frontend/src/utilities/__tests__/addTypesToK8sListedResources.spec.ts
  frontend/src/utilities/addTypesToK8sListedResources.ts
Labels: lgtm, approved

#1926 fix bug when filtering cluster storageclasses and now doing correct s…
  frontend/src/pages/projects/screens/spawner/storage/usePreferredStorageClass.ts
Labels: lgtm, approved, ok-to-test

#1878 Improvements to edit model server modal
  frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenInput.tsx
  frontend/src/pages/modelServing/screens/projects/utils.ts
  frontend/src/pages/modelServing/screens/types.ts
  frontend/src/pages/modelServing/utils.ts
  frontend/src/utilities/useAcceleratorState.ts
  frontend/src/utilities/utils.ts
Labels: lgtm, approved

#1934 move AcceleratorProfile crd version out of alpha
  backend/src/utils/resourceUtils.ts
  frontend/src/api/models/openShift.ts
  frontend/src/utilities/useAcceleratorState.ts
  manifests/crd/acceleratorprofiles.opendatahub.io.crd.yaml
Labels: lgtm, approved

#1930 Enforce strict equality operator
  backend/.eslintrc
  backend/src/routes/api/gpu/gpuUtils.ts
  frontend/.eslintrc
  frontend/src/pages/BYONImages/UpdateImageModal.tsx
  frontend/src/pages/learningCenter/CategoryFilters.tsx
  frontend/src/utilities/useFetchState.ts
Labels: lgtm, approved

#1949 Make data connection bucket field mandatory
  frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.spec.ts
  frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionSection.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
  frontend/src/pages/projects/dataConnections/AWSField.tsx
  frontend/src/pages/projects/screens/spawner/__tests__/spawnerUtils.spec.ts
  frontend/src/pages/projects/screens/spawner/spawnerUtils.ts
Labels: lgtm, approved

#1966 Moving triage to wiki for ease of use
  docs/process-definition/triage.md
Labels: lgtm, approved

#1936 Check serving runtime kind at creation time
  frontend/src/__mocks__/mockServingRuntimeTemplateK8sResource.ts
  frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts
  frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.stories.tsx
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAddTemplate.tsx
  frontend/src/pages/modelServing/customServingRuntimes/utils.ts
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTemplateSection.tsx
Labels: lgtm, approved

#1910 add descriptions to accelerator profile crd
  manifests/crd/acceleratorprofiles.opendatahub.io.crd.yaml
Labels: lgtm, approved

#1974 fix proxy call content-length header for encoded characters in payload
  backend/src/utils/httpUtils.ts
Labels: lgtm, approved

#1972 Update ovms and add Caikit Custom Serving Runtime
  manifests/modelserving/caikit-ootb.yaml
  manifests/modelserving/kustomization.yaml
  manifests/modelserving/ovms-gpu-ootb.yaml
  manifests/modelserving/ovms-ootb.yaml
Labels: lgtm, approved

#1957 Create dashboard configuration to control kserve and modelmesh
  backend/src/types.ts
  backend/src/utils/constants.ts
  backend/src/utils/resourceUtils.ts
  docs/dashboard-config.md
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/types.ts
  manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
  manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Labels: lgtm, approved, pr/no-tests-allowed

#1959 [Service Mesh] General Improvements
  backend/src/routes/api/notebooks/utils.ts
  backend/src/utils/resourceUtils.ts
  frontend/src/pages/projects/notebook/useRouteForNotebook.ts
Labels: lgtm, approved

#1866 Log group config errors to the pod and refine logic
  backend/src/routes/api/groups-config/groupsConfigUtil.ts
  backend/src/routes/api/groups-config/index.ts
  backend/src/utils/groupsUtils.ts
  frontend/src/services/groupSettingsService.ts
  frontend/src/utilities/__tests__/useWatchGroups.spec.ts
  frontend/src/utilities/useWatchGroups.tsx
Labels: lgtm, approved

#1981 Expose the DSC status for the client
  backend/src/routes/api/dsc/index.ts
  backend/src/types.ts
  backend/src/utils/dsc.ts
  frontend/src/k8sTypes.ts
  manifests/base/cluster-role.yaml
Labels: lgtm, approved, pr/no-tests-allowed

#1969 Adapt custom serving runtimes to KServe
  frontend/src/__mocks__/mockServingRuntimeTemplateK8sResource.ts
  frontend/src/__tests__/integration/pages/customServingRuntimes/CustomServingRuntimes.spec.ts
  frontend/src/__tests__/integration/pages/customServingRuntimes/CustomServingRuntimes.stories.tsx
  frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.stories.tsx
  frontend/src/__tests__/integration/pages/projects/ProjectDetails.stories.tsx
  frontend/src/api/k8s/templates.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAddTemplate.tsx
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeHeaderLabels.tsx
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeListView.tsx
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimePlatformsLabelGroup.tsx
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimePlatformsSelector.tsx
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeTableRow.tsx
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeView.tsx
  frontend/src/pages/modelServing/customServingRuntimes/templatedData.tsx
  frontend/src/pages/modelServing/customServingRuntimes/utils.ts
  frontend/src/services/dashboardService.ts
  frontend/src/services/templateService.ts
  frontend/src/types.ts
Labels: lgtm, approved

#1992 BYON tests added
  frontend/src/__mocks__/mockByon.ts
  frontend/src/__tests__/integration/pages/notebookImageSettings/NotebookImageSettings.spec.ts
  frontend/src/__tests__/integration/pages/notebookImageSettings/NotebookImageSettings.stories.tsx
  frontend/src/__tests__/unit/testUtils/BYONImagesUtils.spec.ts
  frontend/src/components/table/Table.tsx
  frontend/src/pages/ApplicationsPage.tsx
  frontend/src/pages/BYONImages/BYONImageModal/DisplayedContentTabContent.tsx
  frontend/src/pages/BYONImages/EmptyBYONImages.tsx
Labels: lgtm, approved

#1837 Add details view for pipeline jobs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/__mocks__/mockDataSciencePipelinesApplicationK8sResource.ts
  frontend/src/__mocks__/mockPipelinesJobProxy.ts
  frontend/src/__tests__/integration/pages/pipelines/PipelineRunJobDetails.spec.ts
  frontend/src/__tests__/integration/pages/pipelines/PipelineRunJobDetails.stories.tsx
  frontend/src/concepts/pipelines/content/createRun/useRunFormData.ts
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerBottomTabs.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightContent.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabParameters.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRunJob/PipelineRunJobDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRunJob/PipelineRunJobDetailsActions.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTableRow.tsx
  frontend/src/concepts/pipelines/content/utils.tsx
  frontend/src/pages/pipelines/GlobalPipelineRunsRoutes.tsx
  frontend/src/pages/pipelines/GlobalPipelinesRoutes.tsx
  frontend/src/pages/projects/ProjectViewRoutes.tsx
Labels: lgtm, approved

#1997 BYON Improvements Phase 1 to `main`
  backend/.eslintignore
  backend/jest.config.js
  backend/package-lock.json
  backend/package.json
  backend/src/__tests__/dockerRepositoryURL.spec.ts
  backend/src/routes/api/images/imageUtils.ts
  backend/src/types.ts
  backend/tsconfig.prod.json
  frontend/src/__mocks__/mockByon.ts
  frontend/src/__tests__/integration/pages/notebookImageSettings/NotebookImageSettings.spec.ts
  frontend/src/__tests__/integration/pages/notebookImageSettings/NotebookImageSettings.stories.tsx
  frontend/src/__tests__/unit/testUtils/BYONImagesUtils.spec.ts
  frontend/src/components/table/Table.tsx
  frontend/src/concepts/dashboard/DashboardEmptyTableView.tsx
  frontend/src/concepts/dashboard/DashboardModalFooter.tsx
  frontend/src/concepts/dashboard/DashboardSearchField.tsx
  frontend/src/pages/ApplicationsPage.tsx
  frontend/src/pages/BYONImages/BYONImageDependenciesList.tsx
  frontend/src/pages/BYONImages/BYONImageModal/DeleteBYONImageModal.tsx
  frontend/src/pages/BYONImages/BYONImageModal/DisplayedContentTabContent.tsx
  frontend/src/pages/BYONImages/BYONImageModal/DisplayedContentTable.tsx
  frontend/src/pages/BYONImages/BYONImageModal/DisplayedContentTableRow.tsx
  frontend/src/pages/BYONImages/BYONImageModal/ImageLocationField.tsx
  frontend/src/pages/BYONImages/BYONImageModal/ManageBYONImageModal.tsx
  frontend/src/pages/BYONImages/BYONImageModal/tableData.tsx
  frontend/src/pages/BYONImages/BYONImageStatusToggle.tsx
  frontend/src/pages/BYONImages/BYONImages.tsx
  frontend/src/pages/BYONImages/BYONImagesTable.scss
  frontend/src/pages/BYONImages/BYONImagesTable.tsx
  frontend/src/pages/BYONImages/BYONImagesTableRow.tsx
  frontend/src/pages/BYONImages/DeleteBYONImageModal.tsx
  frontend/src/pages/BYONImages/EditStepTableRow.tsx
  frontend/src/pages/BYONImages/EmptyBYONImages.tsx
  frontend/src/pages/BYONImages/ImportBYONImageButton.tsx
  frontend/src/pages/BYONImages/ImportImageModal.scss
  frontend/src/pages/BYONImages/ImportImageModal.tsx
  frontend/src/pages/BYONImages/UpdateImageModal.scss
  frontend/src/pages/BYONImages/UpdateImageModal.tsx
  frontend/src/pages/BYONImages/tableData.tsx
  frontend/src/pages/BYONImages/utils.ts
  frontend/src/services/imagesService.ts
  frontend/src/types.ts
  frontend/src/utilities/NavData.tsx
  frontend/src/utilities/useWatchBYONImages.ts
  frontend/src/utilities/useWatchBYONImages.tsx
Labels: lgtm, approved

#1999 Update ovms with gpu support and remove the other template
  manifests/modelserving/kustomization.yaml
  manifests/modelserving/ovms-gpu-ootb.yaml
  manifests/modelserving/ovms-ootb.yaml
Labels: lgtm, approved

#2005 Rename Container to Step
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx
Labels: lgtm, approved

#2008 add migrate crd from v1alpha to v1 on start
  manifests/crd/acceleratorprofiles.opendatahub.io.crd.yaml
Labels: lgtm, approved

#1982 Add model serving platform settings
  backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts
  backend/src/types.ts
  frontend/src/__mocks__/mockClusterSettings.ts
  frontend/src/__tests__/integration/pages/clusterSettings/ClusterSettings.spec.ts
  frontend/src/components/SettingSection.tsx
  frontend/src/pages/clusterSettings/ClusterSettings.tsx
  frontend/src/pages/clusterSettings/ModelServingPlatformSettings.tsx
  frontend/src/pages/clusterSettings/const.ts
  frontend/src/types.ts
Labels: lgtm, approved

#2001 handle kserve in global model serving page
  frontend/src/const.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelServing/__tests__/utils.spec.ts
  frontend/src/pages/modelServing/screens/global/DeleteInferenceServiceModal.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceEndpoint.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceModel.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceProject.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceServingRuntime.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx
  frontend/src/pages/modelServing/screens/global/ModelServingGlobal.tsx
  frontend/src/pages/modelServing/screens/global/__tests__/InferenceServiceProject.spec.tsx
  frontend/src/pages/modelServing/screens/global/__tests__/InferenceServiceServingRuntime.spec.tsx
  frontend/src/pages/modelServing/screens/global/data.ts
  frontend/src/pages/modelServing/utils.ts
Labels: lgtm, approved

#2018 Handle Removed but not Disabled DS Pipelines
  frontend/src/concepts/pipelines/context/PipelinesContextWorkaround.tsx
  frontend/src/concepts/pipelines/context/index.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/projects/ProjectDetailsContext.tsx
  frontend/src/pages/projects/screens/detail/pipelines/PipelinesSection.tsx
Labels: lgtm, approved, pr/no-tests-allowed

#2012 Refactor model serving section on the project details page
  backend/src/routes/api/namespaces/namespaceUtils.ts
  frontend/src/__mocks__/mockProjectK8sResource.ts
  frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts
  frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.stories.tsx
  frontend/src/__tests__/integration/pages/projects/ProjectDetails.stories.tsx
  frontend/src/pages/modelServing/screens/projects/ModelMeshSection/EmptyInferenceServicesCell.tsx
  frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeDetails.tsx
  frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTable.tsx
  frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTableExpandedSection.tsx
  frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTableRow.tsx
  frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTokenDisplay.tsx
  frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTokenTableRow.tsx
  frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTokensTable.tsx
  frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx
  frontend/src/pages/modelServing/screens/projects/ModelServingPlatformButtonAction.tsx
  frontend/src/pages/modelServing/screens/projects/ModelServingPlatformCard.tsx
  frontend/src/pages/modelServing/screens/projects/ModelServingPlatformSelect.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeList.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeListButtonAction.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/DeleteServingRuntimeModal.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
  frontend/src/pages/modelServing/screens/projects/__tests__/getProjectModelServingPlatform.spec.ts
  frontend/src/pages/modelServing/screens/projects/utils.ts
  frontend/src/pages/projects/screens/detail/DetailsSection.tsx
  frontend/src/pages/projects/screens/detail/ProjectDetailsComponents.tsx
Labels: lgtm, approved

#2000 PF5 upgrade: styling updates
  frontend/src/app/App.scss
  frontend/src/components/OdhDocCard.tsx
  frontend/src/components/SupportedAppTitle.tsx
  frontend/src/pages/notebookController/NotebookController.scss
  frontend/src/pages/notebookController/screens/server/EnvironmentVariablesField.tsx
  frontend/src/pages/projects/projectSharing/ProjectSharingNameInput.tsx
  frontend/src/pages/projects/projectSharing/ProjectSharingTableRow.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTableRow.tsx
  frontend/src/pages/projects/screens/spawner/environmentVariables/EnvUploadField.tsx
Labels: lgtm, approved, pr/no-tests-allowed

#2025 Implement KServe table on project details page
  frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx
  frontend/src/pages/modelServing/screens/global/data.ts
  frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTable.tsx
  frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTableRow.tsx
  frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeDetails.tsx
  frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx
Labels: lgtm, approved

#1891 Fetch prometheus metrics from UWM
  backend/src/routes/api/prometheus/index.ts
  backend/src/types.ts
  backend/src/utils/constants.ts
  backend/src/utils/prometheusUtils.ts
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/api/prometheus/serving.ts
  frontend/src/api/prometheus/usePrometheusQueryRange.ts
  frontend/src/api/prometheus/useQueryRangeResourceData.ts
  frontend/src/pages/modelServing/screens/metrics/GlobalModelMetricsWrapper.tsx
  frontend/src/pages/modelServing/screens/metrics/ModelServingMetricsContext.tsx
  frontend/src/pages/modelServing/screens/metrics/utils.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectModelMetricsWrapper.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectServerMetricsWrapper.tsx
  frontend/src/pages/modelServing/useModelMetricsEnabled.ts
  frontend/src/types.ts
  manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
  manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Labels: lgtm, approved

#2026 Implement kserve modal
  backend/src/routes/api/namespaces/const.ts
  backend/src/routes/api/namespaces/namespaceUtils.ts
  frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.spec.ts
  frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.stories.tsx
  frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts
  frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.stories.tsx
  frontend/src/api/k8s/inferenceServices.ts
  frontend/src/api/k8s/projects.ts
  frontend/src/pages/modelServing/__tests__/utils.spec.ts
  frontend/src/pages/modelServing/customServingRuntimes/utils.ts
  frontend/src/pages/modelServing/screens/global/DeleteInferenceServiceModal.tsx
  frontend/src/pages/modelServing/screens/global/EmptyModelServing.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceEndpoint.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceListView.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx
  frontend/src/pages/modelServing/screens/global/useRouteForInferenceService.ts
  frontend/src/pages/modelServing/screens/global/utils.ts
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceNameSection.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
  frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTable.tsx
  frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTableRow.tsx
  frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeNameSection.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTemplateSection.tsx
  frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
  frontend/src/pages/modelServing/screens/projects/utils.ts
  frontend/src/pages/projects/types.ts
Labels: lgtm, approved

#2019 apply ownerReference to ServingRuntime related resources
  frontend/src/__mocks__/mockProjectK8sResource.ts
  frontend/src/api/__tests__/apiMergeUtils.spec.ts
  frontend/src/api/__tests__/k8sUtils.spec.ts
  frontend/src/api/apiMergeUtils.ts
  frontend/src/api/index.ts
  frontend/src/api/k8sUtils.ts
  frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx
  frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTable.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/DeleteServingRuntimeModal.tsx
  frontend/src/pages/modelServing/screens/projects/utils.ts
  frontend/src/pages/modelServing/utils.ts
Labels: lgtm, approved

#2002 Add Accelerator section in Admin Panel and feature flag
  backend/src/types.ts
  backend/src/utils/constants.ts
  docs/dashboard-config.md
  frontend/src/__mocks__/mockAcceleratorProfile.ts
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/__tests__/integration/pages/acceleratorProfiles/AcceleratorProfiles.spec.ts
  frontend/src/__tests__/integration/pages/acceleratorProfiles/AcceleratorProfiles.stories.tsx
  frontend/src/app/AppRoutes.tsx
  frontend/src/pages/acceleratorProfiles/AcceleratorProfiles.tsx
  frontend/src/types.ts
  frontend/src/utilities/NavData.tsx
  manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
  manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Labels: lgtm, approved

#2038 Upversion dependencies & fix redux spam
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/AppLauncher.tsx
  frontend/src/redux/selectors/clusterInfo.ts
  frontend/src/redux/selectors/project.ts
  frontend/src/redux/selectors/user.ts
  frontend/src/redux/selectors/utils.ts
Labels: lgtm, approved
