Repository opendatahub-io/odh-dashboard, pull requests merged in 2024-04, with the labels that each got.

#2643 Add chai-subset for simpler object assertions
  frontend/package-lock.json
  frontend/package.json
  frontend/src/__tests__/cypress/cypress/e2e/customServingRuntimes/CustomServingRuntimes.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/modelServing/ServingRuntimeList.cy.ts
  frontend/src/__tests__/cypress/cypress/support/e2e.ts
Labels: lgtm, approved

#2653 added not found page cypress test
  frontend/src/__tests__/cypress/cypress/e2e/modelRegistry/ModelRegistry.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/pageNotFound/PageNotFound.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/pageNotFound.ts
  frontend/src/pages/NotFound.tsx
Labels: lgtm, approved

#2634 RHOAIENG-4834:Modify explore page cypress test
  frontend/src/__tests__/cypress/cypress/e2e/applications/explore.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/components/Card.ts
  frontend/src/__tests__/cypress/cypress/pages/components/JupyterCard.ts
  frontend/src/__tests__/cypress/cypress/pages/explore.ts
  frontend/src/components/OdhExploreCard.tsx
  frontend/src/components/SupportedAppTitle.tsx
Labels: lgtm, approved, ok-to-test

#2622 Update Accelerator profile cypress test
  frontend/src/__tests__/cypress/cypress/e2e/acceleratorProfiles/AcceleratorProfiles.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/modelServing/ServingRuntimeList.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/notebookImageSettings/NotebookImageSettings.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/acceleratorProfile.ts
  frontend/src/__tests__/cypress/cypress/pages/components/TableToolbar.ts
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/pages/notebookImageSettings.ts
  frontend/src/__tests__/cypress/cypress/support/commands/application.ts
  frontend/src/concepts/dashboard/DashboardSearchField.tsx
  frontend/src/pages/acceleratorProfiles/screens/list/AcceleratorProfileEnableToggle.tsx
  frontend/src/pages/acceleratorProfiles/screens/list/DisableAcceleratorProfileModal.tsx
Labels: lgtm, approved

#2631 feat(dw): renaming instances of workload to dw
  frontend/src/__tests__/cypress/cypress/e2e/distributedWorkloads/GlobalDistributedWorkloads.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/distributedWorkloads.ts
  frontend/src/concepts/distributedWorkloads/DistributedWorkloadsContext.tsx
  frontend/src/concepts/distributedWorkloads/__tests__/utils.spec.ts
  frontend/src/pages/distributedWorkloads/global/DistributedWorkloadsNoProjects.tsx
  frontend/src/pages/distributedWorkloads/global/GlobalDistributedWorkloads.tsx
  frontend/src/pages/distributedWorkloads/global/GlobalDistributedWorkloadsTabs.tsx
  frontend/src/pages/distributedWorkloads/global/projectMetrics/GlobalDistributedWorkloadsProjectMetricsTab.tsx
  frontend/src/pages/distributedWorkloads/global/useDistributedWorkloadsTabs.tsx
  frontend/src/pages/distributedWorkloads/global/workloadStatus/DWStatusOverviewDonutChart.tsx
  frontend/src/pages/distributedWorkloads/global/workloadStatus/DWWorkloadsTable.tsx
  frontend/src/utilities/NavData.tsx
Labels: lgtm, approved

#2613 proxy for access to mlmd service
  .env.development
  backend/package-lock.json
  backend/package.json
  backend/src/routes/api/k8s/pass-through.ts
  backend/src/routes/api/mlmd/index.ts
  backend/src/types.ts
  frontend/.eslintignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/concepts/pipelines/context/PipelinesContext.tsx
  frontend/src/third_party/mlmd/generated/ml_metadata/proto/metadata_store_pb.d.ts
  frontend/src/third_party/mlmd/generated/ml_metadata/proto/metadata_store_pb.js
  frontend/src/third_party/mlmd/generated/ml_metadata/proto/metadata_store_service_grpc_web_pb.d.ts
  frontend/src/third_party/mlmd/generated/ml_metadata/proto/metadata_store_service_grpc_web_pb.js
  frontend/src/third_party/mlmd/generated/ml_metadata/proto/metadata_store_service_pb.d.ts
  frontend/src/third_party/mlmd/generated/ml_metadata/proto/metadata_store_service_pb.js
  frontend/src/third_party/mlmd/index.ts
Labels: lgtm, approved

#2652 added cluster storage cypress test
  frontend/src/__mocks__/mockPVCK8sResource.ts
  frontend/src/__tests__/cypress/cypress/e2e/projects/ClusterStorage.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/clusterStorage.ts
  frontend/src/components/ValueUnitField.tsx
  frontend/src/pages/projects/components/PVSizeField.tsx
  frontend/src/pages/projects/pvc/MountPathField.tsx
  frontend/src/pages/projects/screens/detail/storage/StorageList.tsx
  frontend/src/pages/projects/screens/detail/storage/StorageTable.tsx
Labels: lgtm, approved

#2657 RHOAIENG-5067: Model Serving Metrics: Use real namespace name instead of project display name in queries
  frontend/src/pages/modelServing/screens/projects/ProjectServerMetricsWrapper.tsx
Labels: lgtm, approved

#2664 [RHOAIENG-4848] Fix positioning of pipeline actions menu
  frontend/src/concepts/pipelines/content/PipelineServerActions.tsx
Labels: lgtm, approved, ds-projects-rework

#2669 [RHOAIENG-5080] Update order of tabs on project page
  frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
  frontend/src/pages/projects/screens/detail/overview/configuration/ConfigurationSection.tsx
Labels: lgtm, approved

#2557 RHOAIENG-3984 Use the proxy at Red Hat.
  frontend/src/utilities/segmentIOUtils.tsx
Labels: lgtm, approved, ok-to-test, ds-projects-rework

#2654 Remove collapsible borders and fix typo
  frontend/src/concepts/design/CollapsibleSection.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsList.tsx
  frontend/src/pages/projects/screens/detail/overview/configuration/ConfigurationSection.tsx
  frontend/src/pages/projects/screens/detail/overview/serverModels/NoProjectServingEnabledSection.tsx
  frontend/src/pages/projects/screens/detail/overview/serverModels/PlatformSelectSection.tsx
  frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelsSection.tsx
  frontend/src/pages/projects/screens/detail/overview/trainModels/TrainModelsSection.tsx
Labels: priority/high, lgtm, approved, ok-to-test, ds-projects-rework

#2659 feat(dw): top consumption charts
  frontend/src/api/prometheus/__tests__/distributedWorkloads.spec.ts
  frontend/src/api/prometheus/distributedWorkloads.ts
  frontend/src/concepts/distributedWorkloads/DistributedWorkloadsContext.tsx
  frontend/src/pages/distributedWorkloads/global/projectMetrics/GlobalDistributedWorkloadsProjectMetricsTab.tsx
  frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/SharedStates.tsx
  frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/TopResourceConsumingWorkloads.tsx
Labels: priority/high, lgtm, approved

#2637 chore: Add new resource tile for OpenShift AI documentation
  manifests/crd/odhdocuments.dashboard.opendatahub.io.crd.yaml
  manifests/overlays/apps/base/rhoai/rhoai-docs.yaml
Labels: priority/high, lgtm, approved

#2639 fix(overview): Don't show pipeline compatibility error in notebooks card
  frontend/src/pages/projects/screens/detail/overview/trainModels/NotebooksCard.tsx
Labels: priority/high, lgtm, approved, ds-projects-rework

#2640 fix(projects list): fix style issue on striped rows, add default sort
  frontend/src/pages/projects/screens/projects/ProjectListView.tsx
  frontend/src/pages/projects/screens/projects/ProjectTableRow.tsx
Labels: priority/high, lgtm, approved, ds-projects-rework

#2661 [RHOAIENG-4859] Fix for showing correct models in project overview
  frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelsCard.tsx
  frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelsSection.tsx
Labels: priority/high, lgtm, approved, ds-projects-rework

#2642 Update PipelineRuns Cypress test to account for sorting and filtering
  frontend/src/__tests__/cypress/cypress/e2e/pipelines/Experiments.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineCreateRuns.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineRuns.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/pipelines/Pipelines.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineFilterBar.ts
Labels: lgtm, approved

#2655 [RHOAIENG-4660] Compare runs - Manage runs page
  frontend/src/__tests__/cypress/cypress/e2e/pipelines/ManageRuns.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineCreateRuns.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineRuns.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/pipelines/intercepts.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/manageRuns.ts
  frontend/src/app/App.tsx
  frontend/src/components/table/TableBase.tsx
  frontend/src/components/table/useCheckboxTable.ts
  frontend/src/components/table/useCheckboxTableBase.ts
  frontend/src/concepts/pipelines/content/tables/PipelineFilterBar.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRowTitle.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableToolbar.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/usePipelineRunTable.ts
  frontend/src/concepts/pipelines/content/tables/pipelineVersion/usePipelineVersionsCheckboxTable.ts
  frontend/src/concepts/pipelines/content/tables/usePipelineFilter.ts
  frontend/src/concepts/pipelines/content/tables/usePipelineTable.ts
  frontend/src/pages/pipelines/GlobalPipelineExperimentsRoutes.tsx
  frontend/src/pages/pipelines/global/experiments/compareRuns/ManageRunsPage.tsx
  frontend/src/pages/pipelines/global/experiments/compareRuns/ManageRunsTable.tsx
  frontend/src/pages/pipelines/global/runs/ActiveRuns.tsx
  frontend/src/pages/pipelines/global/runs/ArchivedRuns.tsx
  frontend/src/routes/pipelines/experiments.ts
Labels: priority/normal, lgtm, approved

#2665 [RHOAIENG-4996] Show popover help for non-empty pipelines/notebooks cards
  frontend/src/pages/projects/screens/detail/overview/trainModels/NotebooksCard.tsx
  frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesCard.tsx
Labels: priority/high, lgtm, approved, ds-projects-rework

#2666 [RHOAIENG-4845] Fix for import pipeline button action in overview card
  frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesCard.tsx
Labels: priority/high, lgtm, approved, ds-projects-rework

#2667 [RHOAIENG-4994] Navigate to workbenches section after create
  frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
Labels: priority/high, lgtm, approved, ds-projects-rework

#2679 Fix run type switch link in createRunPage and RunPage
  frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineCreateRuns.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/createRunPage.ts
  frontend/src/concepts/pipelines/content/createRun/RunForm.tsx
  frontend/src/concepts/pipelines/content/createRun/RunPage.tsx
  frontend/src/concepts/pipelines/content/createRun/contentSections/RunTypeSection.tsx
Labels: lgtm, approved

#2658 DW: Implement "Workload resource metrics" table on the Project Metrics tab
  frontend/src/__mocks__/mockWorkloadK8sResource.ts
  frontend/src/__tests__/cypress/cypress/e2e/distributedWorkloads/GlobalDistributedWorkloads.cy.ts
  frontend/src/components/MemoryField.tsx
  frontend/src/concepts/distributedWorkloads/__tests__/utils.spec.ts
  frontend/src/concepts/distributedWorkloads/utils.tsx
  frontend/src/k8sTypes.ts
  frontend/src/pages/distributedWorkloads/components/WorkloadResourceUsageBar.scss
  frontend/src/pages/distributedWorkloads/components/WorkloadResourceUsageBar.tsx
  frontend/src/pages/distributedWorkloads/components/WorkloadStatusLabel.tsx
  frontend/src/pages/distributedWorkloads/global/projectMetrics/GlobalDistributedWorkloadsProjectMetricsTab.tsx
  frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/DWSectionCard.tsx
  frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/WorkloadResourceMetrics.tsx
  frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/WorkloadResourceMetricsTable.tsx
  frontend/src/pages/distributedWorkloads/global/workloadStatus/DWWorkloadsTable.tsx
  frontend/src/pages/projects/components/PVSizeField.tsx
  frontend/src/pages/projects/components/StorageSizeBars.tsx
  frontend/src/pages/projects/screens/detail/storage/StorageWarningStatus.tsx
  frontend/src/utilities/__tests__/number.spec.ts
  frontend/src/utilities/__tests__/valueUnits.spec.ts
  frontend/src/utilities/number.ts
  frontend/src/utilities/valueUnits.ts
Labels: priority/high, lgtm, approved

#2673 DW: Implement "Requested resources" bullet charts on Project Metrics page (formerly "Resource usage" charts)
  frontend/src/__mocks__/mockClusterQueueK8sResource.ts
  frontend/src/__mocks__/mockLocalQueueK8sResource.ts
  frontend/src/__tests__/cypress/cypress/e2e/distributedWorkloads/GlobalDistributedWorkloads.cy.ts
  frontend/src/concepts/distributedWorkloads/__tests__/utils.spec.ts
  frontend/src/concepts/distributedWorkloads/utils.tsx
  frontend/src/k8sTypes.ts
  frontend/src/pages/distributedWorkloads/global/projectMetrics/GlobalDistributedWorkloadsProjectMetricsTab.tsx
  frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/DWSectionCard.tsx
  frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/RequestedResources.tsx
  frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/ResourceUsage.tsx
Labels: priority/high, lgtm, approved

#2682 use default cy.visit function
  frontend/src/__tests__/cypress/cypress/e2e/projects/ProjectList.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/acceleratorProfile.ts
  frontend/src/__tests__/cypress/cypress/pages/clusterSettings.ts
  frontend/src/__tests__/cypress/cypress/pages/clusterStorage.ts
  frontend/src/__tests__/cypress/cypress/pages/distributedWorkloads.ts
  frontend/src/__tests__/cypress/cypress/pages/enabled.ts
  frontend/src/__tests__/cypress/cypress/pages/explore.ts
  frontend/src/__tests__/cypress/cypress/pages/modelMetrics.ts
  frontend/src/__tests__/cypress/cypress/pages/modelRegistry.ts
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/pages/notebookImageSettings.ts
  frontend/src/__tests__/cypress/cypress/pages/pageNotFound.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/compareRuns.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/experiments.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/manageRuns.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineRunsGlobal.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesGlobal.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/topology.ts
  frontend/src/__tests__/cypress/cypress/pages/projects.ts
  frontend/src/__tests__/cypress/cypress/pages/servingRuntimes.ts
Labels: lgtm, approved

#2670 [RHOAIENG-5104] Fix empty state image for global model servers
  frontend/src/__tests__/cypress/cypress/e2e/modelServing/ModelServingGlobal.cy.ts
  frontend/src/pages/modelServing/screens/global/EmptyModelServing.tsx
Labels: priority/high, lgtm, approved, ds-projects-rework

#2671 Add Elyra version check functions and ElyraInvalidVersion component
  frontend/src/__tests__/cypress/cypress/e2e/projects/projectDetails.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/projects.ts
  frontend/src/concepts/pipelines/elyra/ElyraInvalidVersionAlerts.tsx
  frontend/src/concepts/pipelines/elyra/utils.ts
  frontend/src/pages/projects/screens/detail/notebooks/NotebookTable.tsx
  frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx
  frontend/src/pages/projects/screens/detail/notebooks/useNotebookImageData.ts
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageVersionSelector.tsx
Labels: priority/high, lgtm, approved

#2672 Add compare runs list
  frontend/src/__tests__/cypress/cypress/e2e/pipelines/CompareRuns.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/compareRuns.ts
  frontend/src/concepts/pipelines/content/compareRuns/CompareRunTableRow.tsx
  frontend/src/concepts/pipelines/content/compareRuns/CompareRunTableToolbar.tsx
  frontend/src/concepts/pipelines/content/compareRuns/CompareRunsRunList.tsx
  frontend/src/concepts/pipelines/content/compareRuns/columns.ts
  frontend/src/concepts/pipelines/content/compareRuns/useCompareRunsCheckboxTable.ts
  frontend/src/pages/ApplicationsPage.tsx
  frontend/src/pages/pipelines/global/experiments/compareRuns/CompareRunsPage.tsx
  frontend/src/pages/pipelines/global/experiments/compareRuns/GlobalComparePipelineRunsLoader.tsx
Labels: priority/normal, lgtm, approved

#2625 Add authorization to kserve
  backend/src/routes/api/dsci/index.ts
  backend/src/types.ts
  backend/src/utils/constants.ts
  backend/src/utils/dsci.ts
  docs/dashboard-config.md
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/__mocks__/mockDsciStatus.ts
  frontend/src/__mocks__/mockInferenceServiceModalData.ts
  frontend/src/__tests__/cypress/cypress/e2e/modelServing/ServingRuntimeList.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/api/k8s/__tests__/inferenceServices.spec.ts
  frontend/src/api/k8s/inferenceServices.ts
  frontend/src/concepts/areas/AreaContext.tsx
  frontend/src/concepts/areas/__tests__/useFetchDsciStatus.spec.ts
  frontend/src/concepts/areas/__tests__/utils.spec.ts
  frontend/src/concepts/areas/const.ts
  frontend/src/concepts/areas/types.ts
  frontend/src/concepts/areas/useFetchDsciStatus.ts
  frontend/src/concepts/areas/useIsAreaAvailable.ts
  frontend/src/concepts/areas/utils.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelServing/ModelServingContext.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceListView.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx
  frontend/src/pages/modelServing/screens/global/ModelServingGlobal.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/__tests__/ManageInferenceServiceModal.spec.tsx
  frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTable.tsx
  frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTableRow.tsx
  frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTokensTable.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/AuthServingRuntimeSection.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenInput.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenSection.tsx
  frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
  frontend/src/pages/modelServing/screens/projects/utils.ts
  frontend/src/pages/modelServing/screens/types.ts
  frontend/src/pages/modelServing/utils.ts
  manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
  manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
  manifests/overlays/odhdashboardconfig/odhdashboardconfig.yaml
Labels: priority/high, lgtm, approved

#2683 [RHOAIENG-4856] update warning in the project overview page
  frontend/src/pages/projects/screens/detail/overview/serverModels/SelectMultiModelCard.tsx
  frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesCard.tsx
  frontend/src/pages/projects/screens/detail/overview/trainModels/TrainModelsSection.tsx
Labels: lgtm, approved, ds-projects-rework

#2680 Feat(pipelines): Adds support for artifact nodes and vertical layout
  frontend/package-lock.json
  frontend/package.json
  frontend/src/concepts/pipelines/topology/usePipelineTaskTopology.ts
  frontend/src/concepts/topology/PipelineTaskEdge.tsx
  frontend/src/concepts/topology/PipelineVisualizationSurface.tsx
  frontend/src/concepts/topology/TaskEdge.tsx
  frontend/src/concepts/topology/const.ts
  frontend/src/concepts/topology/customNodes/ArtifactTaskNode.tsx
  frontend/src/concepts/topology/customNodes/StandardTaskNode.tsx
  frontend/src/concepts/topology/factories.ts
  frontend/src/concepts/topology/types.ts
  frontend/src/concepts/topology/useTopologyController.ts
  frontend/src/concepts/topology/utils.ts
Labels: lgtm, approved

#2635 Frontend synk vulnerabilities
  frontend/package-lock.json
Labels: priority/high, lgtm, approved

#2628 [RHOAIENG-4226] Add additional tracking for projects UI.
  docs/dev-setup.md
  frontend/src/components/ExternalLink.tsx
  frontend/src/pages/projects/notebook/NotebookRouteLink.tsx
  frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx
  frontend/src/pages/projects/screens/projects/DeleteProjectModal.tsx
  frontend/src/pages/projects/screens/projects/NewProjectButton.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
  frontend/src/types.ts
  frontend/src/utilities/segmentIOUtils.tsx
Labels: priority/high, lgtm, approved, ok-to-test, ds-projects-rework

#2675 added workbench cypress test
  frontend/src/__mocks__/mock-upload-configmap.yaml
  frontend/src/__mocks__/mockNotebookK8sResource.ts
  frontend/src/__mocks__/mockPodK8sResource.ts
  frontend/src/__tests__/cypress/cypress/e2e/projects/Workbench.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/workbench.ts
  frontend/src/pages/projects/components/ExistingPVCField.tsx
  frontend/src/pages/projects/notebook/NotebookRouteLink.tsx
  frontend/src/pages/projects/notebook/NotebookStatusText.tsx
  frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx
  frontend/src/pages/projects/notebook/StopNotebookConfirmModal.tsx
  frontend/src/pages/projects/pvc/AddNotebookStorage.tsx
  frontend/src/pages/projects/screens/detail/notebooks/NotebookList.tsx
  frontend/src/pages/projects/screens/detail/notebooks/NotebookStorageBars.tsx
  frontend/src/pages/projects/screens/spawner/EditSpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/dataConnection/DataConnectionField.tsx
  frontend/src/pages/projects/screens/spawner/dataConnection/ExistingDataConnectionField.tsx
  frontend/src/pages/projects/screens/spawner/deploymentSize/ContainerSizeSelector.tsx
  frontend/src/pages/projects/screens/spawner/environmentVariables/EnvDataTypeField.tsx
  frontend/src/pages/projects/screens/spawner/environmentVariables/EnvTypeSelectField.tsx
  frontend/src/pages/projects/screens/spawner/environmentVariables/EnvUploadField.tsx
  frontend/src/pages/projects/screens/spawner/environmentVariables/EnvironmentVariables.tsx
  frontend/src/pages/projects/screens/spawner/environmentVariables/GenericKeyValuePairField.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageStreamSelector.tsx
  frontend/src/pages/projects/screens/spawner/storage/StorageField.tsx
Labels: lgtm, approved

#2489 Unit test case for useQueryRangeResourceData
  frontend/src/api/prometheus/__tests__/useQueryRangeResourceData.spec.ts
Labels: lgtm, approved

#2692 Fix pipeline version reference in pipeline run details
  frontend/src/concepts/pipelines/content/__tests__/utils.spec.tsx
  frontend/src/concepts/pipelines/content/compareRuns/CompareRunsRunList.tsx
  frontend/src/concepts/pipelines/content/createRun/RunPage.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabDetails.tsx
  frontend/src/concepts/pipelines/content/tables/usePipelineRunVersionInfo.ts
  frontend/src/concepts/pipelines/kfTypes.ts
Labels: lgtm, approved

#2694 Add ImportPipelineButton to NoPipelineServer component
  frontend/src/concepts/pipelines/NoPipelineServer.tsx
Labels: lgtm, approved

#2689 feat(dw): move quota level issue states out of tabs
  frontend/src/__tests__/cypress/cypress/e2e/distributedWorkloads/GlobalDistributedWorkloads.cy.ts
  frontend/src/pages/distributedWorkloads/global/GlobalDistributedWorkloadsTabs.tsx
  frontend/src/pages/distributedWorkloads/global/projectMetrics/GlobalDistributedWorkloadsProjectMetricsTab.tsx
Labels: lgtm, approved

#2686 chore(dw): factor some stuff out, improve table empty state
  frontend/src/__tests__/cypress/cypress/e2e/distributedWorkloads/GlobalDistributedWorkloads.cy.ts
  frontend/src/pages/distributedWorkloads/components/LoadingState.tsx
  frontend/src/pages/distributedWorkloads/components/NoWorkloadState.tsx
  frontend/src/pages/distributedWorkloads/global/GlobalDistributedWorkloadsTabs.tsx
  frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/RequestedResources.tsx
  frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/SharedStates.tsx
  frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/TopResourceConsumingWorkloads.tsx
  frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/WorkloadResourceMetricsTable.tsx
  frontend/src/pages/distributedWorkloads/global/workloadStatus/DWStatusOverviewDonutChart.tsx
  frontend/src/pages/distributedWorkloads/global/workloadStatus/DWWorkloadsTable.tsx
  frontend/src/pages/distributedWorkloads/global/workloadStatus/GlobalDistributedWorkloadsWorkloadStatusTab.tsx
Labels: lgtm, approved

#2674 Cypress test for permissions tab
  frontend/src/__mocks__/mockRoleBindingK8sResource.ts
  frontend/src/__tests__/cypress/cypress/e2e/projects/Permissions.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/permissions.ts
  frontend/src/pages/projects/projectSharing/ProjectSharingNameInput.tsx
  frontend/src/pages/projects/projectSharing/ProjectSharingTable.tsx
  frontend/src/pages/projects/projectSharing/ProjectSharingTableRow.tsx
  frontend/src/pages/projects/projectSharing/ProjectSharingTableRowAdd.tsx
  frontend/src/pages/projects/projectSharing/ProjectSharingTableSection.tsx
Labels: lgtm, approved

#2687 added test for application launcher
  frontend/src/__tests__/cypress/cypress/e2e/appLauncher/AppLauncher.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/appChrome.ts
  frontend/src/__tests__/cypress/cypress/pages/appLauncher.ts
  frontend/src/app/AppLauncher.tsx
Labels: lgtm, approved

#2677 Registered model table
  frontend/src/__mocks__/mockRegisteredModel.ts
  frontend/src/api/modelRegistry/__tests__/custom.spec.ts
  frontend/src/components/SimpleDropdownSelect.tsx
  frontend/src/concepts/dashboard/DashboardSearchField.tsx
  frontend/src/concepts/design/utils.ts
  frontend/src/concepts/modelRegistry/apiHooks/useModelVersionsByRegisteredModel.ts
  frontend/src/concepts/modelRegistry/context/ModelRegistryContext.tsx
  frontend/src/concepts/modelRegistry/types.ts
  frontend/src/pages/modelRegistry/ModelRegistryRoutes.tsx
  frontend/src/pages/modelRegistry/screens/ModelRegistry.tsx
  frontend/src/pages/modelRegistry/screens/ModelRegistrySelector.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModelLabels.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModelLastModified.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModelListView.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModelOwner.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModelTable.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModelTableRow.tsx
  frontend/src/pages/modelRegistry/screens/__tests__/utils.spec.ts
  frontend/src/pages/modelRegistry/screens/const.ts
  frontend/src/pages/modelRegistry/screens/utils.ts
Labels: lgtm, approved

#2525 add test case for usePrometheusQueryRange
  frontend/src/api/prometheus/__tests__/usePrometheusQueryRange.spec.ts
Labels: lgtm, approved

#2693 feat(DW): gray donuts for empty data top-consuming charts
  frontend/src/__tests__/cypress/cypress/e2e/distributedWorkloads/GlobalDistributedWorkloads.cy.ts
  frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/TopResourceConsumingWorkloads.tsx
  frontend/src/pages/distributedWorkloads/global/workloadStatus/DWStatusOverviewDonutChart.tsx
  frontend/src/pages/distributedWorkloads/global/workloadStatus/GlobalDistributedWorkloadsWorkloadStatusTab.tsx
Labels: lgtm, approved

#2685 Enable Distributed Workloads feature flag by default in manifests
  backend/src/types.ts
  backend/src/utils/constants.ts
  docs/dashboard-config.md
  manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
  manifests/overlays/odhdashboardconfig/odhdashboardconfig.yaml
Labels: lgtm, approved

#2473 Unit Test Case for k8s/notebooks
  frontend/src/__mocks__/mockNotebookK8sResource.ts
  frontend/src/__mocks__/mockRoleBindingK8sResource.ts
  frontend/src/__mocks__/mockStartNotebookData.ts
  frontend/src/api/k8s/__tests__/notebooks.spec.ts
  frontend/src/api/k8s/notebooks.ts
Labels: lgtm, approved

#2703 Fix issue when selecting a pipeline without version on the clone run page
  frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineCreateRuns.cy.ts
  frontend/src/concepts/pipelines/content/createRun/useRunFormData.ts
  frontend/src/concepts/pipelines/content/createRun/utils.ts
Labels: lgtm, approved

#2697 [RHOAIENG-4648] UX content updates
  frontend/src/concepts/pipelines/content/DeletePipelineRunsModal.tsx
  frontend/src/concepts/pipelines/content/createRun/RunForm.tsx
  frontend/src/concepts/pipelines/content/createRun/RunPage.tsx
  frontend/src/concepts/pipelines/content/createRun/const.ts
  frontend/src/concepts/pipelines/content/createRun/contentSections/ExperimentSection.tsx
  frontend/src/concepts/pipelines/content/createRun/contentSections/ParamsSection/ParamsSection.tsx
  frontend/src/concepts/pipelines/content/createRun/contentSections/PipelineSection.tsx
  frontend/src/concepts/pipelines/content/createRun/contentSections/PipelineVersionSection.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/SelectedTaskDrawerContent.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightContent.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightTabs.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/SelectedNodeDetailsTab.tsx
  frontend/src/concepts/pipelines/content/tables/columns.ts
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx
  frontend/src/pages/pipelines/GlobalPipelineExperimentsRoutes.tsx
  frontend/src/pages/pipelines/global/experiments/compareRuns/ManageRunsTable.tsx
  frontend/src/pages/pipelines/global/pipelines/const.ts
Labels: lgtm, approved

#2704 chore(dw): fix nits related to pr2645
  frontend/src/api/prometheus/distributedWorkloads.ts
  frontend/src/concepts/distributedWorkloads/DistributedWorkloadsContext.tsx
Labels: lgtm, approved

#2702 RHOAIENG-4346 Harden backend security
  .env.development
  backend/package-lock.json
  backend/src/routes/api/mlmd/index.ts
  backend/src/routes/api/proxy/index.ts
  backend/src/routes/api/service/mlmd/index.ts
  backend/src/routes/api/service/pipelines/index.ts
  backend/src/routes/api/service/trustyai/index.ts
  backend/src/types.ts
  backend/src/utils/proxy.ts
  frontend/src/__tests__/cypress/cypress/e2e/modelServing/ModelMetrics.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/modelServing/ModelServingGlobal.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/notebookImageSettings/NotebookImageSettings.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/pipelines/CompareRuns.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/pipelines/Experiments.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/pipelines/ManageRuns.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineCreateRuns.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineDeleteRuns.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineRuns.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/pipelines/Pipelines.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelinesList.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelinesTopology.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/projects/projectDetails.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/cloneRunPage.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/createRunPage.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/experiments.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineFilterBar.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineImportModal.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineRunTable.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineVersionImportModal.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesTable.ts
  frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
  frontend/src/api/__tests__/proxyUtils.spec.ts
  frontend/src/api/proxyUtils.ts
  frontend/src/concepts/pipelines/context/PipelinesContext.tsx
  frontend/src/concepts/trustyai/context/TrustyAIContext.tsx
  frontend/src/concepts/trustyai/useTrustyAIAPIRoute.ts
Labels: lgtm, approved

#2688 Update ModelServingGlobal Cypress test to account for sorting and filtering
  frontend/src/__tests__/cypress/cypress/e2e/modelServing/ModelServingGlobal.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/components/TableToolbar.ts
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
Labels: lgtm, approved

#2708 Update SHAs of caikit-tgis and tgis
  manifests/overlays/modelserving/kustomization.yaml
Labels: lgtm, approved

#2705 Add useUser hook to EnsureCompatiblePipelineServer component
  frontend/src/concepts/pipelines/EnsureCompatiblePipelineServer.tsx
Labels: lgtm, approved

#2696 Fixes Image selection dropdown scroll issue
  frontend/src/__tests__/cypress/cypress/e2e/projects/Workbench.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/pages/workbench.ts
  frontend/src/__tests__/cypress/cypress/support/commands/application.ts
  frontend/src/components/SimpleDropdownSelect.tsx
  frontend/src/concepts/dashboard/DashboardSearchField.tsx
  frontend/src/concepts/pipelines/content/compareRuns/CompareRunTableToolbar.tsx
  frontend/src/concepts/pipelines/content/createRun/contentSections/TriggerTypeField.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableToolbar.tsx
  frontend/src/pages/acceleratorProfiles/screens/manage/tolerations/TolerationFields.tsx
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAPIProtocolSelector.tsx
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimePlatformsSelector.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTemplateSection.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageStreamSelector.tsx
Labels: lgtm, approved

#2701 Add InvalidArgoDeploymentAlert component to AppRoutes
  frontend/src/app/AppRoutes.tsx
  frontend/src/concepts/areas/types.ts
  frontend/src/concepts/areas/utils.ts
  frontend/src/concepts/pipelines/content/InvalidArgoDeploymentAlert.tsx
Labels: lgtm, approved

#2698 [RHOAIENG-5083] updated UI for the Serve models section and Models tab
  frontend/src/components/error/ErrorBoundary.tsx
  frontend/src/concepts/design/TypeBorderCard.scss
  frontend/src/images/gears.svg
  frontend/src/pages/modelServing/screens/projects/EmptyModelServingPlatform.tsx
  frontend/src/pages/modelServing/screens/projects/EmptyMultiModelServingCard.tsx
  frontend/src/pages/modelServing/screens/projects/EmptySingleModelServingCard.tsx
  frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx
  frontend/src/pages/projects/screens/detail/DetailsSection.tsx
  frontend/src/pages/projects/screens/detail/overview/ProjectOverview.tsx
  frontend/src/pages/projects/screens/detail/overview/components/OverviewCard.tsx
  frontend/src/pages/projects/screens/detail/overview/serverModels/AddModelFooter.tsx
  frontend/src/pages/projects/screens/detail/overview/serverModels/NoProjectServingEnabledSection.tsx
  frontend/src/pages/projects/screens/detail/overview/serverModels/SelectMultiModelCard.tsx
  frontend/src/pages/projects/screens/detail/overview/serverModels/SelectSingleModelCard.tsx
  frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelCard.tsx
  frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelsCard.tsx
  frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelsGallery.tsx
  frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelsSection.tsx
Labels: lgtm, approved, ds-projects-rework

#2709 Show all the nodes in pipeline details topology
  frontend/src/concepts/pipelines/topology/usePipelineTaskTopology.ts
Labels: lgtm, approved

#2713 notebook.spec.ts unit test flake
  frontend/src/api/k8s/__tests__/notebooks.spec.ts
Labels: lgtm, approved

#2716 [RHOAIENG-3984] Make sure analytics.js is loaded via proxy
  frontend/src/utilities/segmentIOUtils.tsx
Labels: lgtm, approved, ok-to-test

#2681 Adding support for s390x and ppc64le for multi-arch image build
  Makefile
Labels: lgtm, approved, ok-to-test

#2712 add command to simplify service port forwarding for development
  .env.development
  Makefile
Labels: lgtm, approved

#2714 Refactor pipelines context and add useSafePipelines hook
  frontend/src/concepts/pipelines/apiHooks/usePipelines.ts
  frontend/src/concepts/pipelines/context/PipelinesContext.tsx
  frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesCard.tsx
  frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesCardMetrics.tsx
  frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesOverviewCard.tsx
Labels: lgtm, approved

#2711 add jest coverage command and configuration
  frontend/.gitignore
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved

#2695 Read pipeline run node details from mlmd context
  frontend/src/concepts/pipelines/apiHooks/mlmd/types.ts
  frontend/src/concepts/pipelines/apiHooks/mlmd/useExecutionsFromMlmdContext.ts
  frontend/src/concepts/pipelines/apiHooks/mlmd/useMlmdContext.ts
  frontend/src/concepts/pipelines/apiHooks/mlmd/usePipelineRunMlmdContext.ts
  frontend/src/concepts/pipelines/apiHooks/usePipelineRunById.ts
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/useExecutionsForPipelineRun.ts
  frontend/src/concepts/pipelines/kfTypes.ts
  frontend/src/concepts/pipelines/topology/__tests__/parseUtils.spec.ts
  frontend/src/concepts/pipelines/topology/parseUtils.ts
  frontend/src/concepts/pipelines/topology/pipelineTaskTypes.ts
  frontend/src/concepts/pipelines/topology/usePipelineTaskTopology.ts
Labels: lgtm, approved

#2718 Refactor pipelines context and add useSafePipelines hook
  frontend/src/concepts/pipelines/apiHooks/usePipelines.ts
  frontend/src/concepts/pipelines/context/PipelinesContext.tsx
  frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesCard.tsx
  frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesCardMetrics.tsx
  frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesOverviewCard.tsx
Labels: lgtm, approved

#2719 [RHOAIENG-5487] Initial "empty state" of home page
  backend/src/types.ts
  backend/src/utils/constants.ts
  docs/dashboard-config.md
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/__tests__/cypress/cypress/e2e/home/home.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/enabled.ts
  frontend/src/app/AppRoutes.tsx
  frontend/src/concepts/areas/const.ts
  frontend/src/concepts/areas/types.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/home/Home.tsx
  frontend/src/utilities/NavData.tsx
  manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
  manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
  manifests/overlays/odhdashboardconfig/odhdashboardconfig.yaml
Labels: lgtm, approved

#2720 Refactor model registry routes and configuration
  .env.development
  Makefile
  backend/src/routes/api/service/modelregistry/index.ts
  backend/src/types.ts
  backend/src/utils/proxy.ts
  frontend/src/api/modelRegistry/__tests__/custom.spec.ts
  frontend/src/api/modelRegistry/custom.ts
  frontend/src/concepts/modelRegistry/const.ts
  frontend/src/concepts/modelRegistry/context/ModelRegistryContext.tsx
  frontend/src/concepts/modelRegistry/context/useModelRegistryAPIRoute.ts
  frontend/src/pages/modelRegistry/ModelRegistryCoreLoader.tsx
Labels: lgtm, approved

#2722 [RHOAIENG-2986] Artifacts - Initial Infrastructure
  frontend/src/app/AppRoutes.tsx
  frontend/src/components/table/TableBase.tsx
  frontend/src/pages/ApplicationsPage.tsx
  frontend/src/pages/pipelines/GlobalArtifactsRoutes.tsx
  frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactsListTable.tsx
  frontend/src/pages/pipelines/global/experiments/artifacts/GlobalArtifactsPage.tsx
  frontend/src/pages/pipelines/global/experiments/artifacts/index.ts
  frontend/src/pages/pipelines/global/experiments/artifacts/useGetArtifactsList.ts
  frontend/src/routes/pipelines/artifacts.ts
  frontend/src/routes/pipelines/index.ts
  frontend/src/utilities/NavData.tsx
Labels: lgtm, approved

#2684 Empty state registered models
  frontend/src/__mocks__/mockModelRegistry.ts
  frontend/src/__mocks__/mockRegisteredModelsList.ts
  frontend/src/__mocks__/mockRouteK8sResource.ts
  frontend/src/__tests__/cypress/cypress/e2e/modelRegistry/ModelRegistry.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/modelRegistry.ts
  frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
  frontend/src/api/models/odh.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelRegistry/ModelRegistryEmpty.tsx
  frontend/src/pages/modelRegistry/screens/EmptyRegisteredModels.tsx
  frontend/src/pages/modelRegistry/screens/ModelRegistry.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModelListView.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModelsTableToolbar.tsx
Labels: lgtm, approved

#2707 Registered model table follow-up and cypress testing
  frontend/src/__mocks__/mockModelVersion.ts
  frontend/src/__mocks__/mockModelVersionList.ts
  frontend/src/__mocks__/mockRegisteredModel.ts
  frontend/src/__mocks__/mockRegisteredModelsList.ts
  frontend/src/__tests__/cypress/cypress/e2e/modelRegistry/ModelRegistry.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/modelRegistry.ts
  frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
  frontend/src/api/modelRegistry/k8s.ts
  frontend/src/api/models/index.ts
  frontend/src/api/models/odh.ts
  frontend/src/pages/modelRegistry/screens/ModelRegistry.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModelLabels.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModelListView.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModelOwner.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModelTable.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModelTableRow.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModelsTableToolbar.tsx
Labels: lgtm, approved

#2730 eslint ignore cypress coverage
  frontend/.eslintignore
Labels: lgtm, approved

#2540 Unit Test Case for useDraggableTable
  frontend/src/utilities/__tests__/useDraggableTable.spec.ts
  frontend/src/utilities/useDraggableTable.ts
Labels: lgtm, approved

#2727 add support to run tests with different user permissions
  frontend/src/__mocks__/mockStatus.ts
  frontend/src/__tests__/cypress/cypress/e2e/Application.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/acceleratorProfiles/AcceleratorProfiles.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/acceleratorProfiles/ManageAcceleratorProfiles.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/appLauncher/AppLauncher.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/clusterSettings/ClusterSettings.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/customServingRuntimes/CustomServingRuntimes.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/modelServing/ModelServingGlobal.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/notebookImageSettings/NotebookImageSettings.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/pageNotFound/PageNotFound.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/pipelines/Pipelines.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/projects/Permissions.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/projects/ProjectList.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/appChrome.ts
  frontend/src/__tests__/cypress/cypress/pages/clusterSettings.ts
  frontend/src/__tests__/cypress/cypress/pages/notebookImageSettings.ts
  frontend/src/__tests__/cypress/cypress/pages/pageNotFound.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesGlobal.ts
  frontend/src/__tests__/cypress/cypress/pages/servingRuntimes.ts
  frontend/src/__tests__/cypress/cypress/support/e2e.ts
  frontend/src/__tests__/cypress/cypress/utils/users.ts
  frontend/src/concepts/pipelines/EnsureCompatiblePipelineServer.tsx
  frontend/src/pages/UnauthorizedError.tsx
Labels: lgtm, approved

#2723 [RHOAIENG-5491] Landing page: Info section about AI flows
  frontend/src/__tests__/cypress/cypress/e2e/home/home.cy.ts
  frontend/src/concepts/design/DividedGallery.tsx
  frontend/src/concepts/design/InfoGalleryItem.tsx
  frontend/src/concepts/design/TypeBorderCard.scss
  frontend/src/concepts/design/TypeBorderedCard.tsx
  frontend/src/concepts/design/vars.scss
  frontend/src/images/UI_icon-Red_Hat-Branch-Color.svg
  frontend/src/images/UI_icon-Red_Hat-Chart-Color.svg
  frontend/src/images/UI_icon-Red_Hat-Folder-Color.svg
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/aiFlows/AIFlowCard.tsx
  frontend/src/pages/home/aiFlows/CreateAndTrainGallery.tsx
  frontend/src/pages/home/aiFlows/DeployAndMonitorGallery.tsx
  frontend/src/pages/home/aiFlows/InfoGallery.tsx
  frontend/src/pages/home/aiFlows/ProjectsGallery.tsx
  frontend/src/pages/home/aiFlows/useAIFlows.tsx
Labels: lgtm, approved

#2721 chore(DW): 5294 refactor resourceUsageBar
  frontend/src/pages/distributedWorkloads/components/WorkloadResourceUsageBar.scss
  frontend/src/pages/distributedWorkloads/components/WorkloadResourceUsageBar.tsx
  frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/WorkloadResourceMetricsTable.tsx
Labels: lgtm, approved

#2724 Cypress test for Administration tab
  frontend/src/__mocks__/mockAllowedUsers.ts
  frontend/src/__mocks__/mockNotebookImageInfo.ts
  frontend/src/__tests__/cypress/cypress/e2e/applications/Administration.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/administration.ts
  frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
  frontend/src/pages/notebookController/screens/admin/ImpersonateAlert.tsx
  frontend/src/pages/notebookController/screens/admin/NotebookAdminControl.tsx
  frontend/src/pages/notebookController/screens/admin/NotebookControllerTabs.tsx
  frontend/src/pages/notebookController/screens/admin/ServerStatus.tsx
  frontend/src/pages/notebookController/screens/admin/StopAllServersButton.tsx
  frontend/src/pages/notebookController/screens/admin/types.ts
  frontend/src/pages/notebookController/screens/server/ImageSelector.tsx
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
Labels: lgtm, approved

#2738 [RHOAIENG-5488] New landing page: Projects section - Empty state
  frontend/src/__tests__/cypress/cypress/e2e/home/home.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/home/homeAIFlows.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/home/homeProjects.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/home/homeUtils.ts
  frontend/src/images/AI_ML-illustration-Blog-thumbnail.svg
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/projects/EmptyProjectsCard.tsx
  frontend/src/pages/home/projects/ProjectsLoading.tsx
  frontend/src/pages/home/projects/ProjectsSection.tsx
Labels: lgtm, approved

#2731 Use project display names in DW, move related utils from `~/pages/projects` to `~/concepts/projects` and `~/concepts/k8s`
  frontend/src/__mocks__/mockProjectK8sResource.ts
  frontend/src/api/k8s/__tests__/inferenceServices.spec.ts
  frontend/src/api/k8s/inferenceServices.ts
  frontend/src/api/k8s/notebooks.ts
  frontend/src/api/k8s/projects.ts
  frontend/src/api/k8s/pvcs.ts
  frontend/src/api/k8s/secrets.ts
  frontend/src/api/k8s/servingRuntimes.ts
  frontend/src/concepts/distributedWorkloads/DistributedWorkloadsContext.tsx
  frontend/src/concepts/k8s/NameDescriptionField.tsx
  frontend/src/concepts/k8s/__tests__/utils.spec.ts
  frontend/src/concepts/k8s/utils.ts
  frontend/src/concepts/pipelines/content/DeletePipelineServerModal.tsx
  frontend/src/concepts/pipelines/content/createRun/RunForm.tsx
  frontend/src/concepts/pipelines/content/experiment/CreateExperimentModal.tsx
  frontend/src/concepts/pipelines/content/import/PipelineImportModal.tsx
  frontend/src/concepts/pipelines/content/import/PipelineVersionImportModal.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabDetails.tsx
  frontend/src/concepts/projects/ProjectSelector.tsx
  frontend/src/concepts/projects/__tests__/utils.spec.ts
  frontend/src/concepts/projects/utils.ts
  frontend/src/pages/distributedWorkloads/global/GlobalDistributedWorkloads.tsx
  frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/RequestedResources.tsx
  frontend/src/pages/modelServing/customServingRuntimes/utils.ts
  frontend/src/pages/modelServing/screens/global/EmptyModelServing.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceProject.tsx
  frontend/src/pages/modelServing/screens/global/data.ts
  frontend/src/pages/modelServing/screens/global/utils.ts
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceServingRuntimeSection.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectModelMetricsConfigurationPage.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectModelMetricsPage.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectServerMetricsWrapper.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenInput.tsx
  frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
  frontend/src/pages/modelServing/screens/projects/utils.ts
  frontend/src/pages/modelServing/utils.ts
  frontend/src/pages/pipelines/global/GlobalPipelineCoreDetails.tsx
  frontend/src/pages/pipelines/global/experiments/compareRuns/ManageRunsPage.tsx
  frontend/src/pages/projects/projectSharing/utils.ts
  frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
  frontend/src/pages/projects/screens/detail/pipelines/ProjectPipelineBreadcrumbPage.tsx
  frontend/src/pages/projects/screens/projects/DeleteProjectModal.tsx
  frontend/src/pages/projects/screens/projects/ManageProjectModal.tsx
  frontend/src/pages/projects/screens/projects/ProjectLink.tsx
  frontend/src/pages/projects/screens/projects/ProjectListView.tsx
  frontend/src/pages/projects/screens/projects/ProjectTableRow.tsx
  frontend/src/pages/projects/screens/projects/tableData.tsx
  frontend/src/pages/projects/screens/spawner/EditSpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/utils.ts
Labels: lgtm, approved

#2741 [RHOAIENG-5489] Home page: projects w/ tiles
  frontend/src/__tests__/cypress/cypress/e2e/home/homeProjects.cy.ts
  frontend/src/components/EvenlySpacedGallery.tsx
  frontend/src/components/OdhCard.scss
  frontend/src/components/OdhDocCard.tsx
  frontend/src/components/TruncatedText.tsx
  frontend/src/concepts/projects/ProjectsContext.tsx
  frontend/src/pages/home/aiFlows/useAIFlows.tsx
  frontend/src/pages/home/projects/CreateProjectCard.tsx
  frontend/src/pages/home/projects/ProjectCard.tsx
  frontend/src/pages/home/projects/ProjectsSection.tsx
  frontend/src/pages/home/projects/ProjectsSectionHeader.tsx
Labels: lgtm, approved

#2728 added user management cypress test
  frontend/src/__mocks__/mockGroupConfig.ts
  frontend/src/__tests__/cypress/cypress/e2e/projects/projectDetails.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/userManagement/userManagement.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/userManagement.ts
  frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
  frontend/src/components/MultiSelection.tsx
  frontend/src/components/SettingSection.tsx
  frontend/src/pages/groupSettings/GroupSettings.tsx
Labels: lgtm, approved

#2734 start webpack dev server with external cluster target
  frontend/config/webpack.dev.js
  frontend/package.json
  frontend/src/app/HeaderTools.tsx
  frontend/src/utilities/const.ts
Labels: lgtm, approved

#2735 chore(dw): refactor otherUsage and getWorkloadName
  frontend/src/api/prometheus/__tests__/distributedWorkloads.spec.ts
  frontend/src/api/prometheus/distributedWorkloads.ts
  frontend/src/concepts/distributedWorkloads/utils.tsx
  frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/TopResourceConsumingWorkloads.tsx
  frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/WorkloadResourceMetricsTable.tsx
  frontend/src/pages/distributedWorkloads/global/workloadStatus/DWWorkloadsTable.tsx
Labels: lgtm, approved

#2739 chore(dw): requested resources always show tooltip
  frontend/src/pages/distributedWorkloads/global/projectMetrics/GlobalDistributedWorkloadsProjectMetricsTab.tsx
Labels: lgtm, approved

#2732 MetricsCommonContext (DW and Model Serving): Persist refresh interval selection in browser sessionStorage
  frontend/src/__tests__/cypress/cypress/e2e/distributedWorkloads/GlobalDistributedWorkloads.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/distributedWorkloads.ts
  frontend/src/concepts/metrics/MetricsCommonContext.tsx
  frontend/src/concepts/metrics/MetricsRefreshIntervalSelect.tsx
  frontend/src/concepts/metrics/useRefreshIntervalBrowserStorage.ts
Labels: lgtm, approved

#2743 [RHOAIENG-5495] Landing page: resources section
  frontend/src/__tests__/cypress/cypress/e2e/home/homeResources.cy.ts
  frontend/src/components/OdhDocCard.tsx
  frontend/src/concepts/design/CollapsibleSection.tsx
  frontend/src/concepts/design/ScrolledGallery.tsx
  frontend/src/concepts/docResources/docUtils.ts
  frontend/src/concepts/docResources/useDocResources.tsx
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/resources/ResourcesLoading.tsx
  frontend/src/pages/home/resources/useResourcesSection.tsx
  frontend/src/pages/home/resources/useSpecifiedResources.tsx
  frontend/src/pages/learningCenter/LearningCenter.tsx
  frontend/src/pages/projects/screens/detail/overview/configuration/ConfigurationSection.tsx
  frontend/src/types.ts
Labels: lgtm, approved

#2736 DW: Consistently show resource usage for finished workloads that are still spinning down
  frontend/src/__mocks__/mockDWUsageByJobPrometheusResponse.ts
  frontend/src/__tests__/cypress/cypress/e2e/distributedWorkloads/GlobalDistributedWorkloads.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/distributedWorkloads.ts
  frontend/src/pages/distributedWorkloads/global/projectMetrics/GlobalDistributedWorkloadsProjectMetricsTab.tsx
  frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/WorkloadResourceMetricsTable.tsx
  frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/WorkloadResourceMetricsTableRow.tsx
Labels: lgtm, approved

#2750 Jupyter tile, merge cert info from old notebook to avoid loss
  backend/src/routes/api/notebooks/utils.ts
  backend/src/utils/notebookUtils.ts
Labels: lgtm, approved

#2751 Jupyter tile, merge cert info from old notebook to avoid loss
  backend/src/routes/api/notebooks/utils.ts
  backend/src/utils/notebookUtils.ts
Labels: lgtm, approved

#2754 [RHOAIENG-6519] DW: Support workloads owned by either a RayCluster or a Job when querying CPU and Memory usage
  frontend/src/__mocks__/mockDWUsageByJobPrometheusResponse.ts
  frontend/src/__mocks__/mockDWUsageByOwnerPrometheusResponse.ts
  frontend/src/__mocks__/mockWorkloadK8sResource.ts
  frontend/src/__tests__/cypress/cypress/e2e/distributedWorkloads/GlobalDistributedWorkloads.cy.ts
  frontend/src/api/prometheus/__tests__/distributedWorkloads.spec.ts
  frontend/src/api/prometheus/distributedWorkloads.ts
  frontend/src/concepts/distributedWorkloads/__tests__/utils.spec.ts
  frontend/src/concepts/distributedWorkloads/utils.tsx
  frontend/src/k8sTypes.ts
Labels: lgtm, approved

#2755 [v2.22.0] [RHOAIENG-6519] DW: Support workloads owned by either a RayCluster or a Job when querying CPU and Memory usage
  frontend/src/__mocks__/mockDWUsageByOwnerPrometheusResponse.ts
  frontend/src/__mocks__/mockWorkloadK8sResource.ts
  frontend/src/__tests__/cypress/cypress/e2e/distributedWorkloads/GlobalDistributedWorkloads.cy.ts
  frontend/src/api/prometheus/__tests__/distributedWorkloads.spec.ts
  frontend/src/api/prometheus/distributedWorkloads.ts
  frontend/src/concepts/distributedWorkloads/__tests__/utils.spec.ts
  frontend/src/concepts/distributedWorkloads/utils.tsx
  frontend/src/k8sTypes.ts
Labels: lgtm, approved

#2749 Model versions table and empty state
  frontend/src/pages/modelRegistry/ModelRegistryRoutes.tsx
  frontend/src/pages/modelRegistry/screens/EmptyModelVersions.tsx
  frontend/src/pages/modelRegistry/screens/GlobalModelVersionsTabs.tsx
  frontend/src/pages/modelRegistry/screens/ModelLabels.tsx
  frontend/src/pages/modelRegistry/screens/ModelLastModified.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersionListView.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersions.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersionsHeaderActions.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersionsTable.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersionsTableColumns.ts
  frontend/src/pages/modelRegistry/screens/ModelVersionsTableRow.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModelLink.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModelTable.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModelTableRow.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModelsTableColumns.ts
  frontend/src/pages/modelRegistry/screens/__tests__/utils.spec.ts
  frontend/src/pages/modelRegistry/screens/const.ts
  frontend/src/pages/modelRegistry/screens/utils.ts
Labels: lgtm, approved

#2746 additional cypress test case for pipeline detail
  frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelinesTopology.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/topology.ts
  frontend/src/concepts/pipelines/content/pipelinesDetails/PipelineDetailsYAML.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineTaskDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/SelectedTaskDrawerContent.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/TaskDetailsCodeBlock.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/TaskDetailsInputOutput.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/TaskDetailsSection.tsx
Labels: lgtm, approved

#2758 Add dscinitializations resource to cluster-role.yaml and handle missing dsci status in ServingRuntimeList.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/modelServing/ServingRuntimeList.cy.ts
  frontend/src/concepts/areas/__tests__/utils.spec.ts
  manifests/base/cluster-role.yaml
Labels: lgtm, approved

#2756 update anaconda image
  manifests/overlays/rhoai/anaconda-ce-validator-cron.yaml
Labels: lgtm, approved, ok-to-test

#2748 [RHOAIENG-5492] Landing page: admin section
  frontend/src/__tests__/cypress/cypress/e2e/customServingRuntimes/CustomServingRuntimes.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/customServingRuntimes/customServingRuntimesUtils.ts
  frontend/src/__tests__/cypress/cypress/e2e/home/homeAdmin.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/home/homeUtils.ts
  frontend/src/app/NavSidebar.tsx
  frontend/src/concepts/design/InfoGalleryItem.tsx
  frontend/src/images/Icon-Red_Hat-Storage-A-Black-RGB.svg
  frontend/src/images/Icon-Red_Hat-Sys_admin-A-Black-RGB.svg
  frontend/src/images/UI_icon-Red_Hat-Notebook-Images-RGB.svg
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/useEnableTeamSection.tsx
Labels: lgtm, approved

#2744 [RHOAIENG-2977] Artifacts table
  frontend/src/__tests__/cypress/cypress/pages/pipelines/experiments.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineFilterBar.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineRunTable.ts
  frontend/src/components/table/TableBase.tsx
  frontend/src/concepts/pipelines/content/tables/PipelineFilterBar.tsx
  frontend/src/concepts/pipelines/context/MlmdListContext.tsx
  frontend/src/concepts/pipelines/context/index.ts
  frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactsList.tsx
  frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactsTable.tsx
  frontend/src/pages/pipelines/global/experiments/artifacts/GlobalArtifactsPage.tsx
  frontend/src/pages/pipelines/global/experiments/artifacts/constants.ts
  frontend/src/pages/pipelines/global/experiments/artifacts/useGetArtifactsList.ts
Labels: lgtm, approved

#2753 Executions empty state and table
  frontend/src/app/AppRoutes.tsx
  frontend/src/concepts/pipelines/apiHooks/mlmd/useExecutionsFromMlmdContext.ts
  frontend/src/concepts/pipelines/apiHooks/mlmd/useGetExecutionsList.ts
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/useExecutionsForPipelineRun.ts
  frontend/src/concepts/pipelines/kfTypes.ts
  frontend/src/concepts/pipelines/topology/usePipelineTaskTopology.ts
  frontend/src/pages/pipelines/GlobalPipelineExecutionsRoutes.tsx
  frontend/src/pages/pipelines/global/experiments/executions/ExecutionsList.tsx
  frontend/src/pages/pipelines/global/experiments/executions/ExecutionsTable.tsx
  frontend/src/pages/pipelines/global/experiments/executions/ExecutionsTableRow.tsx
  frontend/src/pages/pipelines/global/experiments/executions/ExecutionsTableRowStatusIcon.tsx
  frontend/src/pages/pipelines/global/experiments/executions/ExecutionsTableToolbar.tsx
  frontend/src/pages/pipelines/global/experiments/executions/GlobalExecutions.tsx
  frontend/src/pages/pipelines/global/experiments/executions/columns.ts
  frontend/src/pages/pipelines/global/experiments/executions/const.ts
  frontend/src/routes/pipelines/executions.ts
  frontend/src/routes/pipelines/index.ts
  frontend/src/utilities/NavData.tsx
Labels: lgtm, approved

#2752 [RHOAIENG-5496] Landing page: New home page hint
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/__tests__/cypress/cypress/e2e/home/home.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/home/homeResources.cy.ts
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/HomeHint.tsx
  frontend/src/pages/home/projects/EmptyProjectsCard.tsx
  frontend/src/pages/home/resources/useResourcesSection.tsx
Labels: lgtm, approved

#2745 Cypress test for pagination
  frontend/src/__tests__/cypress/cypress/e2e/acceleratorProfiles/AcceleratorProfiles.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/applications/Administration.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/modelServing/ModelServingGlobal.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/notebookImageSettings/NotebookImageSettings.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/projects/ProjectList.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/components/Pagination.ts
  frontend/src/__tests__/cypress/cypress/utils/pagination.ts
Labels: lgtm, approved

#2759 [RHOAIENG-6606] Correctly nav to application from Jupyter card
  frontend/src/__tests__/cypress/cypress/e2e/applications/enabled.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/components/Card.ts
  frontend/src/components/OdhAppCard.tsx
Labels: lgtm, approved

#2763 [RHOAIENG-6322] Use constants for colors on images in AI Flows
  frontend/src/images/UI_icon-Red_Hat-Branch-Color.svg
  frontend/src/images/UI_icon-Red_Hat-Chart-Color.svg
  frontend/src/images/UI_icon-Red_Hat-Folder-Color.svg
  frontend/src/pages/home/aiFlows/AIFlowCard.tsx
  frontend/src/pages/home/aiFlows/flowImages/BranchImage.tsx
  frontend/src/pages/home/aiFlows/flowImages/ChartImage.tsx
  frontend/src/pages/home/aiFlows/flowImages/ProjectImage.tsx
  frontend/src/pages/home/aiFlows/useAIFlows.tsx
Labels: lgtm, approved

#2747 Add route switching and proxy handling
  backend/src/routes/api/service/modelregistry/index.ts
  frontend/src/__tests__/cypress/cypress/e2e/modelRegistry/ModelRegistry.cy.ts
  frontend/src/__tests__/cypress/cypress/pages/modelRegistry.ts
  frontend/src/concepts/modelRegistry/context/ModelRegistryContext.tsx
  frontend/src/concepts/modelRegistry/context/ModelRegistrySelectorContext.tsx
  frontend/src/pages/modelRegistry/ModelRegistryCoreLoader.tsx
  frontend/src/pages/modelRegistry/ModelRegistryRoutes.tsx
  frontend/src/pages/modelRegistry/screens/EmptyModelRegistryState.tsx
  frontend/src/pages/modelRegistry/screens/EmptyModelVersions.tsx
  frontend/src/pages/modelRegistry/screens/EmptyRegisteredModels.tsx
  frontend/src/pages/modelRegistry/screens/InvalidModelRegistry.tsx
  frontend/src/pages/modelRegistry/screens/ModelRegistry.tsx
  frontend/src/pages/modelRegistry/screens/ModelRegistrySelector.tsx
  frontend/src/pages/modelRegistry/screens/ModelRegistrySelectorNavigator.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersionListView.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersions.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModelLink.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModelsTableToolbar.tsx
Labels: lgtm, approved

#2764 [RHOAIENG-6321] Home Page Microcopy Updates
  frontend/src/__tests__/cypress/cypress/e2e/home/home.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/home/homeAIFlows.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/home/homeAdmin.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/home/homeProjects.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/home/homeResources.cy.ts
  frontend/src/__tests__/cypress/cypress/e2e/home/homeUtils.ts
  frontend/src/__tests__/cypress/cypress/pages/home.ts
  frontend/src/concepts/design/CollapsibleSection.tsx
  frontend/src/concepts/design/InfoGalleryItem.tsx
  frontend/src/pages/home/aiFlows/CreateAndTrainGallery.tsx
  frontend/src/pages/home/aiFlows/DeployAndMonitorGallery.tsx
  frontend/src/pages/home/aiFlows/ProjectsGallery.tsx
  frontend/src/pages/home/useEnableTeamSection.tsx
  frontend/src/pages/projects/screens/detail/overview/configuration/ConfigurationSection.tsx
Labels: lgtm, approved
