Repository opendatahub-io/odh-dashboard, pull requests merged in 2024-06, with the labels that each got.

#2862 Dead code removal
  frontend/src/api/index.ts
  frontend/src/api/k8s/__tests__/dashboardConfig.spec.ts
  frontend/src/api/k8s/__tests__/projects.spec.ts
  frontend/src/api/k8s/__tests__/pvcs.spec.ts
  frontend/src/api/k8s/__tests__/roleBindings.spec.ts
  frontend/src/api/k8s/__tests__/users.spec.ts
  frontend/src/api/k8s/dashboardConfig.ts
  frontend/src/api/k8s/projects.ts
  frontend/src/api/k8s/pvcs.ts
  frontend/src/api/k8s/roleBindings.ts
  frontend/src/api/k8s/users.ts
  frontend/src/api/modelRegistry/k8s.ts
  frontend/src/api/prometheus/__tests__/usePrometheusNumberValueQuery.spec.ts
  frontend/src/api/prometheus/usePrometheusNumberValueQuery.ts
  frontend/src/concepts/areas/__tests__/utils.spec.ts
  frontend/src/concepts/areas/index.ts
  frontend/src/concepts/design/utils.ts
  frontend/src/concepts/k8s/pods/__tests__/usePodContainers.spec.ts
  frontend/src/concepts/k8s/pods/usePodContainers.ts
  frontend/src/concepts/modelRegistry/apiHooks/useModelArtifactById.ts
  frontend/src/concepts/modelRegistry/apiHooks/useModelArtifacts.ts
  frontend/src/concepts/modelRegistry/apiHooks/useModelVersions.ts
  frontend/src/concepts/pipelines/apiHooks/__tests__/usePipelineQuery.spec.ts
  frontend/src/concepts/pipelines/apiHooks/usePipelineQuery.ts
  frontend/src/concepts/pipelines/const.ts
  frontend/src/concepts/pipelines/content/artifacts/charts/confusionMatrix/ConfusionMatrix.tsx
  frontend/src/concepts/pipelines/content/pipelineSelector/useCreateSelectors.ts
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerBottomContent.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerBottomTabs.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/useWindowResize.ts
  frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/TaskDetailsVolumeMounts.tsx
  frontend/src/concepts/pipelines/content/tables/pipeline/expandedRowRenderUtils.tsx
  frontend/src/concepts/pipelines/content/tables/renderUtils.tsx
  frontend/src/concepts/pipelines/content/tables/utils.ts
  frontend/src/concepts/pipelines/content/utils.tsx
  frontend/src/concepts/pipelines/kfTypes.ts
  frontend/src/concepts/topology/TaskEdge.tsx
  frontend/src/concepts/topology/index.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/learningCenter/LearningCenter.tsx
  frontend/src/pages/modelServing/screens/metrics/bias/BiasConfigurationPage/BiasConfigurationButton.tsx
  frontend/src/pages/modelServing/screens/projects/ModelServingPlatformCard.tsx
  frontend/src/pages/modelServing/screens/projects/ModelServingPlatformSelect.tsx
  frontend/src/pages/modelServing/screens/types.ts
  frontend/src/pages/pipelines/global/experiments/GlobalNoExperiments.tsx
  frontend/src/pages/pipelines/global/experiments/artifacts/utils.ts
  frontend/src/pages/projects/projectSharing/utils.ts
  frontend/src/pages/projects/screens/detail/ProjectDetailsComponents.tsx
  frontend/src/pages/projects/screens/detail/data-connections/useDataConnections.ts
  frontend/src/pages/projects/screens/detail/notebooks/types.ts
  frontend/src/pages/projects/screens/spawner/spawnerUtils.ts
  frontend/src/routes/pipelines/runs.ts
  frontend/src/services/dashboardService.ts
  frontend/src/services/getClusterStatusService.ts
  frontend/src/types.ts
  frontend/src/utilities/__tests__/const.spec.ts
  frontend/src/utilities/const.ts
Labels: lgtm, approved

#2871 fix info popover for pipeline overview card
  frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesOverviewCard.tsx
Labels: lgtm, approved

#2858 Pipeline task node details link to execution
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/SelectedNodeInputOutputTab.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/__tests__/SelectedNodeInputOutputTab.spec.tsx
Labels: lgtm, approved

#2865 fix links for invalid argo deployment alert
  frontend/src/__tests__/cypress/cypress/pages/pipelines/argoAlert.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/argoAlert.cy.ts
  frontend/src/concepts/pipelines/content/InvalidArgoDeploymentAlert.tsx
Labels: lgtm, approved

#2869 added method-style rule for eslint
  frontend/.eslintrc
  frontend/src/__tests__/cypress/cypress/support/commands/application.ts
  frontend/src/__tests__/cypress/cypress/support/commands/axe.ts
  frontend/src/__tests__/cypress/cypress/support/commands/intercept-snapshots.ts
  frontend/src/__tests__/cypress/cypress/support/commands/k8s.ts
  frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
  frontend/src/__tests__/cypress/cypress/support/websockets.ts
  frontend/src/__tests__/unit/jest.d.ts
  frontend/src/concepts/pipelines/content/createRun/contentSections/ParamsSection/types.ts
Labels: lgtm, approved

#2874 Add Pipeline Upload filesize limit
  frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineImportModal.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/not-a-pipeline-2-megabytes.yaml
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts
  frontend/src/concepts/pipelines/content/import/PipelineFileUpload.tsx
Labels: lgtm, approved

#2875 chore: Remove unused workflow dispatch on CRD change
  .github/workflows/dispatch_on_crd_change.yaml
Labels: lgtm, approved

#2877 update mlmd service prefix
  Makefile
  backend/src/routes/api/service/mlmd/index.ts
Labels: lgtm, approved

#2860 Added tests for MLMD hooks
  frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useArtifactsFromMlmdContext.spec.ts
  frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useExecutionsFromMlmdContext.spec.ts
  frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useGetArtifactById.spec.ts
  frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useGetArtifactTypes.spec.ts
  frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useGetArtifactsList.spec.ts
  frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useGetEventsByExecutionId.spec.ts
  frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useGetExecutionById.spec.ts
  frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useGetExecutionsList.spec.ts
  frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useGetLinkedArtifactsByEvents.spec.ts
  frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useGetMlmdContextByExecution.spec.ts
  frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useGetMlmdContextType.spec.ts
  frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useMlmdContext.spec.ts
  frontend/src/concepts/pipelines/apiHooks/mlmd/useGetEventsByExecutionId.ts
  frontend/src/concepts/pipelines/content/compareRuns/metricsSection/__tests__/useMlmdPackagesForPipelineRuns.spec.ts
  frontend/src/concepts/pipelines/context/MlmdListContext.tsx
  frontend/src/pages/pipelines/global/experiments/executions/details/ExecutionDetails.tsx
Labels: lgtm, approved

#2873 Refine logic actions for runs on an archived experiment page
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/experiments.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelinesTopology.cy.ts
  frontend/src/concepts/pipelines/content/createRun/RunForm.tsx
  frontend/src/concepts/pipelines/content/createRun/contentSections/ProjectAndExperimentSection.tsx
  frontend/src/concepts/pipelines/content/createRun/submitUtils.ts
  frontend/src/concepts/pipelines/content/createRun/useRunFormData.ts
  frontend/src/concepts/pipelines/content/experiment/ExperimentSelector.tsx
  frontend/src/concepts/pipelines/content/pipelineSelector/useCreateSelectors.ts
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetailsActions.tsx
  frontend/src/concepts/pipelines/content/tables/experiment/useExperimentTable.ts
  frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTableRow.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRowExperiment.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTableToolbar.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineVersion/PipelineVersionTableRow.tsx
  frontend/src/concepts/pipelines/content/tables/renderUtils.tsx
  frontend/src/pages/pipelines/GlobalPipelineExperimentsRoutes.tsx
  frontend/src/pages/pipelines/global/GlobalPipelineCoreDetails.tsx
  frontend/src/pages/pipelines/global/experiments/ExperimentRunsContext.tsx
  frontend/src/pages/pipelines/global/experiments/ExperimentRunsListBreadcrumb.tsx
  frontend/src/pages/pipelines/global/experiments/compareRuns/ManageRunsPage.tsx
  frontend/src/pages/pipelines/global/experiments/useExperimentByParams.ts
  frontend/src/pages/pipelines/global/runs/ActiveRuns.tsx
  frontend/src/pages/pipelines/global/runs/CreateScheduleButton.tsx
  frontend/src/pages/pipelines/global/runs/ScheduledRuns.tsx
Labels: lgtm, approved

#2829 Model Registry Settings: Add model registries table with db config viewer, delete action and stub for permission management modal
  backend/src/routes/api/modelRegistries/index.ts
  backend/src/routes/api/modelRegistries/modelRegistryUtils.ts
  backend/src/types.ts
  frontend/src/__mocks__/mockModelRegistry.ts
  frontend/src/__tests__/cypress/cypress/pages/modelRegistrySettings.ts
  frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistrySettings/modelRegistrySettings.cy.ts
  frontend/src/concepts/dashboard/DashboardModalFooter.tsx
  frontend/src/concepts/modelRegistrySettings/useModelRegistriesBackend.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelRegistrySettings/CreateModal.tsx
  frontend/src/pages/modelRegistrySettings/DeleteModelRegistryModal.tsx
  frontend/src/pages/modelRegistrySettings/ManagePermissionsModal.tsx
  frontend/src/pages/modelRegistrySettings/ModelRegistriesTable.tsx
  frontend/src/pages/modelRegistrySettings/ModelRegistriesTableRow.tsx
  frontend/src/pages/modelRegistrySettings/ModelRegistryDatabasePassword.tsx
  frontend/src/pages/modelRegistrySettings/ModelRegistrySettings.tsx
  frontend/src/pages/modelRegistrySettings/ViewDatabaseConfigModal.tsx
  frontend/src/pages/modelRegistrySettings/columns.ts
  frontend/src/services/modelRegistryService.ts
  frontend/src/services/modelRegistrySettingsService.ts
Labels: lgtm, approved

#2883 update enum utils for string and mixed enums
  frontend/src/utilities/__tests__/utils.spec.ts
  frontend/src/utilities/utils.ts
Labels: lgtm, approved

#2881 deleted dead code in second pass
  frontend/src/api/trustyai/k8s.ts
  frontend/src/api/trustyai/rawTypes.ts
  frontend/src/concepts/dashboard/codeEditor/useCodeEditorAsLogs.tsx
  frontend/src/concepts/modelRegistry/context/useModelRegistryNamespaceCR.ts
  frontend/src/concepts/pipelines/content/tables/utils.ts
  frontend/src/concepts/topology/utils.ts
  frontend/src/pages/modelServing/screens/const.ts
  frontend/src/pages/modelServing/screens/metrics/const.ts
  frontend/src/pages/modelServing/utils.ts
  frontend/src/pages/pipelines/global/experiments/artifacts/utils.ts
  frontend/src/types.ts
Labels: lgtm, approved

#2887 chore(version): Bump versions for several vulnerable packages
  backend/package-lock.json
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved

#2827 Add s3 storage artifact route and ui integration of it
  backend/package-lock.json
  backend/package.json
  backend/src/routes/api/storage/index.ts
  backend/src/routes/api/storage/storageUtils.ts
  backend/src/types.ts
  backend/src/utils/constants.ts
  docs/dashboard-config.md
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/concepts/areas/const.ts
  frontend/src/concepts/areas/types.ts
  frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useGetEventsByExecutionId.spec.ts
  frontend/src/concepts/pipelines/apiHooks/mlmd/useGetEventsByExecutionId.ts
  frontend/src/concepts/pipelines/content/artifacts/ArtifactUriLink.tsx
  frontend/src/concepts/pipelines/content/artifacts/__tests__/utils.spec.ts
  frontend/src/concepts/pipelines/content/artifacts/utils.ts
  frontend/src/concepts/pipelines/content/compareRuns/metricsSection/PipelineRunArtifactSelect.tsx
  frontend/src/concepts/pipelines/content/compareRuns/metricsSection/markdown/MarkdownCompare.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineTaskDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/SelectedNodeInputOutputTab.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/ArtifactNodeDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/ArtifactNodeDrawerContent.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/ArtifactVisualization.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/ArtifactPreview.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/TaskDetailsInputOutput.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/TaskDetailsPrintKeyValues.tsx
  frontend/src/concepts/pipelines/topology/__tests__/parseUtils.spec.ts
  frontend/src/concepts/pipelines/topology/parseUtils.ts
  frontend/src/concepts/pipelines/topology/pipelineTaskTypes.ts
  frontend/src/concepts/pipelines/topology/usePipelineTaskTopology.tsx
  frontend/src/k8sTypes.ts
  frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactDetails/ArtifactOverviewDetails.tsx
  frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactsTable.tsx
  frontend/src/pages/pipelines/global/experiments/artifacts/__tests__/ArtifactDetails.spec.tsx
  frontend/src/pages/pipelines/global/experiments/artifacts/__tests__/ArtifactsTable.spec.tsx
  frontend/src/pages/pipelines/global/experiments/compareRuns/CompareRunsMetricsSection.tsx
  frontend/src/pages/pipelines/global/experiments/executions/details/ExecutionDetails.tsx
  frontend/src/pages/pipelines/global/experiments/executions/utils.ts
  frontend/src/services/storageService.ts
  manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
  manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Labels: lgtm, approved

#2844 [RHOAIENG-6522] Create model metrics kserve page
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/projectDetails.cy.ts
  frontend/src/pages/UnknownError.tsx
  frontend/src/pages/modelServing/screens/metrics/EnsureMetricsAvailable.tsx
  frontend/src/pages/modelServing/screens/metrics/performance/KserveMetrics.tsx
  frontend/src/pages/modelServing/screens/metrics/performance/MetricsPlaceHolder.tsx
  frontend/src/pages/modelServing/screens/metrics/performance/ModelGraphs.tsx
  frontend/src/pages/modelServing/screens/metrics/performance/ModelMeshMetrics.tsx
  frontend/src/pages/modelServing/screens/metrics/performance/PerformanceTab.tsx
Labels: lgtm, approved

#2886 Add "Collapse All" and "Expand All" actions to control bar in topology view
  frontend/package-lock.json
  frontend/package.json
  frontend/src/concepts/topology/PipelineVisualizationSurface.tsx
Labels: lgtm, approved

#2889 fix(cookie): Bump tough-cookie using override
  backend/package-lock.json
  backend/package.json
Labels: lgtm, approved

#2884 update codecov color range
  .codecov.yml
Labels: lgtm, approved

#2876 reduce warnings in webpack prod build
  frontend/config/webpack.prod.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/table/index.ts
Labels: lgtm, approved

#2885 Show correct artifact run node details on artifact side drawer panel
  frontend/src/concepts/pipelines/topology/usePipelineTaskTopology.tsx
  frontend/src/concepts/topology/utils.ts
Labels: lgtm, approved

#2891 Fix label for runs produces by a deleted recurring run
  frontend/src/concepts/pipelines/context/useJobRelatedInformation.ts
Labels: lgtm, approved

#2866 fixed end date issue and issues scheduling pipelines in Firefox
  frontend/src/concepts/pipelines/content/createRun/contentSections/RunTypeSectionScheduled.tsx
  frontend/src/concepts/pipelines/content/createRun/submitUtils.ts
  frontend/src/concepts/pipelines/content/createRun/utils.ts
  frontend/src/utilities/__tests__/time.spec.ts
  frontend/src/utilities/time.ts
Labels: lgtm, approved

#2895 Enable gRPC-web dev tools in dev mode for MLMD client
  frontend/src/concepts/pipelines/context/PipelinesContext.tsx
Labels: lgtm, approved

#2902 Fix authorization header casing in storageUtils
  backend/src/routes/api/k8s/pass-through.ts
  backend/src/routes/api/storage/index.ts
  backend/src/routes/api/storage/storageUtils.ts
  backend/src/types.ts
Labels: lgtm, approved

#2890 Allow experiments table to sort by last run started
  frontend/src/__mocks__/mockExperimentKF.ts
  frontend/src/concepts/pipelines/content/tables/columns.ts
  frontend/src/concepts/pipelines/content/tables/experiment/ExperimentTableRow.tsx
  frontend/src/concepts/pipelines/content/tables/experiment/renderUtils.tsx
  frontend/src/concepts/pipelines/kfTypes.ts
Labels: lgtm, approved

#2903 [RHOAIENG-7428]: update pipelineRunLabel to apply correct colors
  frontend/src/concepts/pipelines/content/pipelinesDetails/PipelineDetailsTitle.tsx
  frontend/src/concepts/pipelines/content/utils.tsx
Labels: lgtm, approved

#2882 set default container and add groups in the dropdown
  frontend/src/__mocks__/mockPodK8sResource.ts
  frontend/src/concepts/k8s/pods/utils.ts
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/usePodContainerLogState.ts
  frontend/src/k8sTypes.ts
  frontend/src/types.ts
Labels: lgtm, approved

#2880 Add character limit for pipeline run name
  frontend/src/concepts/k8s/NameDescriptionField.tsx
  frontend/src/concepts/pipelines/content/createRun/RunForm.tsx
  frontend/src/concepts/pipelines/content/createRun/const.ts
Labels: lgtm, approved

#2894 Added migration for disabling trusty bias for RHOAI
  backend/src/utils/resourceUtils.ts
Labels: lgtm, approved

#2905 [RHOAIENG-7946]: Hide Status Icon on Hovered Artifact Nodes
  frontend/src/concepts/topology/customNodes/ArtifactTaskNode.tsx
Labels: lgtm, approved

#2904 Cypress test for experiments table time
  frontend/src/__tests__/cypress/cypress/pages/pipelines/experiments.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/experiments.cy.ts
Labels: lgtm, approved

#2899 Remove DS pipeline endpoint hack
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts
  frontend/src/concepts/pipelines/content/configurePipelinesServer/__tests__/utils.spec.ts
  frontend/src/concepts/pipelines/content/configurePipelinesServer/utils.ts
Labels: lgtm, approved

#2907 [RHOAIENG-8521] Enable home page in manifest file
  manifests/overlays/odhdashboardconfig/odhdashboardconfig.yaml
Labels: lgtm, approved

#2855 Convert templates to use websocket
  frontend/src/__tests__/cypress/cypress/tests/mocked/customServingRuntimes/customServingRuntimes.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/customServingRuntimes/customServingRuntimesUtils.ts
  frontend/src/api/k8s/__tests__/groups.spec.ts
  frontend/src/api/k8s/__tests__/projects.spec.ts
  frontend/src/api/k8s/__tests__/templates.spec.ts
  frontend/src/api/k8s/groups.ts
  frontend/src/api/k8s/projects.ts
  frontend/src/api/k8s/templates.ts
  frontend/src/concepts/projects/ProjectsContext.tsx
  frontend/src/pages/modelServing/ModelServingContext.tsx
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeContext.tsx
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeEditTemplate.tsx
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeEnabledToggle.tsx
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeListView.tsx
  frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeView.tsx
  frontend/src/pages/modelServing/customServingRuntimes/DeleteCustomServingRuntimeModal.tsx
  frontend/src/pages/modelServing/customServingRuntimes/useTemplates.ts
  frontend/src/pages/modelServing/screens/global/ServeModelButton.tsx
  frontend/src/pages/modelServing/screens/projects/EmptyMultiModelServingCard.tsx
  frontend/src/pages/modelServing/screens/projects/EmptySingleModelServingCard.tsx
  frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx
  frontend/src/pages/modelServing/screens/projects/ModelServingPlatformButtonAction.tsx
  frontend/src/pages/projects/ProjectDetailsContext.tsx
  frontend/src/pages/projects/screens/detail/overview/serverModels/AddModelFooter.tsx
  frontend/src/types.ts
  frontend/src/utilities/__tests__/useK8sWatchResourceList.spec.ts
  frontend/src/utilities/const.ts
  frontend/src/utilities/useK8sWatchResourceList.ts
Labels: lgtm, approved

#2892 Enable pipeline experiments in dashboard config
  backend/src/utils/constants.ts
  docs/dashboard-config.md
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineRunsGlobal.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/topology.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelineCreateRuns.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelineDeleteRuns.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelineRuns.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelinesTopology.cy.ts
  frontend/src/api/pipelines/custom.ts
  frontend/src/concepts/pipelines/apiHooks/usePipelineQuery.ts
  frontend/src/concepts/pipelines/apiHooks/usePipelineRunJobs.ts
  frontend/src/concepts/pipelines/apiHooks/usePipelineRuns.ts
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetailsActions.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineTaskDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetailsActions.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRunJob/PipelineRunJobDetails.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableToolbar.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTable.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTableRow.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTableToolbar.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineVersion/PipelineVersionTableRow.tsx
  frontend/src/concepts/pipelines/elyra/__tests__/useElyraSecret.spec.ts
  frontend/src/concepts/pipelines/elyra/utils.ts
  frontend/src/concepts/pipelines/types.ts
  frontend/src/pages/pipelines/GlobalPipelinesRoutes.tsx
  frontend/src/pages/pipelines/global/experiments/executions/details/ExecutionDetailsReferenceSection.tsx
  frontend/src/pages/pipelines/global/runs/ActiveRuns.tsx
  frontend/src/pages/pipelines/global/runs/ArchivedRuns.tsx
  frontend/src/pages/pipelines/global/runs/CreateScheduleButton.tsx
  frontend/src/pages/pipelines/global/runs/GlobalPipelineVersionRuns.tsx
  frontend/src/pages/pipelines/global/runs/ScheduledRuns.tsx
  frontend/src/routes/pipelines/global.ts
  frontend/src/routes/pipelines/runs.ts
  frontend/src/utilities/NavData.tsx
Labels: lgtm, approved

#2843 [RHOAIENG-4385] DSPA - Add back the Folder Info
  frontend/src/concepts/pipelines/content/configurePipelinesServer/ObjectStorageSection.tsx
  frontend/src/concepts/pipelines/content/configurePipelinesServer/const.ts
Labels: lgtm, approved

#2912 [RHOAIENG-8521] Enable home page in manifest file
  manifests/overlays/odhdashboardconfig/odhdashboardconfig.yaml
Labels: lgtm, approved

#2824 Fix inconsistency in authentication
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts
  frontend/src/pages/home/aiFlows/DeployAndMonitorGallery.tsx
  frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTableRow.tsx
  frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/AuthServingRuntimeSection.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenSection.tsx
  frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
Labels: lgtm, approved

#2911 [RHOAIENG-8359] Move and update pipeline and run detail tabs
  frontend/src/__tests__/cypress/cypress/pages/pipelines/topology.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelinesTopology.cy.ts
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineSummaryDescriptionList.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetailsTabs.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerBottomContent.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerBottomTabs.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabParameters.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRunJob/PipelineRunJobDetails.tsx
  frontend/src/concepts/topology/PipelineTopology.tsx
Labels: lgtm, approved

#2893 Fix types for ServingRuntimes and InferenceService
  backend/src/routes/api/servingRuntimes/index.ts
  backend/src/types.ts
  frontend/src/__mocks__/mockInferenceServiceK8sResource.ts
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts
  frontend/src/api/k8s/__tests__/inferenceServices.spec.ts
  frontend/src/api/k8s/inferenceServices.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelServing/screens/global/InferenceServiceEndpoint.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceStatus.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx
  frontend/src/pages/modelServing/screens/global/InternalServicePopoverContent.tsx
  frontend/src/pages/modelServing/screens/global/utils.ts
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/useModelFramework.ts
  frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTableRow.tsx
  frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeDetails.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/DeleteServingRuntimeModal.tsx
  frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
  frontend/src/pages/modelServing/screens/projects/useServingAcceleratorProfile.ts
  frontend/src/pages/modelServing/screens/projects/utils.ts
  frontend/src/pages/modelServing/utils.ts
  frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelsGallery.tsx
Labels: lgtm, approved

#2913 Support model metrics for KServe (RHOAIENG-6560) (RHOAIENG-6561)
  frontend/src/__mocks__/mockConfigMap.ts
  frontend/src/__mocks__/mockKserveMetricsConfigMap.ts
  frontend/src/__tests__/cypress/cypress/pages/modelMetrics.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelMetrics.cy.ts
  frontend/src/api/index.ts
  frontend/src/api/k8s/__tests__/configMaps.spec.ts
  frontend/src/api/k8s/configMaps.ts
  frontend/src/api/prometheus/const.ts
  frontend/src/api/prometheus/kservePerformanceMetrics.ts
  frontend/src/api/prometheus/useQueryRangeResourceData.ts
  frontend/src/concepts/metrics/kserve/KserveMetricsContext.tsx
  frontend/src/concepts/metrics/kserve/__tests__/utils.spec.ts
  frontend/src/concepts/metrics/kserve/const.ts
  frontend/src/concepts/metrics/kserve/content/KserveCpuUsageGraph.tsx
  frontend/src/concepts/metrics/kserve/content/KserveMeanLatencyGraph.tsx
  frontend/src/concepts/metrics/kserve/content/KserveMemoryUsageGraph.tsx
  frontend/src/concepts/metrics/kserve/content/KserveMetricsContent.tsx
  frontend/src/concepts/metrics/kserve/content/KservePerformanceGraphs.tsx
  frontend/src/concepts/metrics/kserve/content/KserveRequestCountGraph.tsx
  frontend/src/concepts/metrics/kserve/types.ts
  frontend/src/concepts/metrics/kserve/useKserveMetricsConfigMap.ts
  frontend/src/concepts/metrics/kserve/useKserveMetricsGraphDefinitions.ts
  frontend/src/concepts/metrics/kserve/utils.ts
  frontend/src/pages/modelServing/screens/metrics/MetricsChart.tsx
  frontend/src/pages/modelServing/screens/metrics/performance/KserveMetrics.tsx
  frontend/src/pages/modelServing/screens/metrics/performance/ModelGraphs.tsx
  frontend/src/pages/modelServing/screens/metrics/performance/PerformanceTab.tsx
  frontend/src/types.ts
  frontend/src/utilities/useRestructureContextResourceData.tsx
Labels: lgtm, approved

#2916 [RHOAIENG-8568] Remove 'Learn more' link from pipeline server bucket form field popover
  frontend/src/concepts/pipelines/content/configurePipelinesServer/ObjectStorageSection.tsx
  frontend/src/concepts/pipelines/content/configurePipelinesServer/const.ts
Labels: lgtm, approved

#2898 create page objects for cypress home page test
  frontend/src/__tests__/cypress/cypress/pages/enabled.ts
  frontend/src/__tests__/cypress/cypress/pages/home.ts
  frontend/src/__tests__/cypress/cypress/pages/home/home.ts
  frontend/src/__tests__/cypress/cypress/pages/home/homeAIFlow.ts
  frontend/src/__tests__/cypress/cypress/pages/home/homeAdmin.ts
  frontend/src/__tests__/cypress/cypress/pages/home/homeProject.ts
  frontend/src/__tests__/cypress/cypress/pages/home/homeResource.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/applications/notebookServer.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/home/home.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/home/homeAIFlows.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/home/homeAdmin.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/home/homeProjects.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/home/homeResources.cy.ts
Labels: lgtm, approved

#2917 Refactor useMetricColumnNames to handle empty experimentId
  frontend/src/concepts/pipelines/content/tables/pipelineRun/useMetricColumnNames.ts
Labels: lgtm, approved

#2921 fixed test for experiments
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/experiments.cy.ts
Labels: lgtm, approved

#2923 add always() condition to upload cypress artifacts
  .github/workflows/test.yml
Labels: lgtm, approved

#2922 [RHOAIENG-7970] Very long pipeline names make pipelines list view scroll columns off …
  frontend/src/concepts/pipelines/content/pipelinesDetails/PipelineDetailsTitle.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx
  frontend/src/concepts/pipelines/content/tables/experiment/ExperimentTableRow.tsx
  frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTableRow.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineVersion/PipelineVersionTableRow.tsx
  frontend/src/pages/pipelines/global/runs/GlobalPipelineVersionRuns.tsx
Labels: lgtm, approved

#2930 Upversion to v2.24.0
  frontend/.env
Labels: lgtm, approved

#2931 Cherry-pick "Upversion to v2.24.0"
  frontend/.env
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/experiments.cy.ts
Labels: lgtm, approved

#2932 Update references of docs.openshift.com to the latest OCP version
  docs/dev-setup.md
  manifests/overlays/apps/apps-onprem/starburst-enterprise/starburstenterprise-app.yaml
Labels: kind/documentation, lgtm, approved

#2928 remove artifact preview
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/ArtifactNodeDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/ArtifactPreview.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/TaskDetailsInputOutput.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/TaskDetailsPrintKeyValues.tsx
Labels: lgtm, approved

#2908 Fix UX issues on archived experiment runs table
  frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineRunTable.ts
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx
  frontend/src/pages/pipelines/global/experiments/ExperimentRunsListBreadcrumb.tsx
Labels: lgtm, approved

#2935 remove artifact preview
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/ArtifactNodeDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/ArtifactPreview.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/TaskDetailsInputOutput.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/TaskDetailsPrintKeyValues.tsx
Labels: lgtm, approved

#2936 Cleanup S3 endpoint host in configurePipelinesServer utils
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts
  frontend/src/concepts/pipelines/content/configurePipelinesServer/__tests__/utils.spec.ts
  frontend/src/concepts/pipelines/content/configurePipelinesServer/utils.ts
Labels: lgtm, approved

#2926 Fix breadcrumb navigation to correct tabs for pipeline run and jobs details page
  frontend/src/concepts/pipelines/content/createRun/CloneRunPage.tsx
  frontend/src/concepts/pipelines/content/createRun/CreateRunPage.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRunJob/PipelineRunJobDetails.tsx
  frontend/src/concepts/pipelines/content/types.ts
  frontend/src/pages/pipelines/global/GlobalPipelineCoreDetails.tsx
  frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactDetails/ArtifactDetails.tsx
  frontend/src/pages/pipelines/global/experiments/compareRuns/CompareRunsPage.tsx
  frontend/src/pages/pipelines/global/experiments/executions/details/ExecutionDetails.tsx
  frontend/src/pages/pipelines/global/runs/GlobalPipelineVersionRuns.tsx
  frontend/src/pages/projects/screens/detail/pipelines/ProjectPipelineBreadcrumbPage.tsx
  frontend/src/routes/pipelines/experiments.ts
  frontend/src/routes/pipelines/global.ts
Labels: lgtm, approved

#2939 Cleanup S3 endpoint host in configurePipelinesServer utils
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts
  frontend/src/concepts/pipelines/content/configurePipelinesServer/__tests__/utils.spec.ts
  frontend/src/concepts/pipelines/content/configurePipelinesServer/utils.ts
Labels: lgtm, approved

#2933 [RHOAIENG-8837] Truncate min width issue
  frontend/src/concepts/pipelines/content/pipelinesDetails/PipelineDetailsTitle.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx
  frontend/src/concepts/pipelines/content/tables/experiment/ExperimentTableRow.tsx
  frontend/src/pages/pipelines/global/runs/GlobalPipelineVersionRuns.tsx
Labels: lgtm, approved

#2941 [RHOAIENG-7403] Pipeline system.ClassificationMetrics artifacts provide a uri but have no source in storage
  frontend/src/concepts/pipelines/content/artifacts/ArtifactUriLink.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/ArtifactNodeDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/TaskDetailsInputOutput.tsx
  frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactDetails/ArtifactOverviewDetails.tsx
  frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactsTable.tsx
Labels: lgtm, approved

#2938 [RHOAIENG-8124] Show Pipeline Group Label on Hover at Low Scale
  frontend/package-lock.json
  frontend/package.json
  frontend/src/concepts/topology/PipelineDefaultTaskGroup.tsx
Labels: lgtm, approved

#2927 update double params to be fixed at 1
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelineCreateRuns.cy.ts
  frontend/src/concepts/pipelines/content/createRun/contentSections/ParamsSection/NumberInputParam.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/SelectedNodeInputOutputTab.tsx
Labels: lgtm, approved

#2929 Upgrade patternfly packages
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved

#2920 New Dockerfile for Running Cypress in CI
  scripts/ci/Dockerfile
Labels: infrastructure, lgtm, approved

#2940 refactored k8 resources
  frontend/src/api/k8s/__tests__/clusterQueues.spec.ts
  frontend/src/api/k8s/__tests__/configMaps.spec.ts
  frontend/src/api/k8s/__tests__/inferenceServices.spec.ts
  frontend/src/api/k8s/__tests__/localQueues.spec.ts
  frontend/src/api/k8s/__tests__/projects.spec.ts
  frontend/src/api/k8s/__tests__/pvcs.spec.ts
  frontend/src/api/k8s/__tests__/roleBindings.spec.ts
  frontend/src/api/k8s/__tests__/secrets.spec.ts
  frontend/src/api/k8s/__tests__/servingRuntimes.spec.ts
  frontend/src/api/k8s/__tests__/workloads.spec.ts
  frontend/src/api/pipelines/__tests__/k8s.spec.ts
  frontend/src/pages/projects/screens/detail/storage/__tests__/useProjectPvcs.spec.ts
Labels: lgtm, approved

#2934 configured default environment for cypress
  frontend/.eslintrc
  frontend/src/__tests__/cypress/cypress/pages/components/JupyterCard.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/application.cy.ts
Labels: lgtm, approved

#2918 [RHOAIENG-7717] Make pipeline table name cell be a clickable link to the latest pipeline version details
  frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesTable.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts
  frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTableRow.tsx
  frontend/src/concepts/pipelines/content/tables/pipeline/usePipelineTableRowData.ts
Labels: lgtm, approved

#2949 Rename Edit Permission to Contributor
  frontend/src/pages/projects/projectSharing/utils.ts
Labels: lgtm, approved

#2919 [RHOAIENG-2905] Pipeline Run Details tabs without content should be disabled
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelinesTopology.cy.ts
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightTabs.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/SelectedNodeInputOutputTab.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/SelectedNodeVolumeMountsTab.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx
Labels: lgtm, approved

#2951 Mock gRPC responses for MLMD cypress tests using ts-proto
  frontend/.eslintrc
  frontend/package-lock.json
  frontend/package.json
  frontend/src/__mocks__/mlmd/mockGetArtifactTypes.ts
  frontend/src/__mocks__/mlmd/mockGetArtifactsByContext.ts
  frontend/src/__mocks__/mlmd/mockGetContextByTypeAndName.ts
  frontend/src/__mocks__/mlmd/mockGetEventsByExecutionIDs.ts
  frontend/src/__mocks__/mlmd/mockGetExecutionsByContext.ts
  frontend/src/__mocks__/mlmd/utils.ts
  frontend/src/__mocks__/third_party/mlmd/README.md
  frontend/src/__mocks__/third_party/mlmd/generated/google/protobuf/any.ts
  frontend/src/__mocks__/third_party/mlmd/generated/google/protobuf/descriptor.ts
  frontend/src/__mocks__/third_party/mlmd/generated/google/protobuf/field_mask.ts
  frontend/src/__mocks__/third_party/mlmd/generated/google/protobuf/struct.ts
  frontend/src/__mocks__/third_party/mlmd/generated/ml_metadata/proto/metadata_store.ts
  frontend/src/__mocks__/third_party/mlmd/generated/ml_metadata/proto/metadata_store_service.ts
  frontend/src/__mocks__/third_party/mlmd/index.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/compareRuns.ts
  frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/compareRuns.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/mlmdUtils.ts
  frontend/src/concepts/pipelines/content/compareRuns/metricsSection/scalar/ScalarMetricTable.tsx
Labels: lgtm, approved

#2952 [RHOAIENG-7425]: Update Pipeline Group Labels and Positioning
  frontend/package-lock.json
  frontend/package.json
  frontend/src/concepts/topology/PipelineDefaultTaskGroup.tsx
Labels: lgtm, approved

#2947 remove isAdmin logic for EnsureCompatiblePipelineServer empty state
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts
  frontend/src/concepts/pipelines/EnsureCompatiblePipelineServer.tsx
Labels: lgtm, approved

#2945 support feature flag overrides via query string
  backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts
  backend/src/routes/api/cluster-settings/index.ts
  backend/src/routes/api/storage/index.ts
  backend/src/utils/resourceUtils.ts
  frontend/.eslintrc
  frontend/src/api/k8s/__tests__/projects.spec.ts
  frontend/src/api/k8s/projects.ts
  frontend/src/api/prometheus/__tests__/distributedWorkloads.spec.ts
  frontend/src/api/prometheus/__tests__/pvcs.spec.ts
  frontend/src/api/prometheus/__tests__/usePrometheusQuery.spec.ts
  frontend/src/api/prometheus/__tests__/usePrometheusQueryRange.spec.ts
  frontend/src/api/prometheus/usePrometheusQuery.ts
  frontend/src/api/prometheus/usePrometheusQueryRange.ts
  frontend/src/app/App.tsx
  frontend/src/app/DevFeatureFlagsBanner.tsx
  frontend/src/app/__tests__/DevFeatureFlagsBanner.spec.tsx
  frontend/src/app/__tests__/useDevFeatureFlags.spec.ts
  frontend/src/app/useDevFeatureFlags.ts
  frontend/src/components/browserStorage/BrowserStorageContext.tsx
  frontend/src/concepts/areas/__tests__/useFetchDscStatus.spec.ts
  frontend/src/concepts/areas/__tests__/useFetchDsciStatus.spec.ts
  frontend/src/concepts/areas/const.ts
  frontend/src/concepts/areas/useFetchDscStatus.ts
  frontend/src/concepts/areas/useFetchDsciStatus.ts
  frontend/src/concepts/areas/utils.ts
  frontend/src/redux/actions/actions.ts
  frontend/src/services/acceleratorProfileService.ts
  frontend/src/services/acceleratorService.ts
  frontend/src/services/buildsService.ts
  frontend/src/services/clusterSettingsService.ts
  frontend/src/services/componentsServices.ts
  frontend/src/services/consoleLinksService.ts
  frontend/src/services/dashboardConfigService.ts
  frontend/src/services/dashboardService.ts
  frontend/src/services/docsService.ts
  frontend/src/services/envService.ts
  frontend/src/services/groupSettingsService.ts
  frontend/src/services/imagesService.ts
  frontend/src/services/impersonateService.ts
  frontend/src/services/modelRegistrySettingsService.ts
  frontend/src/services/notebookEventsService.ts
  frontend/src/services/notebookService.ts
  frontend/src/services/quickStartsService.ts
  frontend/src/services/roleBindingService.ts
  frontend/src/services/routeService.ts
  frontend/src/services/segmentKeyService.ts
  frontend/src/services/storageService.ts
  frontend/src/services/templateService.ts
  frontend/src/services/validateIsvService.ts
  frontend/src/types.ts
  frontend/src/utilities/__tests__/useDetectUser.spec.ts
  frontend/src/utilities/axios.ts
  frontend/src/utilities/useDetectUser.ts
Labels: lgtm, approved

#2948 remove the length check for the loaded state of customize metric columns
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx
Labels: lgtm, approved

#2964 [RHOAIENG-9175] Broken link to Fraud Detection tutorial in Dashboard Home
  manifests/overlays/apps/base/rhoai/rhoai-docs.yaml
Labels: lgtm, approved

#2967 Broken link to Fraud Detection tutorial in Dashboard Home (RHOAI 2.11.0)
  manifests/overlays/apps/base/rhoai/rhoai-docs.yaml
Labels: lgtm, approved

#2960 Create NPM Cache directories for CI and run `npm ci` in Dockerfile build
  scripts/ci/Dockerfile
Labels: infrastructure, lgtm, approved
