Repository opendatahub-io/odh-dashboard, pull requests merged in 2025-03, with the labels that each got.

#3767 [RHOAIENG-18124] Add Workload Metrics Sanity tests
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/workloadMetricsResources/testWorkloadMetricsResources.yaml
  frontend/src/__tests__/cypress/cypress/fixtures/resources/yaml/kueue_reosources.yaml
  frontend/src/__tests__/cypress/cypress/pages/distributedWorkloads.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/distributedWorkloadMetrics/testWorkloadMetricsDefaultPageContents.cy.ts
  frontend/src/__tests__/cypress/cypress/types.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/distributedWorkloads.ts
  frontend/src/__tests__/cypress/cypress/utils/workloadMetricsUtils.ts
  frontend/src/__tests__/resources/distributedworkloads/kueue_reosources.yaml
Labels: lgtm, approved

#3832 Update microcopy
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/registerCatalogModel.cy.ts
  frontend/src/concepts/modelRegistry/utils/updateTimestamps.ts
  frontend/src/pages/modelCatalog/screens/RegisterCatalogModel.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx
  frontend/src/pages/modelRegistry/screens/components/DeployRegisteredModelModal.tsx
Labels: lgtm, approved

#3834 Render URLs as external links in MR customProperties
  frontend/src/pages/modelRegistry/screens/ModelPropertiesTableRow.tsx
  frontend/src/pages/modelRegistry/screens/__tests__/utils.spec.ts
  frontend/src/pages/modelRegistry/screens/utils.ts
Labels: lgtm, approved

#3801 Create OOTB ConfigMap for curated model list data
  manifests/rhoai/shared/apps/kustomization.yaml
  manifests/rhoai/shared/apps/model-catalog/kustomization.yaml
  manifests/rhoai/shared/apps/model-catalog/model-catalog-configmap.yaml
  manifests/rhoai/shared/apps/model-catalog/model-catalog-rbac.yaml
Labels: lgtm, approved

#3833 Cypress e2e - Button redirect Workaround
  frontend/src/__tests__/cypress/cypress/tests/e2e/dashboardNavigation/testManifestLinks.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataSciencePipelines/pipelines.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/clusterStorage/testClusterStorageCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/connections/testDataConnectionCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testMultiModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelContributorCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testLaunchStandaloneNotebook.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testProjectAdminPermissions.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testProjectContributorPermissions.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchControlSuite.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchEditing.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchNegativeTests.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchStatus.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchTolerations.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchVariables.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/workbenches.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/learningResources/testCustomResourceCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/storageClasses/clusterStorage.cy.ts
Labels: lgtm, approved

#3824 Manage ilab pipeline at project scope
  frontend/src/__mocks__/mockDsc.ts
  frontend/src/__tests__/cypress/cypress/pages/clusterSettings.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/clusterSettings/clusterSettings.cy.ts
  frontend/src/api/k8s/dsc.ts
  frontend/src/api/pipelines/k8s.ts
  frontend/src/concepts/notificationWatcher/NotificationWatcherContext.tsx
  frontend/src/concepts/pipelines/content/ManageSamplePipelinesModal.tsx
  frontend/src/concepts/pipelines/content/configurePipelinesServer/ConfigurePipelinesServerModal.tsx
  frontend/src/concepts/pipelines/content/configurePipelinesServer/InstructLabPipelineEnablement.tsx
  frontend/src/concepts/pipelines/content/configurePipelinesServer/SamplePipelineSettingsSection.tsx
  frontend/src/concepts/pipelines/content/configurePipelinesServer/__tests__/utils.spec.ts
  frontend/src/concepts/pipelines/content/configurePipelinesServer/types.ts
  frontend/src/concepts/pipelines/content/configurePipelinesServer/utils.ts
  frontend/src/concepts/pipelines/content/import/ImportPipelineSplitButton.tsx
  frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTableRow.tsx
  frontend/src/concepts/pipelines/context/PipelinesContext.tsx
  frontend/src/k8sTypes.ts
  frontend/src/pages/clusterSettings/ClusterSettings.tsx
  frontend/src/pages/clusterSettings/InstructLabSettings.tsx
  frontend/src/pages/clusterSettings/utils.ts
  frontend/src/pages/pipelines/global/pipelines/GlobalNoPipelines.tsx
Labels: lgtm, approved

#3847 remove node version matrix from Tests job
  .github/workflows/test.yml
Labels: lgtm, approved

#3850 [v2.21.0-fixes] remove node version matrix from Tests job
  .github/workflows/pull_request.yml
Labels: lgtm, approved

#3849 [v2.26.0-fixes] remove node version matrix from Tests job
  .github/workflows/test.yml
Labels: lgtm, approved

#3848 [v2.29.0-fixes] remove node version matrix from Tests job
  .github/workflows/test.yml
Labels: lgtm, approved

#3851 fix(17779): misaligned deploy model modal buttons
  frontend/src/pages/modelServing/screens/projects/kServeModal/EnvironmentVariablesSection.tsx
  frontend/src/pages/modelServing/screens/projects/kServeModal/ServingRuntimeArgsSection.tsx
Labels: lgtm, approved

#3854 Cypress quarantine test resources filters
  frontend/src/__tests__/cypress/cypress/tests/e2e/learningResources/testResourcesfilters.cy.ts
Labels: lgtm, approved

#3757 allow to restore archived runs whose associate experiments are archived
  frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineRunTable.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/restoreModal.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelineRuns.cy.ts
  frontend/src/concepts/dashboard/DashboardModalFooter.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRowExperiment.tsx
  frontend/src/concepts/pipelines/content/useRestoreStatuses.tsx
  frontend/src/pages/pipelines/global/runs/RestoreRunWithArchivedExperimentModal.tsx
  frontend/src/pages/pipelines/global/runs/RestoreRunsStatusIcon.tsx
  frontend/src/pages/pipelines/global/runs/RestoreRunsTableRowExperiment.tsx
  frontend/src/pages/pipelines/global/runs/RunsWithArchivedExperimentTable.tsx
  frontend/src/pages/pipelines/global/runs/types.ts
  frontend/src/pages/pipelines/global/runs/utils.ts
  frontend/src/utilities/allSettledPromises.ts
Labels: lgtm, approved

#3836 disableKServeOCIModels filters out ootb type
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/connections.cy.ts
  frontend/src/concepts/modelRegistry/apiHooks/__tests__/usePrefillDeployModalFromModelRegistry.spec.ts
  frontend/src/pages/projects/screens/detail/connections/useConnections.ts
  frontend/src/utilities/useWatchConnectionTypes.tsx
Labels: lgtm, approved

#3829 Fix flashing error message during iLab Pipeline project selection
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts
  frontend/src/concepts/pipelines/content/modelCustomizationForm/useIlabPipeline.ts
Labels: lgtm, approved

#3838 FIX : Title and Project Selector Overflow on Data Science Pages
  frontend/src/concepts/projects/ProjectSelector.tsx
  frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
  frontend/src/pages/projects/screens/projects/ProjectLink.tsx
Labels: lgtm, approved

#3818 List only Pull OCI Connections in ConnectionSection
  frontend/src/concepts/connectionTypes/__tests__/utils.spec.ts
  frontend/src/concepts/connectionTypes/utils.ts
  frontend/src/pages/connectionTypes/ConnectionTypesTableRow.tsx
  frontend/src/pages/connectionTypes/manage/ManageConnectionTypePage.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModels/usePrefillDeployModalFromModelRegistry.ts
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/__tests__/ConnectionSection.spec.tsx
  frontend/src/pages/modelServing/screens/projects/utils.ts
  frontend/src/pages/projects/screens/detail/connections/ConnectionsTableRow.tsx
  frontend/src/pages/projects/screens/detail/connections/useConnections.ts
  frontend/src/utilities/useWatchConnectionTypes.tsx
Labels: lgtm, approved

#3856 Allow user to edit file field contents
  frontend/src/concepts/connectionTypes/fields/FileFormField.tsx
  frontend/src/concepts/connectionTypes/fields/__tests__/FileFormField.spec.tsx
Labels: lgtm, approved

#3841 Feat/20078 model detail fine tune popover
  frontend/src/__tests__/cypress/cypress/pages/modelCatalog/modelDetailsPage.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelDetailsPage.cy.ts
  frontend/src/images/UI_icon-Red_Hat-Controls-Black.svg
  frontend/src/images/icons/RhUiControlsIcon.ts
  frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx
Labels: lgtm, approved

#3852 Add back the notification for auth resource updates
  frontend/src/concepts/userConfigs/useWatchGroups.tsx
Labels: lgtm, approved

#3844 Update encodeParams util and fix modelName prefill in Register model form
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalog.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelDetailsPage.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/registerCatalogModel.cy.ts
  frontend/src/pages/modelCatalog/__tests__/utils.spec.ts
  frontend/src/pages/modelCatalog/screens/RegisterCatalogModel.tsx
  frontend/src/pages/modelCatalog/utils.ts
Labels: lgtm, approved

#3857 remove disableKServeOCIModels
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/connections.cy.ts
  frontend/src/concepts/areas/const.ts
  frontend/src/concepts/areas/types.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/projects/screens/detail/connections/useConnections.ts
  frontend/src/utilities/useWatchConnectionTypes.tsx
Labels: lgtm, approved

#3859 Fix runtime config parameter handling in pipeline run creation
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelineCreateRuns.cy.ts
  frontend/src/concepts/pipelines/content/createRun/RunForm.tsx
  frontend/src/concepts/pipelines/content/createRun/submitUtils.ts
  frontend/src/concepts/pipelines/content/createRun/utils.ts
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/utils.tsx
  frontend/src/concepts/pipelines/kfTypes.ts
Labels: lgtm, approved

#3864 changed the ilab pipeline status from warning to danger to match Figma
  frontend/src/pages/pipelines/global/modelCustomization/startRunModal/MissingConditionAlert.tsx
Labels: lgtm, approved

#3855 cache cypress build for improved test execution performance
  .github/workflows/test.yml
  frontend/package.json
Labels: lgtm, approved

#3860 Link pipeline run from MR version details page
  frontend/src/__tests__/cypress/cypress/pages/modelRegistry/modelVersionDetails.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionDetails.cy.ts
  frontend/src/pages/modelRegistry/screens/ModelPropertiesDescriptionListGroup.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersionDetails/const.ts
  frontend/src/pages/modelRegistry/screens/__tests__/utils.spec.ts
  frontend/src/pages/modelRegistry/screens/utils.ts
Labels: lgtm, approved

#3853 Fix selecting all projects for global model page
  frontend/src/concepts/projects/ProjectSelectorNavigator.tsx
  frontend/src/pages/modelServing/ModelServingContext.tsx
Labels: lgtm, approved

#3835 add ilab hardware sections
  frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationForm.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts
  frontend/src/concepts/hardwareProfiles/HardwareProfileCustomize.tsx
  frontend/src/concepts/hardwareProfiles/HardwareProfileFormSection.tsx
  frontend/src/concepts/hardwareProfiles/HardwareProfileSelect.tsx
  frontend/src/concepts/hardwareProfiles/validationUtils.ts
  frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/validationUtils.ts
  frontend/src/pages/notebookController/screens/server/AcceleratorProfileSelectField.tsx
  frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx
  frontend/src/pages/pipelines/global/modelCustomization/FineTunePageFooter.tsx
  frontend/src/pages/pipelines/global/modelCustomization/FineTuneTaxonomySection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/ModelCustomizationForm.tsx
  frontend/src/pages/pipelines/global/modelCustomization/const.ts
  frontend/src/pages/pipelines/global/modelCustomization/teacherJudgeSection/TeacherJudgeInputComponents.tsx
  frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/ContainerCustomSize.tsx
  frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/TrainingAcceleratorFormSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/TrainingHardwareProfileFormSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/TrainingHardwareSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/type.ts
  frontend/src/pages/pipelines/global/modelCustomization/useIlabPodSpecOptionsState.ts
  frontend/src/pages/pipelines/global/modelCustomization/utils.ts
  frontend/src/pages/projects/screens/spawner/storage/CreateNewStorageSection.tsx
  frontend/src/pages/projects/screens/spawner/storage/StorageClassSelect.tsx
  frontend/src/utilities/useAcceleratorProfileFormState.ts
Labels: lgtm, approved

#3866 Change Model deployments column header
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts
  frontend/src/pages/modelServing/screens/global/data.ts
Labels: lgtm, approved

#3870 Improve hardware profiles permission state
  frontend/src/concepts/userSSAR/AccessReviewContext.tsx
  frontend/src/pages/hardwareProfiles/HardwareProfileEnableToggle.tsx
  frontend/src/pages/hardwareProfiles/HardwareProfilesRoutes.tsx
  frontend/src/utilities/NavData.tsx
Labels: lgtm, approved

#3845 RHOAIENG-20641 Add more Analytics for Registry and Pipelines
  frontend/src/concepts/analyticsTracking/segmentIOUtils.tsx
  frontend/src/concepts/pipelines/content/ArchiveModal.tsx
  frontend/src/concepts/pipelines/content/DeletePipelineServerModal.tsx
  frontend/src/concepts/pipelines/content/DeletePipelinesModal.tsx
  frontend/src/concepts/pipelines/content/PipelineServerActions.tsx
  frontend/src/concepts/pipelines/content/RestoreModal.tsx
  frontend/src/concepts/pipelines/content/configurePipelinesServer/ConfigurePipelinesServerModal.tsx
  frontend/src/concepts/pipelines/content/createRun/RunPageFooter.tsx
  frontend/src/concepts/pipelines/content/experiment/CreateExperimentModal.tsx
  frontend/src/concepts/pipelines/content/import/PipelineImportModal.tsx
  frontend/src/concepts/pipelines/content/import/PipelineVersionImportModal.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRecurringRun/PipelineRecurringRunDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRecurringRun/PipelineRecurringRunTable.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx
  frontend/src/pages/modelRegistry/screens/RegisterModel/RegisterModel.tsx
  frontend/src/pages/modelRegistry/screens/components/ArchiveModelVersionModal.tsx
  frontend/src/pages/modelRegistry/screens/components/ArchiveRegisteredModelModal.tsx
  frontend/src/pages/modelRegistry/screens/components/RestoreModelVersionModal.tsx
  frontend/src/pages/modelRegistry/screens/components/RestoreRegisteredModel.tsx
  frontend/src/pages/modelRegistrySettings/CreateModal.tsx
  frontend/src/pages/modelRegistrySettings/DeleteModelRegistryModal.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx
  frontend/src/pages/pipelines/global/experiments/ArchiveExperimentModal.tsx
  frontend/src/pages/pipelines/global/experiments/DeleteExperimentModal.tsx
  frontend/src/pages/pipelines/global/experiments/RestoreExperimentModal.tsx
  frontend/src/pages/pipelines/global/runs/ArchiveRunModal.tsx
  frontend/src/pages/pipelines/global/runs/RestoreRunModal.tsx
Labels: lgtm, approved

#3873 [Backport] 2.16.2 CVE dompurify
  frontend/package-lock.json
  frontend/package.json
  frontend/src/utilities/markdown.ts
Labels: lgtm, approved

#3861 Deploy models with OCI from model registry
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionDeploy.cy.ts
  frontend/src/concepts/connectionTypes/utils.ts
  frontend/src/concepts/modelRegistry/__tests__/utils.spec.ts
  frontend/src/concepts/modelRegistry/utils.ts
  frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModels/useLabeledConnections.ts
  frontend/src/pages/modelRegistry/screens/RegisteredModels/usePrefillDeployModalFromModelRegistry.ts
  frontend/src/pages/modelRegistry/screens/RegisteredModels/useRegisteredModelDeployInfo.ts
  frontend/src/pages/modelRegistry/screens/__tests__/utils.spec.ts
  frontend/src/pages/modelRegistry/screens/components/DeployRegisteredModelModal.tsx
  frontend/src/pages/modelRegistry/screens/utils.ts
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ProjectSelector.tsx
  frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
Labels: lgtm, approved

#3815 fix(serving): change raw label to annotation
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts
  frontend/src/api/k8s/__tests__/inferenceServices.spec.ts
  frontend/src/api/k8s/inferenceServices.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelServing/screens/projects/utils.ts
Labels: lgtm, approved

#3863 Cypress e2e Test - Verifies that workbench images have an additional dropdown which supports N/N-1 image versions.
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/dataScienceProjects/testWorkbenchImages.yaml
  frontend/src/__tests__/cypress/cypress/pages/workbench.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataSciencePipelines/createRunDeletePipelineCustomPipMirror.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataSciencePipelines/pipelines.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchImages.cy.ts
  frontend/src/__tests__/cypress/cypress/types.ts
  frontend/src/__tests__/cypress/cypress/utils/dataLoader.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/imageStreams.ts
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageVersionSelector.tsx
Labels: lgtm, approved

#3878 [Backport] Fix Jupyter Tile env var readback
  frontend/src/__mocks__/mockNotebookK8sResource.ts
  frontend/src/__tests__/cypress/cypress/pages/notebookServer.ts
  frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/applications/notebookServer.cy.ts
  frontend/src/pages/notebookController/screens/server/EnvironmentVariablesField.tsx
  frontend/src/pages/notebookController/screens/server/EnvironmentVariablesRow.tsx
Labels: lgtm, approved

#3773 Add NIM enable test flow
  frontend/src/__tests__/cypress/cypress/pages/components/NIMCard.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/nim/testEnableNIM.cy.ts
  frontend/src/__tests__/cypress/cypress/types.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/baseCommands.ts
  frontend/src/__tests__/cypress/cypress/utils/testConfig.ts
  frontend/src/__tests__/cypress/test-variables.yml.example
  frontend/src/pages/exploreApplication/EnableModal.tsx
  frontend/src/pages/exploreApplication/GetStartedPanel.tsx
Labels: lgtm, approved, ok-to-test

#3862 Enhance ODS-1877 'Verify a Jupyter Notebook can be launched directly from the Data Science Project List View'
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testLaunchStandaloneNotebook.cy.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/baseCommands.ts
Labels: lgtm, approved

#3879 further improvements to PR test run times
  .github/workflows/test.yml
  frontend/src/__tests__/cypress/cypress/tests/mocked/applications/application.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/applications/externalRedirects.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionArchive.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDeploy.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDetails.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersions.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/runs/compareRuns.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/runs/manageRuns.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/runs/pipelineCreateRuns.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/runs/pipelineDeleteRuns.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/runs/pipelineRuns.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/topology/pipelinesTopology.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/clusterStorage.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/connections.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/modelServingNim.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/permissions.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/workbench.cy.ts
Labels: lgtm, approved

#3817 add ilab basic params
  frontend/src/__mocks__/mockPipelineVersionsProxy.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationForm.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts
  frontend/src/__tests__/cypress/cypress/types.ts
  frontend/src/components/ParamsDefaultFields.tsx
  frontend/src/concepts/pipelines/content/createRun/contentSections/ParamsSection/ParamsSection.tsx
  frontend/src/concepts/pipelines/content/modelCustomizationForm/hyperparameterFields/HyperparameterEvaluationField.tsx
  frontend/src/concepts/pipelines/content/modelCustomizationForm/hyperparameterFields/HyperparameterLongNumberField.tsx
  frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/__tests__/validationUtils.spec.ts
  frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/hyperparameterValidationUtils.ts
  frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/types.ts
  frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/validationUtils.ts
  frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx
  frontend/src/pages/pipelines/global/modelCustomization/FineTunePageFooter.tsx
  frontend/src/pages/pipelines/global/modelCustomization/HyperparameterSection/HyperparameterFields.tsx
  frontend/src/pages/pipelines/global/modelCustomization/HyperparameterSection/HyperparameterFieldsUtils.tsx
  frontend/src/pages/pipelines/global/modelCustomization/HyperparameterSection/HyperparameterPageSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/ModelCustomizationForm.tsx
  frontend/src/pages/pipelines/global/modelCustomization/RunTypeSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/const.ts
  frontend/src/pages/pipelines/global/modelCustomization/utils.ts
Labels: lgtm, approved

#3880 fix(RHOAIENG-20551):added scrollable prop to the Hardware profiles dropdown
  frontend/src/concepts/hardwareProfiles/HardwareProfileSelect.tsx
Labels: lgtm, approved

#3871 Update reliantAreas of Fine tuning feature
  frontend/src/concepts/areas/const.ts
Labels: lgtm, approved

#3884 Update prefilled connections data to persist correctly
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDeploy.cy.ts
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
  frontend/src/pages/projects/screens/detail/connections/ManageConnectionsModal.tsx
  frontend/src/pages/projects/screens/detail/connections/usePersistentData.ts
Labels: lgtm, approved

#3888 Cypress e2e - Verify Unauthorized User Is Not Able To Spawn Jupyter Notebook
  frontend/src/__tests__/cypress/cypress/pages/components/Header.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/userManagement/testUnauthorizedUserNotebookSpawnBlocked.cy.ts
Labels: lgtm, approved

#3885 Error handling for incompatible ilab pipeline yaml
  frontend/src/__mocks__/mockIlabPipelineVersionParameters.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationForm.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts
  frontend/src/__tests__/cypress/cypress/types.ts
  frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/__tests__/validationUtils.spec.ts
  frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/validationUtils.ts
  frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx
  frontend/src/pages/pipelines/global/modelCustomization/ModelCustomizationForm.tsx
  frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/PipelineDetailsSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/const.ts
Labels: lgtm, approved

#3889 Organize Models by group
  frontend/src/api/k8s/hardwareProfiles.ts
  frontend/src/api/modelRegistry/k8s.ts
  frontend/src/api/models/index.ts
  frontend/src/api/models/kserve.ts
  frontend/src/api/models/kubeflow.ts
  frontend/src/api/models/modelRegistry.ts
  frontend/src/api/models/odh.ts
  frontend/src/api/models/pipelines.ts
  frontend/src/api/models/trustyai.ts
  frontend/src/api/pipelines/k8s.ts
  frontend/src/api/trustyai/k8s.ts
  frontend/src/concepts/k8s/__tests__/utils.spec.ts
  frontend/src/concepts/k8s/utils.ts
  frontend/src/pages/hardwareProfiles/migration/utils.ts
  frontend/src/pages/modelRegistrySettings/CreateModal.tsx
Labels: lgtm, approved

#3891 Add fine-tuned model section to ilab form
  frontend/src/concepts/connectionTypes/utils.ts
  frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/validationUtils.ts
  frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx
  frontend/src/pages/pipelines/global/modelCustomization/FineTunePageFooter.tsx
  frontend/src/pages/pipelines/global/modelCustomization/ModelCustomizationForm.tsx
  frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/BaseModelSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/const.ts
  frontend/src/pages/pipelines/global/modelCustomization/fineTunedModelSection/FineTunedModelConnectionSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/fineTunedModelSection/FineTunedModelExistingConnectionField.tsx
  frontend/src/pages/pipelines/global/modelCustomization/fineTunedModelSection/FineTunedModelNewConnectionContext.tsx
  frontend/src/pages/pipelines/global/modelCustomization/fineTunedModelSection/FineTunedModelNewConnectionField.tsx
  frontend/src/pages/pipelines/global/modelCustomization/fineTunedModelSection/FineTunedModelOciPathField.tsx
  frontend/src/pages/pipelines/global/modelCustomization/fineTunedModelSection/FineTunedModelSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/utils.ts
Labels: lgtm, approved

#3858 Model registry ilab fine tune button on version details, and kebab action on model versions table
  frontend/src/__tests__/cypress/cypress/pages/modelRegistry/modelVersionDetails.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDetails.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersions.cy.ts
  frontend/src/concepts/modelRegistry/context/ModelRegistrySelectorContext.tsx
  frontend/src/concepts/modelRegistry/hooks/useModelVersionTuningData.ts
  frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetails.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsHeaderActions.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionListView.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionsTable.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionsTableRow.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersionsArchive/ModelVersionsArchive.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersionsArchive/ModelVersionsArchiveListView.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersionsArchive/ModelVersionsArchiveTable.tsx
  frontend/src/pages/pipelines/global/modelCustomization/startRunModal/StartRunModal.tsx
Labels: lgtm, approved

#3900 fix: add BUCKET_1 to test-variables
  frontend/src/__tests__/cypress/test-variables.yml.example
Labels: lgtm, approved

#3823 fix: add NIM specific API key validation messages
  backend/src/types.ts
  frontend/src/__mocks__/mockOdhApplication.ts
  frontend/src/pages/exploreApplication/EnableModal.tsx
  frontend/src/types.ts
  manifests/common/crd/odhapplications.dashboard.opendatahub.io.crd.yaml
  manifests/rhoai/shared/apps/nvidia-nim/nvidia-nim-app.yaml
Labels: lgtm, approved, ok-to-test

#3883 Add feature flag for registered model links in Pipelines UI
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/SelectedNodeDetailsTab.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/useFetchRunArtifact.tsx
  frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx
  frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactDetails/ArtifactDetails.tsx
  frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactDetails/ArtifactOverviewDetails.tsx
  frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactsTableRow.tsx
Labels: lgtm, approved

#3901 Quarantine ODS-1877 'Verify That Usage Data Collection Can Be Set In Cluster Settings'
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/clusterSettings/testDataCollection.cy.ts
Labels: lgtm, approved

#3893 Show error if only Push access
  frontend/src/__mocks__/mockConnectionType.ts
  frontend/src/concepts/connectionTypes/ConnectionTypeForm.tsx
  frontend/src/concepts/connectionTypes/fields/ConnectionTypeFormFields.tsx
  frontend/src/concepts/connectionTypes/fields/DropdownFormField.tsx
  frontend/src/concepts/connectionTypes/fields/FileFormField.tsx
  frontend/src/concepts/connectionTypes/fields/NumericFormField.tsx
  frontend/src/concepts/connectionTypes/fields/UriFormField.tsx
  frontend/src/concepts/connectionTypes/fields/types.d.ts
  frontend/src/pages/connectionTypes/manage/DataFieldPropertiesForm.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/__tests__/ConnectionSection.spec.tsx
  frontend/src/pages/pipelines/global/modelCustomization/fineTunedModelSection/FineTunedModelNewConnectionContext.tsx
  frontend/src/pages/projects/screens/detail/connections/ManageConnectionsModal.tsx
  frontend/src/pages/projects/screens/detail/connections/usePersistentData.ts
Labels: lgtm, approved

#3723 Rhoaieng 17802
  frontend/src/__tests__/cypress/cypress/pages/notFound.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/userManagement/testUnathorizedPermChange.cy.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/groupConfig.ts
Labels: lgtm, approved

#3768 fix: ensure tokens consistency after editing and redeploying.
  frontend/src/pages/modelServing/utils.ts
  frontend/src/pages/projects/ProjectDetailsContext.tsx
Labels: lgtm, approved, ok-to-test

#3902 Cypress e2e Tests Readme
  frontend/src/__tests__/cypress/cypress/tests/e2e/README.md
Labels: lgtm, approved

#3895 Feat/20077 link back to catalog
  frontend/src/__tests__/cypress/cypress/pages/modelRegistry/modelVersionDetails.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDetails.cy.ts
  frontend/src/pages/modelCatalog/components/ModelCatalogCard.tsx
  frontend/src/pages/modelCatalog/const.ts
  frontend/src/pages/modelCatalog/routeUtils.ts
  frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx
  frontend/src/pages/modelCatalog/screens/RegisterCatalogModel.tsx
  frontend/src/pages/modelCatalog/utils.ts
  frontend/src/pages/modelRegistry/screens/ModelPropertiesDescriptionListGroup.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersionDetails/const.ts
  frontend/src/pages/modelRegistry/screens/__tests__/utils.spec.ts
  frontend/src/pages/modelRegistry/screens/utils.ts
Labels: lgtm, approved

#3869 fix: prevent useEffect from overwriting model server size selection
  frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx
Labels: lgtm, approved, ok-to-test

#3911 Updates model catalog sources in ConfigMap
  manifests/rhoai/shared/apps/model-catalog/model-catalog-configmap.yaml
Labels: lgtm, approved

#3912 Show errors when failing to load artifacts for ilab modal
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersions.cy.ts
  frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionsTableRow.tsx
  frontend/src/pages/pipelines/global/modelCustomization/startRunModal/StartRunModal.tsx
Labels: lgtm, approved

#3909 add proper empty state for hardware profile table
  frontend/src/pages/hardwareProfiles/HardwareProfiles.tsx
Labels: lgtm, approved

#3910 Model customization landing page microcopy
  frontend/src/__tests__/cypress/cypress/pages/pipelines/index.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationGlobal.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationLandingPage.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomization.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationLandingPage.cy.ts
  frontend/src/concepts/design/TypedObjectIcon.tsx
  frontend/src/concepts/design/utils.ts
  frontend/src/images/icons/LabTuningIcon.ts
  frontend/src/images/icons/index.ts
  frontend/src/pages/pipelines/GlobalModelCustomizationRoutes.tsx
  frontend/src/pages/pipelines/global/modelCustomization/GlobalModelCustomization.tsx
  frontend/src/pages/pipelines/global/modelCustomization/ModelCustomization.tsx
  frontend/src/pages/pipelines/global/modelCustomization/ModelRegistries.tsx
  frontend/src/pages/pipelines/global/modelCustomization/landingPage/BaseSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/landingPage/LabMethodDescriptionSection.scss
  frontend/src/pages/pipelines/global/modelCustomization/landingPage/LabMethodDescriptionSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/landingPage/ModelCustomization.tsx
  frontend/src/pages/pipelines/global/modelCustomization/landingPage/ModelCustomizationAccordionItem.tsx
  frontend/src/pages/pipelines/global/modelCustomization/landingPage/ModelCustomizationDrawerContent.tsx
  frontend/src/pages/pipelines/global/modelCustomization/landingPage/NextStepsSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/landingPage/PrerequisitesSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/landingPage/ProjectSetupSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/landingPage/useToggleAccordion.tsx
Labels: lgtm, approved

#3915 RHOAIENG-21549: Quarantine test due to Automation Bug: Verify NIM ena…
  frontend/src/__tests__/cypress/cypress/tests/e2e/nim/testEnableNIM.cy.ts
Labels: lgtm, approved, needs-ok-to-test

#3897 (feat RHOAIENG-21376) : Rewording for the hardware profile customization section
  frontend/src/concepts/hardwareProfiles/HardwareProfileCustomize.tsx
  frontend/src/pages/hardwareProfiles/manage/HardwareProfileVisibilitySection.tsx
  frontend/src/pages/modelServing/screens/global/EmptyModelServing.tsx
  frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
Labels: lgtm, approved

#3905 Model catalog/Model registry microcopy
  frontend/src/__tests__/cypress/cypress/pages/modelCatalog/registerCatalogModel.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelDetailsPage.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDeploy.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersions.cy.ts
  frontend/src/concepts/roleBinding/RoleBindingPermissionsTableRow.tsx
  frontend/src/pages/modelCatalog/screens/ModelCatalog.tsx
  frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx
  frontend/src/pages/modelCatalog/screens/ModelDetailsView.tsx
  frontend/src/pages/modelCatalog/screens/RegisterCatalogModel.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsHeaderActions.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionListView.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionsTableRow.tsx
  frontend/src/pages/modelRegistry/screens/RegisterModel/RegisterVersion.tsx
  frontend/src/pages/modelRegistry/screens/RegisteredModels/usePrefillDeployModalFromModelRegistry.ts
  frontend/src/pages/modelRegistry/screens/RegisteredModels/useProjectErrorForRegisteredModel.ts
  frontend/src/pages/modelRegistry/screens/__tests__/useProjectErrorForRegisteredModel.spec.ts
  frontend/src/pages/modelRegistrySettings/CreateModal.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ProjectSelector.tsx
Labels: lgtm, approved

#3920 Refactor to support multiple model catalog sources in one configmap
  frontend/src/__mocks__/mockModelCatalogConfigMap.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalog.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelDetailsPage.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/registerCatalogModel.cy.ts
  frontend/src/concepts/modelCatalog/const.ts
  frontend/src/concepts/modelCatalog/types.ts
  frontend/src/concepts/modelCatalog/useModelCatalogSources.ts
  manifests/rhoai/shared/apps/model-catalog/model-catalog-configmap.yaml
  manifests/rhoai/shared/apps/model-catalog/model-catalog-rbac.yaml
Labels: lgtm, approved

#3868 Add helperText property to FileField
  frontend/src/concepts/connectionTypes/fields/FileFormField.tsx
  frontend/src/concepts/connectionTypes/fields/__tests__/FileFormField.spec.tsx
  frontend/src/concepts/connectionTypes/types.ts
  manifests/common/connection-types/oci-v1.yaml
Labels: lgtm, approved

#3922 Update catalog models with licenses and timestamps
  manifests/rhoai/shared/apps/model-catalog/model-catalog-configmap.yaml
Labels: lgtm, approved

#3875 Feat(Rhoaieng 21255) ilab mircocopy ux rewording modal content
  frontend/src/__tests__/cypress/cypress/pages/modelRegistry/modelVersionDetails.ts
  frontend/src/pages/pipelines/global/modelCustomization/startRunModal/MissingConditionAlert.tsx
  frontend/src/pages/pipelines/global/modelCustomization/startRunModal/StartRunModal.tsx
Labels: lgtm, approved

#3887 InstructLab pipeline upload flow microcopy
  frontend/src/concepts/pipelines/content/ManageSamplePipelinesModal.tsx
  frontend/src/concepts/pipelines/content/configurePipelinesServer/InstructLabPipelineEnablement.tsx
  frontend/src/concepts/pipelines/content/configurePipelinesServer/SamplePipelineSettingsSection.tsx
  frontend/src/concepts/pipelines/content/import/ImportPipelineSplitButton.tsx
Labels: lgtm, approved

#3894 converted connection information alert to button
  frontend/src/concepts/pipelines/content/configurePipelinesServer/ObjectStorageSection.tsx
  frontend/src/pages/hardwareProfiles/nodeResource/NodeResourceForm.tsx
Labels: lgtm, approved

#3924 Quarantine Model Serving and resolve NIM quarantine issue
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelContributorCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/nim/testEnableNIM.cy.ts
Labels: lgtm, approved

#3918 fix: set disableNIMModelServing to false as required for GA (#3747)
  backend/src/utils/constants.ts
  docs/dashboard-config.md
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/concepts/areas/const.ts
  manifests/rhoai/shared/odhdashboardconfig/odhdashboardconfig.yaml
Labels: lgtm, approved, ok-to-test

#3898 Fix: Prevent API key from being removed when closing input early
  frontend/src/pages/exploreApplication/EnableModal.tsx
Labels: lgtm, approved, ok-to-test

#3903 Show ilab student/teacher/judge model indicators on models in model catalog
  frontend/src/__mocks__/mockModelCatalogConfigMap.ts
  frontend/src/__tests__/cypress/cypress/pages/modelCatalog/modelCatalog.ts
  frontend/src/__tests__/cypress/cypress/pages/modelCatalog/modelDetailsPage.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalog.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelDetailsPage.cy.ts
  frontend/src/pages/modelCatalog/__tests__/utils.spec.ts
  frontend/src/pages/modelCatalog/components/ModelCatalogCard.tsx
  frontend/src/pages/modelCatalog/components/ModelCatalogLabels.tsx
  frontend/src/pages/modelCatalog/const.ts
  frontend/src/pages/modelCatalog/routeUtils.ts
  frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx
  frontend/src/pages/modelCatalog/screens/ModelDetailsView.tsx
  frontend/src/pages/modelCatalog/screens/RegisterCatalogModel.tsx
  frontend/src/pages/modelCatalog/types.ts
  frontend/src/pages/modelCatalog/utils.ts
  frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx
  frontend/src/pages/modelRegistry/screens/utils.ts
Labels: lgtm, approved

#3917 Ilab fine tune page microcopy
  frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationForm.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationLandingPage.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationLandingPage.cy.ts
  frontend/src/components/GenericSidebar.tsx
  frontend/src/components/MarkdownView.scss
  frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx
  frontend/src/pages/pipelines/global/modelCustomization/FineTuneTaxonomySection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/HyperparameterSection/HyperparameterPageSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/ModelCustomizationForm.tsx
  frontend/src/pages/pipelines/global/modelCustomization/RunTypeSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/BaseModelSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/InlineEditText.tsx
  frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/PipelineDetailsSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/const.ts
  frontend/src/pages/pipelines/global/modelCustomization/fineTunedModelSection/FineTunedModelSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/landingPage/ModelCustomization.tsx
  frontend/src/pages/pipelines/global/modelCustomization/landingPage/ModelCustomizationDrawerContent.tsx
  frontend/src/pages/pipelines/global/modelCustomization/landingPage/PrerequisitesSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/teacherJudgeSection/JudgeModelSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/teacherJudgeSection/TeacherJudgeInputComponents.tsx
  frontend/src/pages/pipelines/global/modelCustomization/teacherJudgeSection/TeacherModelSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/TrainingHardwareProfileFormSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/TrainingHardwareSection.tsx
  frontend/src/routes/pipelines/modelCustomizationForm.ts
Labels: lgtm, approved

#3882 stashed home hint banner for hardware profiles
  frontend/src/__tests__/cypress/cypress/pages/home/home.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/home/home.cy.ts
  frontend/src/pages/home/HardwareProfilesHomeHint.tsx
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/HomeHint.tsx
  frontend/src/pages/home/LandingPageHomeHint.tsx
Labels: lgtm, approved

#3926 Update readmes and tasks for some 2.19 Granite models
  manifests/rhoai/shared/apps/model-catalog/model-catalog-configmap.yaml
Labels: lgtm, approved

#3907 OCI connections microcopy updates
  frontend/src/concepts/connectionTypes/ConnectionDetailsHelperText.tsx
  frontend/src/concepts/connectionTypes/ConnectionTypeDetailsHelperText.tsx
  frontend/src/concepts/connectionTypes/ConnectionTypeForm.tsx
  frontend/src/concepts/connectionTypes/ConnectionTypePreviewDrawer.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionOciAlert.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionOciPathField.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
  frontend/src/pages/projects/screens/detail/connections/ConnectionsList.tsx
  frontend/src/pages/projects/screens/detail/connections/ManageConnectionsModal.tsx
  frontend/src/pages/projects/screens/detail/connections/__tests__/ManageConnectionsModal.spec.tsx
  manifests/common/connection-types/oci-v1.yaml
Labels: lgtm, approved

#3916 Story/rhoaieng 20530
  frontend/src/__mocks__/mockIlabPipelineVersionParameters.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationForm.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts
  frontend/src/__tests__/cypress/cypress/types.ts
  frontend/src/components/ParamsDefaultFields.tsx
  frontend/src/components/ZodErrorFormHelperText.tsx
  frontend/src/concepts/hardwareProfiles/HardwareProfileFormSection.tsx
  frontend/src/concepts/hardwareProfiles/HardwareProfileSelect.tsx
  frontend/src/concepts/pipelines/apiHooks/usePipelineByName.ts
  frontend/src/concepts/pipelines/content/createRun/contentSections/ParamsSection/JsonInputParam.tsx
  frontend/src/concepts/pipelines/content/createRun/contentSections/ParamsSection/NumberInputParam.tsx
  frontend/src/concepts/pipelines/content/createRun/submitUtils.ts
  frontend/src/concepts/pipelines/content/createRun/utils.ts
  frontend/src/concepts/pipelines/content/modelCustomizationForm/hyperparameterFields/HyperparameterEvaluationField.tsx
  frontend/src/concepts/pipelines/content/modelCustomizationForm/hyperparameterFields/HyperparameterLongNumberField.tsx
  frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/__tests__/validationUtils.spec.ts
  frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/validationUtils.ts
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabDetails.tsx
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/SelectedNodeDetailsTab.tsx
  frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx
  frontend/src/pages/pipelines/global/modelCustomization/FineTunePageFooter.tsx
  frontend/src/pages/pipelines/global/modelCustomization/FineTuneTaxonomySection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/HyperparameterSection/HyperparameterFields.tsx
  frontend/src/pages/pipelines/global/modelCustomization/HyperparameterSection/HyperparameterFieldsUtils.tsx
  frontend/src/pages/pipelines/global/modelCustomization/HyperparameterSection/HyperparameterPageSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/ModelCustomizationForm.tsx
  frontend/src/pages/pipelines/global/modelCustomization/RunTypeSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/BaseModelSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/InlineEditText.tsx
  frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/PipelineDetailsSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/const.ts
  frontend/src/pages/pipelines/global/modelCustomization/fineTunedModelSection/FineTunedModelOciPathField.tsx
  frontend/src/pages/pipelines/global/modelCustomization/fineTunedModelSection/FineTunedModelSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/teacherJudgeSection/JudgeModelSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/teacherJudgeSection/TeacherJudgeInputComponents.tsx
  frontend/src/pages/pipelines/global/modelCustomization/teacherJudgeSection/TeacherModelSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/ContainerCustomSize.tsx
  frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/TrainingAcceleratorFormSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/TrainingHardwareProfileFormSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/TrainingHardwareSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/types.ts
  frontend/src/pages/pipelines/global/modelCustomization/useIlabPodSpecOptionsState.ts
  frontend/src/pages/pipelines/global/modelCustomization/utils.ts
  frontend/src/pages/projects/screens/spawner/storage/StorageClassSelect.tsx
Labels: lgtm, approved

#3921 Prevent overwriting changes to prefilled data in model catalog register form
  frontend/src/pages/modelCatalog/screens/RegisterCatalogModel.tsx
Labels: lgtm, approved

#3923 Feat/20552 mc style layout changes
  frontend/src/pages/modelCatalog/components/ModelCatalogCard.tsx
  frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx
  frontend/src/pages/modelCatalog/screens/ModelDetailsView.tsx
Labels: lgtm, approved

#3925 Cypress e2e - Hardware Profiles (Creating, Editing and Deleting)
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/hardwareProfiles/testHardwareProfiles.yaml
  frontend/src/__tests__/cypress/cypress/pages/hardwareProfile.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/hardwareProfiles/testHardwareProfiles.cy.ts
  frontend/src/__tests__/cypress/cypress/types.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/hardwareProfiles.ts
Labels: lgtm, approved

#3931 Upversion Dashboard
  frontend/.env
Labels: lgtm, approved

#3930 Releasing ODH 2.31.2
  frontend/.env
  manifests/odh/params.env
Labels: lgtm, approved

#3937 limit heading level within model card
  frontend/src/components/MarkdownView.tsx
  frontend/src/pages/modelCatalog/screens/ModelDetailsView.tsx
  frontend/src/utilities/markdown.ts
Labels: lgtm, approved

#3935 Fix Connection Create / Delete E2E test
  frontend/src/__tests__/cypress/cypress/pages/connections.ts
Labels: lgtm, approved

#3892 remove linting from unit test coverage command
  .github/workflows/test.yml
  backend/package.json
  frontend/package.json
Labels: lgtm, approved

#3933 Frontend vulnerabilities fixed
  frontend/package-lock.json
Labels: lgtm, approved

#3934 Backend Snyk vulnerabilities
  backend/package-lock.json
Labels: lgtm, approved

#3939 Remove disableKServeOCIModels in rest of repo
  backend/src/types.ts
  backend/src/utils/constants.ts
  docs/dashboard-config.md
  manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
Labels: lgtm, approved

#3946 Filter out OCI connections for model mesh
  frontend/src/__mocks__/mockConnectionType.ts
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDeploy.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
Labels: lgtm, approved

#3944 Cypress e2e - Model Serving Test Resiliency fix and update Quarantined tests
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataSciencePipelines/pipelines.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testMultiModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelContributorCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchNegativeTests.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/hardwareProfiles/testWorkbenchTolerations.cy.ts
  frontend/src/__tests__/cypress/cypress/utils/models.ts
Labels: lgtm, approved

#3943 Update architecture docs link
  docs/README.md
Labels: lgtm, approved

#3908 Add feature flag for project scoped items
  backend/src/types.ts
  backend/src/utils/constants.ts
  docs/dashboard-config.md
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/concepts/areas/const.ts
  frontend/src/concepts/areas/types.ts
  frontend/src/images/icons/GlobalIcon.ts
  frontend/src/k8sTypes.ts
  manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
Labels: lgtm, approved

#3951 Reactivate ODS-1218 'Verify That Usage Data Collection Can Be Set In Cluster Settings'
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/clusterSettings/testDataCollection.cy.ts
Labels: lgtm, approved

#3948 Filter out OCI connections for model mesh 2.32 cherry pick
  frontend/src/__mocks__/mockConnectionType.ts
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDeploy.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
Labels: lgtm, approved

#3867 Add OCI Deployment E2E Test
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/connectionTypes/testOOTBConnectionType.yaml
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/dataScienceProjects/testDeployOCIModel.yaml
  frontend/src/__tests__/cypress/cypress/pages/connections.ts
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testDeployOCIModel.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/connectionTypes/connectionTypes.cy.ts
  frontend/src/__tests__/cypress/cypress/types.ts
  frontend/src/__tests__/cypress/cypress/utils/dataLoader.ts
  frontend/src/__tests__/cypress/cypress/utils/testConfig.ts
  frontend/src/__tests__/cypress/test-variables.yml.example
Labels: lgtm, approved

#3960 cypress flake in pipelineRuns.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/runs/pipelineRuns.cy.ts
Labels: lgtm, approved

#3945 fix(RHOAIENG-21951):added fix for model customization cancel button redirection
  frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationForm.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts
  frontend/src/pages/pipelines/global/modelCustomization/FineTunePageFooter.tsx
Labels: lgtm, approved

#3936 removed text input from hardware profile migration modal
  frontend/src/pages/hardwareProfiles/migration/MigrationModal.tsx
Labels: lgtm, approved

#3957 Redirect the pipelineversion after import
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts
  frontend/src/concepts/pipelines/content/import/PipelineVersionImportModal.tsx
Labels: lgtm, approved

#3956 Fix page loading error in Jupyter Notebook Admin
  backend/src/utils/adminUtils.ts
Labels: lgtm, approved

#3846 Data connections clean up
  frontend/src/__mocks__/mockDataConnection.ts
  frontend/src/__mocks__/mockStartNotebookData.ts
  frontend/src/__tests__/cypress/cypress/pages/modelRegistry/registerModelPage.ts
  frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesGlobal.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/connections/testConnectionCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts
  frontend/src/concepts/pipelines/content/configurePipelinesServer/ConfigurePipelinesServerModal.tsx
  frontend/src/concepts/pipelines/content/configurePipelinesServer/ObjectStorageSection.tsx
  frontend/src/concepts/pipelines/content/configurePipelinesServer/PipelineDropdown.tsx
  frontend/src/pages/modelRegistry/screens/RegisterModel/ConnectionDropdown.tsx
  frontend/src/pages/modelRegistry/screens/components/DeployRegisteredModelModal.tsx
  frontend/src/pages/modelServing/ModelServingContext.tsx
  frontend/src/pages/modelServing/screens/global/ServeModelButton.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionExistingField.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionSection.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/__tests__/ManageInferenceServiceModal.spec.tsx
  frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTable.tsx
  frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTable.tsx
  frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx
  frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx
  frontend/src/pages/modelServing/screens/projects/__tests__/utils.spec.ts
  frontend/src/pages/modelServing/screens/projects/utils.ts
  frontend/src/pages/modelServing/screens/types.ts
  frontend/src/pages/projects/ProjectDetailsContext.tsx
  frontend/src/pages/projects/screens/detail/connections/useConnections.ts
  frontend/src/pages/projects/screens/detail/const.ts
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsList.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTable.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTableRow.tsx
  frontend/src/pages/projects/screens/detail/data-connections/DeleteDataConnectionModal.tsx
  frontend/src/pages/projects/screens/detail/data-connections/ManageDataConnectionModal.tsx
  frontend/src/pages/projects/screens/detail/data-connections/__tests__/utils.spec.ts
  frontend/src/pages/projects/screens/detail/data-connections/connectionRenderers.tsx
  frontend/src/pages/projects/screens/detail/data-connections/data.ts
  frontend/src/pages/projects/screens/detail/data-connections/useDataConnections.ts
  frontend/src/pages/projects/screens/detail/data-connections/useSelectedNotebooks.ts
  frontend/src/pages/projects/screens/detail/data-connections/utils.ts
  frontend/src/pages/projects/screens/detail/notebooks/NotebookList.tsx
  frontend/src/pages/projects/screens/detail/overview/serverModels/AddModelFooter.tsx
  frontend/src/pages/projects/screens/detail/overview/trainModels/NotebooksCard.tsx
  frontend/src/pages/projects/screens/detail/types.ts
  frontend/src/pages/projects/screens/projects/DeleteProjectModal.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/__tests__/SpawnerFooter.spec.tsx
  frontend/src/pages/projects/screens/spawner/__tests__/spawnerUtils.spec.ts
  frontend/src/pages/projects/screens/spawner/dataConnection/DataConnectionField.tsx
  frontend/src/pages/projects/screens/spawner/dataConnection/ExistingDataConnectionField.tsx
  frontend/src/pages/projects/screens/spawner/dataConnection/useNotebookDataConnection.ts
  frontend/src/pages/projects/screens/spawner/service.ts
  frontend/src/pages/projects/screens/spawner/spawnerUtils.ts
  frontend/src/pages/projects/types.ts
Labels: lgtm, approved

#3949 fix(21844): only show lab-tune button if lab-base tag
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelDetailsPage.cy.ts
  frontend/src/pages/modelCatalog/__tests__/utils.spec.ts
  frontend/src/pages/modelCatalog/components/ModelCatalogLabels.tsx
  frontend/src/pages/modelCatalog/const.ts
  frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx
  frontend/src/pages/modelCatalog/utils.ts
Labels: lgtm, approved

#3952 update test.yml with cache lookup-only
  .github/workflows/test.yml
Labels: lgtm, approved

#3962 Revert a small cypress change from testConnectionCreation
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/connections/testConnectionCreation.cy.ts
Labels: lgtm, approved

#3963 Add oci to connection types Kustomization
  manifests/common/connection-types/kustomization.yaml
Labels: lgtm, approved

#3964 Add oci to connection types Kustomization 2.32.0-fixes cherry pick
  manifests/common/connection-types/kustomization.yaml
Labels: lgtm, approved

#3913 Add sections for multiple sources to the model catalog cards page
  frontend/src/__mocks__/mockCatalogModel.ts
  frontend/src/__mocks__/mockModelCatalogSource.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalog.cy.ts
  frontend/src/concepts/modelCatalog/useModelCatalogSources.ts
  frontend/src/pages/modelCatalog/components/ModelCatalogCards.tsx
Labels: lgtm, approved

#3929 fix: resolve model selection issues for models with complex version formats
  frontend/src/pages/modelServing/screens/projects/NIMServiceModal/NIMModelListSection.tsx
Labels: lgtm, approved, ok-to-test

#3950 Storage class option
  frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx
  frontend/src/pages/modelServing/screens/projects/__tests__/utils.spec.ts
  frontend/src/pages/modelServing/screens/projects/utils.ts
Labels: lgtm, approved, ok-to-test

#3940 Fix Cypress Click Issue - Projects Tabs
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/clusterStorage/testClusterStorageCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/connections/testConnectionCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testMultiModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelContributorCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testProjectAdminPermissions.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testProjectContributorPermissions.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchControlSuite.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchEditing.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchNegativeTests.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchStatus.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchVariables.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/workbenches.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/hardwareProfiles/testWorkbenchTolerations.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/storageClasses/clusterStorage.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/topology/pipelinesTopology.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/projectDetails.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/workbench.cy.ts
  frontend/src/pages/projects/components/GenericHorizontalBar.tsx
  frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
  frontend/src/utilities/useQueryParams.tsx
Labels: lgtm, approved

#3967 Cypress e2e - Refactored Workbench Tolerations test to use Hardware Profiles
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/dataScienceProjects/testWorkbenchTolerations.yaml
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/hardwareProfiles/testWorkbenchTolerations.yaml
  frontend/src/__tests__/cypress/cypress/fixtures/resources/hardwareProfile/workbench_tolerations.yaml
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/hardwareProfiles/testWorkbenchTolerations.cy.ts
  frontend/src/__tests__/cypress/cypress/types.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/hardwareProfiles.ts
Labels: lgtm, approved

#3959 Create mocked cypress tests migration cases for hardware profiles
  frontend/src/__tests__/cypress/cypress/pages/components/MigrationModal.ts
  frontend/src/__tests__/cypress/cypress/pages/hardwareProfile.ts
  frontend/src/__tests__/cypress/cypress/pages/notebookImageSettings.ts
  frontend/src/__tests__/cypress/cypress/pages/notebookServer.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/applications/notebookServer.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/legacyHardwareProfiles.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/notebookImageSettings/notebookImageSettings.cy.ts
  frontend/src/pages/BYONImages/BYONImageModal/HardwareProfileIdentifierMultiselect.tsx
  frontend/src/pages/hardwareProfiles/HardwareProfiles.tsx
  frontend/src/pages/hardwareProfiles/HardwareProfilesTableRow.tsx
  frontend/src/pages/hardwareProfiles/manage/ManageHardwareProfileFooter.tsx
Labels: lgtm, approved

#3919 Update OCI Model URI onChange to not to reset the connection type
  frontend/src/__tests__/cypress/cypress/pages/modelRegistry/modelVersionDeployModal.ts
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDeploy.cy.ts
  frontend/src/concepts/modelRegistry/apiHooks/__tests__/usePrefillDeployModalFromModelRegistry.spec.ts
  frontend/src/concepts/modelRegistry/utils.ts
  frontend/src/pages/modelRegistry/screens/RegisteredModels/__tests__/usePrefillDeployModalFromModelRegistry.spec.ts
  frontend/src/pages/modelRegistry/screens/RegisteredModels/usePrefillDeployModalFromModelRegistry.ts
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ProjectSelector.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/__tests__/ConnectionSection.spec.tsx
  frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
  frontend/src/pages/modelServing/screens/types.ts
Labels: lgtm, approved

#3971 refractor clusterStorageModal
  frontend/src/pages/projects/screens/detail/storage/ClusterStorageModal.tsx
  frontend/src/pages/projects/screens/detail/storage/ClusterStorageTable.tsx
  frontend/src/pages/projects/screens/detail/storage/__tests__/useClusterStorageFormState.spec.ts
  frontend/src/pages/projects/screens/detail/storage/submitUtils.ts
  frontend/src/pages/projects/screens/detail/storage/useClusterStorageFormState.ts
  frontend/src/pages/projects/screens/detail/storage/utils.ts
Labels: lgtm, approved

#3987 Add Mixtral and Prometheus models to Red Hat source in model catalog configmap
  manifests/rhoai/shared/apps/model-catalog/model-catalog-configmap.yaml
Labels: lgtm, approved

#3975 Cleanup additional references to `Gi` on Hardware Profiles
  frontend/src/__tests__/cypress/cypress/tests/mocked/applications/notebookServer.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/workbenchHardwareProfiles.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts
  frontend/src/concepts/hardwareProfiles/HardwareProfileDetailsPopover.tsx
  frontend/src/concepts/hardwareProfiles/HardwareProfileSelect.tsx
Labels: lgtm, approved

#3988 Standardize the behavior of data-dependent buttons on the spawner page
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/workbench.cy.ts
  frontend/src/components/ExtendedButton.tsx
  frontend/src/components/__tests__/ExtendedButton.test.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/connections/ConnectionsFormSection.tsx
  frontend/src/pages/projects/screens/spawner/connections/__tests__/ConnectionsFormSection.spec.tsx
Labels: lgtm, approved

#3985 Adding associated events to workbench status modal
  frontend/src/concepts/__tests__/StartNotebookModal.spec.tsx
  frontend/src/concepts/notebooks/StartNotebookModal.tsx
  frontend/src/types.ts
  frontend/src/utilities/notebookControllerUtils.ts
Labels: lgtm, approved

#3994 Fixing light/dark toggle icon colors
  frontend/src/app/HeaderTools.tsx
Labels: lgtm, approved

#3973 Fix for when modelRegistryNamespace is undefined and no DSC status in response
  frontend/src/__mocks__/mockDscStatus.ts
  frontend/src/__tests__/cypress/cypress/support/e2e.ts
  frontend/src/api/useRulesReview.ts
  frontend/src/concepts/areas/AreaContext.tsx
  frontend/src/concepts/areas/useFetchDscStatus.ts
  frontend/src/concepts/modelRegistry/apiHooks/useModelRegistryServices.ts
  frontend/src/concepts/modelRegistry/context/ModelRegistrySelectorContext.tsx
  frontend/src/concepts/modelRegistry/context/useModelRegistryNamespaceCR.ts
  frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx
  frontend/src/pages/modelRegistry/ModelRegistryCoreLoader.tsx
  frontend/src/pages/modelRegistrySettings/CreateModal.tsx
  frontend/src/pages/modelRegistrySettings/ModelRegistriesPermissions.tsx
  frontend/src/pages/modelRegistrySettings/ModelRegistrySettings.tsx
Labels: lgtm, approved

#3993 Removes the unused /api/group-config endpoint
  backend/src/routes/api/groups-config/groupsConfigUtil.ts
  backend/src/routes/api/groups-config/index.ts
  backend/src/types.ts
  backend/src/utils/adminUtils.ts
  backend/src/utils/groupsUtils.ts
  frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/userManagement/userManagement.cy.ts
  frontend/src/concepts/userConfigs/__tests__/useWatchGroups.spec.tsx
  frontend/src/concepts/userConfigs/useWatchGroups.tsx
  frontend/src/concepts/userConfigs/utils.ts
  frontend/src/services/groupSettingsService.ts
  frontend/src/utilities/NavData.tsx
Labels: lgtm, approved

#3991 Fix issue on run form when optional string parameter does not have a default value
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/runs/pipelineCreateRuns.cy.ts
  frontend/src/components/ParamsDefaultFields.tsx
Labels: lgtm, approved
