Repository opendatahub-io/odh-dashboard, pull requests merged in 2025-06, with the labels that each got.

#4291 Cypress e2e: add namespace to oc modelserving calls
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testDeployOCIModel.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testMultiModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelContributorCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/hardwareProfiles/testModelServingTolerations.cy.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/modelServing.ts
Labels: lgtm, approved

#4293 set tsconfig allowImportingTsExtensions: true
  frontend/packages/tsconfig/tsconfig.json
Labels: lgtm, approved

#4292 Quarantine testManifestLinks tests
  frontend/src/__tests__/cypress/cypress/tests/e2e/dashboardNavigation/testManifestLinks.cy.ts
Labels: lgtm, approved

#4280 Remove provider specification from Jupyter app manifest
  manifests/common/apps/jupyter/jupyter-app.yaml
Labels: lgtm, approved

#4298 Fix glob pattern linting os discrepancies
  frontend/.eslintignore
  frontend/.eslintrc.goal.js
  frontend/.eslintrc.js
  frontend/packages/tsconfig/tsconfig.json
Labels: lgtm, approved

#4294 2.19.1 cherry pick: Fix http prefix removal for OCI path (#4150)
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionOciPathField.tsx
Labels: lgtm, approved

#4301 accessMode columns
  frontend/src/pages/projects/screens/detail/storage/AccessModeLabel.tsx
  frontend/src/pages/projects/screens/detail/storage/StorageTableRow.tsx
  frontend/src/pages/projects/screens/detail/storage/data.ts
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/storage/ClusterStorageTable.tsx
  frontend/src/pages/projects/screens/spawner/storage/constants.ts
  frontend/src/pages/projects/types.ts
Labels: lgtm, approved

#4304 Quarantine test in testAdminClusterSettings
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/clusterSettings/testAdminClusterSettings.cy.ts
Labels: lgtm, approved

#4282 kserve deployment status on models table row
  frontend/packages/kserve/src/api.ts
  frontend/packages/kserve/src/deploymentStatus.ts
  frontend/packages/kserve/src/deployments.ts
  frontend/packages/modelServing/extension-points/index.ts
  frontend/packages/modelServing/src/components/deleteModal/DeleteModelServingModal.tsx
  frontend/packages/modelServing/src/components/deployments/DeploymentsTable.tsx
  frontend/packages/modelServing/src/components/deployments/DeploymentsTableRow.tsx
  frontend/packages/modelServing/src/components/deployments/__tests__/deploymentsTableRow.spec.tsx
  frontend/packages/modelServing/src/components/projectDetails/ModelsProjectDetailsView.tsx
  frontend/packages/modelServing/src/concepts/deploymentUtils.ts
  frontend/packages/modelServing/src/concepts/extensionUtils.ts
  frontend/src/__tests__/cypress/cypress/pages/projects.ts
  frontend/src/concepts/modelServing/ModelStatusIcon.tsx
  frontend/src/concepts/modelServingKServe/__tests__/kserveStatusUtils.spec.ts
  frontend/src/concepts/modelServingKServe/kserveStatusUtils.ts
  frontend/src/pages/modelServing/screens/global/InferenceServiceStatus.tsx
  frontend/src/pages/modelServing/screens/global/useModelStatus.ts
  frontend/src/pages/modelServing/screens/global/useRouteForInferenceService.ts
  frontend/src/pages/modelServing/screens/global/utils.ts
  frontend/src/pages/modelServing/screens/projects/useModelDeploymentNotification.ts
  frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelsGallery.tsx
Labels: lgtm, approved

#4260 Fix duplicate name issue with workbench images
  frontend/src/__mocks__/mockNotebookK8sResource.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/workbench.cy.ts
  frontend/src/api/k8s/notebooks.ts
  frontend/src/concepts/hardwareProfiles/HardwareProfileSelect.tsx
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTemplateSection.tsx
  frontend/src/pages/notebookController/screens/server/AcceleratorProfileSelectField.tsx
  frontend/src/pages/projects/screens/detail/notebooks/NotebookImageDisplayName.tsx
  frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx
  frontend/src/pages/projects/screens/detail/notebooks/useNotebookImage.ts
  frontend/src/pages/projects/screens/detail/notebooks/useNotebookImageData.ts
  frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageSelectorField.tsx
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageStreamSelector.tsx
Labels: lgtm, approved

#4289 Storage class edit modal, access mode configuration
  frontend/src/__tests__/cypress/cypress/pages/storageClasses.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/storageClasses/storageClasses.cy.ts
  frontend/src/pages/storageClasses/StorageClassEditModal.tsx
  frontend/src/pages/storageClasses/constants.ts
Labels: lgtm, approved

#4281 RHOAIENG-15191: Deprecate/Remove the DSPA RBAC setting from Dashboard
  frontend/src/api/k8s/__tests__/notebooks.spec.ts
  frontend/src/api/k8s/notebooks.ts
  frontend/src/concepts/pipelines/elyra/utils.ts
  frontend/src/pages/projects/screens/spawner/__tests__/SpawnerFooter.spec.tsx
Labels: lgtm, approved

#4279 Add version for serving runtime dropdown
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testDeployOCIModel.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testMultiModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelContributorCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/hardwareProfiles/testModelServingTolerations.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDeploy.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
  frontend/src/components/searchSelector/ProjectScopedToggleContent.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTemplateSection.tsx
Labels: lgtm, approved

#4299 Edit pvc modal
  frontend/src/__mocks__/mockPVCK8sResource.ts
  frontend/src/__mocks__/mockStorageClasses.ts
  frontend/src/__tests__/cypress/cypress/pages/clusterStorage.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/clusterStorage.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/storageClasses/storageClasses.cy.ts
  frontend/src/__tests__/cypress/cypress/types.ts
  frontend/src/api/k8s/__tests__/pvcs.spec.ts
  frontend/src/api/k8s/pvcs.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx
  frontend/src/pages/modelServing/screens/projects/__tests__/utils.spec.ts
  frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/TrainingStorageClassSelect.tsx
  frontend/src/pages/projects/screens/detail/storage/AccessModeFullName.tsx
  frontend/src/pages/projects/screens/detail/storage/BaseStorageModal.tsx
  frontend/src/pages/projects/screens/detail/storage/StorageTableRow.tsx
  frontend/src/pages/projects/screens/detail/storage/data.ts
  frontend/src/pages/projects/screens/spawner/storage/AccessModeField.tsx
  frontend/src/pages/projects/screens/spawner/storage/AccessModeLabel.tsx
  frontend/src/pages/projects/screens/spawner/storage/AccessModeRadio.tsx
  frontend/src/pages/projects/screens/spawner/storage/ClusterStorageTable.tsx
  frontend/src/pages/projects/screens/spawner/storage/CreateNewStorageSection.tsx
  frontend/src/pages/projects/screens/spawner/storage/StorageClassSelect.tsx
  frontend/src/pages/projects/screens/spawner/storage/__tests__/utils.spec.ts
  frontend/src/pages/projects/screens/spawner/storage/constants.ts
  frontend/src/pages/projects/screens/spawner/storage/getAccessModePopover.tsx
  frontend/src/pages/projects/screens/spawner/storage/useGetStorageClassConfig.ts
  frontend/src/pages/projects/screens/spawner/storage/utils.ts
  frontend/src/pages/projects/types.ts
  frontend/src/pages/storageClasses/StorageClassesTableRow.tsx
  frontend/src/pages/storageClasses/utils.ts
Labels: lgtm, approved

#4317 fix: cluster storage testing issue
  frontend/src/__tests__/cypress/cypress/tests/e2e/storageClasses/clusterStorage.cy.ts
Labels: lgtm, approved

#4311 Deprecate v1 version of AcceleratorProfile CRD
  manifests/common/crd/acceleratorprofiles.opendatahub.io.crd.yaml
Labels: lgtm, approved

#4286 Content issues related to "notebooks" -> "workbenches"
  frontend/src/__mocks__/mockQuickStarts.ts
  frontend/src/__tests__/cypress/cypress/pages/resources.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/resources/resources.cy.ts
  frontend/src/app/QuickStarts.tsx
  frontend/src/components/OdhDocCard.tsx
  frontend/src/concepts/docResources/docUtils.ts
  frontend/src/pages/BYONImages/BYONImageModal/ImageLocationField.tsx
  frontend/src/types.ts
  manifests/common/apps/jupyter/create-jupyter-notebook-quickstart.yaml
  manifests/rhoai/shared/apps/aikit/oneapi-aikit-notebook-quickstart.yaml
  manifests/rhoai/shared/apps/openvino/openvino-inference-notebook.yaml
  manifests/rhoai/shared/apps/pachyderm/pachyderm-beginner-tutorial-notebook.yaml
Labels: lgtm, approved

#4320 made microcopy changes to storage classes
  frontend/src/pages/projects/screens/spawner/storage/AccessModeRadio.tsx
  frontend/src/pages/projects/screens/spawner/storage/getAccessModePopover.tsx
  frontend/src/pages/storageClasses/constants.tsx
Labels: lgtm, approved

#4305 Access mode support for existing PVC attachment modal in workbench
  frontend/src/__mocks__/mockPVCK8sResource.ts
  frontend/src/__tests__/cypress/cypress/pages/workbench.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/workbench.cy.ts
  frontend/src/components/TypeaheadSelect.tsx
  frontend/src/pages/projects/screens/detail/storage/StorageTableRow.tsx
  frontend/src/pages/projects/screens/detail/storage/data.ts
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/storage/AddExistingStorageField.tsx
  frontend/src/pages/projects/utils.ts
Labels: lgtm, approved

#4307 Add new authorized tag creators
  .github/workflows/authorized-tag-creators.txt
Labels: lgtm, approved

#4313 Cypress logs Improvements: timestamp and log level
  frontend/src/__tests__/cypress/cypress.config.ts
  frontend/src/__tests__/cypress/cypress/utils/logger.ts
Labels: lgtm, approved

#4302 Added character limit to name and description field in the workbench images
  frontend/src/__tests__/cypress/cypress/tests/mocked/notebookImageSettings/workbenchImageCharacterLimits.cy.ts
  frontend/src/concepts/k8s/K8sNameDescriptionField/K8sNameDescriptionField.tsx
  frontend/src/pages/BYONImages/BYONImageModal/ManageBYONImageModal.tsx
Labels: lgtm, approved, ok-to-test

#4335 Enable the OCI e2e test
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testDeployOCIModel.cy.ts
Labels: do-not-merge/hold

#4236 Handle duplicate names in different namespaces for project-scoped accelerator profiles
  frontend/src/__mocks__/mockServingRuntimeK8sResource.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
  frontend/src/api/k8s/notebooks.ts
  frontend/src/api/k8s/servingRuntimes.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelServing/screens/projects/useServingAcceleratorProfileFormState.ts
  frontend/src/pages/notebookController/screens/server/AcceleratorProfileSelectField.tsx
  frontend/src/pages/projects/screens/detail/notebooks/useNotebookAcceleratorProfileFormState.ts
  frontend/src/utilities/useAcceleratorProfileFormState.ts
  frontend/src/utilities/useReadAcceleratorState.ts
Labels: lgtm, approved

#4245 removed elyra secret usage in pipelines context
  frontend/src/concepts/pipelines/context/PipelinesContext.tsx
  frontend/src/concepts/pipelines/context/useManageElyraSecret.ts
Labels: lgtm, approved

#4341 [v2.32.0-fixes]Update k8sMergePatchResource, replace undefined value with null to make it removable
  frontend/src/api/k8s/__tests__/notebooks.spec.ts
  frontend/src/api/k8s/notebooks.ts
  frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
Labels: lgtm, approved

#4329 Workbench images: change recommended to latest
  frontend/src/pages/notebookController/screens/server/ImageVersions.tsx
Labels: lgtm, approved

#4354 Quarantine workbenches tests - RHOAIENG-27515
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchStatus.cy.ts
Labels: lgtm, approved

#4256 Chat integration with BE
  backend/package-lock.json
  backend/package.json
  backend/src/routes/api/llama-stack/index.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/projectDetails.cy.ts
  frontend/src/images/UI_icon-Red_Hat-Chatbot-Avatar.svg
  frontend/src/images/UI_icon-Red_Hat-Patternfly-Avatar.jpg
  frontend/src/pages/projects/screens/detail/chatbot/RagChatbot.tsx
  frontend/src/pages/projects/screens/detail/chatbot/RagChatbotMessagesList.tsx
  frontend/src/pages/projects/screens/detail/chatbot/RagChatbotShareModal.tsx
  frontend/src/services/llamaStackService.ts
  frontend/src/utilities/useFetchLlamaModels.ts
Labels: lgtm, approved

#4326 Add tooltips to create schedule run form
  frontend/src/concepts/pipelines/content/createRun/contentSections/MaxConcurrencyField.tsx
  frontend/src/concepts/pipelines/content/createRun/contentSections/TriggerTypeField.tsx
Labels: lgtm, approved

#4265 Migrate /images GET endpoint to frontend
  frontend/src/__mocks__/mockImageStreamK8sResource.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/applications/administration.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/applications/notebookServer.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/notebookImageSettings/notebookImageSettings.cy.ts
  frontend/src/api/index.ts
  frontend/src/api/k8s/__tests__/imageStreams.spec.ts
  frontend/src/api/k8s/imageStreams.ts
  frontend/src/concepts/pipelines/elyra/ElyraInvalidVersionAlerts.tsx
  frontend/src/k8sTypes.ts
  frontend/src/pages/BYONImages/BYONImages.tsx
  frontend/src/pages/BYONImages/BYONImagesTable.tsx
  frontend/src/pages/BYONImages/BYONImagesToolbar.tsx
  frontend/src/pages/BYONImages/EmptyBYONImages.tsx
  frontend/src/pages/BYONImages/ImportBYONImageButton.tsx
  frontend/src/pages/notebookController/screens/server/NotebookServerDetails.tsx
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/pages/projects/screens/detail/notebooks/useNotebookImageData.ts
  frontend/src/pages/projects/screens/spawner/__tests__/useImageStreams.spec.ts
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageSelectorField.tsx
  frontend/src/pages/projects/screens/spawner/useImageStreams.ts
  frontend/src/services/imagesService.ts
  frontend/src/types.ts
  frontend/src/utilities/__tests__/imageStreamUtils.spec.ts
  frontend/src/utilities/imageStreamUtils.ts
  frontend/src/utilities/useImageStreams.ts
  frontend/src/utilities/useWatchBYONImages.ts
  frontend/src/utilities/useWatchImages.tsx
Labels: lgtm, approved

#4358 Cypress e2e Test - Verify that models and versions can be archived and restored via model registry
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/modelRegistry/testRegisterModel.yaml
  frontend/src/__tests__/cypress/cypress/tests/e2e/modelRegistry/testArchiveModels.cy.ts
  frontend/src/__tests__/cypress/cypress/types.ts
Labels: lgtm, approved

#4351 RHOAIENG-25719: Deleting Memory or CPU from a Hardware Profile, disables the Update button
  frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/manageHardwareProfiles.cy.ts
  frontend/src/pages/hardwareProfiles/manage/__tests__/validationUtils.spec.ts
  frontend/src/pages/hardwareProfiles/manage/validationUtils.ts
Labels: lgtm, approved

#4347 Disable kueue feature flag
  backend/src/types.ts
  backend/src/utils/constants.ts
  docs/dashboard-config.md
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/concepts/areas/const.ts
  frontend/src/concepts/areas/types.ts
  frontend/src/k8sTypes.ts
  manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
Labels: lgtm, approved

#4356 Add stop/start toggle to models
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/pages/projects.ts
  frontend/src/__tests__/cypress/cypress/pages/workbench.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchControlSuite.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/hardwareProfiles/testWorkbenchTolerations.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/workbench.cy.ts
  frontend/src/api/k8s/inferenceServices.ts
  frontend/src/components/StateActionToggle.tsx
  frontend/src/pages/modelServing/__tests__/utils.spec.ts
  frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx
  frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTableRow.tsx
  frontend/src/pages/modelServing/screens/types.ts
  frontend/src/pages/modelServing/utils.ts
  frontend/src/pages/projects/notebook/NotebookStateAction.tsx
  frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx
  frontend/src/pages/projects/screens/projects/ProjectTableRowNotebookTableRow.tsx
Labels: lgtm, approved

#4361 Fix/unit conversion
  frontend/src/pages/hardwareProfiles/__tests__/utils.spec.ts
  frontend/src/utilities/__tests__/valueUnits.spec.ts
  frontend/src/utilities/valueUnits.ts
Labels: lgtm, approved, ok-to-test

#4371 Revert PR#4365
  OWNERS
  OWNERS_ALIASES
  frontend/packages/kserve/OWNERS
  frontend/packages/model-registry/OWNERS
  frontend/packages/modelServing/OWNERS
  frontend/packages/plugin-core/OWNERS
  frontend/packages/template/OWNERS
  frontend/packages/tsconfig/OWNERS
  frontend/src/api/modelRegistry/OWNERS
  frontend/src/api/pipelines/OWNERS
  frontend/src/api/trustyai/OWNERS
  frontend/src/concepts/connectionTypes/OWNERS
  frontend/src/concepts/hardwareProfiles/OWNERS
  frontend/src/concepts/modelRegistry/OWNERS
  frontend/src/concepts/modelRegistrySettings/OWNERS
  frontend/src/concepts/modelServing/OWNERS
  frontend/src/concepts/modelServingKServe/OWNERS
  frontend/src/concepts/notebooks/OWNERS
  frontend/src/concepts/pipelines/OWNERS
  frontend/src/concepts/topology/OWNERS
  frontend/src/concepts/trustyai/OWNERS
  frontend/src/pages/BYONImages/OWNERS
  frontend/src/pages/acceleratorProfiles/OWNERS
  frontend/src/pages/connectionTypes/OWNERS
  frontend/src/pages/hardwareProfiles/OWNERS
  frontend/src/pages/home/modelCatalog/OWNERS
  frontend/src/pages/modelCatalog/OWNERS
  frontend/src/pages/modelRegistry/OWNERS
  frontend/src/pages/modelRegistrySettings/OWNERS
  frontend/src/pages/modelServing/OWNERS
  frontend/src/pages/notebookController/OWNERS
  frontend/src/pages/pipelines/OWNERS
  frontend/src/plugins/OWNERS
  frontend/src/routes/modelCatalog/OWNERS
  frontend/src/routes/modelRegistry/OWNERS
  frontend/src/routes/pipelines/OWNERS
Labels: lgtm, approved

#4374 Fix testManifestLinks.cy.ts and urlValidator.ts retry logic
  frontend/src/__tests__/cypress/cypress.config.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dashboardNavigation/testManifestLinks.cy.ts
  frontend/src/__tests__/cypress/cypress/utils/urlExtractor.ts
  frontend/src/__tests__/cypress/cypress/utils/urlValidator.ts
Labels: lgtm, approved

#4376 Fix import error downstream
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved

#4377 Add stale workflow
  .github/workflows/stale.yml
Labels: lgtm, approved

#4330 Global Models Page No Models Component Refactor
  frontend/packages/modelServing/extensions.ts
  frontend/packages/modelServing/src/GlobalModelsPage.tsx
  frontend/packages/modelServing/src/ModelServingGlobalPlugin.tsx
  frontend/packages/modelServing/src/components/deploy/DeployButton.tsx
  frontend/packages/modelServing/src/components/global/GlobalDeploymentsTable.tsx
  frontend/packages/modelServing/src/components/global/GlobalDeploymentsView.tsx
  frontend/packages/modelServing/src/components/global/GlobalNoModelsView.tsx
  frontend/packages/modelServing/src/components/global/ModelServingProjectSelection.tsx
Labels: lgtm, approved

#4397 Added character limit for create project fields in data science project
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testProjectCreation.cy.ts
  frontend/src/pages/projects/screens/projects/ManageProjectModal.tsx
Labels: lgtm, approved, area/quality

#4327 Fix ODH Dashboard release notes and PR creation
  .github/workflows/release-odh-dashboard.yml
Labels: lgtm, approved

#4373 Update model to show string status
  frontend/packages/modelServing/src/components/deployments/__tests__/deploymentsTableRow.spec.tsx
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
  frontend/src/concepts/modelServing/ModelStatusIcon.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceStatus.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx
  frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelCard.tsx
Labels: lgtm, approved, area/quality

#4405 remove artifact of previous owners effort
  frontend/src/__tests__/cypress/OWNERS
Labels: lgtm, approved, area/quality

#4406 fix: e2e model serving tests tooltip issues
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
Labels: lgtm, approved, area/quality

#4410 Quarantine testResourcesFilters.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/learningResources/testResourcesfilters.cy.ts
Labels: lgtm, approved

#4401 changed labels to v1beta1
  backend/src/routes/api/modelRegistries/modelRegistryUtils.ts
  frontend/src/__tests__/cypress/cypress/fixtures/resources/yaml/model_registry.yaml
  frontend/src/api/models/odh.ts
Labels: lgtm, approved, area/quality

#4213 add cursor rule for jira creation
  .cursor/rules/jira-creation.mdc
Labels: lgtm, approved

#4314 Pipeline creation feedback
  frontend/src/api/k8s/events.ts
  frontend/src/concepts/dashboard/ModalStyles.scss
  frontend/src/concepts/k8s/EventLog/EventLog.tsx
  frontend/src/concepts/notebooks/StartNotebookModal.tsx
  frontend/src/concepts/pipelines/EnsureAPIAvailability.scss
  frontend/src/concepts/pipelines/EnsureAPIAvailability.tsx
  frontend/src/concepts/pipelines/content/PipelineComponentStatusIcon.tsx
  frontend/src/concepts/pipelines/content/StartingStatusModal.tsx
  frontend/src/concepts/pipelines/content/__tests__/StartingStatusModal.spec.tsx
  frontend/src/concepts/pipelines/content/__tests__/utils.spec.tsx
  frontend/src/concepts/pipelines/content/utils.tsx
  frontend/src/concepts/pipelines/context/PipelinesContext.tsx
  frontend/src/concepts/pipelines/context/usePipelineEvents.ts
  frontend/src/concepts/pipelines/context/usePipelineNamespaceCR.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/pipelines/global/pipelines/GlobalPipelines.tsx
  frontend/src/utilities/time.ts
Labels: lgtm, approved

#4414 Deployed models section refactor
  frontend/packages/modelServing/src/ServeModelsSection.tsx
  frontend/packages/modelServing/src/components/overview/DeployedModelsSection.tsx
Labels: lgtm, approved

#4418 Revert "Quarantine model serving tests rhoaieng 28128"
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testDeployOCIModel.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testMultiModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelContributorCreation.cy.ts
Labels: lgtm, approved

#4419 Fix token issue when ISVC and SR are different names (#4209)
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx
  frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTable.tsx
  frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTokensTable.tsx
  frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx
  frontend/src/pages/modelServing/utils.ts
  frontend/src/pages/projects/ProjectDetailsContext.tsx
Labels: lgtm, approved

#4423 Update MR yaml for OAuth-proxy
  frontend/src/__tests__/cypress/cypress/fixtures/resources/yaml/model_registry.yaml
Labels: lgtm, approved

#4416 Microcopy updates for stop/start model
  frontend/packages/modelServing/src/components/deployments/__tests__/deploymentsTableRow.spec.tsx
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
  frontend/src/concepts/modelServing/ModelStatusIcon.tsx
  frontend/src/pages/modelServing/ModelServingStopModal.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx
Labels: lgtm, approved

#4412 Enabling feature flag for LMEval
  backend/src/types.ts
  backend/src/utils/constants.ts
  frontend/src/concepts/areas/const.ts
  manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
Labels: lgtm, approved

#4424 update upstream MR to fix errors when using extensions in MR
  frontend/config/moduleFederation.js
  frontend/package-lock.json
  frontend/package.json
  frontend/packages/model-registry/tsconfig.json
  frontend/packages/model-registry/upstream/frontend/config/moduleFederation.js
  frontend/packages/model-registry/upstream/frontend/config/webpack.common.js
Labels: lgtm, approved

#4408 Model serving refactor: Add <DeploymentTableRowExpandedSection />
  frontend/packages/kserve/extensions.ts
  frontend/packages/kserve/src/deploymentExpandedDetails.ts
  frontend/packages/modelServing/extension-points/index.ts
  frontend/packages/modelServing/src/__tests__/mockUtils.ts
  frontend/packages/modelServing/src/components/deleteModal/DeleteModelServingModal.tsx
  frontend/packages/modelServing/src/components/deployments/DeploymentsTable.tsx
  frontend/packages/modelServing/src/components/deployments/DeploymentsTableRow.tsx
  frontend/packages/modelServing/src/components/deployments/DeploymentsTableRowExpandedSection.tsx
  frontend/packages/modelServing/src/components/deployments/__tests__/DeploymentsTableRow.spec.tsx
  frontend/packages/modelServing/src/concepts/extensionUtils.ts
  frontend/src/concepts/hardwareProfiles/useModelServingPodSpecOptionsState.ts
  frontend/src/concepts/modelServing/modelServingSizesUtils.ts
  frontend/src/pages/hardwareProfiles/migration/useMigratedHardwareProfiles.ts
  frontend/src/pages/modelServing/screens/const.ts
  frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeDetails.tsx
  frontend/src/pages/modelServing/screens/projects/utils.ts
Labels: lgtm, approved

#4385 Add "Defer input" checkbox to connection type field management
  frontend/src/concepts/connectionTypes/fields/FileFormField.tsx
  frontend/src/concepts/connectionTypes/fields/HiddenFormField.tsx
  frontend/src/concepts/connectionTypes/fields/SensitiveFieldHelperText.tsx
  frontend/src/concepts/connectionTypes/types.ts
  frontend/src/pages/connectionTypes/manage/ConnectionTypeDataFieldModal.tsx
  frontend/src/pages/connectionTypes/manage/DataFieldPropertiesForm.tsx
  frontend/src/pages/connectionTypes/manage/__tests__/ConnectionTypeDataFieldModal.spec.tsx
  frontend/src/pages/connectionTypes/manage/__tests__/manageFieldUtils.spec.ts
  frontend/src/pages/connectionTypes/manage/manageFieldUtils.ts
  manifests/common/connection-types/oci-v1.yaml
  manifests/common/connection-types/s3.yaml
Labels: lgtm, approved

#4428 [Cypress e2e]fix: model deployment tooltip text
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testDeployOCIModel.cy.ts
  frontend/src/__tests__/cypress/cypress/utils/models.ts
Labels: lgtm, approved

#4432 updated tekton
  .tekton/odh-dashboard-push.yaml
Labels: lgtm, approved

#4434 upversion dashboard
  frontend/.env
  manifests/odh/params.env
Labels: lgtm, approved

#4431 PVC Serving Feature Flag
  backend/src/types.ts
  backend/src/utils/constants.ts
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/concepts/areas/const.ts
  frontend/src/concepts/areas/types.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
Labels: lgtm, approved
