Repository opendatahub-io/odh-dashboard, pull requests merged in 2025-02, with the labels that each got.

#3702 Cypress e2e - Verify user can set environment variables in their workbenches by uploading a yaml Secret and Config Map file.
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/dataScienceProjects/testWorkbenchVariables.yaml
  frontend/src/__tests__/cypress/cypress/fixtures/resources/yaml/env_vars_cm.yaml
  frontend/src/__tests__/cypress/cypress/fixtures/resources/yaml/env_vars_secret.yaml
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchVariables.cy.ts
  frontend/src/__tests__/cypress/cypress/types.ts
  frontend/src/__tests__/cypress/cypress/utils/dataLoader.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/workbench.ts
Labels: lgtm, approved

#3707 Updated regex for RHOAIENG-15501
  frontend/src/concepts/connectionTypes/utils.ts
Labels: lgtm, approved

#3660 Begin data connection clean up
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/__tests__/cypress/cypress/pages/clusterStorage.ts
  frontend/src/__tests__/cypress/cypress/pages/dataConnection.ts
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/pages/projects.ts
  frontend/src/__tests__/cypress/cypress/pages/workbench.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/connectionTypes/connectionTypes.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionDeploy.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/clusterStorage.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/dataConnection.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/projectDetails.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/workbench.cy.ts
  frontend/src/app/AppRoutes.tsx
  frontend/src/components/TypeaheadSelect.tsx
  frontend/src/concepts/areas/const.ts
  frontend/src/concepts/areas/types.ts
  frontend/src/concepts/connectionTypes/useConnectionTypesEnabled.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/home/aiFlows/ProjectsGallery.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
  frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
  frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
  frontend/src/pages/projects/screens/detail/overview/configuration/ConfigurationSection.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/utilities/NavData.tsx
Labels: lgtm, approved

#3711 Fixes for workbench startup modal stopping and starting states
  frontend/src/concepts/__tests__/StartNotebookModal.spec.tsx
  frontend/src/concepts/notebooks/StartNotebookModal.tsx
  frontend/src/types.ts
  frontend/src/utilities/notebookControllerUtils.ts
Labels: lgtm, approved

#3713 Add feature flag for deploying KServe OCI Models
  backend/src/types.ts
  backend/src/utils/constants.ts
  docs/dashboard-config.md
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/concepts/areas/const.ts
  frontend/src/concepts/areas/types.ts
  frontend/src/k8sTypes.ts
  manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
Labels: lgtm, approved

#3712 Model Catalog page skeletons and new feature flag `disableModelCatalog`
  backend/src/types.ts
  backend/src/utils/constants.ts
  docs/dashboard-config.md
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/__tests__/cypress/cypress/pages/modelCatalog.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalog.cy.ts
  frontend/src/app/AppRoutes.tsx
  frontend/src/concepts/areas/const.ts
  frontend/src/concepts/areas/types.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelCatalog/EmptyModelCatalogState.tsx
  frontend/src/pages/modelCatalog/ModelCatalogCoreLoader.tsx
  frontend/src/pages/modelCatalog/ModelCatalogRoutes.tsx
  frontend/src/pages/modelCatalog/ModelDetailsPage.tsx
  frontend/src/utilities/NavData.tsx
  manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
Labels: lgtm, approved

#3716 Fix for hover state on workbench status labels
  frontend/src/concepts/notebooks/NotebookStatusLabel.tsx
  frontend/src/pages/projects/notebook/NotebookStateStatus.tsx
Labels: lgtm, approved

#3719 Fix: NIM Enable/Disable Behavior for Users in Enable & Explore Pages…
  backend/src/routes/api/integrations/nim/index.ts
  frontend/src/pages/exploreApplication/GetStartedPanel.tsx
Labels: lgtm, approved

#3720 Fix navigation bug: Add direct back link to models list from model metrics page
  frontend/src/pages/modelServing/screens/projects/ProjectModelMetricsPage.tsx
Labels: lgtm, approved, ok-to-test

#3715 E2e tag update
  frontend/src/__tests__/cypress/cypress/tests/e2e/applications/explore/testEnabledISVs.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/connections/testDataConnectionCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testMultiModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelContributorCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testLaunchStandaloneNotebook.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testProjectAdminPermissions.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testProjectContributorPermissions.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testProjectCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testProjectEditing.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchEditing.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/workbenches.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/learningResources/testResourcesfilters.cy.ts
Labels: lgtm, approved

#3726 Cypress e2e Test - Workbench Status Tests
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/dataScienceProjects/testWorkbenchStatus.yaml
  frontend/src/__tests__/cypress/cypress/pages/workbench.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/clusterStorage/testClusterStorageCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchEditing.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchStatus.cy.ts
  frontend/src/__tests__/cypress/cypress/types.ts
  frontend/src/__tests__/cypress/cypress/utils/dataLoader.ts
Labels: lgtm, approved

#3683 migrate e2e test for adding group permission
  frontend/src/__tests__/cypress/cypress/pages/permissions.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testProjectAdminPermissions.cy.ts
  frontend/src/__tests__/cypress/cypress/utils/e2eUsers.ts
  frontend/src/__tests__/cypress/cypress/utils/testConfig.ts
  frontend/src/concepts/roleBinding/RoleBindingPermissionsNameInput.tsx
Labels: lgtm, approved

#3717 disable "Disabled" NIM Link for Non-Admins with Tooltip
  frontend/src/components/OdhAppCard.tsx
Labels: lgtm, approved, ok-to-test

#3718 Add types, mock data and context provider for model catalog
  frontend/src/__mocks__/mockCatalogModel.ts
  frontend/src/__mocks__/mockModelCatalogSource.ts
  frontend/src/app/App.tsx
  frontend/src/concepts/modelCatalog/context/ModelCatalogContext.tsx
  frontend/src/concepts/modelCatalog/mockData/catalogModelMock.ts
  frontend/src/concepts/modelCatalog/mockData/modelCatalogSourceMock.ts
  frontend/src/concepts/modelCatalog/types.ts
  frontend/src/pages/modelCatalog/ModelCatalogCoreLoader.tsx
Labels: lgtm, approved

#3722 Fix for standalone notebook startup dialog looking stuck
  frontend/src/concepts/__tests__/StartNotebookModal.spec.tsx
  frontend/src/concepts/notebooks/StartNotebookModal.tsx
  frontend/src/pages/notebookController/screens/server/StartServerModal.tsx
  frontend/src/pages/projects/notebook/NotebookStateStatus.tsx
Labels: lgtm, approved

#3708 fix/12783-error-for-dup-model-name
  frontend/src/__tests__/cypress/cypress/pages/modelRegistry/registerModelPage.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/registerModel.cy.ts
  frontend/src/pages/modelRegistry/screens/RegisterModel/RegisterModel.tsx
  frontend/src/pages/modelRegistry/screens/RegisterModel/__tests__/utils.spec.ts
  frontend/src/pages/modelRegistry/screens/RegisterModel/utils.ts
Labels: lgtm, approved

#3732 Cypress e2e - Enhance Workbench Editing Tests
  frontend/src/__tests__/cypress/cypress/pages/workbench.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchEditing.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchStatus.cy.ts
Labels: lgtm, approved

#3692 Add e2e test for OOTB connection types
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/connectionTypes/testOOTBConnectionType.yaml
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/connectionTypes/connectionTypes.cy.ts
  frontend/src/__tests__/cypress/cypress/types.ts
  frontend/src/__tests__/cypress/cypress/utils/dataLoader.ts
Labels: lgtm, approved

#3734 Cypress e2e Test - Start/Stop a Workbench from Event Log
  frontend/src/__tests__/cypress/cypress/pages/workbench.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchControlSuite.cy.ts
Labels: lgtm, approved

#3733 Update Model catalog route
  frontend/src/pages/modelCatalog/ModelCatalogCoreLoader.tsx
  frontend/src/pages/modelCatalog/ModelCatalogRoutes.tsx
  frontend/src/pages/modelCatalog/screens/ModelCatalog.tsx
Labels: lgtm, approved

#3727 fix: set default Model Server size to 'Custom' and update helper text
  frontend/src/__mocks__/mockNimResource.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/modelServingNim.cy.ts
  frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx
Labels: lgtm, approved, needs-ok-to-test

#3740 [Backport] Pipeline logs are not appearing on run details page
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelinesTopology.cy.ts
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx
Labels: lgtm, approved

#3694 Use kserve without serverless
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/clusterSettings/ClusterSettings.tsx
  frontend/src/pages/clusterSettings/ModelServingPlatformSettings.tsx
  frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx
  frontend/src/pages/modelServing/screens/projects/NIMServiceModal/NoAuthAlert.tsx
  frontend/src/pages/modelServing/screens/projects/kServeModal/KServeDeploymentModeDropdown.tsx
  frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
  frontend/src/pages/modelServing/screens/projects/kServeModal/NoAuthAlert.tsx
  frontend/src/pages/modelServing/screens/projects/utils.ts
  frontend/src/pages/modelServing/useDefaultDeploymentMode.ts
  frontend/src/pages/modelServing/useKServeDeploymentMode.ts
Labels: lgtm, approved

#3738 Cypress e2e - Verify that logged in users display on the Dashboard
  frontend/src/__tests__/cypress/cypress/pages/components/Header.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dashboardNavigation/testUserLogin.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/clusterStorage/testClusterStorageCreation.cy.ts
Labels: lgtm, approved

#3742 Cypress e2e Test - Verifies users can create a workbench and inject environment variables during creation
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/dataScienceProjects/testWorkbenchVariables.yaml
  frontend/src/__tests__/cypress/cypress/pages/workbench.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchVariables.cy.ts
  frontend/src/__tests__/cypress/cypress/types.ts
Labels: lgtm, approved

#3725 Enable/disable ilab feature
  backend/src/types.ts
  backend/src/utils/constants.ts
  docs/dashboard-config.md
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/__mocks__/mockDsc.ts
  frontend/src/__tests__/cypress/cypress/pages/clusterSettings.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/clusterSettings/clusterSettings.cy.ts
  frontend/src/api/index.ts
  frontend/src/api/k8s/dsc.ts
  frontend/src/api/models/k8s.ts
  frontend/src/concepts/areas/const.ts
  frontend/src/concepts/areas/types.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/clusterSettings/ClusterSettings.tsx
  frontend/src/pages/clusterSettings/InstructLabSettings.tsx
  frontend/src/pages/clusterSettings/useDefaultDsc.ts
  frontend/src/pages/clusterSettings/utils.ts
  manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
Labels: lgtm, approved

#3748 fix: show backend error message for API key validation
  frontend/src/utilities/useEnableApplication.tsx
Labels: lgtm, approved, ok-to-test

#3752 Cypress e2e Test - Updates for 'Verify User Can Access Jupyter Launcher From DS Project Page' & 'Verify That Usage Data Collection Can Be Set In Cluster Settings'
  frontend/src/__tests__/cypress/cypress/pages/notebookServer.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testLaunchStandaloneNotebook.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/clusterSettings/testDataCollection.cy.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/baseCommands.ts
Labels: lgtm, approved

#3751 Add safeExecute utility for error handling in InstructLab feature check
  frontend/src/pages/clusterSettings/utils.ts
  frontend/src/utilities/__tests__/utils.spec.ts
  frontend/src/utilities/utils.ts
Labels: lgtm, approved

#3750 Cypress e2e Test - Verify Notebook Tolerations Are Applied To Workbenches
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/dataScienceProjects/testWorkbenchTolerations.yaml
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchTolerations.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/learningResources/testCustomResourceCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/types.ts
  frontend/src/__tests__/cypress/cypress/utils/clusterSettingsUtils.ts
  frontend/src/__tests__/cypress/cypress/utils/dataLoader.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/modelServing.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/workbench.ts
Labels: lgtm, approved

#3746 Connection type admin view feature flag
  backend/src/types.ts
  backend/src/utils/constants.ts
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/connectionTypes/connectionTypes.cy.ts
  frontend/src/concepts/areas/const.ts
  frontend/src/concepts/areas/types.ts
  frontend/src/k8sTypes.ts
  frontend/src/utilities/NavData.tsx
  manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
Labels: lgtm, approved

#3749 Add model details page for model catalog
  frontend/src/__mocks__/mockCatalogModel.ts
  frontend/src/__tests__/cypress/cypress/pages/modelDetailsPage.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalog.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelDetailsPage.cy.ts
  frontend/src/concepts/modelCatalog/mockData/catalogModelMock.ts
  frontend/src/concepts/modelCatalog/types.ts
  frontend/src/pages/modelCatalog/ModelCatalogCoreLoader.tsx
  frontend/src/pages/modelCatalog/ModelCatalogRoutes.tsx
  frontend/src/pages/modelCatalog/ModelDetailsPage.tsx
  frontend/src/pages/modelCatalog/__tests__/utils.spec.ts
  frontend/src/pages/modelCatalog/const.ts
  frontend/src/pages/modelCatalog/routeUtils.ts
  frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx
  frontend/src/pages/modelCatalog/screens/ModelDetailsView.tsx
  frontend/src/pages/modelCatalog/utils.ts
Labels: lgtm, approved

#3743 Fetch ConfigMap in ModelCatalogContext provider and move provider to route level
  frontend/src/__mocks__/mockModelCatalogConfigMap.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelDetailsPage.cy.ts
  frontend/src/app/App.tsx
  frontend/src/concepts/modelCatalog/const.ts
  frontend/src/concepts/modelCatalog/context/ModelCatalogContext.tsx
  frontend/src/concepts/modelCatalog/mockData/catalogModelMock.ts
  frontend/src/concepts/modelCatalog/mockData/modelCatalogSourceMock.ts
  frontend/src/concepts/modelCatalog/useModelCatalogSources.ts
  frontend/src/pages/modelCatalog/ModelCatalogCoreLoader.tsx
  frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx
Labels: lgtm, approved

#3758 Notebook tolerations box update
  frontend/src/pages/clusterSettings/const.ts
Labels: lgtm, approved

#3747 fix: set disableNIMModelServing to false as required for GA
  backend/src/utils/constants.ts
  docs/dashboard-config.md
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/concepts/areas/const.ts
  manifests/rhoai/shared/odhdashboardconfig/odhdashboardconfig.yaml
Labels: lgtm, approved, ok-to-test

#3710 Alternative for models' info and the drop down list
  frontend/src/__tests__/cypress/cypress/pages/components/NIMDeployModal.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/modelServingNim.cy.ts
  frontend/src/pages/modelServing/screens/projects/NIMServiceModal/NIMModelListSection.tsx
Labels: lgtm, approved, ok-to-test

#3754 feat: catalog page cards
  frontend/src/__mocks__/mockCatalogModel.ts
  frontend/src/__tests__/cypress/cypress/pages/modelCatalog.ts
  frontend/src/__tests__/cypress/cypress/pages/modelDetailsPage.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalog.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelDetailsPage.cy.ts
  frontend/src/concepts/modelCatalog/types.ts
  frontend/src/pages/modelCatalog/__tests__/utils.spec.ts
  frontend/src/pages/modelCatalog/components/ModelCatalogCard.tsx
  frontend/src/pages/modelCatalog/components/ModelCatalogCards.tsx
  frontend/src/pages/modelCatalog/screens/ModelCatalog.tsx
Labels: lgtm, approved

#3761 Model registry name truncation
  frontend/src/pages/modelRegistry/screens/ModelRegistrySelector.tsx
Labels: lgtm, approved

#3763 V2.31.0 fixes more nim stuff
  backend/src/utils/constants.ts
  docs/dashboard-config.md
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/__mocks__/mockNimResource.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/modelServingNim.cy.ts
  frontend/src/components/OdhAppCard.tsx
  frontend/src/concepts/areas/const.ts
  frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx
  frontend/src/pages/modelServing/screens/projects/ProjectModelMetricsPage.tsx
  frontend/src/utilities/useEnableApplication.tsx
  manifests/rhoai/shared/odhdashboardconfig/odhdashboardconfig.yaml
Labels: lgtm, approved

#3755 fix: ensure NIM availability updates without requiring a manual refresh
  frontend/src/concepts/nimServing/NIMAvailabilityContext.tsx
  frontend/src/pages/modelServing/screens/projects/__tests__/utils.spec.ts
  frontend/src/pages/modelServing/screens/projects/useIsNIMAvailable.ts
  frontend/src/pages/modelServing/screens/types.ts
  frontend/src/pages/modelServing/useServingPlatformStatuses.ts
  frontend/src/pages/projects/screens/detail/overview/serverModels/ServeModelsSection.tsx
  frontend/src/utilities/__tests__/useEnableApplication.spec.tsx
Labels: lgtm, approved, ok-to-test

#3759 Less strict connection field env variable names
  frontend/src/concepts/connectionTypes/__tests__/utils.spec.ts
  frontend/src/concepts/connectionTypes/fields/UriFormField.tsx
  frontend/src/concepts/connectionTypes/utils.ts
  frontend/src/concepts/connectionTypes/validationUtils.ts
  frontend/src/pages/connectionTypes/manage/ConnectionTypeDataFieldModal.tsx
Labels: lgtm, approved

#3760 Create a connection with secret type 'kubernetes.io/dockerconfigjson'
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/connections.cy.ts
  frontend/src/concepts/connectionTypes/utils.ts
Labels: lgtm, approved

#3765 feat(ModelCatalog): link to details page
  frontend/src/__tests__/cypress/cypress/pages/modelCatalog.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalog.cy.ts
  frontend/src/pages/modelCatalog/__tests__/utils.spec.ts
  frontend/src/pages/modelCatalog/components/ModelCatalogCard.tsx
  frontend/src/pages/modelCatalog/routeUtils.ts
  frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx
  frontend/src/pages/modelCatalog/utils.ts
Labels: lgtm, approved

#3766 fix: ensure NIM availability updates without requiring a manual refre…
  frontend/src/concepts/nimServing/NIMAvailabilityContext.tsx
  frontend/src/pages/modelServing/screens/projects/__tests__/utils.spec.ts
  frontend/src/pages/modelServing/screens/projects/useIsNIMAvailable.ts
  frontend/src/pages/modelServing/screens/types.ts
  frontend/src/pages/modelServing/useServingPlatformStatuses.ts
  frontend/src/pages/projects/screens/detail/overview/serverModels/ServeModelsSection.tsx
  frontend/src/utilities/__tests__/useEnableApplication.spec.tsx
Labels: lgtm, approved

#3762 Cypress option to skip tests by tags and display skipped in Junit Report
  frontend/src/__tests__/cypress/cypress/support/e2e.ts
Labels: lgtm, approved

#3756 created ilab form
  frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationForm.ts
  frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts
  frontend/src/api/pipelines/callTypes.ts
  frontend/src/api/pipelines/custom.ts
  frontend/src/components/EmptyStateErrorMessage.tsx
  frontend/src/concepts/pipelines/apiHooks/usePipelineByName.ts
  frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/types.ts
  frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/validationUtils.ts
  frontend/src/concepts/pipelines/content/modelCustomizationForm/useIlabPipeline.ts
  frontend/src/concepts/pipelines/context/usePipelineAPIState.ts
  frontend/src/concepts/pipelines/types.ts
  frontend/src/pages/pipelines/GlobalModelCustomizationRoutes.tsx
  frontend/src/pages/pipelines/global/GlobalPipelineCoreLoader.tsx
  frontend/src/pages/pipelines/global/PipelineCoreNoProjects.tsx
  frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx
  frontend/src/pages/pipelines/global/modelCustomization/FineTunePageFooter.tsx
  frontend/src/pages/pipelines/global/modelCustomization/ModelCustomizationForm.tsx
  frontend/src/pages/pipelines/global/modelCustomization/const.ts
  frontend/src/routes/pipelines/modelCustomizationForm.ts
Labels: lgtm, approved

#3764 Patch DSC when Admin changes Default Deployment Mode
  frontend/src/__mocks__/mockDsc.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/clusterSettings/clusterSettings.cy.ts
  frontend/src/api/k8s/dsc.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/clusterSettings/ClusterSettings.tsx
  frontend/src/pages/clusterSettings/ModelServingPlatformSettings.tsx
Labels: lgtm, approved

#3741 Attach pull secret to InferenceService when present
  frontend/src/__mocks__/mockInferenceServiceK8sResource.ts
  frontend/src/__mocks__/mockInferenceServiceModalData.ts
  frontend/src/__mocks__/mockNimResource.ts
  frontend/src/api/k8s/__tests__/inferenceServices.spec.ts
  frontend/src/api/k8s/inferenceServices.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/__tests__/ConnectionSection.spec.tsx
  frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
  frontend/src/pages/modelServing/screens/projects/utils.ts
  frontend/src/pages/modelServing/screens/types.ts
Labels: lgtm, approved

#3753 Cypress e2e - Enhance Retries to run Before hooks
  frontend/src/__tests__/cypress/cypress/tests/e2e/applications/explore/testEnabledISVs.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dashboardNavigation/testManifestLinks.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataSciencePipelines/createRunDeletePipelineCustomPipMirror.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataSciencePipelines/pipelines.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/clusterStorage/testClusterStorageCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/connections/testDataConnectionCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testMultiModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelContributorCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testLaunchStandaloneNotebook.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testProjectAdminPermissions.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testProjectContributorPermissions.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testProjectCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testProjectEditing.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchControlSuite.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchEditing.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchStatus.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchTolerations.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchVariables.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/workbenches.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/learningResources/testCustomResourceCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/clusterSettings/testAdminClusterSettings.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/clusterSettings/testDataCollection.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/connectionTypes/connectionTypes.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/servingRuntimes/testMultiModelServingRuntimeCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/servingRuntimes/testSingleServingRuntimeCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/storageClasses/clusterStorage.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/storageClasses/storageClasses.cy.ts
  frontend/src/__tests__/cypress/cypress/utils/retryableHooks.ts
Labels: lgtm, approved

#3657 added warnings and tests for hardware profiles
  frontend/src/__mocks__/mockHardwareProfile.ts
  frontend/src/__tests__/cypress/cypress/pages/hardwareProfile.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/hardwareProfiles.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/manageHardwareProfiles.cy.ts
  frontend/src/api/k8s/__tests__/hardwareProfiles.spec.ts
  frontend/src/app/NavSidebar.tsx
  frontend/src/concepts/hardwareProfiles/const.ts
  frontend/src/concepts/hardwareProfiles/types.ts
  frontend/src/concepts/hardwareProfiles/validationUtils.ts
  frontend/src/pages/hardwareProfiles/HardwareProfileEnableToggle.tsx
  frontend/src/pages/hardwareProfiles/HardwareProfiles.tsx
  frontend/src/pages/hardwareProfiles/HardwareProfilesTable.tsx
  frontend/src/pages/hardwareProfiles/HardwareProfilesTableRow.tsx
  frontend/src/pages/hardwareProfiles/__tests__/hardwareProfileWarning.spec.ts
  frontend/src/pages/hardwareProfiles/__tests__/isHardwareProfileIdentifierValid.spec.ts
  frontend/src/pages/hardwareProfiles/manage/ManageNodeResourceSection.tsx
  frontend/src/pages/hardwareProfiles/nodeResource/NodeResourceTable.tsx
  frontend/src/pages/hardwareProfiles/nodeResource/NodeResourceTableRow.tsx
  frontend/src/pages/hardwareProfiles/nodeResource/const.ts
  frontend/src/pages/hardwareProfiles/utils.ts
  frontend/src/utilities/NavData.tsx
  frontend/src/utilities/NavWithIcon.tsx
  frontend/src/utilities/__tests__/valueUnits.spec.ts
  frontend/src/utilities/useWatchHardwareProfiles.ts
  frontend/src/utilities/valueUnits.ts
Labels: lgtm, approved

#3772 Enhancement to ODS-1218 'Verify That Usage Data Collection Can Be Set In Cluster Settings'
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/clusterSettings/testDataCollection.cy.ts
Labels: lgtm, approved

#3771 Check if deployment is raw for showing token
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts
  frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTableRow.tsx
Labels: lgtm, approved

#3729 chore: Fix typo in PR template
  .github/pull_request_template.md
Labels: lgtm, approved

#3776 Cypress - Stabilise e2e Tests
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testLaunchStandaloneNotebook.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchControlSuite.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchEditing.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchStatus.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchTolerations.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchVariables.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/storageClasses/clusterStorage.cy.ts
Labels: lgtm, approved

#3782 Upversion dashboard release
  frontend/.env
  manifests/odh/params.env
Labels: lgtm, approved

#3590 Prefill URI connections and fix prefill deploy model form from version
  frontend/src/__tests__/cypress/cypress/pages/modelRegistry/registerModelPage.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionDeploy.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/registerModel.cy.ts
  frontend/src/components/TypeaheadSelect.tsx
  frontend/src/concepts/connectionTypes/__tests__/useConnectionType.spec.ts
  frontend/src/concepts/connectionTypes/utils.ts
  frontend/src/concepts/modelRegistry/__tests__/utils.spec.ts
  frontend/src/concepts/modelRegistry/apiHooks/__tests__/usePrefillDeployModalFromModelRegistry.spec.ts
  frontend/src/concepts/modelRegistry/types.ts
  frontend/src/concepts/modelRegistry/utils.ts
  frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx
  frontend/src/pages/modelRegistry/screens/RegisterModel/ConnectionDropdown.tsx
  frontend/src/pages/modelRegistry/screens/RegisterModel/ConnectionModal.tsx
  frontend/src/pages/modelRegistry/screens/RegisterModel/RegisteredModelSelector.tsx
  frontend/src/pages/modelRegistry/screens/RegisterModel/RegistrationCommonFormSections.tsx
  frontend/src/pages/modelRegistry/screens/RegisterModel/usePrefillRegisterVersionFields.ts
  frontend/src/pages/modelRegistry/screens/RegisterModel/utils.ts
  frontend/src/pages/modelRegistry/screens/RegisteredModels/useLabeledConnections.ts
  frontend/src/pages/modelRegistry/screens/RegisteredModels/useLabeledDataConnections.ts
  frontend/src/pages/modelRegistry/screens/RegisteredModels/usePrefillDeployModalFromModelRegistry.ts
  frontend/src/pages/modelRegistry/screens/RegisteredModels/useRegisteredModelDeployInfo.ts
  frontend/src/pages/modelRegistry/screens/components/DeployRegisteredModelModal.tsx
  frontend/src/pages/modelServing/ModelServingContext.tsx
  frontend/src/pages/modelServing/screens/global/ServeModelButton.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/__tests__/ConnectionSection.spec.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/__tests__/ManageInferenceServiceModal.spec.tsx
  frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTable.tsx
  frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx
  frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
  frontend/src/pages/modelServing/screens/types.ts
  frontend/src/pages/projects/screens/detail/overview/serverModels/AddModelFooter.tsx
Labels: lgtm, approved

#3786 Feat/18962 catalog model detail
  frontend/src/__tests__/cypress/cypress/pages/modelDetailsPage.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelDetailsPage.cy.ts
  frontend/src/components/ExternalLink.tsx
  frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx
  frontend/src/pages/modelCatalog/screens/ModelDetailsView.tsx
Labels: lgtm, approved

#3778 Add oci-v1.yaml ootb connection type
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/connections.cy.ts
  frontend/src/concepts/connectionTypes/__tests__/utils.spec.ts
  frontend/src/concepts/connectionTypes/utils.ts
  manifests/common/connection-types/oci-v1.yaml
Labels: lgtm, approved

#3784 Add base model section to ilab form
  frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/validationUtils.ts
  frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx
  frontend/src/pages/pipelines/global/modelCustomization/ModelCustomizationForm.tsx
  frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/BaseModelSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/InlineEditText.tsx
  frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/__tests__/InlineEditText.spec.tsx
  frontend/src/pages/pipelines/global/modelCustomization/const.ts
Labels: lgtm, approved

#3780 Hardware profile introduction alert banner
  frontend/src/__tests__/cypress/cypress/pages/home/home.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/home/home.cy.ts
  frontend/src/pages/home/HomeHint.tsx
Labels: lgtm, approved

#3769 Add ilab pipeline complete alert mechanism
  frontend/src/app/App.tsx
  frontend/src/app/AppNotificationDrawer.tsx
  frontend/src/components/ToastNotification.tsx
  frontend/src/concepts/notificationWatcher/NotificationWatcherContext.tsx
  frontend/src/concepts/notificationWatcher/__tests__/NotificationWatcherContext.spec.tsx
  frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx
  frontend/src/pages/pipelines/global/modelCustomization/FineTunePageFooter.tsx
  frontend/src/redux/types.ts
  frontend/src/utilities/useNotification.ts
Labels: lgtm, approved

#3795 feat(MR): Add missing key for SimpleSelect
  frontend/src/components/SimpleSelect.tsx
Labels: lgtm, approved

#3654 Show the GPU requests and limits in workbench table
  frontend/src/pages/notebookController/screens/server/AcceleratorProfileSelectField.tsx
  frontend/src/pages/notebookController/screens/server/__tests__/useAcceleratorCountWarning.spec.ts
  frontend/src/pages/notebookController/screens/server/useAcceleratorCountWarning.tsx
  frontend/src/pages/projects/screens/detail/notebooks/NotebookSizeDetails.tsx
  frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx
  frontend/src/pages/projects/screens/detail/notebooks/__tests__/utils.spec.ts
  frontend/src/pages/projects/screens/detail/notebooks/utils.ts
Labels: lgtm, approved

#3797 Make model customization side drawer inline
  frontend/src/pages/pipelines/global/modelCustomization/ModelCustomization.tsx
Labels: lgtm, approved

#3770 Render loading/error states on catalog and details pages
  frontend/src/__tests__/cypress/cypress/pages/modelDetailsPage.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalog.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelDetailsPage.cy.ts
  frontend/src/concepts/modelCatalog/useModelCatalogSources.ts
  frontend/src/pages/modelCatalog/screens/ModelCatalog.tsx
  frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx
Labels: lgtm, approved

#3794 Cypress e2e - Workbenches (new e2e tests) and unquarantine existing tests
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/dataScienceProjects/testWorkbenchNegativeTests.yaml
  frontend/src/__tests__/cypress/cypress/pages/workbench.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dashboardNavigation/testManifestLinks.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchControlSuite.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchEditing.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchNegativeTests.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchStatus.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchTolerations.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchVariables.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/learningResources/testCustomResourceCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/types.ts
  frontend/src/__tests__/cypress/cypress/utils/retryableHooks.ts
Labels: lgtm, approved

#3798 Small truncation fix
  frontend/src/concepts/roleBinding/RoleBindingPermissionsTableRow.tsx
Labels: lgtm, approved

#3737 Fix: Remove Non-Existent Video File in after:spec Handler
  frontend/src/__tests__/cypress/cypress.config.ts
Labels: lgtm, approved

#3802 Add optional flag to Elyra volume secret configuration
  frontend/src/api/k8s/__tests__/notebooks.spec.ts
  frontend/src/concepts/pipelines/elyra/utils.ts
  frontend/src/types.ts
Labels: lgtm, approved

#3804 Make quickstart functionality available outside cards
  frontend/src/utilities/useQuickStart.ts
Labels: lgtm, approved

#3811 Move Cypress testing dependencies to optionalDependencies
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved

#3812 Move non-Cypress testing dependencies to optionalDependencies
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved

#3808 Reorganize main nav to create Models section and update page titles
  frontend/src/__tests__/cypress/cypress/pages/distributedWorkloads.ts
  frontend/src/__tests__/cypress/cypress/pages/modelCatalog.ts
  frontend/src/__tests__/cypress/cypress/pages/modelRegistry.ts
  frontend/src/__tests__/cypress/cypress/pages/modelRegistrySettings.ts
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/pages/projects.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalog.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelRegistry.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomization.cy.ts
  frontend/src/concepts/distributedWorkloads/DistributedWorkloadsContext.tsx
  frontend/src/pages/distributedWorkloads/global/DistributedWorkloadsNoProjects.tsx
  frontend/src/pages/distributedWorkloads/global/GlobalDistributedWorkloads.tsx
  frontend/src/pages/distributedWorkloads/global/GlobalDistributedWorkloadsTabs.tsx
  frontend/src/pages/modelCatalog/screens/ModelCatalog.tsx
  frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx
  frontend/src/pages/modelRegistry/ModelRegistryCoreLoader.tsx
  frontend/src/pages/modelRegistry/screens/ModelRegistry.tsx
  frontend/src/pages/modelRegistrySettings/ModelRegistrySettings.tsx
  frontend/src/pages/modelServing/screens/global/GlobalModelServingCoreLoader.tsx
  frontend/src/pages/modelServing/screens/global/ModelServingGlobal.tsx
  frontend/src/pages/pipelines/global/experiments/const.ts
  frontend/src/pages/projects/screens/projects/ProjectView.tsx
  frontend/src/utilities/NavData.tsx
Labels: lgtm, approved

#3813 Quarantine multiModelAdminCreation Test
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testMultiModelAdminCreation.cy.ts
Labels: lgtm, approved

#3777 Add teacher/judge section to ilab form
  frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationForm.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts
  frontend/src/api/k8s/secrets.ts
  frontend/src/concepts/pipelines/content/createRun/submitUtils.ts
  frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/__tests__/validationUtils.spec.ts
  frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/validationUtils.ts
  frontend/src/concepts/pipelines/content/modelCustomizationForm/useIlabPipeline.ts
  frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx
  frontend/src/pages/pipelines/global/modelCustomization/FineTunePageFooter.tsx
  frontend/src/pages/pipelines/global/modelCustomization/ModelCustomizationForm.tsx
  frontend/src/pages/pipelines/global/modelCustomization/const.ts
  frontend/src/pages/pipelines/global/modelCustomization/teacherJudgeSection/JudgeModelSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/teacherJudgeSection/TeacherJudgeInputComponents.tsx
  frontend/src/pages/pipelines/global/modelCustomization/teacherJudgeSection/TeacherModelSection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/utils.ts
Labels: lgtm, approved

#3814 fix: duplicated tags issue for models' info and the drop down list
  frontend/src/pages/modelServing/screens/projects/NIMServiceModal/NIMModelListSection.tsx
Labels: lgtm, approved, ok-to-test

#3807 feat(serving): add "Model URI" field to deployment modal
  frontend/src/__mocks__/mockConnectionType.ts
  frontend/src/concepts/connectionTypes/__tests__/utils.spec.ts
  frontend/src/concepts/connectionTypes/utils.ts
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionOciPathField.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionS3FolderPathField.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionExistingField.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionSection.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/__tests__/ConnectionSection.spec.tsx
  frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
  frontend/src/pages/modelServing/screens/projects/utils.ts
Labels: lgtm, approved

#3821 Remove Anaconda app
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/dashboardNavigation/testManifestLinks.yaml
  manifests/rhoai/shared/apps/anaconda-ce/anaconda-ce-app.yaml
  manifests/rhoai/shared/apps/anaconda-ce/anaconda-ce-create-jupyter-notebook-quickstart.yaml
  manifests/rhoai/shared/apps/anaconda-ce/anaconda-ce-docs.yaml
  manifests/rhoai/shared/apps/anaconda-ce/kustomization.yaml
  manifests/rhoai/shared/apps/kustomization.yaml
  manifests/rhoai/shared/base/anaconda-ce-validator-cron.yaml
  manifests/rhoai/shared/base/kustomization.yaml
Labels: lgtm, approved

#3822 Remove Anaconda app
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/dashboardNavigation/testManifestLinks.yaml
  manifests/rhoai/shared/apps/anaconda-ce/anaconda-ce-app.yaml
  manifests/rhoai/shared/apps/anaconda-ce/anaconda-ce-create-jupyter-notebook-quickstart.yaml
  manifests/rhoai/shared/apps/anaconda-ce/anaconda-ce-docs.yaml
  manifests/rhoai/shared/apps/anaconda-ce/kustomization.yaml
  manifests/rhoai/shared/apps/kustomization.yaml
  manifests/rhoai/shared/base/anaconda-ce-validator-cron.yaml
  manifests/rhoai/shared/base/kustomization.yaml
Labels: lgtm, approved

#3785 Fine tune taxonomy
  frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationForm.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts
  frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/__tests__/validationUtils.spec.ts
  frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/types.ts
  frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/validationUtils.ts
  frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx
  frontend/src/pages/pipelines/global/modelCustomization/FineTunePageFooter.tsx
  frontend/src/pages/pipelines/global/modelCustomization/FineTuneTaxonomySection.tsx
  frontend/src/pages/pipelines/global/modelCustomization/ModelCustomizationForm.tsx
  frontend/src/pages/pipelines/global/modelCustomization/const.ts
  frontend/src/pages/pipelines/global/modelCustomization/utils.ts
Labels: lgtm, approved

#3792 DOMPurify CVE fix
  frontend/package-lock.json
  frontend/package.json
  frontend/src/utilities/markdown.ts
Labels: lgtm, approved

#3825 add title icon to hardware profiles
  frontend/src/pages/hardwareProfiles/HardwareProfiles.tsx
Labels: lgtm, approved

#3781 Add register model page for model catalog
  frontend/src/__tests__/cypress/cypress/pages/modelCatalog/modelCatalog.ts
  frontend/src/__tests__/cypress/cypress/pages/modelCatalog/modelDetailsPage.ts
  frontend/src/__tests__/cypress/cypress/pages/modelCatalog/registerCatalogModel.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalog.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelDetailsPage.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/registerCatalogModel.cy.ts
  frontend/src/api/modelRegistry/__tests__/custom.spec.ts
  frontend/src/api/modelRegistry/custom.ts
  frontend/src/concepts/modelRegistry/apiHooks/__tests__/updateTimestamps.test.ts
  frontend/src/concepts/modelRegistry/types.ts
  frontend/src/concepts/modelRegistry/utils/updateTimestamps.ts
  frontend/src/pages/modelCatalog/ModelCatalogRoutes.tsx
  frontend/src/pages/modelCatalog/__tests__/utils.spec.ts
  frontend/src/pages/modelCatalog/routeUtils.ts
  frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx
  frontend/src/pages/modelCatalog/screens/RegisterCatalogModel.tsx
  frontend/src/pages/modelCatalog/utils.ts
  frontend/src/pages/modelRegistry/screens/ModelRegistrySelector.tsx
  frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx
  frontend/src/pages/modelRegistry/screens/RegisterModel/RegisterModel.tsx
  frontend/src/pages/modelRegistry/screens/RegisterModel/RegisterModelDetailsFormSection.tsx
  frontend/src/pages/modelRegistry/screens/RegisterModel/RegisterModelErrors.tsx
  frontend/src/pages/modelRegistry/screens/RegisterModel/RegisterVersion.tsx
  frontend/src/pages/modelRegistry/screens/RegisterModel/RegistrationCommonFormSections.tsx
  frontend/src/pages/modelRegistry/screens/RegisterModel/RegistrationFormFooter.tsx
  frontend/src/pages/modelRegistry/screens/RegisterModel/const.ts
  frontend/src/pages/modelRegistry/screens/RegisterModel/useRegisterModelData.ts
  frontend/src/pages/modelRegistry/screens/RegisterModel/utils.ts
  frontend/src/pages/modelRegistry/screens/components/DeployRegisteredModelModal.tsx
Labels: lgtm, approved

#3827 Revert "chore(19957): set rhoai manifest disableModelCatalog flag false"
  manifests/rhoai/shared/odhdashboardconfig/odhdashboardconfig.yaml
Labels: lgtm, approved

#3735 Map component versions to RHOAI releases
  frontend/src/__mocks__/mockDscStatus.ts
  frontend/src/__tests__/cypress/cypress/pages/aboutDialog.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/application.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/clusterSettings/clusterSettings.cy.ts
  frontend/src/app/AboutDialog.tsx
  frontend/src/app/__tests__/AboutDialog.spec.tsx
  frontend/src/concepts/areas/const.ts
  frontend/src/concepts/areas/types.ts
  frontend/src/k8sTypes.ts
Labels: lgtm, approved

#3803 styling tweaks to model catalog cards
  frontend/src/concepts/design/TypedObjectIcon.tsx
  frontend/src/concepts/design/utils.ts
  frontend/src/images/icons/ModelCatalogIcon.ts
  frontend/src/images/icons/RhUiTagIcon.ts
  frontend/src/images/icons/index.ts
  frontend/src/pages/modelCatalog/components/ModelCatalogCard.tsx
  frontend/src/pages/modelCatalog/screens/ModelCatalog.tsx
  frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx
  frontend/src/pages/modelCatalog/screens/ModelDetailsView.tsx
Labels: lgtm, approved

#3783 Upgrade to Node 20
  .github/workflows/test.yml
  Dockerfile
  backend/package-lock.json
  backend/package.json
  docs/dev-setup.md
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
  scripts/ci/Dockerfile
Labels: do-not-merge/hold, lgtm, approved

#3828 Quarantine pipelines.cy.ts Test
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataSciencePipelines/pipelines.cy.ts
Labels: lgtm, approved
