Repository opendatahub-io/odh-dashboard, pull requests merged in 2025-09, with the labels that each got.

#4788 Update Cypress CI image for Shift-Left
  scripts/ci/Dockerfile
Labels: lgtm, approved

#4792 Add hw profiles to deployment wizard
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingDeploy.cy.ts
  frontend/src/concepts/hardwareProfiles/useServingHardwareProfileConfig.ts
  packages/kserve/extensions.ts
  packages/kserve/src/useKServeResources.ts
  packages/model-serving/extension-points/index.ts
  packages/model-serving/src/components/deploymentWizard/EditModelDeploymentPage.tsx
  packages/model-serving/src/components/deploymentWizard/ModelDeploymentWizard.tsx
  packages/model-serving/src/components/deploymentWizard/fields/ModelServingHardwareProfileSection.tsx
  packages/model-serving/src/components/deploymentWizard/fields/ModelTypeSelectField.tsx
  packages/model-serving/src/components/deploymentWizard/fields/__tests__/ModelTypeSelectField.test.tsx
  packages/model-serving/src/components/deploymentWizard/steps/ModelDeploymentStep.tsx
  packages/model-serving/src/components/deploymentWizard/steps/ModelSourceStep.tsx
  packages/model-serving/src/components/deploymentWizard/steps/__tests__/ModelSourceStep.test.tsx
  packages/model-serving/src/components/deploymentWizard/useDeploymentWizard.ts
  packages/model-serving/src/components/deploymentWizard/useDeploymentWizardValidation.tsx
Labels: lgtm, approved

#4783 Feat: BFF for fetching the list of models from ISVC
  packages/gen-ai/bff/go.mod
  packages/gen-ai/bff/go.sum
  packages/gen-ai/bff/internal/api/app.go
  packages/gen-ai/bff/internal/api/models_aa_handler.go
  packages/gen-ai/bff/internal/api/models_aa_handler_test.go
  packages/gen-ai/bff/internal/constants/api_constants.go
  packages/gen-ai/bff/internal/helpers/k8s.go
  packages/gen-ai/bff/internal/integrations/kubernetes/client.go
  packages/gen-ai/bff/internal/integrations/kubernetes/k8smocks/base_testenv.go
  packages/gen-ai/bff/internal/integrations/kubernetes/k8smocks/token_k8s_client_mock.go
  packages/gen-ai/bff/internal/integrations/kubernetes/token_k8s_client.go
  packages/gen-ai/bff/internal/models/genaiassets/aa_models.go
  packages/gen-ai/bff/internal/repositories/aa_models.go
  packages/gen-ai/bff/internal/repositories/repositories.go
Labels: lgtm, approved, area/llama-stack-modular-ui

#4807 Cherry-pick: Avoid destructuring from process.env
  frontend/src/utilities/const.ts
Labels: lgtm, approved

#4780 optimise model registry e2e runtime & stability
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/modelRegistry/testManageRegistryPermissions.yaml
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/modelRegistry/testModelRegistry.yaml
  frontend/src/__tests__/cypress/cypress/fixtures/resources/yaml/model_registry_database.yaml
  frontend/src/__tests__/cypress/cypress/tests/e2e/modelRegistry/testAdminEditRegistry.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/modelRegistry/testArchiveModels.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/modelRegistry/testCreateModelRegistry.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/modelRegistry/testManageRegistryPermissions.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/modelRegistry/testRegisterModel.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/modelRegistry/testRegistryDeployModel.cy.ts
  frontend/src/__tests__/cypress/cypress/types.ts
  frontend/src/__tests__/cypress/cypress/utils/dataLoader.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/modelRegistry.ts
Labels: lgtm, approved, area/quality

#4828 quarantine testNotebookAdministration.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/applications/enabled/testNotebookAdministration.cy.ts
Labels: lgtm, approved, area/quality

#4830 Add root level dependency installation and npm caching to gen-ai frontend workflow
  .github/workflows/gen-ai-frontend-build.yml
Labels: lgtm, approved, ok-to-test

#4825 Add model format field to wizard
  frontend/src/__mocks__/mockInferenceServiceK8sResource.ts
  frontend/src/__mocks__/mockServingRuntimeTemplateK8sResource.ts
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingDeploy.cy.ts
  frontend/src/api/k8s/templates.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelServing/customServingRuntimes/utils.ts
  frontend/src/services/templateService.ts
  packages/kserve/extensions.ts
  packages/kserve/src/modelFormat.ts
  packages/model-serving/extension-points/index.ts
  packages/model-serving/src/components/deploymentWizard/EditModelDeploymentPage.tsx
  packages/model-serving/src/components/deploymentWizard/fields/ModelFormatField.tsx
  packages/model-serving/src/components/deploymentWizard/fields/ModelTypeSelectField.tsx
  packages/model-serving/src/components/deploymentWizard/fields/__tests__/ModelFormatField.test.tsx
  packages/model-serving/src/components/deploymentWizard/fields/__tests__/ModelTypeSelectField.test.tsx
  packages/model-serving/src/components/deploymentWizard/steps/ModelDeploymentStep.tsx
  packages/model-serving/src/components/deploymentWizard/steps/__tests__/ModelSourceStep.test.tsx
  packages/model-serving/src/components/deploymentWizard/useDeploymentWizard.ts
  packages/model-serving/src/components/deploymentWizard/useDeploymentWizardValidation.tsx
  packages/model-serving/src/components/deploymentWizard/utils.ts
  packages/model-serving/src/concepts/__tests__/useAvailableClusterPlatforms.spec.ts
  packages/model-serving/src/concepts/extensionUtils.ts
Labels: lgtm, approved, area/model-serving, area/quality

#4755 Ensure Archive model and Archive model version work correctly
  packages/model-registry/upstream/frontend/src/app/pages/modelRegistry/ModelRegistryRoutes.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelRegistry/screens/ModelVersions/ModelVersionsHeaderActions.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelRegistry/screens/ModelVersions/ModelVersionsTableRow.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelRegistry/screens/RegisteredModels/RegisteredModelListView.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelRegistry/screens/RegisteredModels/RegisteredModelTable.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelRegistry/screens/RegisteredModels/RegisteredModelTableRow.tsx
  packages/model-registry/upstream/frontend/src/odh/VersionDetailsTabExtensionRoutes.tsx
  packages/model-registry/upstream/frontend/src/odh/components/ArchiveButtonDropdownItem.tsx
  packages/model-registry/upstream/frontend/src/odh/components/OdhModelVersionDetails.tsx
  packages/model-registry/upstream/frontend/src/odh/components/OdhModelVersions.tsx
  packages/model-registry/upstream/frontend/src/odh/components/OdhModelVersionsTable.tsx
  packages/model-registry/upstream/frontend/src/odh/components/OdhRegisteredModelTable.tsx
  packages/model-registry/upstream/frontend/src/odh/utils/__tests__/deploymentUtils.spec.ts
  packages/model-registry/upstream/frontend/src/odh/utils/deploymentUtils.ts
Labels: lgtm, approved, area/model-registry

#4786 Feature Data sources
  frontend/src/__tests__/cypress/cypress/pages/featureStore/featureDataSource.ts
  frontend/src/__tests__/cypress/cypress/pages/featureStore/featureDataSourceDetails.ts
  frontend/src/__tests__/cypress/cypress/pages/featureStore/featureStoreGlobal.ts
  frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/featureStore/featureDataSources.cy.ts
  packages/feature-store/extensions.ts
  packages/feature-store/src/FeatureStoreRoutes.tsx
  packages/feature-store/src/__mocks__/mockDataSources.ts
  packages/feature-store/src/api/custom.ts
  packages/feature-store/src/apiHooks/__tests__/useFeatureStoreDataSourceByName.spec.ts
  packages/feature-store/src/apiHooks/__tests__/useFeatureStoreDataSources.spec.ts
  packages/feature-store/src/apiHooks/__tests__/useFeatureViews.test.tsx
  packages/feature-store/src/apiHooks/useFeatureStoreAPIState.tsx
  packages/feature-store/src/apiHooks/useFeatureStoreDataSourceByName.ts
  packages/feature-store/src/apiHooks/useFeatureStoreDataSources.ts
  packages/feature-store/src/apiHooks/useFeatureViews.tsx
  packages/feature-store/src/screens/dataSources/DataSources.tsx
  packages/feature-store/src/screens/dataSources/__tests__/utils.spec.ts
  packages/feature-store/src/screens/dataSources/const.ts
  packages/feature-store/src/screens/dataSources/dataSourceDetails/DataSourceDetailsPage.tsx
  packages/feature-store/src/screens/dataSources/dataSourceDetails/DataSourceDetailsView.tsx
  packages/feature-store/src/screens/dataSources/dataSourceDetails/DataSourceTabs.tsx
  packages/feature-store/src/screens/dataSources/dataSourceTable/FeatureStoreDataSourceListView.tsx
  packages/feature-store/src/screens/dataSources/dataSourceTable/FeatureStoreDataSourceTable.tsx
  packages/feature-store/src/screens/dataSources/dataSourceTable/FeatureStoreDataSourceTableRow.tsx
  packages/feature-store/src/screens/dataSources/utils.ts
  packages/feature-store/src/screens/metrics/PopularTags.tsx
  packages/feature-store/src/types/dataSources.ts
  packages/feature-store/src/types/featureView.ts
  packages/feature-store/src/types/global.ts
  packages/feature-store/src/utils/lineageDataConverter.ts
Labels: lgtm, approved, area/quality, area/feature-store-modular-ui

#4813 Fix videoPath in cypress.config.ts
  frontend/src/__tests__/cypress/cypress.config.ts
  packages/model-registry/upstream/frontend/src/__tests__/cypress/cypress.config.ts
Labels: lgtm, approved, area/model-registry, area/quality

#4838 add fix for gen-ai ci failure
  .github/workflows/gen-ai-frontend-build.yml
Labels: lgtm, approved

#4745 RHOAIENG-32537: Create the Project Namespace Dropdown for choosing the LS
  packages/gen-ai/frontend/.eslintrc.js
  packages/gen-ai/frontend/config/webpack.common.js
  packages/gen-ai/frontend/config/webpack.dev.js
  packages/gen-ai/frontend/config/webpack.prod.js
  packages/gen-ai/frontend/package.json
  packages/gen-ai/frontend/src/app/Chatbot/ChatbotHeader.tsx
  packages/gen-ai/frontend/src/app/Chatbot/ChatbotMain.tsx
  packages/gen-ai/frontend/src/app/Chatbot/components/ProjectDropdown.tsx
  packages/gen-ai/frontend/src/app/hooks/useGenaiNamespaces.ts
  packages/gen-ai/frontend/src/app/services/llamaStackService.ts
  packages/gen-ai/frontend/src/app/types.ts
Labels: lgtm, approved, ok-to-test, area/llama-stack-modular-ui

#4839 RHOAIENG-32237: Update Resource requests and limits section in hardware profiles creation page
  frontend/src/__tests__/cypress/cypress/pages/hardwareProfile.ts
  frontend/src/pages/hardwareProfiles/nodeResource/NodeResourceForm.tsx
  frontend/src/pages/hardwareProfiles/nodeResource/NodeResourceTableRow.tsx
  frontend/src/pages/hardwareProfiles/nodeResource/const.ts
Labels: lgtm, approved, area/quality

#4852 Fixing type error in kserve extension import
  packages/model-serving/src/components/deploymentWizard/utils.ts
Labels: lgtm, approved, area/model-serving

#4853 Overriding form-data package to solve CVE
  frontend/package.json
Labels: lgtm, approved

#4820 github action to check package-lock.json integrity
  .github/workflows/test.yml
  scripts/check-package-lock.sh
Labels: lgtm, approved

#4840 Enable modular architecture in RHOAI
  manifests/odh/kustomization.yaml
  manifests/rhoai/shared/base/kustomization.yaml
Labels: lgtm, approved

#4837 Global search component
  frontend/src/__tests__/cypress/cypress/pages/featureStore/featureStoreGlobal.ts
  frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/featureStore/featureDataSources.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/featureStore/featureEntities.cy.ts
  packages/feature-store/src/FeatureStore.tsx
  packages/feature-store/src/__mocks__/mockGlobalSearch.ts
  packages/feature-store/src/api/custom.ts
  packages/feature-store/src/apiHooks/useFeatureStoreAPIState.tsx
  packages/feature-store/src/apiHooks/useFeatureStoreSearch.ts
  packages/feature-store/src/apiHooks/useGlobalSearch.ts
  packages/feature-store/src/components/FeatureStoreGlobalSearch/GlobalSearchInput.tsx
  packages/feature-store/src/components/FeatureStoreGlobalSearch/LoadMoreFooter.tsx
  packages/feature-store/src/components/FeatureStoreGlobalSearch/const.ts
  packages/feature-store/src/components/FeatureStoreGlobalSearch/hooks/__tests__/useResponsiveSearch.spec.ts
  packages/feature-store/src/components/FeatureStoreGlobalSearch/hooks/__tests__/useSearchHandlers.spec.ts
  packages/feature-store/src/components/FeatureStoreGlobalSearch/hooks/__tests__/useSearchState.spec.ts
  packages/feature-store/src/components/FeatureStoreGlobalSearch/hooks/useResponsiveSearch.ts
  packages/feature-store/src/components/FeatureStoreGlobalSearch/hooks/useSearchHandlers.ts
  packages/feature-store/src/components/FeatureStoreGlobalSearch/hooks/useSearchState.ts
  packages/feature-store/src/components/FeatureStoreGlobalSearch/utils/__tests__/searchUtils.spec.ts
  packages/feature-store/src/components/FeatureStoreGlobalSearch/utils/searchUtils.ts
  packages/feature-store/src/components/FeatureStorePageTitle.tsx
  packages/feature-store/src/screens/dataSets/DataSetDetails/DataSetDetails.tsx
  packages/feature-store/src/screens/dataSets/FeatureStoreDataSets.tsx
  packages/feature-store/src/screens/dataSources/DataSources.tsx
  packages/feature-store/src/screens/dataSources/dataSourceDetails/DataSourceDetailsPage.tsx
  packages/feature-store/src/screens/entities/EntitiesDetails/EntitiesDetailsPage.tsx
  packages/feature-store/src/screens/entities/FeatureStoreEntities.tsx
  packages/feature-store/src/screens/featureServices/FeatureServices.tsx
  packages/feature-store/src/screens/featureServices/featureServiceDetails/FeatureServiceDetails.tsx
  packages/feature-store/src/screens/featureViews/FeatureViews.tsx
  packages/feature-store/src/screens/featureViews/featureViewDetails/FeatureViewDetails.tsx
  packages/feature-store/src/screens/features/Features.tsx
  packages/feature-store/src/screens/features/featureDetails/FeatureDetails.tsx
  packages/feature-store/src/types/global.ts
  packages/feature-store/src/types/search.ts
Labels: lgtm, approved, area/quality, area/feature-store

#4868 Lineage feature view
  frontend/src/__tests__/cypress/cypress/pages/featureStore/featureDataSourceDetails.ts
  frontend/src/components/MultiSelection.tsx
  frontend/src/components/lineage/types.ts
  packages/feature-store/src/api/custom.ts
  packages/feature-store/src/apiHooks/useFeatureStoreAPIState.tsx
  packages/feature-store/src/apiHooks/useFeatureViewLineage.ts
  packages/feature-store/src/components/FeatureStoreLineageToolbar.tsx
  packages/feature-store/src/screens/dataSources/dataSourceDetails/DataSourceTabs.tsx
  packages/feature-store/src/screens/featureViews/featureViewDetails/FeatureViewLineage.tsx
  packages/feature-store/src/screens/featureViews/featureViewDetails/FeatureViewLineageTab.tsx
  packages/feature-store/src/screens/lineage/FeatureStoreLineage.tsx
  packages/feature-store/src/screens/lineage/FeatureStoreLineageComponent.tsx
  packages/feature-store/src/screens/lineage/node/FeatureStoreLineageNodePopover.tsx
  packages/feature-store/src/screens/lineage/utils.ts
  packages/feature-store/src/types/global.ts
  packages/feature-store/src/types/lineage.ts
  packages/feature-store/src/types/toolbarTypes.ts
  packages/feature-store/src/utils/lineageDataConverter.ts
Labels: lgtm, approved, area/quality, area/feature-store

#4880 Quarantine NIM e2e Test RHOAIENG-34177
  frontend/src/__tests__/cypress/cypress/tests/e2e/nim/testEnableNIM.cy.ts
Labels: lgtm, approved, area/quality

#4787 RHOAIENG-33402: BFF to fetch MCP list
  packages/gen-ai/bff/Makefile
  packages/gen-ai/bff/README.md
  packages/gen-ai/bff/cmd/main.go
  packages/gen-ai/bff/go.mod
  packages/gen-ai/bff/go.sum
  packages/gen-ai/bff/internal/api/app.go
  packages/gen-ai/bff/internal/api/mcp_helpers.go
  packages/gen-ai/bff/internal/api/mcp_helpers_test.go
  packages/gen-ai/bff/internal/api/mcp_list_handler.go
  packages/gen-ai/bff/internal/api/mcp_list_handler_test.go
  packages/gen-ai/bff/internal/api/mcp_status_handler.go
  packages/gen-ai/bff/internal/api/mcp_status_handler_test.go
  packages/gen-ai/bff/internal/api/mcp_tools_handler.go
  packages/gen-ai/bff/internal/api/mcp_tools_handler_test.go
  packages/gen-ai/bff/internal/config/environment.go
  packages/gen-ai/bff/internal/constants/api_constants.go
  packages/gen-ai/bff/internal/constants/mcp.go
  packages/gen-ai/bff/internal/integrations/kubernetes/client.go
  packages/gen-ai/bff/internal/integrations/kubernetes/k8smocks/token_k8s_client_mock.go
  packages/gen-ai/bff/internal/integrations/kubernetes/token_k8s_client.go
  packages/gen-ai/bff/internal/integrations/mcp/client.go
  packages/gen-ai/bff/internal/integrations/mcp/config.go
  packages/gen-ai/bff/internal/integrations/mcp/errors.go
  packages/gen-ai/bff/internal/integrations/mcp/factory.go
  packages/gen-ai/bff/internal/integrations/mcp/mcpmocks/mock_client.go
  packages/gen-ai/bff/internal/integrations/mcp/mcpmocks/mock_factory.go
  packages/gen-ai/bff/internal/integrations/mcp/simple_client.go
  packages/gen-ai/bff/internal/integrations/mcp/transport_factory.go
  packages/gen-ai/bff/internal/integrations/types.go
  packages/gen-ai/bff/internal/models/genaiassets/aa_mcp.go
  packages/gen-ai/bff/internal/repositories/mcp_client.go
  packages/gen-ai/bff/internal/repositories/repositories.go
  packages/gen-ai/bff/openapi/src/gen-ai.yaml
Labels: lgtm, approved, area/llama-stack-modular-ui

#4723 Contract Testing implementation
  .github/workflows/test.yml
  .gitignore
  package-lock.json
  package.json
  packages/contract-tests/.eslintrc.js
  packages/contract-tests/README.md
  packages/contract-tests/jest.preset.js
  packages/contract-tests/package.json
  packages/contract-tests/scripts/run-consumer-with-mock-bff.sh
  packages/contract-tests/scripts/run-go-bff-consumer.sh
  packages/contract-tests/src/bff-health.ts
  packages/contract-tests/src/bff.ts
  packages/contract-tests/src/helpers/logging.ts
  packages/contract-tests/src/helpers/setup.ts
  packages/contract-tests/src/helpers/shell-helpers.sh
  packages/contract-tests/src/index.ts
  packages/contract-tests/src/logging.ts
  packages/contract-tests/src/matchers/toMatchContract.ts
  packages/contract-tests/src/mocks/ansi-regex.js
  packages/contract-tests/src/openapi-validator.ts
  packages/contract-tests/src/reporting/generate-html-report.ts
  packages/contract-tests/src/reporting/report-style.css
  packages/contract-tests/src/runner.ts
  packages/contract-tests/src/schema-converter.ts
  packages/contract-tests/src/schema-helpers.ts
  packages/contract-tests/src/schema-validator.ts
  packages/contract-tests/src/utils/api-client.ts
  packages/contract-tests/src/utils/bff-verification.ts
  packages/contract-tests/src/utils/schema-validation.ts
  packages/contract-tests/tsconfig.json
  packages/model-registry/contract-tests/__tests__/testModelRegistryContract.test.ts
  packages/model-registry/jest.config.ts
  packages/model-registry/package.json
  turbo.json
Labels: lgtm, approved, area/model-registry, area/quality

#4827 Add AI assets page and models tab
  packages/gen-ai/frontend/src/app/AIAssets/AIAssetsPage.tsx
  packages/gen-ai/frontend/src/app/AppRoutes.tsx
  packages/gen-ai/frontend/src/app/Chatbot/ChatbotMain.tsx
  packages/gen-ai/frontend/src/app/EmptyStates/NoData.tsx
  packages/gen-ai/frontend/src/app/EmptyStates/NotFound.tsx
  packages/gen-ai/frontend/src/odh/extensions.ts
Labels: lgtm, approved, ok-to-test

#4890 re-generate package-lock.json
  .github/workflows/test.yml
  package-lock.json
Labels: lgtm, approved

#4876 cypress mock test support for modules
  .github/workflows/test.yml
  backend/package.json
  backend/src/routes/module-federation.ts
  backend/src/utils/proxy.ts
  backend/tsconfig.json
  frontend/config/moduleFederation.js
  frontend/config/webpack.dev.js
  frontend/package.json
  frontend/src/__tests__/cypress/cypress.config.ts
  frontend/src/__tests__/cypress/cypress/support/e2e.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelRegistryKF.cy.ts
  frontend/src/__tests__/cypress/package.json
  package-lock.json
  package.json
  packages/app-config/.eslintrc.js
  packages/app-config/package.json
  packages/app-config/scripts/package-subtree.sh
  packages/app-config/src/index.ts
  packages/app-config/src/module-federation.ts
  packages/app-config/src/node/index.ts
  packages/app-config/src/node/module-federation.ts
  packages/app-config/src/types.ts
  packages/app-config/tsconfig.json
  packages/gen-ai/package.json
  packages/lm-eval/package.json
  packages/model-registry/contract-tests/contract-test-results/20250916_122213/artifacts/bff-mock.log
  packages/model-registry/contract-tests/contract-test-results/20250916_122213/artifacts/contract-test-report.html
  packages/model-registry/contract-tests/contract-test-results/20250916_122213/bff-mock.log
  packages/model-registry/contract-tests/contract-test-results/20250916_122213/bff.pid
  packages/model-registry/contract-tests/contract-test-results/20250916_122213/contract-test-output.log
  packages/model-registry/contract-tests/contract-test-results/20250916_122213/contract-test-report.html
  packages/model-registry/package.json
  packages/tsconfig/tsconfig.json
  turbo.json
  turbo.jsonc
Labels: lgtm, approved, area/model-registry, area/platform, area/quality

#4823 Add Deployments column extension for Model Registry
  frontend/@mf-types/@mf/modelRegistry/compiled-types/src/odh/extension-points/index.d.ts
  frontend/@mf-types/@mf/modelRegistry/compiled-types/src/odh/extension-points/table.d.ts
  packages/model-registry/upstream/frontend/src/app/pages/modelRegistry/screens/ModelRegistry.tsx
  packages/model-registry/upstream/frontend/src/odh/components/ExtendedRegisteredModelListView.tsx
  packages/model-registry/upstream/frontend/src/odh/components/ExtendedRegisteredModelTable.tsx
  packages/model-registry/upstream/frontend/src/odh/components/ExtendedRegisteredModelTableRow.tsx
  packages/model-registry/upstream/frontend/src/odh/extension-points/index.ts
  packages/model-registry/upstream/frontend/src/odh/extension-points/table.ts
  packages/model-serving/extensions/model-registry.ts
  packages/model-serving/modelRegistry/DeploymentsColumn.tsx
Labels: lgtm, approved, area/model-registry, area/model-serving

#4864 Replace KServe setting with Serving Refactor
  frontend/src/__mocks__/mockSupportedAreasData.ts
  frontend/src/concepts/areas/__tests__/utils.spec.ts
  frontend/src/concepts/areas/const.ts
  frontend/src/concepts/areas/utils.ts
  frontend/src/plugins/extensions/navigation.ts
  packages/model-serving/extensions/odh.ts
  packages/model-serving/src/components/deploy/DeployButton.tsx
Labels: lgtm, approved, area/model-serving

#4898 Update Cypress tests: remove quarantine and improve test configurations
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/dataScienceProjects/testNotebookCreation.yaml
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataSciencePipelines/createRunDeletePipelineCustomPipMirror.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataSciencePipelines/pipelines.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/servingRuntimes/testSingleServingRuntimeCreation.cy.ts
Labels: lgtm, approved, area/quality

#4902 revert change to backend for module-federation
  backend/package.json
  backend/src/routes/module-federation.ts
  backend/src/utils/proxy.ts
  backend/tsconfig.json
Labels: lgtm, approved

#4904 Sync from kubeflow/model-registry cf8b04a
  package-lock.json
  packages/model-registry/package.json
  packages/model-registry/upstream/Makefile
  packages/model-registry/upstream/api/openapi/mod-arch.yaml
  packages/model-registry/upstream/bff/Makefile
  packages/model-registry/upstream/bff/cmd/main.go
  packages/model-registry/upstream/bff/go.mod
  packages/model-registry/upstream/bff/go.sum
  packages/model-registry/upstream/bff/go.work.sum
  packages/model-registry/upstream/bff/internal/api/app.go
  packages/model-registry/upstream/bff/internal/api/middleware.go
  packages/model-registry/upstream/bff/internal/config/environment.go
  packages/model-registry/upstream/bff/internal/integrations/httpclient/http.go
  packages/model-registry/upstream/bff/internal/integrations/httpclient/http_test.go
  packages/model-registry/upstream/bff/internal/integrations/kubernetes/k8mocks/base_testenv.go
  packages/model-registry/upstream/bff/internal/mocks/model_catalog_client_mock.go
  packages/model-registry/upstream/bff/internal/mocks/static_data_mock.go
  packages/model-registry/upstream/frontend/src/__tests__/cypress/cypress/support/commands/api.ts
  packages/model-registry/upstream/frontend/src/app/api/modelCatalog/service.ts
  packages/model-registry/upstream/frontend/src/app/context/modelCatalog/ModelCatalogContext.tsx
  packages/model-registry/upstream/frontend/src/app/hooks/modelCatalog/useCatalogModelsBySource.ts
  packages/model-registry/upstream/frontend/src/app/modelCatalogTypes.ts
  packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/EmptyModelCatalogState.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/ModelCatalogCoreLoader.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/ModelCatalogRoutes.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/screens/InvalidCatalogSource.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/screens/ModelCatalog.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/screens/ModelCatalogPage.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/screens/ModelCatalogSourceSelector.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/screens/ModelCatalogSourceSelectorNavigator.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/screens/ModelDetailsPage.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/utils/modelCatalogUtils.ts
  packages/model-registry/upstream/frontend/src/app/pages/modelRegistry/screens/components/ThemeAwareSearchInput.tsx
Labels: lgtm, approved, area/model-registry, area/quality

#4885 Feature store Icons
  frontend/src/__tests__/cypress/cypress/pages/featureStore/featureMetrics.ts
  frontend/src/__tests__/cypress/cypress/pages/featureStore/featureStoreGlobal.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/featureStore/featureMetrics.cy.ts
  frontend/src/components/lineage/Lineage.tsx
  frontend/src/concepts/design/vars.scss
  packages/feature-store/src/FeatureStore.tsx
  packages/feature-store/src/components/FeatureStoreLineageToolbar.tsx
  packages/feature-store/src/components/FeatureStoreObjectIcon.tsx
  packages/feature-store/src/components/FeatureStorePageTitle.tsx
  packages/feature-store/src/icons/header-icons/DataSetIcon.ts
  packages/feature-store/src/icons/header-icons/DataSourceIcon.ts
  packages/feature-store/src/icons/header-icons/EntityIcon.ts
  packages/feature-store/src/icons/header-icons/FeatureIcon.ts
  packages/feature-store/src/icons/header-icons/FeatureServiceIcon.ts
  packages/feature-store/src/icons/header-icons/FeatureStoreIcon.ts
  packages/feature-store/src/icons/header-icons/FeatureViewIcon.ts
  packages/feature-store/src/icons/lineage-icons/DataSourceIcon.ts
  packages/feature-store/src/icons/lineage-icons/EntityIcon.ts
  packages/feature-store/src/icons/lineage-icons/FeatureServiceIcon.ts
  packages/feature-store/src/icons/lineage-icons/FeatureViewIcon.ts
  packages/feature-store/src/screens/components/FeatureStoreProjectSelector.tsx
  packages/feature-store/src/screens/dataSets/FeatureStoreDataSets.tsx
  packages/feature-store/src/screens/dataSources/DataSources.tsx
  packages/feature-store/src/screens/entities/FeatureStoreEntities.tsx
  packages/feature-store/src/screens/featureServices/FeatureServices.tsx
  packages/feature-store/src/screens/featureViews/FeatureViews.tsx
  packages/feature-store/src/screens/featureViews/featureViewDetails/FeatureViewLineageTab.tsx
  packages/feature-store/src/screens/featureViews/featureViewDetails/FeatureViewTabs.tsx
  packages/feature-store/src/screens/features/Features.tsx
  packages/feature-store/src/screens/lineage/node/FeatureStoreLineageNodePopover.tsx
  packages/feature-store/src/screens/metrics/MetricCards.tsx
  packages/feature-store/src/screens/metrics/Metrics.tsx
  packages/feature-store/src/screens/metrics/PopularTags.tsx
  packages/feature-store/src/screens/metrics/RecentlyVisitedResources.tsx
  packages/feature-store/src/screens/metrics/__tests__/utils.spec.ts
  packages/feature-store/src/screens/metrics/utils.ts
  packages/feature-store/src/utils.ts
  packages/feature-store/src/utils/featureStoreObjects.tsx
Labels: lgtm, approved, area/quality, area/feature-store

#4849 feat: Added Environment Variables Support for NIM Deployments
  frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx
  frontend/src/pages/modelServing/screens/projects/NIMServiceModal/__tests__/ManageNIMServingModal.spec.tsx
Labels: lgtm, approved, ok-to-test, area/model-serving

#4913 Update default port for genai since module federation port was updated
  packages/gen-ai/frontend/config/dotenv.js
Labels: lgtm, approved

#4887 RHOAIENG-34068: Implement open configuration for storage class
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/clusterStorage.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/storageClasses/storageClasses.cy.ts
  frontend/src/pages/projects/screens/spawner/storage/AccessModeField.tsx
  frontend/src/pages/projects/screens/spawner/storage/CreateNewStorageSection.tsx
  frontend/src/pages/projects/screens/spawner/storage/__tests__/utils.spec.ts
  frontend/src/pages/projects/screens/spawner/storage/getAccessModePopover.tsx
  frontend/src/pages/projects/screens/spawner/storage/useGetStorageClassConfig.ts
  frontend/src/pages/storageClasses/StorageClassEditModal.tsx
  frontend/src/pages/storageClasses/StorageClassesContext.tsx
  frontend/src/pages/storageClasses/StorageClassesTableRow.tsx
  frontend/src/pages/storageClasses/__tests__/StorageClassEditModal.spec.tsx
  frontend/src/pages/storageClasses/__tests__/utils.spec.ts
  frontend/src/pages/storageClasses/utils.ts
Labels: lgtm, approved, feature/storage-classes, area/quality

#4914 add namespace query params to llama stack service call
  packages/gen-ai/frontend/src/app/Chatbot/hooks/__tests__/useChatbotMessages.spec.ts
  packages/gen-ai/frontend/src/app/Chatbot/hooks/useChatbotMessages.ts
  packages/gen-ai/frontend/src/app/Chatbot/hooks/useSourceManagement.ts
  packages/gen-ai/frontend/src/app/Chatbot/sourceUpload/ChatbotSourceSettingsModal.tsx
  packages/gen-ai/frontend/src/app/hooks/useFetchVectorStores.ts
  packages/gen-ai/frontend/src/app/services/llamaStackService.ts
Labels: lgtm, approved

#4905 Enabling feature flag for feature store in the crd
  backend/src/types.ts
  backend/src/utils/constants.ts
  frontend/src/concepts/areas/const.ts
  manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
  packages/feature-store/extensions.ts
Labels: lgtm, approved, area/feature-store

#4930 Update model-registry-ui-image tag from latest to main
  manifests/modular-architecture/params.env
Labels: lgtm, approved

#4934 [feat] Add deletion endpoint for LSD
  packages/gen-ai/bff/internal/api/app.go
  packages/gen-ai/bff/internal/api/llamastack_distribution_handler_delete.go
  packages/gen-ai/bff/internal/api/llamastack_distribution_handler_test.go
  packages/gen-ai/bff/internal/constants/api_constants.go
  packages/gen-ai/bff/internal/integrations/kubernetes/client.go
  packages/gen-ai/bff/internal/integrations/kubernetes/k8smocks/token_k8s_client_mock.go
  packages/gen-ai/bff/internal/integrations/kubernetes/token_k8s_client.go
  packages/gen-ai/bff/internal/models/llamastack_distribution.go
  packages/gen-ai/bff/internal/repositories/llamastack_distribution.go
Labels: lgtm, approved

#4831 changed mr route to default to upstream
  frontend/src/__mocks__/mockModelRegistryService.ts
  frontend/src/__tests__/cypress/cypress/pages/modelRegistry/modelVersionArchive.ts
  frontend/src/__tests__/cypress/cypress/pages/modelRegistry/modelVersionDetails.ts
  frontend/src/__tests__/cypress/cypress/pages/modelRegistry/registerModelPage.ts
  frontend/src/__tests__/cypress/cypress/pages/modelRegistry/registerVersionPage.ts
  frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelRegistry.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelRegistryKF.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionArchive.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDeploy.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDetails.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersions.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/registerModel.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/registerVersion.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/registeredModelArchive.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts
  frontend/src/app/navigation/__tests__/navSidebar.spec.tsx
  frontend/src/k8sTypes.ts
  frontend/src/plugins/extensions/navigation.ts
  frontend/src/plugins/extensions/routes.ts
  packages/model-registry/src/connection/AutofillConnectionButton.tsx
  packages/model-registry/upstream/frontend/src/odh/ModelRegistryWrapper.tsx
  packages/model-registry/upstream/frontend/src/odh/extensions.ts
Labels: lgtm, approved, area/model-registry, area/model-serving, area/platform, area/quality

#4937 Sync from kubeflow/model-registry b9cea72
  packages/model-registry/package.json
  packages/model-registry/upstream/bff/Makefile
  packages/model-registry/upstream/bff/go.work.sum
  packages/model-registry/upstream/bff/internal/api/middleware.go
  packages/model-registry/upstream/bff/internal/constants/keys.go
  packages/model-registry/upstream/bff/internal/integrations/kubernetes/client.go
  packages/model-registry/upstream/bff/internal/integrations/kubernetes/internal_k8s_client.go
  packages/model-registry/upstream/bff/internal/integrations/kubernetes/k8mocks/internal_k8s_client_mock.go
  packages/model-registry/upstream/bff/internal/integrations/kubernetes/k8mocks/token_k8s_client_mock.go
  packages/model-registry/upstream/bff/internal/integrations/kubernetes/shared_k8s_client.go
  packages/model-registry/upstream/bff/internal/integrations/kubernetes/tests/internal_k8s_client_test.go
  packages/model-registry/upstream/bff/internal/integrations/kubernetes/token_k8s_client.go
  packages/model-registry/upstream/bff/internal/mocks/model_catalog_client_mock.go
  packages/model-registry/upstream/bff/internal/models/model_registry.go
  packages/model-registry/upstream/bff/internal/repositories/model_catalog.go
  packages/model-registry/upstream/bff/internal/repositories/model_registry.go
  packages/model-registry/upstream/bff/internal/repositories/model_registry_test.go
  packages/model-registry/upstream/frontend/package-lock.json
  packages/model-registry/upstream/frontend/package.json
Labels: lgtm, approved, area/model-registry

#4875 changed model catalog routes to default to upstream
  backend/src/utils/constants.ts
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalog.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalogDeploy.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelDetailsPage.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/registerCatalogModel.cy.ts
  frontend/src/concepts/areas/const.ts
  frontend/src/plugins/extensions/navigation.ts
  frontend/src/plugins/extensions/routes.ts
  packages/model-registry/upstream/frontend/src/odh/ModelCatalogWrapper.tsx
  packages/model-registry/upstream/frontend/src/odh/extensions.ts
Labels: lgtm, approved, area/model-registry, area/quality

#4916 Remove LlamaStack proxy handler
  packages/gen-ai/bff/internal/api/app.go
  packages/gen-ai/bff/internal/api/app_test.go
  packages/gen-ai/bff/internal/api/proxy_handler.go
Labels: lgtm, approved

#4824 Added a warning for Legacy NVIDIA API keys when enabling NIM
  backend/src/types.ts
  frontend/src/__mocks__/mockComponents.ts
  frontend/src/__tests__/cypress/cypress/pages/components/WarningValidationCard.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/applications/explore.cy.ts
  frontend/src/pages/exploreApplication/EnableModal.tsx
  frontend/src/types.ts
  manifests/common/crd/odhapplications.dashboard.opendatahub.io.crd.yaml
  manifests/rhoai/shared/apps/nvidia-nim/nvidia-nim-app.yaml
Labels: lgtm, approved, ok-to-test, area/quality

#4940 Fix row expansion issue after reordering
  frontend/src/pages/hardwareProfiles/HardwareProfiles.tsx
Labels: lgtm, approved

#4920 chore: Add pgvector resource tile
  manifests/rhoai/shared/apps/kustomization.yaml
  manifests/rhoai/shared/apps/pgvector/kustomization.yaml
  manifests/rhoai/shared/apps/pgvector/pgvector-app.yaml
Labels: lgtm, approved

#4917 Add Cypress E2E GitHub Actions workflow
  .github/workflows/cypress-e2e-test.yml
  frontend/package.json
Labels: lgtm, approved, area/quality

#4948 Sync from kubeflow/model-registry bbb91eb
  packages/model-registry/package.json
  packages/model-registry/upstream/frontend/src/app/hooks/modelCatalog/useCatalogModelsBySource.ts
  packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/components/ModelCatalogCard.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/screens/ModelCatalogPage.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/screens/ModelDetailsPage.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelRegistry/screens/ModelVersions/ModelVersionListView.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelRegistry/screens/ModelVersions/ModelVersionsCard.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelRegistry/screens/ModelVersionsArchive/ModelVersionsArchiveListView.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelRegistry/screens/RegisteredModels/RegisteredModelListView.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelRegistry/screens/RegisteredModelsArchive/RegisteredModelsArchiveListView.tsx
  packages/model-registry/upstream/frontend/src/odh/components/ExtendedRegisteredModelListView.tsx
Labels: lgtm, approved, area/model-registry

#4970 Clean cypress backport
  frontend/src/__tests__/cypress/cypress/support/e2e.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/applications/testAboutDialog.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dashboardNavigation/testApplicationLinks.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchControlSuite.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchStatus.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchVariables.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/workbenches.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/learningResources/testResourcesfilters.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/storageClasses/storageClasses.cy.ts
Labels: lgtm, area/quality

#4963 Show llmd deployments alongside other platforms
  frontend/src/__mocks__/mockLLMInferenceServiceK8sResource.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingLlmd.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/projectDetails.cy.ts
  packages/kserve/extensions.ts
  packages/kserve/src/api.ts
  packages/kserve/src/components/deploymentServingDetails.tsx
  packages/kserve/src/deployments.ts
  packages/llmd-serving/extensions/index.ts
  packages/llmd-serving/package.json
  packages/llmd-serving/src/components/servingRuntime.tsx
  packages/llmd-serving/src/deployments/useWatchDeployments.ts
  packages/llmd-serving/src/index.ts
  packages/llmd-serving/src/types.ts
  packages/model-serving/extension-points/index.ts
  packages/model-serving/modelRegistry/DeploymentsContextProvider.tsx
  packages/model-serving/modelRegistry/ModelDetailsDeploymentCard.tsx
  packages/model-serving/modelRegistry/ModelWideDeploymentsTab.tsx
  packages/model-serving/modelRegistry/VersionDeploymentsTab.tsx
  packages/model-serving/src/ModelsProjectDetailsTab.tsx
  packages/model-serving/src/ServeModelsSection.tsx
  packages/model-serving/src/components/deploymentWizard/CreateModelDeploymentPage.tsx
  packages/model-serving/src/components/deploymentWizard/EditModelDeploymentPage.tsx
  packages/model-serving/src/components/deployments/DeploymentsTableRow.tsx
  packages/model-serving/src/components/deployments/__tests__/DeploymentsTableRow.spec.tsx
  packages/model-serving/src/components/global/GlobalModelsPage.tsx
  packages/model-serving/src/components/projectDetails/ProjectDeploymentsTable.tsx
  packages/model-serving/src/concepts/ModelDeploymentsContext.tsx
  packages/model-serving/src/concepts/deploymentUtils.ts
Labels: lgtm, approved, area/model-serving, area/quality

#4966 Sync from kubeflow/model-registry 0f52126
  packages/model-registry/package.json
  packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/components/ModelCatalogCard.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/components/ModelCatalogFilters.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/components/ModelCatalogLabels.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/screens/ModelCatalog.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/screens/ModelDetailsView.tsx
Labels: lgtm, approved, area/model-registry

#4967 Cherry-pick model catalog fixes: label rendering issue and a11y issue
  packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/components/ModelCatalogCard.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/components/ModelCatalogLabels.tsx
  packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/screens/ModelDetailsView.tsx
Labels: lgtm, approved, area/model-registry

#4969 Add override for rhoai for modular architeture
  manifests/rhoai/shared/base/federation-configmap.yaml
  manifests/rhoai/shared/base/kustomization.yaml
Labels: lgtm, approved

#4888 Follow up to add token auth
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingDeploy.cy.ts
  packages/kserve/src/deploy.ts
  packages/kserve/src/deployUtils.ts
  packages/model-serving/src/components/deploymentWizard/steps/__tests__/ModelSourceStep.test.tsx
Labels: lgtm, approved, area/model-serving, area/quality

#4964 Fix re-render loop
  frontend/src/pages/hardwareProfiles/HardwareProfiles.tsx
Labels: lgtm, approved

#4977 [Cherry-pick 2.x] Add override for rhoai for modular architecture
  manifests/rhoai/shared/base/federation-configmap.yaml
  manifests/rhoai/shared/base/kustomization.yaml
Labels: lgtm, approved

#4980 fixed axios cve
  package-lock.json
  packages/gen-ai/frontend/package-lock.json
Labels: lgtm, approved

#4985 set default retries for mock tests to 2
  frontend/src/__tests__/cypress/cypress.config.ts
Labels: lgtm, approved, area/quality

#4994 Cherry-pick - Featurestore(Review changes -2)
  frontend/src/__tests__/cypress/cypress/tests/mocked/featureStore/featureDataSources.cy.ts
  frontend/src/components/lineage/Lineage.tsx
  packages/feature-store/src/FeatureStore.tsx
  packages/feature-store/src/components/FeatureStoreLineageToolbar.tsx
  packages/feature-store/src/screens/dataSources/dataSourceDetails/DataSourceDetailsPage.tsx
  packages/feature-store/src/screens/dataSources/dataSourceDetails/DataSourceDetailsView.tsx
  packages/feature-store/src/screens/dataSources/dataSourceDetails/DataSourceTabs.tsx
Labels: lgtm, approved, area/quality, area/feature-store

#4997 fix HMR for start:dev:ext
  frontend/config/webpack.dev.js
Labels: lgtm, approved

#4988 RHOAIENG-27684: The workbench image column shows Deleted label after RHOAI upgrade
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/projectDetails.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/workbench.cy.ts
  frontend/src/pages/projects/screens/detail/notebooks/__tests__/useNotebookImageData.spec.ts
  frontend/src/pages/projects/screens/detail/notebooks/useNotebookImageData.ts
Labels: lgtm, approved, area/quality

#4993 add unit test for hooks and api
  packages/gen-ai/frontend/src/__mocks__/mockLlamaStackDistribution.ts
  packages/gen-ai/frontend/src/__mocks__/mockLlamaStackModels.ts
  packages/gen-ai/frontend/src/__mocks__/mockVectorStores.ts
  packages/gen-ai/frontend/src/__tests__/unit/jest.setup.ts
  packages/gen-ai/frontend/src/app/Chatbot/hooks/__tests__/useSourceManagement.spec.ts
  packages/gen-ai/frontend/src/app/Chatbot/hooks/useSourceManagement.ts
  packages/gen-ai/frontend/src/app/hooks/__tests__/useFetchLSDStatus.spec.ts
  packages/gen-ai/frontend/src/app/hooks/__tests__/useFetchLlamaModels.spec.ts
  packages/gen-ai/frontend/src/app/hooks/__tests__/useFetchVectorStores.spec.ts
  packages/gen-ai/frontend/src/app/hooks/__tests__/useSyncPreferredNamespace.spec.ts
  packages/gen-ai/frontend/src/app/hooks/useSyncPreferredNamespace.ts
  packages/gen-ai/frontend/src/app/services/__tests__/llamaStackService.spec.ts
Labels: lgtm, approved

#5010 feat: update page headers to match their nav entry
  frontend/src/__tests__/cypress/cypress/pages/featureStore/featureEntities.ts
  frontend/src/__tests__/cypress/cypress/pages/featureStore/featureMetrics.ts
  packages/feature-store/src/components/FeatureStoreGlobalSearch/const.ts
  packages/feature-store/src/components/FeatureStoreGlobalSearch/utils/__tests__/searchUtils.spec.ts
  packages/feature-store/src/screens/dataSources/dataSourceDetails/DataSourceDetailsPage.tsx
  packages/feature-store/src/screens/dataSources/dataSourceTable/FeatureStoreDataSourceTableRow.tsx
  packages/feature-store/src/screens/entities/EntitiesTable/FeatureStoreEntitiesTableRow.tsx
  packages/feature-store/src/screens/featureServices/FeatureServices.tsx
  packages/feature-store/src/screens/featureViews/FeatureViewTableRow.tsx
  packages/feature-store/src/screens/featureViews/const.ts
  packages/feature-store/src/screens/metrics/PopularTags.tsx
  packages/feature-store/src/utils.ts
  packages/gen-ai/frontend/src/app/AppRoutes.tsx
  packages/gen-ai/frontend/src/app/Chatbot/ChatbotHeader.tsx
Labels: lgtm, approved, area/quality, area/feature-store

#5019 Remove ordering functionality from legacy profiles table
  frontend/src/pages/hardwareProfiles/HardwareProfilesTable.tsx
  frontend/src/pages/hardwareProfiles/HardwareProfilesTableRow.tsx
Labels: lgtm, approved

#4951 RHOAIENG-34758: Update MCP Default NS to Dashboard NS
  packages/gen-ai/bff/internal/api/app.go
  packages/gen-ai/bff/internal/api/mcp_helpers.go
  packages/gen-ai/bff/internal/api/mcp_helpers_test.go
  packages/gen-ai/bff/internal/api/mcp_list_handler.go
  packages/gen-ai/bff/internal/api/mcp_list_handler_test.go
  packages/gen-ai/bff/internal/api/mcp_status_handler.go
  packages/gen-ai/bff/internal/api/mcp_tools_handler.go
  packages/gen-ai/bff/internal/constants/mcp.go
  packages/gen-ai/bff/internal/helpers/namespace.go
Labels: lgtm, approved

#4976 Remove 'disableFineTuning' field from odhdashboardconfigs CRD definition
  manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
Labels: lgtm, approved

#5024 update: upgrade Axios to version 1.12.0 across all packages
  frontend/package.json
  package-lock.json
  packages/contract-tests/package.json
  packages/gen-ai/frontend/package-lock.json
  packages/gen-ai/frontend/package.json
Labels: dependencies, lgtm, approved

#5026 Remove 'disableFineTuning' field from odhdashboardconfigs CRD definit…
  manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
Labels: lgtm, approved

#5027 update: upgrade Axios to version 1.12.0 across all packages (#5024)
  frontend/package.json
  package-lock.json
  packages/contract-tests/package.json
  packages/gen-ai/frontend/package-lock.json
  packages/gen-ai/frontend/package.json
Labels: lgtm, approved

#5005 Support more llmd viewing data
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/pages/projects.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingLlmd.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
  frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx
  frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTableRow.tsx
  frontend/src/pages/modelServing/screens/projects/data.ts
  packages/kserve/extensions.ts
  packages/kserve/src/deploymentExpandedDetails.ts
  packages/kserve/src/hardware.ts
  packages/llmd-serving/extensions/extensions.ts
  packages/llmd-serving/package.json
  packages/llmd-serving/src/__tests__/utils.ts
  packages/llmd-serving/src/deployments/endpoints.ts
  packages/llmd-serving/src/deployments/hardware.ts
  packages/llmd-serving/src/deployments/model.ts
  packages/llmd-serving/src/deployments/status.ts
  packages/llmd-serving/src/deployments/useWatchDeployments.ts
  packages/llmd-serving/src/types.ts
  packages/model-serving/extension-points/index.ts
  packages/model-serving/src/components/deployments/DeploymentsTable.tsx
  packages/model-serving/src/components/deployments/DeploymentsTableRowExpandedSection.tsx
  packages/model-serving/src/components/deployments/__tests__/DeploymentsTableRow.spec.tsx
  packages/model-serving/src/components/deployments/row/DeploymentsTableRow.tsx
  packages/model-serving/src/components/deployments/row/DeploymentsTableRowExpandedSection.tsx
  packages/model-serving/src/components/deployments/row/HardwareProfileNameValue.tsx
  packages/model-serving/src/components/projectDetails/ProjectDeploymentsTable.tsx
  packages/model-serving/src/concepts/auth.ts
Labels: lgtm, approved, area/model-serving, area/quality

#5001 Starting a standalone workbench with a hardware profile yields an error
  backend/src/utils/notebookUtils.ts
Labels: lgtm, approved

#5049 Fix UX issue with DW permissions
  frontend/src/concepts/distributedWorkloads/DistributedWorkloadsContext.tsx
  frontend/src/concepts/distributedWorkloads/PermissionsNotSet.tsx
Labels: lgtm, approved

#5048 Moving saveAsAiAsset up a level
  packages/model-serving/src/components/deploymentWizard/fields/AvailableAiAssetsFields.tsx
  packages/model-serving/src/components/deploymentWizard/fields/__tests__/AvailableAiAssetsFields.test.tsx
  packages/model-serving/src/components/deploymentWizard/steps/AdvancedOptionsStep.tsx
Labels: lgtm, approved, area/model-serving

#5042 feat(gen-ai): Add MaaS models and tokens APIs to BFF
  packages/gen-ai/Makefile
  packages/gen-ai/OPENSHIFT.md
  packages/gen-ai/README.md
  packages/gen-ai/bff/Makefile
  packages/gen-ai/bff/README.md
  packages/gen-ai/bff/cmd/main.go
  packages/gen-ai/bff/internal/api/app.go
  packages/gen-ai/bff/internal/api/maas_middleware_test.go
  packages/gen-ai/bff/internal/api/maas_models_handler.go
  packages/gen-ai/bff/internal/api/maas_models_handler_test.go
  packages/gen-ai/bff/internal/api/maas_token_handler.go
  packages/gen-ai/bff/internal/api/maas_tokens_handler.go
  packages/gen-ai/bff/internal/api/maas_tokens_handler_test.go
  packages/gen-ai/bff/internal/api/middleware.go
  packages/gen-ai/bff/internal/config/environment.go
  packages/gen-ai/bff/internal/constants/api_constants.go
  packages/gen-ai/bff/internal/constants/keys.go
  packages/gen-ai/bff/internal/helpers/maas.go
  packages/gen-ai/bff/internal/integrations/maas/maas_client.go
  packages/gen-ai/bff/internal/integrations/maas/maas_client_factory.go
  packages/gen-ai/bff/internal/integrations/maas/maasmocks/maas_client_factory_mock.go
  packages/gen-ai/bff/internal/integrations/maas/maasmocks/maas_client_mock.go
  packages/gen-ai/bff/internal/models/maas_models.go
  packages/gen-ai/bff/internal/repositories/maas_models.go
  packages/gen-ai/bff/internal/repositories/repositories.go
  packages/gen-ai/bff/openapi/src/gen-ai.yaml
Labels: lgtm, approved

#5013 GEN AI - Add playground configuration modal
  packages/gen-ai/bff/internal/api/lsd_handler_test.go
  packages/gen-ai/bff/internal/integrations/kubernetes/k8smocks/token_k8s_client_mock.go
  packages/gen-ai/bff/internal/integrations/kubernetes/token_k8s_client.go
  packages/gen-ai/bff/internal/models/aaa_models.go
  packages/gen-ai/frontend/.eslintrc.js
  packages/gen-ai/frontend/src/app/AIAssets/AIAssetsModelsTab.tsx
  packages/gen-ai/frontend/src/app/AIAssets/AIAssetsPage.tsx
  packages/gen-ai/frontend/src/app/AIAssets/components/AIModelTableRow.tsx
  packages/gen-ai/frontend/src/app/AIAssets/components/AIModelsTable.tsx
  packages/gen-ai/frontend/src/app/AIAssets/components/AIModelsTableRowEndpoint.tsx
  packages/gen-ai/frontend/src/app/AIAssets/data/columns.ts
  packages/gen-ai/frontend/src/app/AIAssets/hooks/useFetchAIModels.ts
  packages/gen-ai/frontend/src/app/AIAssets/types.ts
  packages/gen-ai/frontend/src/app/Chatbot/ChatbotMain.tsx
  packages/gen-ai/frontend/src/app/Chatbot/components/chatbotConfiguration/ChatbotConfigurationModal.tsx
  packages/gen-ai/frontend/src/app/Chatbot/components/chatbotConfiguration/ChatbotConfigurationState.tsx
  packages/gen-ai/frontend/src/app/Chatbot/components/chatbotConfiguration/ChatbotConfigurationTable.tsx
  packages/gen-ai/frontend/src/app/Chatbot/components/chatbotConfiguration/ChatbotConfigurationTableRow.tsx
  packages/gen-ai/frontend/src/app/Chatbot/components/chatbotConfiguration/__tests__/ChatbotConfigurationModal.spec.tsx
  packages/gen-ai/frontend/src/app/Chatbot/components/chatbotConfiguration/columns.ts
  packages/gen-ai/frontend/src/app/context/ChatbotContext.tsx
  packages/gen-ai/frontend/src/app/hooks/useFetchAIModels.ts
  packages/gen-ai/frontend/src/app/services/llamaStackService.ts
  packages/gen-ai/frontend/src/app/types.ts
  packages/gen-ai/frontend/src/app/utilities/utils.ts
Labels: lgtm, approved
