Repository opendatahub-io/odh-dashboard, pull requests merged in 2025-08, with the labels that each got.

#4586 Update MR e2e test `testArchiveModels'
  frontend/src/__tests__/cypress/cypress/pages/modelRegistry.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/modelRegistry/testArchiveModels.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/modelRegistry/testRegisterModel.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/modelRegistry/testRegistryDeployModel.cy.ts
  frontend/src/__tests__/cypress/cypress/utils/modelRegistryUtils.ts
Labels: lgtm, approved

#4612 Doc upload in chatbot
  frontend/packages/llama-stack-modular-ui/frontend/package-lock.json
  frontend/packages/llama-stack-modular-ui/frontend/package.json
  frontend/packages/llama-stack-modular-ui/frontend/src/__mocks__/llamaStackModels.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/api/llamaStack/index.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/AppLayout/AppLayout.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/ChatbotMain.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/sourceUpload/ChatbotSourceSettingsModal.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/sourceUpload/ChatbotSourceUploadPanel.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/app.css
  frontend/packages/llama-stack-modular-ui/frontend/src/app/hooks/useDocumentTitle.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/hooks/useFetchLlamaModels.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/hooks/useFetchModelsByType.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/hooks/useFetchVectorDBs.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/services/llamaStackService.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/types.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/utilities/extractPdfText.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/index.html
Labels: lgtm, approved, area/llama-stack-modular-ui

#4616 Increasing memory allocation to 8GB for linting tests
  .github/workflows/test.yml
  frontend/package.json
Labels: do-not-merge/hold, lgtm, approved

#4542 Link refactor deploy buttons to existing deploy modal
  frontend/packages/modelServing/src/components/deploy/DeployButton.tsx
  frontend/packages/modelServing/src/components/global/GlobalDeploymentsTable.tsx
  frontend/packages/modelServing/src/components/global/GlobalDeploymentsView.tsx
  frontend/packages/modelServing/src/components/global/GlobalModelsToolbar.tsx
  frontend/packages/modelServing/src/concepts/useProjectServingPlatform.ts
Labels: lgtm, approved

#4620 Kueue microcopy changes
  frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/hardwareProfiles.cy.ts
  frontend/src/concepts/hardwareProfiles/HardwareProfileDetailsPopover.tsx
  frontend/src/pages/hardwareProfiles/HardwareProfilesTableRow.tsx
  frontend/src/pages/hardwareProfiles/manage/ManageWorkloadStrategySection.tsx
Labels: lgtm, approved

#4583 E2E test for model deployment with Kserve Raw
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/dataScienceProjects/testDeployKserveRaw.yaml
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testDeployKserveRaw.cy.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/modelServing.ts
Labels: lgtm, approved

#4574 add feature page
  frontend/src/__mocks__/index.ts
  frontend/src/__mocks__/mockFeatureServices.ts
  frontend/src/__mocks__/mockFeatures.ts
  frontend/src/__tests__/cypress/cypress/pages/featureStore/featureStoreGlobal.ts
  frontend/src/__tests__/cypress/cypress/pages/featureStore/features.ts
  frontend/src/__tests__/cypress/cypress/pages/featureStore/featuresDetails.ts
  frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/featureStore/features.cy.ts
  frontend/src/api/featureStore/custom.ts
  frontend/src/pages/featureStore/FeatureStoreRoutes.tsx
  frontend/src/pages/featureStore/apiHooks/__tests__/useFeatureByName.spec.ts
  frontend/src/pages/featureStore/apiHooks/__tests__/useFeatures.spec.ts
  frontend/src/pages/featureStore/apiHooks/useFeatureByName.ts
  frontend/src/pages/featureStore/apiHooks/useFeatureStoreAPIState.tsx
  frontend/src/pages/featureStore/apiHooks/useFeatures.ts
  frontend/src/pages/featureStore/const.ts
  frontend/src/pages/featureStore/screens/components/FeatureStoreInfoTooltip.tsx
  frontend/src/pages/featureStore/screens/entities/utils.ts
  frontend/src/pages/featureStore/screens/features/FeatureTableRow.tsx
  frontend/src/pages/featureStore/screens/features/Features.tsx
  frontend/src/pages/featureStore/screens/features/FeaturesList.tsx
  frontend/src/pages/featureStore/screens/features/FeaturesTable.tsx
  frontend/src/pages/featureStore/screens/features/const.ts
  frontend/src/pages/featureStore/screens/features/featureDetails/FeatureDetails.tsx
  frontend/src/pages/featureStore/screens/features/featureDetails/FeatureDetailsTab.tsx
  frontend/src/pages/featureStore/screens/features/utils.ts
  frontend/src/pages/featureStore/types/featureServices.ts
  frontend/src/pages/featureStore/types/features.ts
  frontend/src/pages/featureStore/types/global.ts
  frontend/src/pages/featureStore/utils/filterUtils.ts
Labels: lgtm, approved

#4571 Feature services
  frontend/src/__mocks__/mockFeatureServices.ts
  frontend/src/__tests__/cypress/cypress/pages/featureStore/featureService.ts
  frontend/src/__tests__/cypress/cypress/pages/featureStore/featureStoreGlobal.ts
  frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/featureStore/featureServices.cy.ts
  frontend/src/api/featureStore/__tests__/custom.spec.ts
  frontend/src/api/featureStore/custom.ts
  frontend/src/pages/featureStore/FeatureStoreRoutes.tsx
  frontend/src/pages/featureStore/apiHooks/__tests__/useFeatureServices.spec.ts
  frontend/src/pages/featureStore/apiHooks/useFeatureServices.ts
  frontend/src/pages/featureStore/apiHooks/useFeatureStoreAPIState.tsx
  frontend/src/pages/featureStore/routes.ts
  frontend/src/pages/featureStore/screens/featureServices/FeatureServiceTableRow.tsx
  frontend/src/pages/featureStore/screens/featureServices/FeatureServices.tsx
  frontend/src/pages/featureStore/screens/featureServices/FeatureServicesListView.tsx
  frontend/src/pages/featureStore/screens/featureServices/FeatureServicesTable.tsx
  frontend/src/pages/featureStore/screens/featureServices/const.ts
  frontend/src/pages/featureStore/screens/featureServices/featureServiceDetails/featureServiceDetails.tsx
  frontend/src/pages/featureStore/screens/featureServices/utils.ts
  frontend/src/pages/featureStore/types/featureServices.ts
  frontend/src/pages/featureStore/types/global.ts
  frontend/src/plugins/extensions/navigation.ts
Labels: lgtm, approved

#4624 Refractor ChatbotMain.tsx file
  frontend/packages/llama-stack-modular-ui/frontend/README.md
  frontend/packages/llama-stack-modular-ui/frontend/jest.config.js
  frontend/packages/llama-stack-modular-ui/frontend/src/__mocks__/llamaStackModels.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/__tests__/cypress/tests/e2e/app.cy.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/App.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/ChatbotMain.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/components/ChatbotSettingsPanel.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/components/ModelSelectFormGroup.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/components/SystemInstructionsFormGroup.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/components/alerts/SourceUploadErrorAlert.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/components/alerts/SourceUploadSuccessAlert.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/const.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/hooks/__tests__/useAccordionState.spec.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/hooks/__tests__/useAlertManagement.spec.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/hooks/__tests__/useChatbotMessages.spec.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/hooks/useAccordionState.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/hooks/useAlertManagement.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/hooks/useChatbotMessages.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/hooks/useSourceManagement.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/hooks/useSystemInstructions.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/sourceUpload/ChatbotSourceSettingsModal.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/sourceUpload/ChatbotSourceUploadPanel.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/routes.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/index.tsx
  frontend/packages/llama-stack-modular-ui/frontend/tsconfig.json
Labels: lgtm, approved, area/llama-stack-modular-ui

#4597 RHOAIENG-28377: Clean up use default storage class hooks
  frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx
  frontend/src/pages/modelServing/screens/projects/NIMServiceModal/__tests__/ManageNIMServingModal.spec.tsx
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/TrainingStorageClassSelect.tsx
  frontend/src/pages/projects/screens/detail/storage/BaseStorageModal.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/screens/spawner/storage/StorageClassSelect.tsx
  frontend/src/pages/projects/screens/spawner/storage/__tests__/StorageClassSelect.spec.tsx
  frontend/src/pages/projects/screens/spawner/storage/useAdminDefaultStorageClass.ts
  frontend/src/pages/projects/screens/spawner/storage/useDefaultStorageClass.ts
  frontend/src/pages/projects/screens/spawner/storage/useOpenshiftDefaultStorageClass.ts
  frontend/src/pages/projects/screens/spawner/storage/usePreferredStorageClass.ts
Labels: lgtm, approved

#4623 Serving refactor cypress: Re-add deploy from registry button link
  frontend/packages/modelServing/src/components/overview/ModelPlatformSection.tsx
  frontend/packages/modelServing/src/components/projectDetails/NoModelsView.tsx
  frontend/src/concepts/modelServing/NavigateBackToRegistryButton.tsx
  frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx
  frontend/src/pages/projects/screens/detail/overview/serverModels/AddModelFooter.tsx
Labels: lgtm, approved

#4435 Upgrade PatternFly to 6.3.0
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/AboutDialog.tsx
  frontend/src/app/Header.tsx
  frontend/src/pages/projects/components/GenericHorizontalBar.tsx
Labels: lgtm, approved

#4627 Move 'Use existing settings' to top of Hardware Profile select list
  frontend/src/concepts/hardwareProfiles/HardwareProfileSelect.tsx
  frontend/src/concepts/hardwareProfiles/__tests__/HardwareProfileSelect.spec.tsx
Labels: lgtm, approved

#4602 Model serving fix cypress platform selection errors
  frontend/packages/modelServing/src/components/overview/ModelPlatformSection.tsx
  frontend/packages/modelServing/src/components/projectDetails/ModelsProjectDetailsView.tsx
  frontend/packages/modelServing/src/components/projectDetails/NoModelsView.tsx
  frontend/packages/modelServing/src/components/projectDetails/SelectPlatformView.tsx
  frontend/packages/modelServing/src/concepts/useProjectServingPlatform.ts
  frontend/src/concepts/modelServing/Platforms/ModelServingPlatformSelectErrorAlert.tsx
  frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx
  frontend/src/pages/projects/screens/detail/overview/serverModels/PlatformSelectSection.tsx
  frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelsSection.tsx
Labels: lgtm, approved

#4638 Verify Required type and add system instruction
  frontend/packages/llama-stack-modular-ui/frontend/src/__mocks__/llamaStackModels.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/AppLayout/AppLayout.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/ChatbotMain.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/components/ChatbotApplicationPage.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/components/ChatbotSettingsPanel.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/components/ModelDetailsDropdown.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/components/ModelSelectFormGroup.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/components/SystemInstructionFormGroup.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/components/SystemInstructionsFormGroup.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/const.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/hooks/__tests__/useChatbotMessages.spec.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/hooks/useChatbotMessages.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/hooks/useSourceManagement.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/hooks/useSystemInstructions.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/sourceUpload/ChatbotSourceSettingsModal.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/sourceUpload/ChatbotSourceUploadPanel.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/app.css
  frontend/packages/llama-stack-modular-ui/frontend/src/app/hooks/useFetchLlamaModels.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/services/llamaStackService.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/types.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/utilities/extractPdfText.ts
Labels: lgtm, approved, area/llama-stack-modular-ui

#4635 RHOAIENG 29677 -Feature Views details section
  frontend/src/__mocks__/mockFeatureServices.ts
  frontend/src/__mocks__/mockFeatureViews.ts
  frontend/src/__tests__/cypress/cypress/pages/featureStore/featureServiceDetails.ts
  frontend/src/__tests__/cypress/cypress/pages/featureStore/featureView.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/featureStore/featureEntities.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/featureStore/featureServiceDetails.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/featureStore/featureViews.cy.ts
  frontend/src/__tests__/cypress/tsconfig.json
  frontend/src/api/featureStore/__tests__/custom.spec.ts
  frontend/src/api/featureStore/custom.ts
  frontend/src/pages/featureStore/FeatureStoreRoutes.tsx
  frontend/src/pages/featureStore/apiHooks/__tests__/useFeatureServices.spec.ts
  frontend/src/pages/featureStore/apiHooks/__tests__/useFeatureStoreEntityByName.spec.ts
  frontend/src/pages/featureStore/apiHooks/__tests__/useFeatureViews.test.tsx
  frontend/src/pages/featureStore/apiHooks/useFeatureServiceByName.ts
  frontend/src/pages/featureStore/apiHooks/useFeatureServices.ts
  frontend/src/pages/featureStore/apiHooks/useFeatureStoreAPIState.tsx
  frontend/src/pages/featureStore/apiHooks/useFeatureStoreEntityByName.ts
  frontend/src/pages/featureStore/apiHooks/useFeatureViews.tsx
  frontend/src/pages/featureStore/apiHooks/useFeatureViewsByName.ts
  frontend/src/pages/featureStore/components/FeatureStoreCodeBlock.tsx
  frontend/src/pages/featureStore/routes.ts
  frontend/src/pages/featureStore/screens/components/FeatureViewTab.tsx
  frontend/src/pages/featureStore/screens/entities/EntitiesTable/FeatureStoreEntitiesListView.tsx
  frontend/src/pages/featureStore/screens/entities/EntitiesTable/FeatureStoreEntitiesTable.tsx
  frontend/src/pages/featureStore/screens/entities/EntitiesTable/FeatureStoreEntitiesTableRow.tsx
  frontend/src/pages/featureStore/screens/entities/const.ts
  frontend/src/pages/featureStore/screens/featureServices/FeatureServicesListView.tsx
  frontend/src/pages/featureStore/screens/featureServices/const.ts
  frontend/src/pages/featureStore/screens/featureServices/utils.ts
  frontend/src/pages/featureStore/screens/featureViews/FeatureViewTableRow.tsx
  frontend/src/pages/featureStore/screens/featureViews/FeatureViewToolbar.tsx
  frontend/src/pages/featureStore/screens/featureViews/FeatureViews.tsx
  frontend/src/pages/featureStore/screens/featureViews/FeatureViewsListView.tsx
  frontend/src/pages/featureStore/screens/featureViews/FeatureViewsTable.tsx
  frontend/src/pages/featureStore/screens/featureViews/__tests__/utils.spec.ts
  frontend/src/pages/featureStore/screens/featureViews/const.ts
  frontend/src/pages/featureStore/screens/featureViews/featureViewDetails/FeatureViewConsumingTab.tsx
  frontend/src/pages/featureStore/screens/featureViews/featureViewDetails/FeatureViewDetails.tsx
  frontend/src/pages/featureStore/screens/featureViews/featureViewDetails/FeatureViewDetailsTab.tsx
  frontend/src/pages/featureStore/screens/featureViews/featureViewDetails/FeatureViewLineageTab.tsx
  frontend/src/pages/featureStore/screens/featureViews/featureViewDetails/FeatureViewMaterialization.tsx
  frontend/src/pages/featureStore/screens/featureViews/featureViewDetails/FeatureViewSchemaTable.tsx
  frontend/src/pages/featureStore/screens/featureViews/featureViewDetails/FeatureViewTabs.tsx
  frontend/src/pages/featureStore/screens/featureViews/featureViewDetails/FeatureViewTransformation.tsx
  frontend/src/pages/featureStore/screens/featureViews/utils.ts
  frontend/src/pages/featureStore/screens/features/FeatureTableRow.tsx
  frontend/src/pages/featureStore/screens/features/FeaturesList.tsx
  frontend/src/pages/featureStore/screens/features/FeaturesTable.tsx
  frontend/src/pages/featureStore/screens/features/const.ts
  frontend/src/pages/featureStore/screens/features/utils.ts
  frontend/src/pages/featureStore/types/featureServices.ts
  frontend/src/pages/featureStore/types/featureView.ts
  frontend/src/pages/featureStore/types/global.ts
  frontend/src/pages/featureStore/utils/filterUtils.ts
  frontend/src/plugins/extensions/navigation.ts
Labels: lgtm, approved

#4470 Migrate /images POST, PUT, and DELETE endpoints to frontend
  backend/src/__tests__/dockerRepositoryURL.spec.ts
  backend/src/__tests__/imageUtils.spec.ts
  backend/src/routes/api/images/imageUtils.ts
  backend/src/routes/api/images/index.ts
  backend/src/utils/notebookUtils.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/notebookImageSettings/notebookImageSettings.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/notebookImageSettings/workbenchImageCharacterLimits.cy.ts
  frontend/src/api/k8s/imageStreams.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/BYONImages/BYONImageModal/DeleteBYONImageModal.tsx
  frontend/src/pages/BYONImages/BYONImageModal/ManageBYONImageModal.tsx
  frontend/src/pages/BYONImages/BYONImageStatusToggle.tsx
  frontend/src/services/imagesService.ts
  frontend/src/types.ts
  frontend/src/utilities/__tests__/imageStreamUtils.spec.ts
  frontend/src/utilities/imageStreamUtils.ts
Labels: lgtm, approved

#4651 PVC Model Path Helper Text Update
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/PVCFields.tsx
  frontend/src/pages/projects/screens/detail/connections/ConnectedResources.tsx
  frontend/src/pages/projects/screens/spawner/storage/PVCContextField.tsx
Labels: lgtm, approved

#4625 Add reviewers in llama-stack-modular-ui (rag-playground)
  frontend/packages/llama-stack-modular-ui/OWNERS
Labels: lgtm, approved, area/llama-stack-modular-ui

#4652 Fix the pipelines run metrics table
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/__tests__/utils.spec.ts
  frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/utils.ts
Labels: lgtm, approved

#4645 Update start / stop models with UX improvements
  frontend/packages/kserve/extensions.ts
  frontend/packages/kserve/src/deploymentEndpoints.ts
  frontend/packages/modelServing/extension-points/index.ts
  frontend/packages/modelServing/src/components/deployments/DeploymentEndpointsPopupButton.tsx
  frontend/packages/modelServing/src/components/deployments/DeploymentStatus.tsx
  frontend/packages/modelServing/src/components/deployments/DeploymentsTable.tsx
  frontend/packages/modelServing/src/components/deployments/DeploymentsTableRow.tsx
  frontend/packages/modelServing/src/components/deployments/__tests__/DeploymentsTableRow.spec.tsx
  frontend/packages/modelServing/src/components/overview/DeployedModelsSection.tsx
  frontend/src/__mocks__/mockInferenceServiceK8sResource.ts
  frontend/src/__mocks__/mockNimResource.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
  frontend/src/concepts/modelServing/ModelStatusIcon.tsx
  frontend/src/pages/modelServing/screens/global/DeleteInferenceServiceModal.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceEndpoint.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx
  frontend/src/pages/modelServing/screens/global/InternalServicePopoverContent.tsx
  frontend/src/pages/modelServing/screens/global/data.ts
Labels: lgtm, approved

#4588 Add CY_RETRY option for Cypress test retry configuration
  docs/testing.md
  frontend/src/__tests__/cypress/cypress.config.ts
  frontend/src/__tests__/cypress/cypress/support/e2e.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/README.md
Labels: lgtm, approved

#4683 Cherry pick E2E Test Fix
  frontend/src/__tests__/cypress/cypress/utils/models.ts
Labels: lgtm, approved

#4687 Add deployment wizard feature flag
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/concepts/areas/const.ts
  frontend/src/concepts/areas/types.ts
  frontend/src/k8sTypes.ts
Labels: lgtm, approved

#4644 Serving runtime list fixes
  frontend/packages/modelServing/src/components/deploy/DeployButton.tsx
  frontend/packages/modelServing/src/components/deployments/DeploymentsTable.tsx
  frontend/packages/modelServing/src/components/deployments/DeploymentsTableRow.tsx
  frontend/packages/modelServing/src/components/deployments/DeploymentsTableRowExpandedSection.tsx
  frontend/packages/modelServing/src/components/overview/ModelPlatformSection.tsx
  frontend/packages/modelServing/src/components/projectDetails/ModelsProjectDetailsView.tsx
  frontend/packages/modelServing/src/components/projectDetails/SelectPlatformView.tsx
  frontend/packages/modelServing/src/concepts/ModelDeploymentsContext.tsx
  frontend/packages/modelServing/src/concepts/useProjectServingPlatform.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/projectDetails.cy.ts
  frontend/src/pages/modelServing/screens/global/InferenceServiceServingRuntime.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx
  frontend/src/services/componentsServices.ts
Labels: lgtm, approved

#4577 RHOAIENG-30958: Add pre-commit hook for linting
  .husky/pre-commit
  docs/PRE-COMMIT.md
  package-lock.json
  package.json
Labels: lgtm, approved

#4699 manage upload document
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/hooks/useSourceManagement.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/sourceUpload/ChatbotSourceUploadPanel.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/utilities/utils.ts
Labels: lgtm, approved, area/llama-stack-modular-ui

#4700 Quarantine/Unquarantine workbench/distributed workload metrics test
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/distributedWorkloadMetrics/testWorkloadMetricsDefaultPageContents.cy.ts
Labels: lgtm, approved

#4694 Init deployment wizard
  frontend/packages/modelServing/extensions/odh.ts
  frontend/packages/modelServing/src/GlobalModelsRoutes.tsx
  frontend/packages/modelServing/src/ModelDeploymentWizardRoutes.tsx
  frontend/packages/modelServing/src/components/deploy/DeployButton.tsx
  frontend/packages/modelServing/src/components/deploymentWizard/CreateModelDeploymentPage.tsx
  frontend/packages/modelServing/src/components/deploymentWizard/EditModelDeploymentPage.tsx
  frontend/packages/modelServing/src/components/deploymentWizard/ModelDeploymentWizard.tsx
  frontend/packages/modelServing/src/components/deploymentWizard/utils.ts
  frontend/packages/modelServing/src/components/deployments/DeploymentsTable.tsx
  frontend/packages/modelServing/src/components/global/GlobalModelsToolbar.tsx
  frontend/packages/modelServing/src/components/global/GlobalNoModelsView.tsx
  frontend/packages/modelServing/src/components/overview/ModelPlatformSection.tsx
  frontend/packages/modelServing/src/components/projectDetails/ModelsProjectDetailsView.tsx
  frontend/packages/modelServing/src/components/projectDetails/NoModelsView.tsx
  frontend/packages/plugin-core/src/extension-points/project-details.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingDeploy.cy.ts
  frontend/src/pages/projects/ProjectViewRoutes.tsx
Labels: lgtm, approved

#4632 Min max deployment improvements
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
  frontend/src/components/ReplicaSection.tsx
  frontend/src/pages/modelServing/screens/projects/kServeModal/KServeAutoscalerReplicaSection.tsx
  frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
Labels: lgtm, approved

#4715 add lighter code rabbit
  .coderabbit.yaml
Labels: lgtm, approved

#4716 [RHOAIENG-32294] Quarantine Authorino-related test changes
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testModelTokenAuth.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelAdminCreation.cy.ts
Labels: lgtm, approved

#4730 Fix proxy port issue for llama-stack
  frontend/packages/llama-stack-modular-ui/frontend/config/dotenv.js
  frontend/packages/llama-stack-modular-ui/frontend/config/webpack.dev.js
Labels: lgtm, approved, area/llama-stack-modular-ui

#4729 Wizard deployment type field
  frontend/packages/modelServing/src/components/deploymentWizard/ModelDeploymentWizard.tsx
  frontend/packages/modelServing/src/components/deploymentWizard/fields/ModelTypeSelectField.tsx
  frontend/packages/modelServing/src/components/deploymentWizard/fields/__tests__/ModelTypeSelectField.test.tsx
  frontend/packages/modelServing/src/components/deploymentWizard/steps/ModelSourceStep.tsx
  frontend/packages/modelServing/src/components/deploymentWizard/steps/__tests__/ModelSourceStep.test.tsx
  frontend/packages/modelServing/src/components/deploymentWizard/useDeploymentWizard.ts
  frontend/src/hooks/useZodFormValidation.ts
Labels: lgtm, approved

#4707 Move constants into a single file
  frontend/packages/llama-stack-modular-ui/bff/internal/api/app.go
  frontend/packages/llama-stack-modular-ui/bff/internal/api/app_test.go
  frontend/packages/llama-stack-modular-ui/bff/internal/api/healthcheck_handler.go
  frontend/packages/llama-stack-modular-ui/bff/internal/api/healthcheck_handler_test.go
  frontend/packages/llama-stack-modular-ui/bff/internal/api/models_handler.go
  frontend/packages/llama-stack-modular-ui/bff/internal/api/models_handler_test.go
  frontend/packages/llama-stack-modular-ui/bff/internal/api/openapi_handler.go
  frontend/packages/llama-stack-modular-ui/bff/internal/constants/api_constants.go
Labels: lgtm, approved, area/llama-stack-modular-ui

#4740 Quarantine/Unquarantine workbench/distributed workload metrics test- cherry-pick
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/distributedWorkloadMetrics/testWorkloadMetricsDefaultPageContents.cy.ts
Labels: lgtm, approved

#4742 regenerate package-lock.json
  backend/package.json
  frontend/package.json
  frontend/packages/feature-store/package.json
  frontend/packages/feature-store/src/__tests__/unit/jest.setup.ts
  frontend/packages/feature-store/src/__tests__/unit/testUtils/hooks.ts
  frontend/src/__tests__/cypress/cypress/pages/lmEval/lmEvalFormPage.ts
  frontend/src/__tests__/cypress/cypress/pages/notebookImageSettings.ts
  frontend/src/__tests__/cypress/cypress/pages/notebookServer.ts
  frontend/src/app/__tests__/AboutDialog.spec.tsx
  package-lock.json
  package.json
Labels: lgtm, approved, area/feature-store-modular-ui

#4739 Fix layout issues and some clean up
  frontend/packages/llama-stack-modular-ui/frontend/package-lock.json
  frontend/packages/llama-stack-modular-ui/frontend/package.json
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/ChatbotMain.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/components/ChatbotSettingsPanel.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/standalone/AppLayout.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/standalone/NavBar.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/bootstrap.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/odh/LlamaStackWrapper.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/odh/extensions.ts
Labels: lgtm, approved, area/llama-stack-modular-ui

#4738 [Cypress-e2e] add a timeout to model status check
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/support/timeouts.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testModelStopStart.cy.ts
Labels: lgtm, approved

#4718 update lint-staged and markdown linting
  docs/best-practices.md
  docs/code_examples.md
  docs/extensibility.md
  docs/module-federation.md
  docs/testing.md
  frontend/src/__tests__/cypress/cypress/tests/e2e/README.md
  package.json
  packages/eslint-config/markdown.js
Labels: lgtm, approved

#4746 Implement code-exporter endpoint with template-based Python code generation
  frontend/packages/llama-stack-modular-ui/bff/internal/api/app.go
  frontend/packages/llama-stack-modular-ui/bff/internal/api/code_exporter_handler.go
  frontend/packages/llama-stack-modular-ui/bff/internal/api/code_exporter_handler_test.go
  frontend/packages/llama-stack-modular-ui/bff/internal/api/helpers.go
  frontend/packages/llama-stack-modular-ui/bff/internal/constants/templates.go
  frontend/packages/llama-stack-modular-ui/bff/internal/models/code_export.go
  frontend/packages/llama-stack-modular-ui/bff/internal/repositories/repositories.go
  frontend/packages/llama-stack-modular-ui/bff/internal/repositories/templates.go
  frontend/packages/llama-stack-modular-ui/bff/openapi/src/llama-stack-modular-ui.yaml
Labels: lgtm, approved, area/llama-stack-modular-ui

#4760 Quarantine Model Serving tests due to RHOAIENG-32764 & RHOAIENG-32763
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testModelPvcDeployment.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testModelStopStart.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testModelTokenAuth.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testMultiModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelContributorCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/servingRuntimes/testMultiModelServingRuntimeCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/servingRuntimes/testSingleServingRuntimeCreation.cy.ts
Labels: lgtm, approved

#4758 Use new vectorstores and files upload BFF
  frontend/packages/llama-stack-modular-ui/frontend/config/webpack.dev.js
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/ChatbotMain.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/components/ChatbotSettingsPanel.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/components/ModelDetailsDropdown.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/hooks/__tests__/useChatbotMessages.spec.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/hooks/useChatbotMessages.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/hooks/useSourceManagement.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/sourceUpload/ChatbotSourceSettingsModal.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/sourceUpload/ChatbotSourceUploadPanel.tsx
  frontend/packages/llama-stack-modular-ui/frontend/src/app/hooks/useFetchVectorDBs.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/hooks/useFetchVectorStores.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/services/llamaStackService.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/types.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/utilities/utils.ts
  frontend/packages/llama-stack-modular-ui/package.json
Labels: lgtm, approved, area/llama-stack-modular-ui

#4763 Refactor resource handling in assembleNotebook function by simplifyin…
  backend/src/utils/notebookUtils.ts
Labels: lgtm, approved

#4712 Model Deployment Notification Update
  frontend/@mf-types/@mf/modelRegistry/compiled-types/src/odh/extension-points.d.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDetails.cy.ts
  frontend/src/api/k8s/inferenceServices.ts
  frontend/src/concepts/modelServing/ModelStatusIcon.tsx
  frontend/src/concepts/modelServingKServe/kserveStatusUtils.ts
  frontend/src/pages/modelServing/__tests__/useInferenceServiceStatus.spec.ts
  frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx
  frontend/src/pages/modelServing/screens/global/useRouteForInferenceService.ts
  frontend/src/pages/modelServing/screens/projects/useModelDeploymentNotification.ts
  frontend/src/pages/modelServing/screens/types.ts
  frontend/src/pages/modelServing/useInferenceServiceStatus.ts
  frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelsGallery.tsx
  packages/kserve/extensions.ts
  packages/kserve/src/deploymentStatus.ts
  packages/kserve/src/deployments.ts
  packages/model-serving/extension-points/index.ts
  packages/model-serving/src/components/deployments/DeploymentStatus.tsx
  packages/model-serving/src/components/deployments/DeploymentsTableRow.tsx
  packages/model-serving/src/components/deployments/__tests__/DeploymentsTableRow.spec.tsx
  packages/model-serving/src/components/overview/DeployedModelsSection.tsx
  packages/model-serving/src/concepts/deploymentUtils.ts
  packages/model-serving/src/concepts/useModelDeploymentNotification.ts
Labels: lgtm, approved

#4693 Easy Developer Access for the Commit Hash
  README.md
  frontend/config/webpack.common.js
  frontend/src/app/AboutDialog.tsx
  frontend/src/types.ts
  packages/jest-config/config/jest.setup.ts
Labels: lgtm, approved

#4762 Serving refactor: show model in project details from yaml only
  packages/model-serving/src/ModelsProjectDetailsTab.tsx
  packages/model-serving/src/ServeModelsSection.tsx
  packages/model-serving/src/components/overview/DeployedModelsSection.tsx
  packages/model-serving/src/components/projectDetails/ModelsProjectDetailsView.tsx
  packages/model-serving/src/concepts/ModelDeploymentsContext.tsx
Labels: lgtm, approved

#4726 Update the pipelines E2E test for FIPS
  frontend/src/__mocks__/mockPipelineVersionsProxy.ts
  frontend/src/__tests__/cypress/cypress/fixtures/resources/pipelines/iris_pipeline_pip_index_url_compiled.yaml
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/v1-pipeline.yaml
  frontend/src/__tests__/resources/pipelines_samples/dummy_pipeline.py
  frontend/src/__tests__/resources/pipelines_samples/dummy_pipeline_compiled.yaml
Labels: lgtm, approved

#4736 [feat] Add K8s client support for llamastack-modular ui
  frontend/packages/llama-stack-modular-ui/bff/Makefile
  frontend/packages/llama-stack-modular-ui/bff/README.md
  frontend/packages/llama-stack-modular-ui/bff/cmd/main.go
  frontend/packages/llama-stack-modular-ui/bff/go.mod
  frontend/packages/llama-stack-modular-ui/bff/go.sum
  frontend/packages/llama-stack-modular-ui/bff/internal/api/app.go
  frontend/packages/llama-stack-modular-ui/bff/internal/api/middleware.go
  frontend/packages/llama-stack-modular-ui/bff/internal/api/namespace_handler.go
  frontend/packages/llama-stack-modular-ui/bff/internal/config/environment.go
  frontend/packages/llama-stack-modular-ui/bff/internal/helpers/k8s.go
  frontend/packages/llama-stack-modular-ui/bff/internal/integrations/factory.go
  frontend/packages/llama-stack-modular-ui/bff/internal/integrations/kubernetes/client.go
  frontend/packages/llama-stack-modular-ui/bff/internal/integrations/kubernetes/factory.go
  frontend/packages/llama-stack-modular-ui/bff/internal/integrations/kubernetes/k8smocks/base_testenv.go
  frontend/packages/llama-stack-modular-ui/bff/internal/integrations/kubernetes/k8smocks/mock_factory.go
  frontend/packages/llama-stack-modular-ui/bff/internal/integrations/kubernetes/k8smocks/token_k8s_client_mock.go
  frontend/packages/llama-stack-modular-ui/bff/internal/integrations/kubernetes/token_k8s_client.go
  frontend/packages/llama-stack-modular-ui/bff/internal/integrations/types.go
  frontend/packages/llama-stack-modular-ui/bff/internal/models/model.go
  frontend/packages/llama-stack-modular-ui/bff/internal/repositories/namespace.go
  frontend/packages/llama-stack-modular-ui/bff/internal/repositories/repositories.go
  frontend/packages/llama-stack-modular-ui/bff/openapi/src/llama-stack-modular-ui.yaml
Labels: lgtm, approved, area/llama-stack-modular-ui

#4743 Show PVC Select Instead of Existing URI for Missing PVCs
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/PVCFields.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/PVCSelect.tsx
Labels: lgtm, approved

#4764 Update advanced / standard vocab
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testDeployKserveRaw.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/clusterSettings/clusterSettings.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
  frontend/src/pages/clusterSettings/ModelServingPlatformSettings.tsx
  frontend/src/pages/modelServing/screens/projects/kServeModal/KServeDeploymentModeDropdown.tsx
Labels: lgtm, approved

#4768 [feat] Add endpoint for fetching LSD status
  frontend/packages/llama-stack-modular-ui/bff/README.md
  frontend/packages/llama-stack-modular-ui/bff/go.mod
  frontend/packages/llama-stack-modular-ui/bff/go.sum
  frontend/packages/llama-stack-modular-ui/bff/internal/api/app.go
  frontend/packages/llama-stack-modular-ui/bff/internal/api/errors.go
  frontend/packages/llama-stack-modular-ui/bff/internal/api/llamastack_distribution_handler.go
  frontend/packages/llama-stack-modular-ui/bff/internal/api/llamastack_distribution_handler_test.go
  frontend/packages/llama-stack-modular-ui/bff/internal/api/middleware.go
  frontend/packages/llama-stack-modular-ui/bff/internal/constants/keys.go
  frontend/packages/llama-stack-modular-ui/bff/internal/helpers/k8s.go
  frontend/packages/llama-stack-modular-ui/bff/internal/integrations/kubernetes/client.go
  frontend/packages/llama-stack-modular-ui/bff/internal/integrations/kubernetes/k8smocks/base_testenv.go
  frontend/packages/llama-stack-modular-ui/bff/internal/integrations/kubernetes/k8smocks/mock_factory.go
  frontend/packages/llama-stack-modular-ui/bff/internal/integrations/kubernetes/k8smocks/token_k8s_client_mock.go
  frontend/packages/llama-stack-modular-ui/bff/internal/integrations/kubernetes/token_k8s_client.go
  frontend/packages/llama-stack-modular-ui/bff/internal/models/llamastack_distribution.go
  frontend/packages/llama-stack-modular-ui/bff/internal/repositories/llamastack_distribution.go
  frontend/packages/llama-stack-modular-ui/bff/internal/repositories/repositories.go
  frontend/packages/llama-stack-modular-ui/bff/openapi/src/llama-stack-modular-ui.yaml
Labels: lgtm, approved, ok-to-test, area/llama-stack-modular-ui

#4776 move package-subtree script to root/scripts
  scripts/package-subtree.sh
Labels: lgtm, approved

#4759 Feature store metrics tab(overview page)
  frontend/src/__tests__/cypress/cypress/pages/featureStore/featureMetrics.ts
  frontend/src/__tests__/cypress/cypress/pages/featureStore/featureStoreGlobal.ts
  frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/featureStore/featureMetrics.cy.ts
  packages/feature-store/src/FeatureStore.tsx
  packages/feature-store/src/FeatureStoreRoutes.tsx
  packages/feature-store/src/__mocks__/mockMetrics.ts
  packages/feature-store/src/api/custom.ts
  packages/feature-store/src/apiHooks/__tests__/useMetricsResourceCount.spec.ts
  packages/feature-store/src/apiHooks/useFeatureStoreAPIState.tsx
  packages/feature-store/src/apiHooks/useMetricsPopularTags.ts
  packages/feature-store/src/apiHooks/useMetricsResourceCount.ts
  packages/feature-store/src/apiHooks/useRecentlyVisitedResources.ts
  packages/feature-store/src/const.ts
  packages/feature-store/src/screens/metrics/MetricCards.tsx
  packages/feature-store/src/screens/metrics/Metrics.tsx
  packages/feature-store/src/screens/metrics/PopularTags.tsx
  packages/feature-store/src/screens/metrics/RecentlyVisitedResources.tsx
  packages/feature-store/src/screens/metrics/__tests__/utils.spec.ts
  packages/feature-store/src/screens/metrics/const.ts
  packages/feature-store/src/screens/metrics/utils.ts
  packages/feature-store/src/types/global.ts
  packages/feature-store/src/types/metrics.ts
Labels: lgtm, approved, area/feature-store-modular-ui

#4778 add error state
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/sourceUpload/ChatbotSourceSettingsModal.tsx
Labels: lgtm, approved, area/llama-stack-modular-ui

#4774 feat: Add authentication button to Swagger UI for Bearer token support
  frontend/packages/llama-stack-modular-ui/bff/internal/api/openapi_handler.go
  frontend/packages/llama-stack-modular-ui/bff/openapi/src/llama-stack-modular-ui.yaml
Labels: lgtm, approved, area/llama-stack-modular-ui

#4772 feat: refactor module dockerfiles
  docs/workspace-dockerfiles.md
  manifests/modular-architecture/deployment.yaml
  packages/model-registry/Dockerfile.workspace
  packages/model-registry/README.md
  packages/plugin-template/Dockerfile.workspace
Labels: lgtm, approved

#4779 quarantine the pipelines test
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataSciencePipelines/createRunDeletePipelineCustomPipMirror.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataSciencePipelines/pipelines.cy.ts
Labels: lgtm, approved

#4634 RHOAIENG-30493: Error creating a new workbench from a kueue enabled project, assigning a hwp with node scheduling
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/projectDetails.cy.ts
  frontend/src/concepts/hardwareProfiles/HardwareProfileSelect.tsx
  frontend/src/concepts/hardwareProfiles/__tests__/HardwareProfileSelect.spec.tsx
  frontend/src/concepts/hardwareProfiles/kueueConstants.ts
  frontend/src/concepts/hardwareProfiles/kueueUtils.ts
  frontend/src/concepts/hardwareProfiles/useHardwareProfileConfig.ts
  frontend/src/pages/modelServing/screens/global/ServeModelButton.tsx
  frontend/src/pages/modelServing/screens/projects/ModelServingPlatformButtonAction.tsx
  frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
  frontend/src/pages/projects/screens/detail/notebooks/NotebookList.tsx
  frontend/src/pages/projects/screens/detail/overview/trainModels/MetricsContents.tsx
  frontend/src/pages/projects/screens/detail/overview/trainModels/NotebooksCard.tsx
Labels: lgtm, approved
