Repository opendatahub-io/odh-dashboard, pull requests merged in 2025-07, with the labels that each got.

#4440 Rhoaieng 26502
  frontend/src/__tests__/cypress/cypress/fixtures/resources/yaml/dspa.yaml
  frontend/src/__tests__/cypress/cypress/pages/workbench.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataSciencePipelines/createRunDeletePipelineCustomPipMirror.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataSciencePipelines/pipelines.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchStatus.cy.ts
  frontend/src/__tests__/cypress/cypress/types.ts
  frontend/src/__tests__/cypress/cypress/utils/pipelines.ts
Labels: lgtm, approved, area/quality

#4437 Add feature flag for Feature store
  frontend/src/__mocks__/mockDashboardConfig.ts
  frontend/src/concepts/areas/const.ts
  frontend/src/concepts/areas/types.ts
  frontend/src/k8sTypes.ts
Labels: lgtm, approved

#4427 Fixed bug where storage class select wouldn't appear in NIM Modal
  frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx
  frontend/src/pages/modelServing/screens/projects/NIMServiceModal/__tests__/ManageNIMServingModal.spec.tsx
  frontend/src/pages/projects/screens/spawner/storage/StorageClassSelect.tsx
  frontend/src/pages/projects/screens/spawner/storage/__tests__/StorageClassSelect.spec.tsx
Labels: lgtm, approved, ok-to-test

#4441 Serving refactor: Add tokens and hardware accelerators
  frontend/packages/kserve/extensions.ts
  frontend/packages/kserve/src/deploymentExpandedDetails.ts
  frontend/packages/kserve/src/useAuth.ts
  frontend/packages/kserve/src/useKServeResources.ts
  frontend/packages/modelServing/extension-points/index.ts
  frontend/packages/modelServing/src/GlobalModelsPage.tsx
  frontend/packages/modelServing/src/ModelsProjectDetailsTab.tsx
  frontend/packages/modelServing/src/ServeModelsSection.tsx
  frontend/packages/modelServing/src/components/deployments/DeploymentsTable.tsx
  frontend/packages/modelServing/src/components/deployments/DeploymentsTableRow.tsx
  frontend/packages/modelServing/src/components/deployments/DeploymentsTableRowExpandedSection.tsx
  frontend/packages/modelServing/src/components/deployments/__tests__/DeploymentsTableRow.spec.tsx
  frontend/packages/modelServing/src/components/overview/DeployedModelsSection.tsx
  frontend/packages/modelServing/src/components/overview/ModelPlatformSection.tsx
  frontend/packages/modelServing/src/components/projectDetails/ModelsProjectDetailsView.tsx
  frontend/packages/modelServing/src/concepts/ModelDeploymentsContext.tsx
  frontend/packages/modelServing/src/concepts/ModelServingPlatformContext.tsx
  frontend/packages/modelServing/src/concepts/auth.ts
  frontend/packages/modelServing/src/concepts/extensionUtils.ts
  frontend/src/concepts/modelServing/ModelRow/ServingRuntimeTokenDisplay.tsx
  frontend/src/concepts/modelServing/ModelRow/ServingRuntimeTokenTableRow.tsx
  frontend/src/concepts/modelServing/ModelRow/TokensDescriptionItem.tsx
  frontend/src/concepts/modelServingKServe/ServingRuntimeTokensTable.tsx
  frontend/src/pages/modelServing/screens/global/data.ts
  frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTableRow.tsx
  frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTableExpandedSection.tsx
Labels: lgtm, approved

#4444 Cypress e2e Test - Verify a model version can be registered via versions view
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/modelRegistry/testRegisterModel.yaml
  frontend/src/__tests__/cypress/cypress/pages/modelRegistry.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/modelRegistry/testAdminEditRegistry.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/modelRegistry/testArchiveModels.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/modelRegistry/testCreateModelRegistry.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/modelRegistry/testRegisterModel.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelRegistry.cy.ts
  frontend/src/__tests__/cypress/cypress/types.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/modelRegistry.ts
Labels: lgtm, approved

#4407 Allow empty requested/limit for CPU and memory when hardware profile is disabled
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
  frontend/src/components/CPUField.tsx
  frontend/src/components/MemoryField.tsx
  frontend/src/components/NumberInputWrapper.tsx
  frontend/src/components/ValueUnitField.tsx
  frontend/src/components/__tests__/CPUField.spec.tsx
  frontend/src/components/__tests__/MemoryField.spec.tsx
  frontend/src/concepts/hardwareProfiles/HardwareProfileCustomize.tsx
  frontend/src/hooks/__tests__/useZodFormValidation.spec.ts
  frontend/src/hooks/useZodFormValidation.ts
  frontend/src/pages/hardwareProfiles/nodeResource/CountFormField.tsx
  frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeExpandedField.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/__tests__/validationUtils.spec.ts
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/validationUtils.ts
  frontend/src/pages/modelServing/screens/projects/__tests__/useModelServerSizeValidation.spec.ts
  frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
  frontend/src/pages/modelServing/screens/projects/useModelServerSizeValidation.ts
  frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/ContainerCustomSize.tsx
Labels: lgtm, approved, area/quality

#4451 Serving refactor: Show deployments of all projects in global page
  frontend/packages/modelServing/extension-points/index.ts
  frontend/packages/modelServing/src/GlobalModelsPage.tsx
  frontend/packages/modelServing/src/components/deployments/DeploymentsTable.tsx
  frontend/packages/modelServing/src/components/deployments/DeploymentsTableRow.tsx
  frontend/packages/modelServing/src/components/deployments/__tests__/DeploymentsTableRow.spec.tsx
  frontend/packages/modelServing/src/components/global/GlobalDeploymentsTable.tsx
  frontend/packages/modelServing/src/components/global/GlobalDeploymentsView.tsx
  frontend/packages/modelServing/src/components/projectDetails/ModelsProjectDetailsView.tsx
  frontend/packages/modelServing/src/components/projectDetails/ProjectDeploymentsTable.tsx
  frontend/packages/modelServing/src/concepts/extensionUtils.ts
Labels: lgtm, approved

#4456 Cypress e2e Test - Verify model registry permissions can be managed
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/modelRegistry/testManageRegistryPermissions.yaml
  frontend/src/__tests__/cypress/cypress/pages/modelRegistrySettings.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/modelRegistry/testManageRegistryPermissions.cy.ts
  frontend/src/__tests__/cypress/cypress/types.ts
  frontend/src/__tests__/cypress/cypress/utils/dataLoader.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/roleBindings.ts
Labels: lgtm, approved

#4409 Change "Launch application" to "Open application"
  docs/dev-setup.md
  frontend/src/__mocks__/mockComponents.ts
  frontend/src/components/OdhAppCard.tsx
  manifests/common/apps/jupyter/create-jupyter-notebook-quickstart.yaml
  manifests/common/apps/jupyter/jupyter-app.yaml
  manifests/rhoai/addon/apps/nvidia/gpu-quickstart.yaml
  manifests/rhoai/addon/apps/starburst/starburst-galaxy-quickstart.yaml
  manifests/rhoai/onprem/apps/starburst-enterprise/query-starburstenterprise-quickstart.yaml
  manifests/rhoai/shared/apps/pachyderm/pachyderm-app.yaml
  package.json
Labels: lgtm, approved

#4436 Pipeline failure feedback 2
  frontend/src/__tests__/cypress/cypress/support/e2e.ts
  frontend/src/concepts/dashboard/ModalStyles.scss
  frontend/src/concepts/pipelines/EnsureAPIAvailability.tsx
  frontend/src/concepts/pipelines/content/StartingStatusModal.tsx
  frontend/src/concepts/pipelines/content/__tests__/StartingStatusModal.spec.tsx
  frontend/src/concepts/pipelines/context/PipelinesContext.tsx
  frontend/src/pages/pipelines/global/PipelineCoreApplicationPage.tsx
  frontend/src/pages/pipelines/global/experiments/GlobalExperiments.tsx
  frontend/src/pages/pipelines/global/experiments/artifacts/GlobalArtifactsPage.tsx
  frontend/src/pages/pipelines/global/experiments/executions/GlobalExecutions.tsx
  frontend/src/pages/pipelines/global/pipelines/GlobalPipelines.tsx
  frontend/src/pages/pipelines/global/runs/GlobalPipelineRuns.tsx
  frontend/src/pages/projects/components/GenericHorizontalBar.tsx
  frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesCard.tsx
  frontend/src/pages/projects/screens/detail/pipelines/PipelinesSection.tsx
  frontend/src/utilities/time.ts
Labels: lgtm, approved

#4350 Add toast notification upon successful datascience pipeline configuration
  frontend/src/__tests__/cypress/cypress/pages/components/ToastNotifications.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts
  frontend/src/components/ToastNotification.tsx
  frontend/src/components/ToastNotifications.tsx
  frontend/src/concepts/notificationWatcher/NotificationWatcherContext.tsx
  frontend/src/concepts/notificationWatcher/__tests__/NotificationWatcherContext.spec.tsx
  frontend/src/concepts/pipelines/EnsureAPIAvailability.tsx
  frontend/src/concepts/pipelines/content/__tests__/StartingStatusModal.spec.tsx
  frontend/src/concepts/pipelines/content/configurePipelinesServer/ConfigurePipelinesServerModal.tsx
  frontend/src/concepts/pipelines/context/PipelinesContext.tsx
  frontend/src/concepts/pipelines/context/usePipelineNamespaceCR.ts
Labels: lgtm, approved

#4403 Stop/Start Model e2e Test
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/dataScienceProjects/testModelStopStart.yaml
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testModelStopStart.cy.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/modelServing.ts
Labels: lgtm, approved, area/quality

#4448 Microcopy updates for "project-scoped" items
  frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/workbenchHardwareProfiles.cy.ts
  frontend/src/components/ProjectScopedPopover.tsx
  frontend/src/concepts/hardwareProfiles/HardwareProfileSelect.tsx
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
  frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
  frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/TrainingHardwareProfileFormSection.tsx
Labels: lgtm, approved

#4458 Updated Serving Runtime Label Microcopy
  frontend/src/pages/modelServing/screens/ServingRuntimeVersionStatus.tsx
Labels: lgtm, approved

#4461 split frontend lint task into two separate runs
  frontend/package.json
Labels: lgtm, approved

#4463 Updates and enhancements for 'Verify the filters on Resources page' e2e test
  frontend/src/__tests__/cypress/cypress/pages/resources.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/learningResources/testResourcesfilters.cy.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/learningResources.ts
Labels: lgtm, approved

#4467 Fix type errors for array in es2021
  frontend/src/api/k8s/__tests__/notebooks.spec.ts
  frontend/src/pages/hardwareProfiles/utils.ts
  frontend/src/pages/notebookController/screens/server/StopServerModal.tsx
  frontend/src/pages/projects/screens/detail/notebooks/NotebookUpdateImageModalFooter.tsx
  frontend/src/pages/projects/screens/detail/notebooks/useNotebookImageData.ts
  frontend/src/utilities/imageUtils.ts
Labels: lgtm, approved

#4421 Add stopping status to model deployments
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
  frontend/src/components/StateActionToggle.tsx
  frontend/src/concepts/modelServing/ModelStatusIcon.tsx
  frontend/src/pages/modelServing/__tests__/useModelStatus.spec.ts
  frontend/src/pages/modelServing/__tests__/utils.spec.ts
  frontend/src/pages/modelServing/screens/global/InferenceServiceStatus.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx
  frontend/src/pages/modelServing/screens/types.ts
  frontend/src/pages/modelServing/useModelPodStatus.ts
  frontend/src/pages/modelServing/useModelStatus.ts
  frontend/src/pages/modelServing/utils.ts
  frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelCard.tsx
Labels: lgtm, approved

#4474 Quarantine model serving tests due to [Product Bug: RHOAIENG-29340]
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testDeployOCIModel.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testModelStopStart.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testMultiModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelContributorCreation.cy.ts
Labels: lgtm, approved

#4400 Update Hardware profile admin page
  frontend/packages/modelServing/src/components/deployments/DeploymentsTableRowExpandedSection.tsx
  frontend/src/__mocks__/mockHardwareProfile.ts
  frontend/src/__mocks__/mockWorkloadPriorityClassK8Resource.ts
  frontend/src/__tests__/cypress/cypress/fixtures/resources/hardwareProfile/model_tolerations.yaml
  frontend/src/__tests__/cypress/cypress/pages/hardwareProfile.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/applications/notebookServer.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/hardwareProfiles.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/legacyHardwareProfiles.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/manageHardwareProfiles.cy.ts
  frontend/src/api/k8s/__tests__/hardwareProfiles.spec.ts
  frontend/src/api/k8s/hardwareProfiles.ts
  frontend/src/api/models/kueue.ts
  frontend/src/api/models/odh.ts
  frontend/src/concepts/distributedWorkloads/useWorkloadPriorityClasses.ts
  frontend/src/concepts/hardwareProfiles/HardwareProfileDetailsPopover.tsx
  frontend/src/concepts/hardwareProfiles/HardwareProfileSelect.tsx
  frontend/src/concepts/hardwareProfiles/__tests__/useModelServingPodSpecOptionsState.spec.ts
  frontend/src/concepts/hardwareProfiles/__tests__/useNotebookPodSpecOptionsState.spec.ts
  frontend/src/concepts/hardwareProfiles/useHardwareProfileConfig.ts
  frontend/src/concepts/hardwareProfiles/useModelServingPodSpecOptionsState.ts
  frontend/src/concepts/hardwareProfiles/useNotebookPodSpecOptionsState.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/BYONImages/BYONImageHardwareProfiles.tsx
  frontend/src/pages/hardwareProfiles/DeleteHardwareProfileModal.tsx
  frontend/src/pages/hardwareProfiles/HardwareProfileEnableToggle.tsx
  frontend/src/pages/hardwareProfiles/HardwareProfiles.tsx
  frontend/src/pages/hardwareProfiles/HardwareProfilesTable.tsx
  frontend/src/pages/hardwareProfiles/HardwareProfilesTableRow.tsx
  frontend/src/pages/hardwareProfiles/const.tsx
  frontend/src/pages/hardwareProfiles/manage/ManageHardwareProfile.tsx
  frontend/src/pages/hardwareProfiles/manage/ManageLocalQueueFieldSection.tsx
  frontend/src/pages/hardwareProfiles/manage/ManageNodeSelectorSection.tsx
  frontend/src/pages/hardwareProfiles/manage/ManageResourceAllocationSection.tsx
  frontend/src/pages/hardwareProfiles/manage/ManageTolerationSection.tsx
  frontend/src/pages/hardwareProfiles/manage/ManageWorkloadPrioritySection.tsx
  frontend/src/pages/hardwareProfiles/manage/ManageWorkloadStrategySection.tsx
  frontend/src/pages/hardwareProfiles/manage/__tests__/validationUtils.spec.ts
  frontend/src/pages/hardwareProfiles/manage/types.ts
  frontend/src/pages/hardwareProfiles/manage/validationUtils.ts
  frontend/src/pages/hardwareProfiles/migration/MigrationModal.tsx
  frontend/src/pages/hardwareProfiles/migration/__tests__/useMigratedHardwareProfiles.spec.ts
  frontend/src/pages/hardwareProfiles/migration/__tests__/utils.spec.ts
  frontend/src/pages/hardwareProfiles/migration/useMigratedHardwareProfiles.ts
  frontend/src/pages/hardwareProfiles/migration/utils.ts
  frontend/src/pages/hardwareProfiles/nodeResource/const.ts
  frontend/src/pages/hardwareProfiles/utils.ts
  frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeDetails.tsx
  frontend/src/pages/notebookController/screens/server/NotebookServerDetails.tsx
  frontend/src/pages/pipelines/global/modelCustomization/useIlabPodSpecOptionsState.ts
  frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRowHardwareProfile.tsx
  frontend/src/types.ts
  manifests/common/crd/hardwareprofiles.opendatahub.io.crd.yaml
Labels: lgtm, approved, area/quality

#4237 easier to use feature flags via a button in the header
  frontend/src/app/App.tsx
  frontend/src/app/DevFeatureFlagsBanner.tsx
  frontend/src/app/Header.tsx
  frontend/src/app/HeaderTools.tsx
  frontend/src/app/featureFlags/DevFeatureFlagsBanner.tsx
  frontend/src/app/featureFlags/FeatureFlagLauncher.tsx
  frontend/src/app/featureFlags/FeatureFlagModal.tsx
  frontend/src/app/featureFlags/__tests__/DevFeatureFlagsBanner.spec.tsx
  frontend/src/app/featureFlags/__tests__/useDevFeatureFlags.spec.tsx
  frontend/src/app/featureFlags/useDevFeatureFlags.ts
  frontend/src/types.ts
Labels: lgtm, approved

#4462 Retrieve default local queue name from DSC
  frontend/src/__mocks__/mockDsc.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/manageHardwareProfiles.cy.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/hardwareProfiles/manage/ManageResourceAllocationSection.tsx
  frontend/src/pages/hardwareProfiles/nodeResource/const.ts
Labels: lgtm, approved

#4478 Remove deleted crd from kustomization file
  manifests/common/crd/kustomization.yaml
Labels: lgtm, approved

#4480 Temporarily restore dashboard HWP crd
  manifests/common/crd/hardwareprofiles.opendatahub.io.crd.yaml
  manifests/common/crd/kustomization.yaml
Labels: lgtm, approved

#4459 Serving refactor: Add modelmesh as a platform shortcircuit option
  frontend/package-lock.json
  frontend/package.json
  frontend/packages/kserve/extensions.ts
  frontend/packages/model-serving-backport/extensions.ts
  frontend/packages/model-serving-backport/package.json
  frontend/packages/model-serving-backport/tsconfig.json
  frontend/packages/modelServing/extension-points/index.ts
  frontend/packages/modelServing/src/ModelsProjectDetailsTab.tsx
  frontend/packages/modelServing/src/ServeModelsSection.tsx
  frontend/packages/modelServing/src/__tests__/mockUtils.ts
  frontend/packages/modelServing/src/concepts/useProjectServingPlatform.ts
Labels: lgtm, approved

#4475 Internal model serving endpoint
  frontend/packages/kserve/src/deploymentEndpoints.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
  frontend/src/pages/modelServing/screens/global/InternalServicePopoverContent.tsx
Labels: lgtm, approved

#4442 Change how model deployment links appear
  frontend/packages/modelServing/src/components/deployments/DeploymentStatus.tsx
  frontend/packages/modelServing/src/components/deployments/DeploymentsTableRow.tsx
  frontend/packages/modelServing/src/components/overview/DeployedModelsSection.tsx
  frontend/src/__mocks__/mockInferenceServiceK8sResource.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/projectDetails.cy.ts
  frontend/src/pages/modelServing/__tests__/useInferenceServiceStatus.spec.ts
  frontend/src/pages/modelServing/screens/global/InferenceServiceEndpoint.tsx
  frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx
  frontend/src/pages/modelServing/useInferenceServiceStatus.ts
  frontend/src/pages/modelServing/utils.ts
  frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelCard.tsx
  frontend/src/pages/projects/screens/spawner/storage/types.ts
Labels: lgtm, approved

#4488 Remove Model Serving Tests from Quarantine following bug fix RHOAIENG-29340
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testDeployOCIModel.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testModelStopStart.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testMultiModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelContributorCreation.cy.ts
Labels: lgtm, approved

#4413 RHOAIENG-25339: Update application of hardware profiles in all workloads
  frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/legacyHardwareProfiles.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
  frontend/src/api/k8s/__tests__/notebooks.spec.ts
  frontend/src/api/k8s/__tests__/servingRuntimes.spec.ts
  frontend/src/api/k8s/notebooks.ts
  frontend/src/api/k8s/servingRuntimes.ts
  frontend/src/concepts/hardwareProfiles/useNotebookHardwareProfileConfig.ts
  frontend/src/concepts/hardwareProfiles/useServingHardwareProfileConfig.ts
Labels: lgtm, approved

#4481 Feature flag modal re-organization
  frontend/src/app/featureFlags/FeatureFlagModal.tsx
  frontend/src/app/featureFlags/__tests__/DevFeatureFlagsBanner.spec.tsx
  frontend/src/concepts/areas/const.ts
Labels: lgtm, approved

#4487 Feature Store Initial Setup
  frontend/src/__mocks__/mockDataSources.ts
  frontend/src/__mocks__/mockEntities.ts
  frontend/src/__mocks__/mockFeatureServices.ts
  frontend/src/__mocks__/mockFeatureStore.ts
  frontend/src/__mocks__/mockFeatureStoreProject.ts
  frontend/src/__mocks__/mockFeatureViews.ts
  frontend/src/api/models/odh.ts
  frontend/src/concepts/design/utils.ts
  frontend/src/concepts/featureStore/context/FeatureStoreProjectContext.tsx
  frontend/src/concepts/featureStore/types.ts
  frontend/src/concepts/featureStore/useFeatureStoreEnabled.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/featureStore/FeatureStore.tsx
  frontend/src/pages/featureStore/FeatureStoreCoreLoader.tsx
  frontend/src/pages/featureStore/FeatureStoreRoutes.tsx
  frontend/src/pages/featureStore/components/FeatureStoreCodeBlock.tsx
  frontend/src/pages/featureStore/components/FeatureStoreLabels.tsx
  frontend/src/pages/featureStore/components/FeatureStoreTags.tsx
  frontend/src/pages/featureStore/screens/FeatureStoreProjectSelectorNavigator.tsx
  frontend/src/pages/featureStore/screens/components/EmptyStateFeatureStore.tsx
  frontend/src/pages/featureStore/screens/components/FeatureStoreProjectSelector.tsx
  frontend/src/plugins/extensions/navigation.ts
  frontend/src/plugins/extensions/routes.ts
Labels: lgtm, approved

#4492 Fix bug when stopping model with confirmation modal
  frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx
Labels: lgtm, approved

#4490 RHOAIENG-27574: Filter Hardware profiles if kueue disabled
  frontend/src/concepts/hardwareProfiles/HardwareProfileSelect.tsx
  frontend/src/concepts/hardwareProfiles/__tests__/HardwareProfileSelect.spec.tsx
  frontend/src/k8sTypes.ts
Labels: lgtm, approved

#4496 RHOAIENG-30110: The workload priority is not maintained when switching between local queue and not selectors.
  frontend/src/pages/hardwareProfiles/manage/ManageHardwareProfile.tsx
  frontend/src/pages/hardwareProfiles/manage/ManageResourceAllocationSection.tsx
  frontend/src/pages/hardwareProfiles/manage/ManageWorkloadPrioritySection.tsx
  frontend/src/pages/hardwareProfiles/manage/ManageWorkloadStrategySection.tsx
  frontend/src/pages/hardwareProfiles/manage/__tests__/ManageResourceAllocationSection.spec.tsx
Labels: lgtm, approved

#4489 Kueue extras
  frontend/packages/kserve/src/useKServeResources.ts
  frontend/src/__mocks__/mockInferenceServiceK8sResource.ts
  frontend/src/__mocks__/mockInferenceServiceModalData.ts
  frontend/src/__mocks__/mockNimResource.ts
  frontend/src/__mocks__/mockServingRuntimeK8sResource.ts
  frontend/src/__mocks__/mockStartNotebookData.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
  frontend/src/api/k8s/__tests__/inferenceServices.spec.ts
  frontend/src/api/k8s/__tests__/notebooks.spec.ts
  frontend/src/api/k8s/__tests__/servingRuntimes.spec.ts
  frontend/src/api/k8s/inferenceServices.ts
  frontend/src/api/k8s/notebooks.ts
  frontend/src/api/k8s/servingRuntimes.ts
  frontend/src/concepts/hardwareProfiles/useHardwareProfileConfig.ts
  frontend/src/concepts/hardwareProfiles/useModelServingPodSpecOptionsState.ts
  frontend/src/concepts/hardwareProfiles/useServingHardwareProfileConfig.ts
  frontend/src/k8sTypes.ts
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/__tests__/ManageInferenceServiceModal.spec.tsx
  frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeDetails.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx
  frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
  frontend/src/pages/modelServing/screens/projects/utils.ts
  frontend/src/pages/modelServing/screens/types.ts
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/pages/projects/types.ts
Labels: lgtm, approved

#4491 Add missing frontmatter to cypress-e2e.mdc rule file
  .cursor/rules/cypress-e2e.mdc
Labels: lgtm, approved

#4499 Add test IDs for deployed model names in ModelMesh and plugin components
  frontend/packages/modelServing/src/components/deployments/DeploymentsTableRow.tsx
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testDeployOCIModel.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testModelStopStart.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testMultiModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelContributorCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/hardwareProfiles/testModelServingTolerations.cy.ts
  frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx
Labels: lgtm, approved

#4500 Remove dashboard hardware profiles CRD
  manifests/common/crd/hardwareprofiles.opendatahub.io.crd.yaml
  manifests/common/crd/kustomization.yaml
  manifests/core-bases/base/fetch-hardwares.rbac.yaml
Labels: lgtm, approved

#4503 upversion dashboard
  frontend/.env
Labels: lgtm, approved

#4506 Update Tekton output-image tags to version v2.35.2-odh
  .tekton/odh-dashboard-push.yaml
Labels: lgtm, approved

#4508 upversion dashboard
  frontend/.env
  manifests/odh/params.env
Labels: lgtm, approved

#4507 Add back hardware profiles crd
  manifests/common/crd/hardwareprofiles.opendatahub.io.crd.yaml
  manifests/common/crd/kustomization.yaml
Labels: lgtm, approved

#4510 Fixes Documentation & Support Links Missing
  frontend/src/utilities/const.ts
Labels: lgtm, approved

#4518 Add back hardware profiles crd (#4507)
  manifests/common/crd/hardwareprofiles.opendatahub.io.crd.yaml
  manifests/common/crd/kustomization.yaml
Labels: lgtm, approved

#4522 Add fix to only show images that have the correct annotation in notebooks
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageSelectorField.tsx
Labels: lgtm, approved

#4526 Add fix to image streams notebook enabling label (#4522)
  frontend/src/pages/projects/screens/spawner/imageSelector/ImageSelectorField.tsx
Labels: lgtm, approved

#4454 Add skeleton for accelerator profile while loading
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/workbench.cy.ts
  frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx
  frontend/src/pages/notebookController/screens/server/AcceleratorProfileSelectField.tsx
  frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
  frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/TrainingAcceleratorFormSection.tsx
  frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
  frontend/src/utilities/useAcceleratorProfileFormState.ts
  frontend/src/utilities/useReadAcceleratorState.ts
Labels: lgtm, approved

#4519 Globals page exports routes with metrics too
  frontend/packages/modelServing/extensions.ts
  frontend/packages/modelServing/src/GlobalModelsRoutes.tsx
  frontend/packages/modelServing/src/components/deployments/DeploymentsTableRow.tsx
  frontend/packages/modelServing/src/components/global/GlobalDeploymentsView.tsx
  frontend/packages/modelServing/src/components/global/GlobalModelsPage.tsx
  frontend/packages/modelServing/src/components/metrics/DeploymentMetricsLink.tsx
  frontend/packages/modelServing/src/components/metrics/GlobalMetricsRoutes.tsx
  frontend/src/plugins/extensions/routes.ts
Labels: lgtm, approved

#4535 Initial folder structure for llama stack ui (RAG/Gen AI v3)
  frontend/packages/llama-stack-modular-ui/OWNERS
  frontend/packages/llama-stack-modular-ui/bff/.gitignore
  frontend/packages/llama-stack-modular-ui/frontend/.gitignore
Labels: lgtm, approved

#4450 Enable MR Modular Architecture deployment
  frontend/config/moduleFederation.js
  frontend/config/webpack.common.js
  frontend/config/webpack.dev.js
  frontend/package.json
  frontend/packages/model-registry/Dockerfile
  frontend/packages/model-registry/package.json
  frontend/src/__tests__/cypress/cypress/support/e2e.ts
  frontend/src/__tests__/cypress/cypress/utils/moduleFederationMock.ts
  frontend/src/plugins/useAppExtensions.ts
  manifests/core-bases/base/service.yaml
  manifests/modular-architecture/README.md
  manifests/modular-architecture/deployment.yaml
  manifests/modular-architecture/federation-configmap.yaml
  manifests/modular-architecture/kustomization.yaml
  manifests/modular-architecture/service.yaml
Labels: lgtm, approved

#4536 fix: update title and label text in Enable NIM dialog
  frontend/src/__tests__/cypress/cypress/pages/components/NIMCard.ts
  manifests/rhoai/shared/apps/nvidia-nim/nvidia-nim-app.yaml
Labels: lgtm, approved, ok-to-test

#4420 Refactor RegisterCatlogModel and Remove useEffect
  frontend/src/pages/modelCatalog/ModelCatalogRoutes.tsx
  frontend/src/pages/modelCatalog/screens/RegisterCatalogModel.tsx
  frontend/src/pages/modelCatalog/screens/RegisterCatalogModelForm.tsx
  frontend/src/pages/modelCatalog/screens/RegisterCatalogModelPage.tsx
  frontend/src/pages/modelRegistry/screens/RegisterModel/useRegisterModelData.ts
Labels: lgtm, approved

#4497 Aggregate get/list/watch permissions to project admins/contributors
  manifests/core-bases/base/aggregate-permissions.rbac.yaml
  manifests/core-bases/base/kustomization.yaml
Labels: lgtm, approved

#4538 chore: e2e Test Maintenance - Jul 24th 25'
  frontend/src/__tests__/cypress/cypress/support/e2e.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testModelStopStart.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelContributorCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/distributedWorkloadMetrics/testWorkloadMetricsDefaultPageContents.cy.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/distributedWorkloads.ts
Labels: lgtm, approved

#4523 Add version labels to refactored code
  frontend/packages/kserve/extensions.ts
  frontend/packages/kserve/src/deploymentServingDetails.tsx
  frontend/packages/kserve/src/deploymentsTable.ts
  frontend/packages/modelServing/extension-points/index.ts
  frontend/packages/modelServing/src/components/deployments/DeployedModelsVersion.tsx
  frontend/packages/modelServing/src/components/deployments/DeploymentsTable.tsx
  frontend/packages/modelServing/src/components/deployments/DeploymentsTableRow.tsx
  frontend/packages/modelServing/src/components/overview/DeployedModelsSection.tsx
Labels: lgtm, approved

#4531 Serving refactor global models page backport
  frontend/packages/model-serving-backport/extensions.ts
  frontend/packages/modelServing/extension-points/index.ts
  frontend/packages/modelServing/src/components/global/GlobalModelsPage.tsx
  frontend/packages/modelServing/src/concepts/useProjectServingPlatform.ts
Labels: lgtm, approved

#4546 add llama stack github action workflow
  .github/workflows/llama-stack-modular-ui-bff-build.yml
  .github/workflows/llama-stack-modular-ui-frontend-build.yml
  frontend/packages/llama-stack-modular-ui/frontend/.eslintrc.js
  frontend/packages/llama-stack-modular-ui/frontend/package-lock.json
  frontend/packages/llama-stack-modular-ui/frontend/package.json
  frontend/packages/llama-stack-modular-ui/frontend/src/__tests__/cypress/cypress.config.ts
  frontend/packages/llama-stack-modular-ui/frontend/src/app/Chatbot/ChatbotMessagesList.tsx
  frontend/packages/llama-stack-modular-ui/frontend/tsconfig.json
Labels: lgtm, approved

#4562 config: enable typecheck for source files, disable only for test files
  frontend/packages/llama-stack-modular-ui/bff/.golangci.yml
Labels: lgtm, approved, area/llama-stack-modular-ui

#4566 exclude llama-stack-modular-ui in tsconfig.json
  frontend/tsconfig.json
Labels: lgtm, approved

#4567 Removed out of date documentation files
  docs/README.md
  docs/byon.md
  docs/dashboard-config.md
  docs/dev-setup.md
Labels: lgtm, approved

#4570 Quarantine model serving tests for Product Bug RHOAIENG-30799
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testDeployOCIModel.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testModelPvcDeployment.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testModelStopStart.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testMultiModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelAdminCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelContributorCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/settings/servingRuntimes/testSingleServingRuntimeCreation.cy.ts
Labels: lgtm, approved

#4556 module federation documentation
  .env
  backend/src/routes/module-federation.ts
  docs/README.md
  docs/module-federation.md
Labels: lgtm, approved

#4565 Adapt base images in Dockerfile
  Dockerfile
  frontend/packages/llama-stack-modular-ui/Dockerfile
  frontend/packages/model-registry/Dockerfile
Labels: lgtm, approved, area/llama-stack-modular-ui

#4564 Cypress e2e Test - Verify models can be deployed from model registry
  frontend/src/__tests__/cypress/cypress/fixtures/e2e/modelRegistry/testRegisterModel.yaml
  frontend/src/__tests__/cypress/cypress/fixtures/resources/yaml/model_registry.yaml
  frontend/src/__tests__/cypress/cypress/pages/modelRegistry.ts
  frontend/src/__tests__/cypress/cypress/pages/modelRegistry/modelVersionDeployModal.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/modelRegistry/testArchiveModels.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/modelRegistry/testRegisterModel.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/modelRegistry/testRegistryDeployModel.cy.ts
  frontend/src/__tests__/cypress/cypress/types.ts
  frontend/src/__tests__/cypress/cypress/utils/modelRegistryUtils.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/modelRegistry.ts
  frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ProjectSelector.tsx
Labels: lgtm, approved

#4528 RHOAIENG-28909: Add Storage Class Provisioner "disk.csi.azure.com" to Storage Enums
  frontend/src/pages/storageClasses/__tests__/StorageClassEditModal.spec.tsx
  frontend/src/pages/storageClasses/storageEnums.ts
Labels: lgtm, approved

#4580 Serving refactor: fix project details tab cypress tests
  frontend/packages/model-serving-backport/extensions.ts
  frontend/packages/modelServing/src/components/platformSelection.tsx
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/pages/projects.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/projectDetails.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/modelServingNim.cy.ts
  frontend/src/pages/modelServing/screens/projects/EmptyMultiModelServingCard.tsx
  frontend/src/pages/modelServing/screens/projects/EmptyNIMModelServingCard.tsx
  frontend/src/pages/modelServing/screens/projects/EmptySingleModelServingCard.tsx
  frontend/src/pages/projects/screens/detail/overview/serverModels/SelectMultiModelCard.tsx
  frontend/src/pages/projects/screens/detail/overview/serverModels/SelectNIMCard.tsx
  frontend/src/pages/projects/screens/detail/overview/serverModels/SelectSingleModelCard.tsx
Labels: lgtm, approved
