Repository opendatahub-io/odh-dashboard, pull requests merged in 2025-10, with the labels that each got.

#5056 Moved npm-run-all to dev-dependencies
  packages/gen-ai/frontend/package-lock.json
  packages/gen-ai/frontend/package.json
Labels: lgtm, approved

#5033 [feat] Add SA token while fetching models
  packages/gen-ai/bff/internal/integrations/kubernetes/k8smocks/token_k8s_client_mock.go
  packages/gen-ai/bff/internal/integrations/kubernetes/token_k8s_client.go
  packages/gen-ai/bff/internal/models/aaa_models.go
  packages/gen-ai/bff/openapi/src/gen-ai.yaml
Labels: lgtm, approved

#5011 fix package-lock check and workflow cache
  .github/workflows/test.yml
Labels: lgtm, approved

#4891 Add tests, edit, and deploy functionality for wizard model location
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingDeploy.cy.ts
  frontend/src/k8sTypes.ts
  packages/kserve/extensions.ts
  packages/kserve/src/deploy.ts
  packages/kserve/src/modelLocationData.ts
  packages/model-serving/extension-points/index.ts
  packages/model-serving/src/__tests__/mockUtils.ts
  packages/model-serving/src/components/deploymentWizard/CreateModelDeploymentPage.tsx
  packages/model-serving/src/components/deploymentWizard/EditModelDeploymentPage.tsx
  packages/model-serving/src/components/deploymentWizard/ModelDeploymentWizard.tsx
  packages/model-serving/src/components/deploymentWizard/fields/ModelLocationInputFields.tsx
  packages/model-serving/src/components/deploymentWizard/fields/ModelLocationSelectField.tsx
  packages/model-serving/src/components/deploymentWizard/fields/__tests__/ModelLocationSelectField.test.tsx
  packages/model-serving/src/components/deploymentWizard/fields/modelLocationFields/ExistingConnectionField.tsx
  packages/model-serving/src/components/deploymentWizard/fields/modelLocationFields/PVCInputField.tsx
  packages/model-serving/src/components/deploymentWizard/fields/modelLocationFields/PVCSelectField.tsx
  packages/model-serving/src/components/deploymentWizard/fields/modelLocationFields/types.ts
  packages/model-serving/src/components/deploymentWizard/steps/ModelSourceStep.tsx
  packages/model-serving/src/components/deploymentWizard/steps/__tests__/ModelSourceStep.test.tsx
  packages/model-serving/src/components/deploymentWizard/utils.ts
Labels: lgtm, approved, area/model-serving, area/quality

#5052 Add Delete Action for LLMd
  packages/kserve/extensions.ts
  packages/llmd-serving/extensions/extensions.ts
  packages/llmd-serving/src/deployments.ts
  packages/model-serving/extension-points/index.ts
  packages/model-serving/src/components/deleteModal/DeleteModelServingModal.tsx
Labels: lgtm, approved, area/model-serving

#5046 feat: Add file and vectorstore delete/list operations with query para…
  package-lock.json
  packages/gen-ai/bff/go.mod
  packages/gen-ai/bff/internal/api/app.go
  packages/gen-ai/bff/internal/api/lsd_files_handler.go
  packages/gen-ai/bff/internal/api/lsd_files_handler_test.go
  packages/gen-ai/bff/internal/api/lsd_vectorstores_handler.go
  packages/gen-ai/bff/internal/api/lsd_vectorstores_handler_test.go
  packages/gen-ai/bff/internal/constants/api_constants.go
  packages/gen-ai/bff/internal/integrations/llamastack/llamastack_client.go
  packages/gen-ai/bff/internal/integrations/llamastack/llamastack_client_factory.go
  packages/gen-ai/bff/internal/integrations/llamastack/lsmocks/llamastack_client_mock.go
  packages/gen-ai/bff/internal/repositories/lsd_files.go
  packages/gen-ai/bff/internal/repositories/lsd_vectorstores.go
  packages/gen-ai/bff/internal/testutil/constants.go
  packages/gen-ai/bff/openapi/src/gen-ai.yaml
  packages/gen-ai/package.json
Labels: lgtm, approved, area/hardware-profiles, area/model-registry, area/model-serving, area/pipelines, area/platform, area/quality, area/model-training, area/feature-store

#5063 feat: Add previous response ID support for conversation continuity
  packages/gen-ai/bff/internal/api/lsd_responses_handler.go
  packages/gen-ai/bff/internal/api/lsd_responses_handler_test.go
  packages/gen-ai/bff/internal/integrations/llamastack/llamastack_client.go
  packages/gen-ai/bff/internal/integrations/llamastack/llamastack_client_factory.go
  packages/gen-ai/bff/internal/integrations/llamastack/lsmocks/llamastack_client_factory_mock.go
  packages/gen-ai/bff/internal/integrations/llamastack/lsmocks/llamastack_client_mock.go
  packages/gen-ai/bff/internal/repositories/lsd_responses.go
  packages/gen-ai/bff/openapi/src/gen-ai.yaml
Labels: lgtm, approved

#5058 [feat] Add support for llminferenceservice
  packages/gen-ai/bff/go.mod
  packages/gen-ai/bff/go.sum
  packages/gen-ai/bff/internal/api/aaa_models_handler_test.go
  packages/gen-ai/bff/internal/integrations/kubernetes/k8smocks/token_k8s_client_mock.go
  packages/gen-ai/bff/internal/integrations/kubernetes/token_k8s_client.go
  packages/gen-ai/bff/openapi/src/gen-ai.yaml
Labels: lgtm, approved

#5065 Remove delete button for the OOTB hardware profile
  frontend/src/__mocks__/mockHardwareProfile.ts
  frontend/src/__tests__/cypress/cypress/pages/components/table.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/hardwareProfiles.cy.ts
  frontend/src/pages/hardwareProfiles/HardwareProfilesTableRow.tsx
  frontend/src/pages/hardwareProfiles/const.tsx
  frontend/src/pages/hardwareProfiles/utils.ts
Labels: lgtm, approved, area/quality

#5066 GEN AI - Add delete playground and update configuration flow
  packages/gen-ai/bff/internal/api/lsd_models_handler_test.go
  packages/gen-ai/bff/internal/api/middleware_test.go
  packages/gen-ai/bff/internal/integrations/kubernetes/k8smocks/token_k8s_client_mock.go
  packages/gen-ai/bff/internal/integrations/llamastack/lsmocks/llamastack_client_mock.go
  packages/gen-ai/frontend/src/app/Chatbot/ChatbotHeaderActions.tsx
  packages/gen-ai/frontend/src/app/Chatbot/ChatbotMain.tsx
  packages/gen-ai/frontend/src/app/Chatbot/components/DeletePlaygroundModal.tsx
  packages/gen-ai/frontend/src/app/Chatbot/components/chatbotConfiguration/ChatbotConfigurationModal.tsx
  packages/gen-ai/frontend/src/app/Chatbot/components/chatbotConfiguration/ChatbotConfigurationState.tsx
  packages/gen-ai/frontend/src/app/Chatbot/components/chatbotConfiguration/ChatbotConfigurationTable.tsx
  packages/gen-ai/frontend/src/app/shared/DeleteModal.tsx
Labels: lgtm, approved

#5075 Update HardwareProfile API version to v1 across mock data and tests
  frontend/src/__mocks__/mockHardwareProfile.ts
  frontend/src/__tests__/cypress/cypress/fixtures/resources/hardwareProfile/model_tolerations.yaml
  frontend/src/api/k8s/__tests__/hardwareProfiles.spec.ts
  frontend/src/api/models/odh.ts
Labels: lgtm, approved, area/quality

#5082 Fix llama model and aaa model matching issues
  packages/gen-ai/frontend/src/__mocks__/mockLlamaStackModels.ts
  packages/gen-ai/frontend/src/app/AIAssets/AIAssetsModelsTab.tsx
  packages/gen-ai/frontend/src/app/AIAssets/components/AIModelTableRow.tsx
  packages/gen-ai/frontend/src/app/AIAssets/components/AIModelsTable.tsx
  packages/gen-ai/frontend/src/app/Chatbot/ChatbotMain.tsx
  packages/gen-ai/frontend/src/app/Chatbot/ChatbotPlayground.tsx
  packages/gen-ai/frontend/src/app/Chatbot/components/ModelDetailsDropdown.tsx
  packages/gen-ai/frontend/src/app/Chatbot/components/chatbotConfiguration/ChatbotConfigurationModal.tsx
  packages/gen-ai/frontend/src/app/Chatbot/components/chatbotConfiguration/__tests__/ChatbotConfigurationModal.spec.tsx
  packages/gen-ai/frontend/src/app/Chatbot/hooks/useSourceManagement.ts
  packages/gen-ai/frontend/src/app/hooks/useFetchLlamaModels.ts
  packages/gen-ai/frontend/src/app/services/llamaStackService.ts
  packages/gen-ai/frontend/src/app/types.ts
  packages/gen-ai/frontend/src/app/utilities/utils.ts
Labels: lgtm, approved

#5088 Fix gen-ai routes
  packages/gen-ai/frontend/src/app/AIAssets/components/mcp/MCPServersToolbar.tsx
  packages/gen-ai/frontend/src/app/App.tsx
  packages/gen-ai/frontend/src/app/AppRoutes.tsx
  packages/gen-ai/frontend/src/app/utilities/const.ts
Labels: lgtm, approved

#5079 Cleanup assemble inference service and add loading states
  packages/kserve/src/deploy.ts
  packages/kserve/src/deployModel.ts
  packages/kserve/src/deployUtils.ts
  packages/kserve/src/hardware.ts
  packages/model-serving/src/__tests__/mockUtils.ts
  packages/model-serving/src/components/deploymentWizard/EditModelDeploymentPage.tsx
  packages/model-serving/src/components/deploymentWizard/ModelDeploymentWizard.tsx
  packages/model-serving/src/components/deploymentWizard/fields/ModelFormatField.tsx
  packages/model-serving/src/components/deploymentWizard/fields/ModelLocationInputFields.tsx
  packages/model-serving/src/components/deploymentWizard/steps/AdvancedOptionsStep.tsx
  packages/model-serving/src/components/deploymentWizard/steps/ModelSourceStep.tsx
  packages/model-serving/src/components/deploymentWizard/types.ts
  packages/model-serving/src/components/deploymentWizard/useDeploymentWizard.ts
Labels: lgtm, approved, area/model-serving

#5087 Show model id in model info popover
  packages/gen-ai/frontend/src/app/AIAssets/components/AIModelTableRow.tsx
  packages/gen-ai/frontend/src/app/AIAssets/components/AIModelsTableRowEndpoint.tsx
  packages/gen-ai/frontend/src/app/AIAssets/components/AIModelsTableRowInfo.tsx
  packages/gen-ai/frontend/src/app/AIAssets/data/columns.ts
Labels: lgtm, approved

#5096 fix: vllm model port being wrong
  packages/gen-ai/bff/internal/integrations/kubernetes/token_k8s_client.go
Labels: lgtm, approved

#5098 [feat] Add SSAR to verify if user has access to LSD service
  packages/gen-ai/bff/internal/api/app.go
  packages/gen-ai/bff/internal/api/middleware.go
  packages/gen-ai/bff/internal/integrations/kubernetes/client.go
  packages/gen-ai/bff/internal/integrations/kubernetes/k8smocks/token_k8s_client_mock.go
  packages/gen-ai/bff/internal/integrations/kubernetes/token_k8s_client.go
  packages/gen-ai/bff/internal/integrations/kubernetes/token_k8s_client_test.go
Labels: lgtm, approved

#5091 Add creating an LLMD deployment test
  frontend/src/__mocks__/mockSecretK8sResource.ts
  frontend/src/__mocks__/mockServingRuntimeTemplateK8sResource.ts
  frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/customServingRuntimes/customServingRuntimesUtils.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingDeploy.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingLlmd.cy.ts
  packages/llmd-serving/src/__tests__/utils.ts
  packages/model-serving/src/components/deployments/row/DeploymentsTableRowExpandedSection.tsx
Labels: lgtm, approved, area/model-serving, area/quality

#5107 feat: add BFF build support for OpenShift
  packages/gen-ai/bff/Dockerfile
  packages/gen-ai/bff/build.openshift.sh
  packages/gen-ai/bff/cmd/main.go
  packages/gen-ai/bff/internal/api/openapi_handler.go
Labels: lgtm, approved

#5071 Added mcp tools for the code exporter
  packages/gen-ai/bff/internal/api/code_exporter_handler.go
  packages/gen-ai/bff/internal/api/code_exporter_handler_test.go
  packages/gen-ai/bff/internal/constants/templates.go
  packages/gen-ai/bff/internal/models/code_export.go
  packages/gen-ai/bff/openapi/src/gen-ai.yaml
Labels: lgtm, approved

#5110 Delete cypress logs
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/connections/testConnectionCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchCreation.cy.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/baseCommands.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/dataConnection.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/presistentVolumeClaim.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/pvcLoaderPod.ts
  frontend/src/__tests__/cypress/cypress/utils/oc_commands/storageClass.ts
  frontend/src/__tests__/cypress/cypress/utils/pipelines.ts
Labels: lgtm, approved, area/quality
